### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by andrewreid** [vouch/vouch-proxy#100]
I apologise – I've read through just about all of the issues, perused the source and still can't nut this out. I think I'm losing my touch!

My nginx configuration is shown below. My internal "protected" app and vouch are behind the same nginx proxy:

```
server {
  listen 80;
  listen [::]:80;
  server_name cloud.reid.ee;
  return 301 https://$host$request_uri;
}

# Vouch

server {
	listen 443 ssl http2;
  listen [::]:443 ssl http2;
	server_name vouch.reid.ee;
	include /config/nginx/ssl.conf;
	location / {
		proxy_set_header Host vouch.reid.ee;
		proxy_pass http://172.16.1.82:9090;
	}
}

server {
	listen 443 ssl http2 default_server;
	listen [::]:443 ssl http2 default_server;
	server_name cloud.reid.ee;
	include /config/nginx/ssl.conf;
	root /config/www;
	index index.html index.htm index.php;
	auth_request /validate;

	location = /validate {
		internal;
		proxy_pass http://172.16.1.82:9090;
		proxy_set_header Host cloud.reid.ee;
		proxy_set_header Content-Length "";
		proxy_pass_request_body off;
		auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
		auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
		auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
		auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
	}

	location /sonarr {
		proxy_pass http://mogul.reid.ee:8989;
		proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
		auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
	}

	error_page 401 = @error401;

	location @error401 {
		# redirect to Vouch Proxy for login
		return 302 https://vouch.reid.ee/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
	}
}
```

My vouch `config.yml` is pretty straight-forward and it successfully interacts with Google:

```
vouch:
  logLevel: debug
  listen: 0.0.0.0
  port: 9090

  domains:
  - reid.ee

  whiteList:
  - ndrewreid@gmail.com
  - andrew@reid.ee

oauth:
  provider: google
  client_id: xxxxx
  client_secret: xxxxx
  callback_urls:
  - https://vouch.reid.ee/auth
  preferredDomain: reid.ee
```

When I hit my protected location, `cloud.reid.ee/sonarr`, I'm redirected via `/validate` to Google, where I'm successfully redirected back to `vouch.reid.ee/auth`. The logs seem to indicate that my session state is matched, the username is found in the whitelist and, hey, it should be happy days. It seems as though `/auth` responds with a `302` to `/validate` again, where my domain isn't seen as authorised, but also found as a matched array value:

```
{"level":"debug","ts":1554723612.927297,"msg":"*ptokenCLaims: {andrew@reid.ee [] { 1554738012  0 Vouch 0 }}"}
{"level":"info","ts":1554723612.9294083,"msg":"jwt cookie","username":"andrew@reid.ee"}
{"level":"error","ts":1554723612.9306395,"msg":"http header 'Host: cloud.reid.ee' not authorized for configured `vouch.domains` (is Host being sent properly?)"}
{"level":"debug","ts":1554723612.9322002,"msg":"domain cloud.reid.ee matched array value at [0]=reid.ee"}
{"level":"debug","ts":1554723612.9332013,"msg":"CaptureWriter.Write set w.StatusCode Ƒ"}
{"level":"debug","ts":1554723612.9341297,"msg":"Request handled successfully: 401"}
```

Now, I've been trying all manner of variations on the setting the `Host` header theme as mentioned in `README.md` without success. I'm sorry to bother – but can you point me in the right direction?

**Comment by bnfinet** [comment]
Try two things quick..

Remove..

proxy_set_header Host cloud.reid.ee;

From the /validate block

And try v0.5.6

There may be a bug there in the most recent release.

I'll look at your config a bit closer later today from my machine.

**Comment by bnfinet** [comment]
@andrewreid the config looks generally with the exception of the `proxy_set_header Host cloud.reid.ee;` noted above.

Please use `v0.5.9` pushed today

**Comment by krishnam-ntnx** [comment]
getting errors during build for v0.5.9. I also have this too many redirects issue so checking if this newer version will fix it. 
./main.go:31:21: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
./main.go:32:21: cfg.Cfg.FastLogger undefined (type cfg.config has no field or method FastLogger)

**Comment by bnfinet** [comment]
Travis tests for v0.5.9 are passing including build.  That seems odd, like
the 'cfg' package was not updated. Have your updated your code base?  What's
your build command? You're running from docker or binary?

Please do keep us updated.

**Comment by andrewreid** [comment]
Thanks for your super speedy assistance, @bnfinet – I've solved my problem. Well, I should say, your commit solved my problem!

Of note, after upgrading to 0.5.9, the issue was not solved with nginx configuration change you suggested. With `proxy_set_header Host cloud.reid.ee` removed, vouch complained about the host `172.16.1.82:9090` not being in the allowed domains:

```
{"level":"error","ts":1554801382.7945857,"msg":"http header 'Host: 172.16.1.82:9090' not authorized for configured `vouch.domains` (is Host being sent properly?)"}
{"level":"warn","ts":1554801382.7965245,"msg":"domain 172.16.1.82:9090 not found in any domains [reid.ee]"}
```

Changing my nginx configuration around for `/validate` to include `proxy_set_param Host cloud.reid.ee` fixed things.

Given that, can I offer a pull request for `README.md` that reflects the requirement that the `Host` header being sent for `/validate` be inside `vouch.domains`?

**Comment by bnfinet** [comment]
Hmmm.

Why isn't cloud.reid.ee getting passed by nginx?  Are you using just the IP
address in the browser?

**Comment by krishnam-ntnx** [comment]
> ests for v0.5.9 are passing including build. Tha

I am running from the source. I was able successfully run the previous build. is there particular go version i need to use? i have "go version go1.10.1 linux/amd64"

drwxr-xr-x.  9 root root 4096 Apr  9 20:55 vouch-proxy-0.5.9
[root@ip-172-1-41-28 src]# cd vouch-proxy-0.5.9/
[root@ip-172-1-41-28 vouch-proxy-0.5.9]# go get ./...
# vouch-proxy-0.5.9
./main.go:31:21: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
./main.go:32:21: cfg.Cfg.FastLogger undefined (type cfg.config has no field or method FastLogger)
# vouch-proxy-0.5.9/handlers
handlers/handlers.go:54:19: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
handlers/handlers.go:55:19: cfg.Cfg.FastLogger undefined (type cfg.config has no field or method FastLogger)
# vouch-proxy-0.5.9/pkg/cookie
pkg/cookie/cookie.go:13:18: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/cors
pkg/cors/cors.go:9:18: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/domains
pkg/domains/domains.go:11:18: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/jwtmanager
pkg/jwtmanager/jwtmanager.go:33:18: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/model
pkg/model/model.go:35:15: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/response
pkg/response/response.go:13:18: cfg.Cfg.FastLogger undefined (type cfg.config has no field or method FastLogger)
# vouch-proxy-0.5.9/pkg/timelog
pkg/timelog/timelog.go:17:15: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
# vouch-proxy-0.5.9/pkg/transciever
pkg/transciever/client.go:22:18: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
[root@ip-172-1-41-28 vouch-proxy-0.5.9]# go build
# vouch-proxy-0.5.9
./main.go:31:21: cfg.Cfg.Logger undefined (type cfg.config has no field or method Logger)
./main.go:32:21: cfg.Cfg.FastLogger undefined (type cfg.config has no field or method FastLogger)

**Comment by bnfinet** [comment]
is your old source (`v0.5.8`) still at `~/go/src/github.com/vouch/vouch-proxy`?

what does
`cd ${GOPATH}/src/github.com/vouch/vouch-proxy && git tag | tail --lines=1` show?

**Comment by krishnam-ntnx** [comment]
cd /root/go/src/github.com/vouch/vouch-proxy && git tag | tail --lines=1
v0.5.9

i am able to run the build now. i cleaned up the go installation and ran the build it worked. Thank you for your help. I will be testing the redirect issue that is the main one to solve :-)

**Comment by andrewreid** [comment]
> Hmmm. Why isn't the header `Host: cloud.reid.ee` getting passed by nginx? Are you using just the IP address in the browser? 

I'm assuming that without the `Host:` header explicitly set otherwise, nginx is using the hostname of the `proxy_pass` URL, which in this case is `http://172.16.1.82:9090`. 

Is this simply the expected behaviour in this instance? Looking at `ValidateRequestHandler()` in [handlers.go](https://github.com/vouch/vouch-proxy/blob/7954ed863e05298739a7b702ba35345ef41477b0/handlers/handlers.go#L186), it seems as though it's specifically looking for the `Host:` header to match something inside `vouch.domains`.

> Does anything change if you remove `internal`?

Nope. If I remove `internal` and `proxy_set_header Host cloud.reid.ee`, I return to having `domain 172.16.1.82:9090 not found in any domains [reid.ee]"` errors. My understanding of nginx's `internal` directive was that it simply prevented external requests to the path in question, only allowing internal redirects.

**Comment by bnfinet** [comment]
What is the requested URL in the browser?  What browser are you using?  What URL including host are you seeing in the nginx access logs and the vouch proxy log?

`proxy_pass` does not set the `Host` header, it only passes the request.  The original Host header will be passed unless you explicitly modify it with `proxy_set_header Host cloud.reid.ee`

**Comment by andrewreid** [comment]
> What is the requested URL in the browser? 

https://cloud.reid.ee/sonarr

> What browser are you using? 

Safari and Chrome.

> What URL including host are you seeing in the nginx access logs and the vouch proxy log?

nginx access log doesn't show a hostname in the default configuration, as far as I can tell, but vouch logs show the `Host` for the request. With `proxy_set_header Host cloud.reid.ee` set, I see corresponding hostname in the logs:

```
{"level":"info","ts":1554852286.1677315,"msg":"|200| 80.669588ms /validate","statusCode":200,"request":248,"latency":0.080669588,"avgLatency":0.064478638,"ipPort":"10.42.52.172:56368","method":"GET","host":"cloud.reid.ee","path":"/validate","referer":"https://cloud.reid.ee/sonarr"}
```

If I remove the `proxy_set_header` directive, on initial redirect to `/validate` by `auth_request`, I see complaints about the `$proxy_host` being outside of `vouch.domains`:

```
{"level":"warn","ts":1554853036.6469402,"msg":"domain 172.16.1.82:9090 not found in any domains [reid.ee]"}
{"level":"info","ts":1554853036.654698,"msg":"|401| 21.921339ms /validate","statusCode":401,"request":262,"latency":0.021921339,"avgLatency":0.065550747,"ipPort":"10.42.52.172:59648","method":"GET","host":"172.16.1.82:9090","path":"/validate","referer":"https://cloud.reid.ee/sonarr"}
```

Completing authentication to Google is successful, but then results in a redirect loop. Inspecting vouch logs shows the issue is to do with the `Host:` header:

```
{"level":"error","ts":1554853134.9598646,"msg":"http header 'Host: 172.16.1.82:9090' not authorized for configured `vouch.domains` (is Host being sent properly?)"}
{"level":"warn","ts":1554853134.961415,"msg":"domain 172.16.1.82:9090 not found in any domains [reid.ee]"}
```

> `proxy_pass` does not set the `Host` header, it only passes the request. The original Host header will be passed unless you explicitly modify it with `proxy_set_header Host cloud.reid.ee`

That doesn't seem to be what the [nginx documentation](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers) suggests:

_"By default, NGINX redefines two header fields in proxied requests, “Host” and “Connection”, and eliminates the header fields whose values are empty strings. “Host” is set to the $proxy_host variable, and “Connection” is set to close."_

To that end, my reading is that nginx is doing what it's meant to do and rewriting the `Host:` header when it proxies the request to vouch to the hostname of the vouch proxy (i.e., `$proxy_host`, which in my case is `http://172.16.1.82:9090`).

**Comment by krishnam-ntnx** [comment]
i am still having redirects issue, just attaching logs , can you see anything here? 

I am trying to integration with OKTA, using OAUTH

Here is my login and it keeps redirecting after getting http code 200 from the identity provider. Here is the log. If you need more information i can add but here is the log extract.

I have similar ngnix config as andrew,   application request is on devops.stage.com , intercepted the auth-request, routed to login.stage.com (vouch proxy) and once authenticated routes back to devops.stage.com.  I think it is problem with vouch config somewhere , need your help here.

2019-04-10T00:38:09.358Z	WARN	domain login.stage.com not found in any domains []
2019-04-10T00:38:09.358Z	INFO	|401|   80.026µs /validate	{"statusCode": 401, "request": 19, "latency": "80.026µs", "avgLatency": "64.692098ms", "ipPort": "127.0.0.1:38204", "method": "GET", "host": "login.stage.com", "path": "/validate", "referer": ""}
2019-04-10T00:38:09.433Z	WARN	domain login.stage.com not found in any domains []
2019-04-10T00:38:09.433Z	INFO	|200|  566.976µs /login	{"statusCode": 200, "request": 20, "latency": "566.976µs", "avgLatency": "61.485842ms", "ipPort": "127.0.0.1:38206", "method": "GET", "host": "login.stage.com", "path": "/login", "referer": ""}
2019-04-10T00:38:14.408Z	INFO	OpenID userinfo body: %!(EXTRA string={"sub":"00uhkumqcm8aFOaYn0h7","email":"kri@gmail.com","email_verified":true})
2019-04-10T00:38:14.409Z	WARN	domain login.stage.com not found in any domains []
2019-04-10T00:38:14.410Z	INFO	|200| 378.454854ms /auth	{"statusCode": 200, "request": 21, "latency": "378.454854ms", "avgLatency": "76.579604ms", "ipPort": "127.0.0.1:38208", "method": "GET", "host": "login.stage.saas.nutanix.com", "path": "/auth", "referer": "https://login.stage.com/login?url=https://devops.stage.com/kibana&vouch-failcount=&X-Vouch-Token=&error="}
2019-04-10T00:38:18.249Z	ERROR	no jwt found in request

**Comment by andrewreid** [comment]
@krishnam-ntnx is `stage.com` in `vouch.domains`? Can you share your `config.yml`?

**Comment by andrewreid** [comment]
My apologies, I didn't see the attachment.

You've specified `domain:` not `domains:` (note the 's') in your config.yml. Try changing that and restarting vouch.

**Comment by krishnam-ntnx** [comment]
> My apologies, I didn't see the attachment.
> 
> You've specified `domain:` not `domains:` (note the 's') in your config.yml. Try changing that and restarting vouch.

okay corrected the domain part to domains, still the same problem.  I am attaching the logs and also my nginx config.
"no jwt found in request"

domains: 
  - stage.com



[nginix_vouch.txt](https://github.com/vouch/vouch-proxy/files/3061595/nginix_vouch.txt)
[new_log_vouch.txt](https://github.com/vouch/vouch-proxy/files/3061582/new_log_vouch.txt)

**Comment by bnfinet** [comment]
Instead of attachments could you please use hastebin.com or gists

**Comment by krishnam-ntnx** [comment]
Added logs and config here.
https://gist.github.com/krishnam-ntnx/5b2356e97f86949829d11534f8b383e9
https://gist.github.com/krishnam-ntnx/dc49a8452f87ce8fa94715e84444bb4d

**Comment by krishnam-ntnx** [comment]
Any help here?  Validation is 100% successful but it goes into a loop after that.

I have the location set exactly like this after successful auth

location /kibana {
		proxy_pass http://mogul.reid.ee:8989;
		proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
		auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
	}

not sure what is missing. I am not able to debug this problem.

**Comment by andrewreid** [comment]
Adding `logLevel: debug` might provide a bit more insight into what’s causing the redirect loop between `/validate` and `login` — it’s not immediately clear to me from the information you’ve provided.

**Comment by krishnam-ntnx** [comment]
Attaching the debug log @andrewreid 

https://gist.github.com/krishnam-ntnx/f252e943ec771dea4398bd3732f6812b

**Comment by andrewreid** [comment]
I can’t see your vouch config right now on this device, but I have read references in other issues to problems with the cookie. 

Have you tried removing all jwt/cookie config from your `config.yml` so vouch just uses its defaults?

**Comment by krishnam-ntnx** [comment]
Here is my current vouch config file
https://gist.github.com/krishnam-ntnx/1b2a61adb8d25fb2b861bb8848c1ddb3

**Comment by artagel** [comment]
I suspect it might be this line in your nginx config:
`return 302 https://login.stage.com/login?url=https://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;`

Notice the url=https://?  Change that to $scheme://

**Comment by artagel** [comment]
Also, what url are you trying to reach? 
In your log it shows: https://devops.stage.com/, but you don't have that path exposed.  You only have /kibana and some others exposed.

**Comment by krishnam-ntnx** [comment]
yes this is the path, https://devops.stage.com/, it should show be the welcome index.html of nginx. I have tried https://devops.stage.com/kibana as well same redirect issue.

I am looking at the return 302 path as you suggested, will get back to you after testing.

**Comment by artagel** [comment]
I find it useful to watch the network tab in the debug area of the browser.  You'll be able to see if cookies get stored and push down in requests, etc.  Also, check to see if you have a cookie set in your browser for your domain.  It should be called VouchSession I believe.

**Comment by krishnam-ntnx** [comment]
Still the same problem both VouchCookie and VouchSession are set properly, infact while in this loop when i go to /validate in new tab i get http200 ok.  I am not able to understand when there is successful auth why the loop is continuing without honoring location blocks which has auth_request_set data

"VouchCookie=H4sIAAAAAAAA_2zMzY6qMBgA0DcyUKlXl0qkfk0p8Q9aNje0JUOxrSSIDjz9ZPazPJvTzrRTRNvCUrgvEHMLI4QL1ils4DGIMqW7VTvTWKNyVj571VfYgH_NjeDPXzPPn02Fo4ZkoxF0OBMcG5JNjfiaJNq9wH6sRi6qRW4LN9qalEitDwsLPJKVcSzwTop8UqGMZIWHNsW9QpFlKR0VMoOyeDEkC_UVL7LKFub_-NeXrkb3SaOs0zOejLh0yruEef5WV2pYSl172tuiP8b8dsb5TSe8f4zg3aJn2ICr36biTwjRiomP7pPA0j0vJn5aD54kgLajb913K_9tz_7-X97yg-LHnwAAAP__8I2EsDwBAAA=; Path=/; Domain=login.stage.com; Max-Age=14400; HttpOnly"

"VouchSession=MTU1NDkwMzQ2OXxEdi1CQkFFQ180SUFBUkFCRUFBQV85Yl9nZ0FEQm5OMGNtbHVad3dPQUF4eVpYRjFaWE4wWldSVlVrd0djM1J5YVc1bkRDMEFLMmgwZEhBNkx5OWtaWFp2Y0hNdWMzUmhaMlV1YzJGaGN5NXVkWFJoYm1sNExtTnZiUzlyYVdKaGJtRUdjM1J5YVc1bkRDMEFLMmgwZEhBNkx5OWtaWFp2Y0hNdWMzUmhaMlV1YzJGaGN5NXVkWFJoYm1sNExtTnZiUzlyYVdKaGJtRURhVzUwQkFJQUFnWnpkSEpwYm1jTUJ3QUZjM1JoZEdVR2MzUnlhVzVuREM0QUxGSjRUVkp6U1VGelRWaFlSRXBXYTJkcFJHNURkbTVHWmxKVVF6UkJTR0YzU201eGFFNW9WVGw2ZEVVOXxn8neCfIHC6Txx3SxBYM6pYwj_umtJ4yBWkjQ8fx0i7Q==; Path=/; Expires=Fri, 10 May 2019 13:37:49 GMT; Max-Age=2592000; HttpOnly"

**Comment by artagel** [comment]
Yeah, I saw the 200OK, which is actually good.  Do your nginx logs show any hints?

**Comment by bnfinet** [comment]
> > `proxy_pass` does not set the `Host` header, it only passes the request. The original Host header will be passed unless you explicitly modify it with `proxy_set_header Host cloud.reid.ee`
> 
> That doesn't seem to be what the [nginx documentation](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers) suggests:
> 
> _"By default, NGINX redefines two header fields in proxied requests, “Host” and “Connection”, and eliminates the header fields whose values are empty strings. “Host” is set to the $proxy_host variable, and “Connection” is set to close."_
> 
> To that end, my reading is that nginx is doing what it's meant to do and rewriting the `Host:` header when it proxies the request to vouch to the hostname of the vouch proxy (i.e., `$proxy_host`, which in my case is `http://172.16.1.82:9090`).
> 
> If we want nginx to pass the original `Host:` header on (i.e., the `server_name`), we'd need to use something like `proxy_set_header Host $http_host`.

@andrewreid OMG you're right, I had an entirely different understanding.  I'll update the README shortly.

**Comment by krishnam-ntnx** [comment]
Thank you @bnfinet @artagel  and @andrewreid  for trying to help me out on this issue.
My issue got resolved 
in the location = /validate
proxy_pass http://login.stage.com;
           #proxy_pass http://127.0.0.1:9090;

I used the domain i have set in the vouch config instead of ip address,  and redirect issue is solved. I am successfully logged in.

**Comment by bnfinet** [comment]
Oh I'm so glad.  Hope it's smooth sailing from here.
