### ISSUE TITLE
Improve debug log in handlers/handlers.go

### ISSUE THREAD

**Issue by mmorsky** [vouch/vouch-proxy#106]
Hi,

I've been playing with a test setup of Nginx/Vouch, it's a really nice tool and you have done great job with it! There's one minor thing that really threw me off while trying to debug why my setup was not working and it's a log line in `handlers/handlers.go#VerifyUser` function. 

In the last `else` block, which I assume is the "everything is ok block" there's a log line "no domains configured", which I don't think is true based on the previous if blocks (or it _could_ be true, but not necessarily). I was assuming my domains were configured wrong or missing and spend quite a while trying to figure out why.

```
func VerifyUser(u interface{}) (ok bool, err error) {
...
...
  } else {
      ok = true
      log.Debug("no domains configured")
  }
  return ok, err
}
``` 
Am I missing something, or could this log be changed to something like "User verified" or something else. I can give this a go my self too but I'm not too familiar with Go language.

**Comment by bnfinet** [comment]
Thanks @mmorsky, yeah that is a confusing Debug message.

There's a discussion in #82 going on about that specific block of VerifyUser and the general configuration of Vouch Proxy.  Would you care to chime in on that thread?

I'm going to close this and will make note in 382 that this message should be changed.

**Comment by mmorsky** [comment]
Ah, great! Thanks @bnfinet!
