### ISSUE TITLE
Run vouch-proxy as systemd

### ISSUE THREAD

**Issue by LickABrick** [vouch/vouch-proxy#110]
Does anyone have a systemd file to run vouch-proxy as a service?
I've tried building my own, but I am not very familiar with creating systemd files.

**Comment by artagel** [comment]
Not offhand, but I plan on adding some in some documentation and example updates I'm working on in the next week or two

**Comment by LickABrick** [comment]
> Not offhand, but I plan on adding some in some documentation and example updates I'm working on in the next week or two

Damn your quick. I just posted this, took a shit and you already replied.
Glad to hear you're working on this, Vouch Proxy has been working pretty well for me :)

**Comment by artagel** [comment]
Out of curiosity...Are you running a compiled binary or go run main.go, ./do.sh run?

**Comment by LickABrick** [comment]
I did what is mentioned in 'Running from source'

```
go get ./...
  go build
  ./vouch-proxy
```

**Comment by artagel** [comment]
This will work in a pinch.
```
[Unit]
Description=Vouch
After=vouch.service

[Service]
Type=simple
WorkingDirectory=/root/vouch-proxy
ExecStart=/root/vouch/vouch-proxy
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=default.target
```
Warning, it runs as root.  If you want to run it as another user you can run it as a user: https://gist.github.com/torch2424/a2d4632831db4327b02d839147685007

**Comment by bnfinet** [comment]
FYI - The preferred build method is currently

./do.sh build

Which will add the version and other meta data to the binary.

Glad to hear you're enjoying Vouch Proxy!

**Comment by LickABrick** [comment]
@artagel Thanks it works, you got a typo in ExecStart though, it needs to be /root/vouch-proxy/vouch-proxy

**Comment by artagel** [comment]
> @artagel Thanks it works, you got a typo in ExecStart though, it needs to be /root/vouch-proxy/vouch-proxy

Yeah I don't use the same path because I have several versions running.  But yes good catch.

**Comment by bnfinet** [comment]
wow, pretty sweet!

I'll link to this thread from the README
