### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by eeebalu** [vouch/vouch-proxy#116]
Not sure what was the configuration problem. I have been struggling to get it working. Everything works great by commenting auth_request line in nginx configuration (https). I have valid certs and both vouch and application runs in the same server. Okta login works and finally it is always redirecting to invalid character '<' looking for the beginning of the value. In the Nginx log I am getting 400 and vouch log, I am getting page not found error. Can you please suggest?

**Comment by eeebalu** [comment]
Everything runs in docker (application, vouch proxy and nginx) inside EC2.
Below is the nginx configuration,

upstream private-domain.company.com {
        server 10.90.139.44:3838;
}

server {
   listen 80 default_server;
   listen [::]:80 default_server ipv6only=on;
   server_name private-domain.company.com;
   return 301 https://$server_name$request_uri/;
}

server {
   listen 443 ssl;
   server_name private-domain.company.com;

   #alias /usr/share/nginx/public;
   #index index.html index.htm;

   ssl_certificate /etc/nginx/ssl/priviate-domain.cert.crt;
   ssl_certificate_key /etc/nginx/ssl/priviate-domain.cert.key;

   #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   #ssl_prefer_server_ciphers on;
   #ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128:AES256:AES:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK';
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        #ssl_stapling on; # Requires nginx >= 1.3.7
        #ssl_stapling_verify on; # Requires nginx => 1.3.7


   # send all requests to the `/validate` endpoint for authorization
   auth_request /validate;

   location / {
       #proxy_pass http://172.17.0.4:3838;
       #proxy_pass http://172.17.0.4:3838/;
        proxy_pass http://private-domain.company.com;
       #proxy_pass http://private-domain.company.com:3838;
       #proxy_redirect http://172.17.0.4:3838/ https://$host/;
       #proxy_http_version 1.1;
       proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
#    proxy_set_header X-Real-IP  $remote_addr;
#       proxy_set_header Host $http_host;
#    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       #proxy_set_header Upgrade $http_upgrade;
       #proxy_set_header Connection $connection_upgrade;
  #     proxy_read_timeout 20d;
            proxy_http_version  1.1;

            # The following lines enable WebSockets proxying, do not remove them
            # as they are used by Shiny Server to improve user experience
#            proxy_set_header    Upgrade $http_upgrade;
 #           proxy_set_header    Connection $connection_upgrade;

            proxy_connect_timeout 3h;
            proxy_send_timeout 3h;
            proxy_read_timeout 3h;
   }

    location = /validate {
      # forward the /validate request to Vouch Proxy
      #proxy_pass http://172.17.0.3:9090/validate;
      # be sure to pass the original host header
      proxy_set_header Host $http_host;

      # Vouch Proxy only acts on the request headers
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;

      # Vouch Proxy can run behind the same Nginx reverse proxy
      # may need to comply to "upstream" server naming
      proxy_pass http://private-domain-vouch.company.tyson.com;
      # proxy_set_header Host $http_host;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 https://private-domain-vouch.company.tyson.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
        # you usually *want* to redirect to Vouch running behind the same Nginx config proteced by https
        # but to get started you can just forward the end user to the port that vouch is running on
        # return 302 http://vouch.yourdomain.com:9090/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }
}


# vouch.yourdomain.com
upstream private-domain-vouch.company.tyson.com {
        ## Can be connect with "bridge" network
        # vouch-proxy
        server 10.90.139.44:9090;
}
# cert: vouch.yourdomain.com
server {
        server_name private-domain-vouch.company.tyson.com;
        listen 80 ;
        access_log /var/log/nginx/$host-access.log;
        # return 302 to prevent cacheing
        return 302 https://$host$request_uri;
}

server {
    listen 443 ssl http2;

    server_name private-domain-vouch.company.tyson.com;

    ssl_certificate /etc/nginx/ssl/priviate-domain-vouch.cert.crt;
    ssl_certificate_key /etc/nginx/ssl/priviate-domain-vouch.cert.key;

 location / {
                proxy_pass http://private-domain-vouch.company.tyson.com;
        }
}

----> Below is the vouch configuration
vouch:
  logLevel: debug
  #logLevel: info
  listen: 0.0.0.0
  port: 9090

  domains:
  - company.com
#  - private-domain.company.com
#  - private-domain-vouch.company.com
#  - 10.90.139.44


  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  allowAllUsers: true
  #publicAccess: true
  #testing: true


  # domains:
  # each of these domains must serve the url https://vouch.$domains[0] https://vouch.$domains[1] ...
  # so that the cookie which stores the JWT can be set in the relevant domain
  # you usually *don't* want to list every individual website that will be protected
  # if you have siteA.internal.yourdomain.com and siteB.internal.yourdomain.com
  # then your domains should be set as yourdomain.com or perhaps internal.yourdomain.com
  # usually you'll just have one.
  # Comment `domains:` out if you set allowAllUser:true

  jwt:
    # secret: a random string used to cryptographically sign the jwt
    # Vouch Proxy complains if the string is less than 44 characters (256 bits as 32 base64 bytes)
    # if the secret is not set here then..
    # look for the secret in `./config/secret`
    # if `./config/secret` doesn't exist then randomly generate a secret and store it there
    # in order to run multiple instances of vouch on multiple servers (perhaps purely for validating the jwt),
    # you'll want them all to have the same secret
    secret: secret_key_of_more_than_44_characters
    issuer: Vouch
    # number of minutes until jwt expires
    maxAge: 2400
    # compress the jwt
    compress: true

  cookie:
    name: VouchCookie
    domain: company.com
    secure: true
    httpOnly: false
    # Set cookie maxAge to 0 to delete the cookie every time the browser is closed.
    maxAge: 14400

  session:
    # name of session variable stored locally
    name: VouchSession
    # key: a cryptographic string used to store the session variable
    # if the key is not set here then it is generated at startup and stored in memory
    # Vouch Proxy complains if the string is less than 44 characters (256 bits as 32 base64 bytes)
    # you only want to set this if you're running multiple user facing vouch.yourdomain.com instances
    key: secret_key_of_more_than_44_characters

  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI

  db:
    file: data/vouch_bolt.db

  # testing: force all 302 redirects to be rendered as a webpage with a link
  testing: true
  # test_url: add this URL to the page which vouch displays
  #test_url: https://private-domain.company.com
  # webapp: WIP for web interface to vouch (mostly logs)
  webapp: true

oauth:
  provider: oidc
  client_id: xxxx
  client_secret: yyyyyyyyy
  auth_url: https://dev-111111.oktapreview.com/oauth2/uniquekey/v1/authorize
  token_url: https://dev-111111.oktapreview.com/oauth2/uniquekey/v1/token
  user_info_url: https://dev-111111.oktapreview.com/oauth2/uniquekey/userinfo
  scopes:
    - openid
    - email

  # Set the callback URL to the domain that Lasso is running on
  #callback_url: http://private-domain-vouch.company.com:9090/auth
  callback_url: https://private-domain-vouch.company.com/auth

**Comment by bnfinet** [comment]
Please follow these instructions. 

https://github.com/vouch/vouch-proxy#okay-i-looked-at-the-issues-and-have-tried-some-things-with-my-configs-but-i-still-cant-figure-it-out

We'll need to see the logs.  But please do use Hastebin which is much easier to reference by line and copy in order to offer support.

**Comment by bnfinet** [comment]
and set `vouch.testing: true` too please

**Comment by eeebalu** [comment]
nginx default.conf
```
upstream application.company.com {
        server 10.90.139.44:3838;
}

server {
   listen 80 default_server;
   server_name application.company.com;
   return 301 https://$server_name$request_uri/;
}

server {
   listen 443 ssl http2;
   server_name application.company.com;

   #alias /usr/share/nginx/public;
   #index index.html index.htm;

   ssl_certificate /etc/nginx/ssl/app.crt;
   ssl_certificate_key /etc/nginx/ssl/app.key;

   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_prefer_server_ciphers on;
   ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;

   # send all requests to the `/validate` endpoint for authorization
   auth_request /validate;

   location / {
	proxy_pass http://application.company.com;
	proxy_set_header  Host  $host;
	proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
   }

    location = /validate {
      # Vouch Proxy only acts on the request headers
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;


      # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;

      # Vouch Proxy can run behind the same Nginx reverse proxy
      # may need to comply to "upstream" server naming
      proxy_pass http://application-vouch.company.com;
      proxy_set_header Host $http_host;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
#        return 302 https://application-vouch.company.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
	return 302 https://application-vouch.company.com/login?url=$scheme://$http_host$request_uri&lasso-failcount=$auth_resp_failcount&X-Lasso-Token=$auth_resp_jwt&error=$auth_resp_err;

        # you usually *want* to redirect to Vouch running behind the same Nginx config proteced by https  
        # but to get started you can just forward the end user to the port that vouch is running on
        # return 302 http://vouch.yourdomain.com:9090/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }
}


# vouch.yourdomain.com
upstream application-vouch.company.com {
        ## Can be connect with "bridge" network
        # vouch-proxy
        server 10.90.139.44:9090;
}
# cert: vouch.yourdomain.com
server {
        server_name application-vouch.company.com;
        listen 80 ;
        access_log /var/log/nginx/$host-access.log;
        # return 302 to prevent cacheing
        return 302 https://$host$request_uri;
}

server {
    listen 443 ssl http2;

    server_name application-vouch.company.com;

    ssl_certificate /etc/nginx/ssl/app.crt;
    ssl_certificate_key /etc/nginx/ssl/app.key;

 location / {
                proxy_pass http://application-vouch.company.com;
		proxy_set_header Host $http_host;
        }
}

```
vouch config.yml
```

-------------------------

#
# redacted Vouch Proxy config/config.yml
# 2019-05-03
#

vouch:
  logLevel: debug
  listen: 0.0.0.0
  port: 9090

  domains:
  - +++++.+++

  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  allowAllUsers: true


  # testing: force all 302 redirects to be rendered as a webpage with a link
  testing: true
  # webapp: WIP for web interface to vouch (mostly logs)
  #webapp: true

oauth:
  provider: oidc
  client_id: XXXXXXXXXXX
  client_secret: XXXXXXXXXXX
  auth_url: https://+++-++++++.+++++++++++.+++/oauth2/ausk8mtgyn2kSipz40h7/v1/authorize
  token_url: https://+++-++++++.+++++++++++.+++/oauth2/ausk8mtgyn2kSipz40h7/v1/token
  user_info_url: https://+++-++++++.+++++++++++.+++/oauth2/ausk8mtgyn2kSipz40h7/userinfo
  scopes:
    - openid
    - email

  # Set the callback URL to the domain that Lasso is running on
  #callback_url: http://++++++-+++-+++++.+++++.+++:9090/auth
  callback_url: https://++++++-+++-+++++.+++++.+++/auth

-------------------------

```
Currently Hastebin is not working, so used gist logs
Here are vouch logs: https://gist.github.com/eeebalu/872ee98984c4ca8b5b4aa950ed54e0e9
Here are the ngnix logs: https://gist.github.com/eeebalu/39ee6ec1f4cadfbe948fc0fc37e54246

**Comment by bnfinet** [comment]
as per the instructions in the README, please edit your comment and post your configs to gists as well

**Comment by eeebalu** [comment]
Added the config files in gists. Can you please look and suggest?

**Comment by bnfinet** [comment]
Thanks much for that.  I'm traveling through Tuesday and will look at it
first thing after I get back.

**Comment by eeebalu** [comment]
Thank you! We are running in EC2 and vouch-proxy, nginx, and actual application runs in the same EC2 inside Docker containers in different ports.
Looking forward for your suggestions...

**Comment by eeebalu** [comment]
Hi can you please look into it when you get a chance?

**Comment by bnfinet** [comment]
Sorry for the delay..

it would appear that your `userinfo` url is not returning userinfo, it's returning an HTML page.

Be sure that you've enabled an Authorization Server in Okta
https://developer.okta.com/authentication-guide/implementing-authentication/set-up-authz-server/
https://developer.okta.com/docs/api/resources/oidc/

The logs you posted do not appear to have `loglevel: debug` set though you show it set in your config.  Please do post logs that correspond to the config you've provided.

**Comment by moritan** [comment]
hello, 
did you try to add the header "X-Forward-Proto https" ?

vouch-proxy run on http but your public access is on https
 
an extract of my nginx conf ( the set upstream is to bypass docker initialisation problem) :

> 
>set $upstream_auth vouch-proxy;
>        proxy_set_header  X-Forwarded-Proto https;
>        proxy_pass http://$upstream_auth:9090;
>

**Comment by bnfinet** [comment]
@eeebalu feel free to reopen the issue if you care to work on the problem further
