### ISSUE TITLE
AWS Cognito Error

### ISSUE THREAD

**Issue by nilava** [vouch/vouch-proxy#117]
oauth2: cannot fetch token: 405 Method Not Allowed

Getting this error everytime after logging in!

**Comment by bnfinet** [comment]
does your `user_info_url` have a capitalized I in the `userInfo` endpoint as per.. 
https://docs.aws.amazon.com/cognito/latest/developerguide/userinfo-endpoint.html

**Comment by nilava** [comment]
Yes, that's the first that i did

**Comment by bnfinet** [comment]
please follow these instructions to provide more information about what you're seeing
https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests

**Comment by bnfinet** [comment]
@nilava did you resolve your issue?
