### ISSUE TITLE
Provide helm chart

### ISSUE THREAD

**Issue by ksaffarian** [vouch/vouch-proxy#122]
Hi

I noticed there is no helm chart for this package. As you have suggested the required configuration for NGINX Ingress on k8s, I would suggest to publish the proper helm chart too.

Thanks in advance

Kev

**Comment by halkeye** [comment]
I have a helm chart @ https://halkeye.github.io/helm-charts/

**Comment by bnfinet** [comment]
I'll add a link to @halkeye 's helm chart from the README

**Comment by ksaffarian** [comment]
Thanks guys.
