### ISSUE TITLE
Using same port as cockpit

### ISSUE THREAD

**Issue by menathor** [vouch/vouch-proxy#126]
Hi guys

Just started playing around with vouch but running into conflicts with Cockpit (cockpit-project.org). Cockpit also uses port 9090 and is becoming a really popular option for gui-based server management. Maybe it's worth changing vouch's default port in light of that? Might avoid some headaches down the line. Just a suggestion :)

**Comment by bnfinet** [comment]
Thanks for the suggestion and your interest in Vouch Proxy.

If Cockpit or another active project had a registered port with ICANN I could possibly see changing the port, but the overlap with Cockpit seems slight and it is not difficult to change the Vouch Proxy port.

Overall, I'd prefer not to change the port, which would disrupt existing setups.

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=9090
https://www.adminsub.net/tcp-udp-port-finder/9090
