### ISSUE TITLE
Login failure after Token expire

### ISSUE THREAD

**Issue by csckhw303** [vouch/vouch-proxy#128]
I am getting error as below
![image](https://user-images.githubusercontent.com/22225680/59847385-54af5200-9330-11e9-93cf-56106b417ded.png)

"/login too  many redirects for https://example.com/login/loggedIn" after using the application for 15-20 min. Currently, Vouch token expires after 17 min and Salesforce(IDP) session expires 15 min.  Nginx & Vouch are running on the same aws ec2 instance. (It needs to clear cookies to see the slaeforce login screen and log back in.)

SInce the Vouch is not exposed to public, I am using extra proxy pass as below:

location @error401 {
        # redirect to Vouch Proxy for login
         return 302  http://dev.iv.example.com/loginToIdp?url=https://dev.iv.example.com$request_uri/loggedIn&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;

          }
location /loginToIdp {
      proxy_pass http://localhost:9090/login;
 }

It seems that  Vouch try to login after Token expires but fails more than 2 times and throw errors. I appreciate if you provide the idea on this.

Nginx & Vouch configurations are as below:

Nginx  nginx.config file
/////////////////////////////////
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    resolver 10.32.1.155;
    default_type  application/octet-stream;
    include       /etc/nginx/mime.types;
    
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

#################################

Nginx default.config file###############

server {
    listen       80;
    server_name localhost;
    root /usr/share/nginx/html;

    # referece healthcheck file in nginx container /usr/share/nginx/html folder
    location = /healthcheck {
    }

      location /auth {
      proxy_pass http://localhost:9090/auth$is_args$args;
      proxy_redirect off;
    }

    location /loginToIdp {
      proxy_pass http://localhost:9090/login;
    }

    location /SFDCChangePassword  {
        return 302 https://dev-miscg.cs20.force.com/miptest/MIP_ForgotPassword;
    }

    
    location ~* /loggedIn {
        rewrite (.*)/loggedIn  https://dev.iv.example.com/$1 permanent;
    }

    location = /validate {
      internal;
      # forward the /validate request to Vouch Proxy
      proxy_pass http://localhost:9090;

      # be sure to pass the original host header
      proxy_set_header Host dev.iv.example.com;

      # Vouch Proxy only acts on the request headers
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;

    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
         return 302  http://dev.iv.example.com/loginToIdp?url=https://dev.iv.example.com$request_uri/loggedIn&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;

          }

    location ~/api/spg/administration/(.*) {
        # return 301 http://apidns:8084/administration/$1;
        proxy_http_version 1.1;
        auth_request /validate;
        proxy_pass http://apidns:8084/administration/$1?$query_string;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~/api/research/document/(.*) {
        proxy_http_version 1.1;
        auth_request /validate;
        proxy_pass http://apidns:8081/api/mdc/pdf?docId=$1&alt=pdf;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~/api/search/(.*) {
        proxy_http_version 1.1;
        auth_request /validate;
        proxy_pass http://apidns:8081/api/mdc/research?$query_string;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~/api/profile/(.*) {
        proxy_http_version 1.1;
        auth_request /validate;
        proxy_pass http://apidns:8081/api/sfdc/employee?$query_string;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~/api/team/(.*) {
        proxy_http_version 1.1;
        auth_request /validate;
        proxy_pass http://apidns:8081/api/sfdc/team?$query_string;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

  
    location / {
        auth_request /validate;

        proxy_pass http://internal-iport-qa3-dotcms-elb-1111111.us-east-1.elb.amazonaws.com/;
        proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    
    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /error;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

vouch config.yml #######################################
vouch:
  listen: 0.0.0.0
  logLevel: debug
  port: 9090
  domains:
  - dev.iv.example.com

  allowAllUsers: true

  jwt:
     issuer: Vouch
     maxAge: 17
     compress: true

  cookie:
    name: IVAccessJWT

  session:
    name: IVAccessSession

  db:
    file: /tmp/vouch-proxy-testing.db

oauth:
  provider: oidc
  client_id: 11111111111111111111111111111111111111111111111111
  client_secret: 22222222222222222222222222222222222222222222222
  auth_url: https://dev-miscg.cs20.force.com/miptest/services/oauth2/authorize
  token_url: https://dev-miscg.cs20.force.com/miptest/services/oauth2/token
  user_info_url: https://dev-miscg.cs20.force.com/miptest/services/oauth2/userinfo
  scopes: email
  callback_url: https://dev.iv.example.com/auth

########################################################

And I see the error as below from vouch log##########################
- How to format ts as local time (ex. hh/mm/tttt/yyyyyy)? I am not sure the exact log sentence but the below seems to be repeating.

level":"debug","ts":1560919376.5554783,"msg":"Request received : &{GET /login?url=https://dev.iv.example.com//loggedIn&vouch-failcount=&X-Vouch-Token=&error= HTTP/1.0 1 0 map[X-Forwarded-Proto:[https] X-Forwarded-Port:[443] X-Amzn-Trace-Id:[Root=1-5d09bd50-5fb4abae2414b220c160cd83] User-Agent:[Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36] Accept-Encoding:[gzip, deflate, br] Connection:[close] X-Forwarded-For:[141.160.5.251] Upgrade-Insecure-Requests:[1] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Accept-Language:[en-US,en;q=0.9]] {} <nil> 0 [] true localhost:9090 map[] map[] <nil> map[] 127.0.0.1:33302 /login?url=https://dev.iv.example.com//loggedIn&vouch-failcount=&X-Vouch-Token=&error= <nil> <nil> <nil> 0xc42022dd70}"}
{"level":"debug","ts":1560919376.5555184,"msg":"/login"}
{"level":"warn","ts":1560919376.5555265,"msg":"domain localhost:9090 not found in any domains [dev.iv.example.com]"}
{"level":"debug","ts":1560919376.5555465,"msg":"session state set to bohYKeA8XC8pg0PvH5x4bCUnKRPPbCVoLWvDelx8rSI="}
{"level":"debug","ts":1560919376.5555553,"msg":"session requestedURL set to https://dev.iv.example.com//loggedIn"}
{"level":"debug","ts":1560919376.555568,"msg":"saving session"}
{"level":"debug","ts":1560919376.5556402,"msg":"redirecting to oauthURL https://dev-miscg.cs20.force.com/miptest/services/oauth2/authorize?client_id=1111111111111111111111111111111111111111111111111&redirect_uri=https%3A%2F%2Fdev.iv.example.com%2Fauth&response_type=code&scope=email&state=bohYKeA8XC8pg0PvH5x4bCUnKRPPbCVoLWvDelx8rSI%3D"}
{"level":"debug","ts":1560919376.5556538,"msg":"CaptureWriter.Write set w.StatusCode Į"}
{"level":"debug","ts":1560919376.5556674,"msg":"Request handled successfully: 302"}
{"level":"info","ts":1560919376.5556755,"msg":"|302|  150.335µs /login","statusCode":302,"request":73,"latency":0.000150335,"avgLatency":0.009386731,"ipPort":"127.0.0.1:33302","method":"GET","host":"localhost:9090","path":"/login","referer":""}
{"level":"debug","ts":1560919379.0467596,"msg":"Request received : &{GET /validate HTTP/1.0 1 0 map[Connection:[close] User-Agent:[ELB-HealthChecker/2.0] Accept-Encoding:[gzip, compressed]] {} <nil> 0 [] true iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com map[] map[] <nil> map[] 127.0.0.1:33306 /validate <nil> <nil> <nil> 0xc42026c570}"}
{"level":"debug","ts":1560919379.046795,"msg":"/validate"}
{"level":"error","ts":1560919379.0468037,"msg":"no jwt found in request"}
{"level":"warn","ts":1560919379.046811,"msg":"domain iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com not found in any domains [dev.iv.example.com]"}
{"level":"debug","ts":1560919379.0468218,"msg":"CaptureWriter.Write set w.StatusCode Ƒ"}
{"level":"debug","ts":1560919379.046832,"msg":"Request handled successfully: 401"}
{"level":"info","ts":1560919379.0468397,"msg":"|401|   37.464µs /validate","statusCode":401,"request":74,"latency":0.000037464,"avgLatency":0.00926039,"ipPort":"127.0.0.1:33306","method":"GET","host":"iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com","path":"/validate","referer":""}
{"level":"debug","ts":1560919379.0469844,"msg":"Request received : &{GET /validate HTTP/1.0 1 0 map[Accept-Encoding:[gzip, compressed] Connection:[close] User-Agent:[ELB-HealthChecker/2.0]] {} <nil> 0 [] true iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com map[] map[] <nil> map[] 127.0.0.1:33304 /validate <nil> <nil> <nil> 0xc42026c780}"}
{"level":"debug","ts":1560919379.0470028,"msg":"/validate"}
{"level":"error","ts":1560919379.0470088,"msg":"no jwt found in request"}
{"level":"warn","ts":1560919379.047019,"msg":"domain iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com not found in any domains [dev.iv.example.com]"}
{"level":"debug","ts":1560919379.047027,"msg":"CaptureWriter.Write set w.StatusCode Ƒ"}
{"level":"debug","ts":1560919379.047036,"msg":"Request handled successfully: 401"}
{"level":"info","ts":1560919379.0470424,"msg":"|401|   32.874µs /validate","statusCode":401,"request":75,"latency":0.000032874,"avgLatency":0.009137357,"ipPort":"127.0.0.1:33304","method":"GET","host":"iport-dev-nginx-live-elb-c586965e99198220.elb.us-east-1.amazonaws.com","path":"/validate","referer":""}

###################################################

**Comment by bnfinet** [comment]
Could you please follow these instructions and please post your configs and logs to hastebin.com.  It's much easier to find needles in haystacks with a proper paste service.

And  be sure to set `vouch.testing: true`

https://github.com/vouch/vouch-proxy#im-getting-an-infinite-redirect-loop-which-returns-me-to-my-idp-googleoktagithub

**Comment by bnfinet** [comment]
@csckhw303 I'm going to close this for now, please do reach out if you care to reopen

**Comment by ffdybuster** [comment]
I have a similar problem. I'm using vouch-proxy together with [dex](https://github.com/dexidp/dex/). The site that is protected regularly reloads (once per minute), so after `jwt.maxAge` minutes, dex's login screen appears. Now I have multiple tabs of this open, so I end up with a different login screen in every tab. If I log into one of them, I get `/auth Invalid session state.`. I can try to log in again, with the same result.

This happens for me with at least three tabs. With two tabs. I managed to get logged in after some tries (in both tabs). With only one tab, it worked as expected: I get logged in directly.

**Comment by bnfinet** [comment]
@ffdybuster please follow the instructions in the README and open a new issue

**Comment by ffdybuster** [comment]
@bnfinet I created a new issue, but I don't have the setup anymore, so I don't have logs. Feel free to close #167 if you really want the logs.
