### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by macourteau** [vouch/vouch-proxy#129]
I have a server configured exactly as described in the README. It works great when reverse proxying most servers, but it fails when a site requires websockets.

I created a minimal websocket server [here](https://github.com/macourteau/websocket-test) (a Docker image is also available [here](https://hub.docker.com/r/macourteau/websocket-test)). It works correctly if I reverse-proxy it without `auth_request` pointing to vouch-proxy, and it works if I use [pusher/oauth2_proxy](https://github.com/pusher/oauth2_proxy) for `auth_request`, but it does not when using vouch-proxy (which I would prefer using).

The site loads, but the websocket connection fails. Looking at the devtools console when using vouch-proxy, I see:
```
client.js:1 WebSocket connection to 'wss://<snip>/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

**Comment by bnfinet** [comment]
@macourteau could you please post your redacted configs and logs including nginx as per
https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests

I suspect that you should be able to detect the 200 returned from the `auth_request` sidecar (which is what I think you're seeing in the logs) and then issue the `upgrade` back to the browser as shown in...
https://www.nginx.com/blog/websocket-nginx/

**Comment by macourteau** [comment]
I figured I'd try to make a simpler setup from scratch to repro the issue, and WebSockets worked fine in that simpler setup. 🤦‍♂️

I rebuilt my entire setup from scratch, and everything works now - thanks! 🎉

**Comment by bnfinet** [comment]
oh I'm so glad to hear it.

Did you need to do anything specific with your config?  Is there any aspect of your Nginx config which you would be valuable to share for others trying to protect a WebSocket service with Vouch Proxy?

**Comment by macourteau** [comment]
Sure, here's my setup. I'm running [letsencrypt](https://hub.docker.com/r/linuxserver/letsencrypt/) as a reverse proxy, [vouch-proxy](https://hub.docker.com/r/voucher/vouch-proxy) for OAuth2 authentication, and [websocket-test](https://hub.docker.com/r/macourteau/websocket-test) as a demo websocket application.

It's likely that I don't need _everything_ in these configuration blocks, but this works for me. :)

My `vouch.config` file, allows login for some specific gmail addresses:
```
vouch:
  domains:
    - +++++.+++
    - gmail.com
  whiteList:
    - +++++@gmail.com
    - +++++++@gmail.com
  headers:
    accesstoken: X-Vouch-IdP-AccessToken
    idtoken: X-Vouch-IdP-IdToken

oauth:
  provider: google
  client_id: XXXXXXXXXX
  client_secret: XXXXXXXXXX
  callback_urls:
    - https://login.+++++.+++/auth
  preferredDomain: gmail.com
```

Nginx server block for the `login` subdomain:
```
server {
  listen 443 ssl;
  server_name login.+++++.+++;
  include /config/nginx/ssl.conf;

  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_vouch_proxy http://vouch-proxy:9090;
    proxy_pass $upstream_vouch_proxy$request_uri;
    proxy_set_header Host $http_host;
  }
}
```

Main server block, using `websocket-test`:
```
server {
  listen 443 ssl;
  server_name +++++.+++;
  include /config/nginx/ssl.conf;

  resolver 127.0.0.11 valid=30s;
  client_max_body_size 0;

  location = /validate {
    set $upstream_vouch_proxy http://vouch-proxy:9090;
    proxy_pass $upstream_vouch_proxy/validate;
    proxy_set_header Host $http_host;
  
    # vouch only acts on the request headers
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
  
    # these return values are used by the @error401 call
    auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
    auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
    auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
  }
  
  error_page 401 = @error401;
  
  location @error401 {
    return 302 https://login.+++++.+++/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
  }

  location /ws { return 301 /ws/; }
  location /ws/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/vouch.conf;
    include /config/nginx/vouch-user.conf;
    include /config/nginx/websocket.conf;

    set $upstream_websocket_test http://websocket-test:3000;
    rewrite ^/ws(/.*) $1 break;
    proxy_pass $upstream_websocket_test$uri$is_args$args;
  }
}
```

The `ssl.conf` and `proxy.conf` files are the ones shipped with the `letsencrypt` image: [ssl.conf](https://github.com/linuxserver/docker-letsencrypt/blob/6f6c458ea448ca1139c12ef9cbc2b36c820bfe29/root/defaults/ssl.conf), [proxy.conf](https://github.com/linuxserver/docker-letsencrypt/blob/6f6c458ea448ca1139c12ef9cbc2b36c820bfe29/root/defaults/proxy.conf).

The `vouch.conf` file enables Vouch for a location:
```
auth_request /validate;
auth_request_set $auth_cookie $upstream_http_set_cookie;
add_header Set-Cookie $auth_cookie;
```

The `vouch-user.conf` file adds headers with user info for a location:
```
auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;
auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;
proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
proxy_set_header X-Vouch-IdP-AccessToken $auth_resp_x_vouch_idp_accesstoken;
proxy_set_header X-Vouch-IdP-IdToken $auth_resp_x_vouch_idp_idtoken;
```

The `websocket.conf` file enables websockets for a location:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

Hope that helps!

**Comment by bnfinet** [comment]
@macourteau thanks so much for providing your setup!

**Comment by macourteau** [comment]
No worries, thanks for Vouch Proxy! 👍
