### ISSUE TITLE
Healthcheck command line option

### ISSUE THREAD

**Issue by madworx** [vouch/vouch-proxy#130]
It would be nice to have a `-healthcheck` command line option to the ` vouch-proxy` command, to enable some sort of rudimentary healthcheck in a docker-compose environment.

Agreed that if the main pid of the container dies it serves as a quite solid indication that the application has failed, but I'm thinking more in the lines of software-lockups etc which could hopefully be detected with a `--healthcheck` option. (In conjunction with a docker-compose/Dockerfile HEALTCHCHECK statement, naturally)

**Comment by madworx** [comment]
Unless this is something that goes against some unwritten thought pattern or idea around `vouch-proxy`, I'm available to implement such a functionality.

**Comment by bnfinet** [comment]
thanks @madworx that seems reasonable, would happily accept a PR for a `HEALTHCHECK` addition to `Dockerfile` and `Dockerfile.alpine`

You've probably already seen the `/healthcheck` endpoint.  I'd suggest that `./vouch-proxy --healthcheck` make a client request of the `/healthcheck` endpoint and then exit with an error code on poor response
https://github.com/vouch/vouch-proxy/blob/master/handlers/handlers.go#L306-L313

I've sometimes thought `/heahtcheck` could be improved with a test of connectivity to the IdP and perhaps some other examination of the state, but that's a bit outside of the scope of what you're suggesting.

**Comment by madworx** [comment]
Awesome. Yes, I did find it, but in a "docker-compose" context, the healthcheck would need to be a command possible to execute inside the docker container.

I'll get on working on it :)

**Comment by madworx** [comment]
And I agree on your sentiment that it "could" attempt some other sanity checks, but alas, there's only so much you can validate outside of your own scope/domain.

All in all, I just feel that a HEALTHCHECK stating at least something is > no healthcheck :D

**Comment by bnfinet** [comment]
@madworx thanks for the contribution!
