### ISSUE TITLE
Docker-Compose with NGINX in front of App and Vouch containers

### ISSUE THREAD

**Issue by pipersniper** [vouch/vouch-proxy#131]
Hi all,

Having trouble getting a dockerized setup working. My goal is to run docker-compose to stand up a single instance of NGINX to reverse proxy both Vouch and my web app. I got everything working with just NGINX and my web app prior to adding Vouch into the mix, at which point I seem to have broken things. When I browse to http://localhost, it appears to be redirecting me per the `location @error401` block to `http://vouch:9090/validate/login?url=http://localhost/&vouch-failcount=&X-Vouch-Token=&error=` but the parameters are missing, and the redirect fails to resolve. While the basic NGINX config without Vouch worked, I won't claim that I'm a whiz with NGINX - more that I've been lucky with following some examples out there. My suspicion is that my problem is in the `@error401` block but I'm not sure how to resolve it.

Also, worth noting that for now I'm not running with SSL while I try to get this to work - I figured I'd introduce one thing at a time :)

Without further ado, a gist with my relevant data:

[Gist](https://gist.github.com/pipersniper/2e0db74bdd42fad0127f53908b853d87)

**Comment by bnfinet** [comment]
Could you please review the README regarding trouble shooting and modify your issue to use a paste service such as hastebin.com

And please set 'vouch.testing: true'

**Comment by pipersniper** [comment]
I tried that at first but unfortunately the paste services I'm aware of are all blocked at my office - I'll have to do that this evening if I get a chance.

I moved the testing: true block inside of the vouch heading in the config.yml file and got the same output in the logs, for whatever that's worth.

**Comment by bnfinet** [comment]
How about gists?  Something that provides like numbers and preserves spacing please.

**Comment by pipersniper** [comment]
Ah - fair enough. Does this work?

[Gist](https://gist.github.com/pipersniper/2e0db74bdd42fad0127f53908b853d87)

**Comment by bnfinet** [comment]
Thanks, that helps considerably with troubleshooting.

> and the redirect fails to resolve

Have you configured it to resolve?

If http://vouch:9090  is not resolvable by your browser, you can try modifying the 302 redirect to reference http://localhost:9090, or modify your `/etc/hosts` file to set `vouch` to a local ip address (probably `127.0.0.1`) 

If you're not seeing the vars from L19-22 set properly try copying those into the `@error401` block
https://gist.github.com/pipersniper/2e0db74bdd42fad0127f53908b853d87#file-proxy-conf-L19-L22

I haven't used compose in a couple years so perhaps there's a nuance of the networking I'm not appreciating but I suspect your issue is DNS related.

**Comment by pipersniper** [comment]
You were right about the DNS thing, I just was struggling to wrap my head around how to send data to the vouch container with a redirect, since most configs I've written thus far are just `proxy_pass http://<container-name>:<port>`

I tried both options for configuring the redirect to resolve, it appears to resolve now (but the resulting page only says `404 page not found`) either way. For now, I'm leaving it with the modified 302 redirect to localhost.

I tried the suggestion of copying lines 19-22 into the `location @error401` block with no luck - the vars aren't set in the redirect url, and I'm getting that 404 error. I don't see anything new in the logs unfortunately.

**Comment by bnfinet** [comment]
this line should reference `/login`, not `/validate/login`
https://gist.github.com/pipersniper/2e0db74bdd42fad0127f53908b853d87#file-proxy-conf-L29

**Comment by pipersniper** [comment]
Would help if I could read :) Anyway, progress! With vouch.testing set to true, I got prompted to login with okta, and then forwarded on to the test site properly. Once I turned off testing I got stuck in a redirect loop. Looks like there are some issues  about this already logged, I'll take a look there first but might come back.

**Comment by bnfinet** [comment]
glad to hear it.  I'd bet what you're experiencing now is issue is cookie related..
https://github.com/vouch/vouch-proxy#im-getting-an-infinite-redirect-loop-which-returns-me-to-my-idp-googleoktagithub

**Comment by pipersniper** [comment]
Ok, so my oauth.callback_url is set to http://localhost/auth. 

When I browse to http://localhost to start everything, the localhost network request has the Host header set to localhost.

The request initiated by the 302 redirect has the Host header set to localhost:9090. 

Could the port number be messing with things? I'm wondering if I need to make a fake domain that I can resolve in order to test this rather than just using localhost. I've noticed I'm still not getting the vars from L19-22 of the proxy config in the redirected url, even after moving them into the `@error401 block`.

**Comment by bnfinet** [comment]
have you tried using developer tools in the browser to inspect the cookie?  What domain is the cookie getting set into (I'm guessing its `vouch`)  If its not `localhost` then `localhost` will never see the cookie and can't forward it along in the sidecar call to `/validate`

**Comment by pipersniper** [comment]
Yeah, domain on the VouchSession cookie is set to localhost. Everything __looks__ right to me here - does anything jump out at you?
<img width="1920" alt="Screen Shot 2019-06-28 at 11 34 13 AM" src="https://user-images.githubusercontent.com/26089489/60353773-bc9d1280-9998-11e9-8162-ef538df1e9c4.png">

**Comment by bnfinet** [comment]
that's the Session cookie used to store the URL which you will be forwarded to after successful login, not the Vouch cookie which stores the JWT.

Please post refreshed logs and config to a gist.

**Comment by pipersniper** [comment]
Certainly: [New Gist](https://gist.github.com/pipersniper/3cde4501d83e5daf6bb3518bdaf354eb)

**Comment by bnfinet** [comment]
Until you get Vouch Proxy running behind Nginx you'll need to have your `callback_url` as `localhost:9090/auth` 
https://gist.github.com/pipersniper/3cde4501d83e5daf6bb3518bdaf354eb#file-config-yml-L18

**Comment by pipersniper** [comment]
That did it! Thanks so much for the help!
