### ISSUE TITLE
Does OAuth OpenID Connect Config.yml support multiple callback_urls?

### ISSUE THREAD

**Issue by jayb1122** [vouch/vouch-proxy#133]
Running Vouch Proxy in a docker swarm where any of the swarm member VMs may be running or not. If callback_url is set to a specific VM that happens to be unavailable (for any reason), then the callback fails. I tried adding multiple callback_url entries but vouch proxy was unhappy. Using keycloak as the authentication server and it does support multiple entries as does Okta. Any ideas? Maybe I'm doing something wrong.

Thanks!
Jay

# vouch config
# bare minimum to get vouch running with OpenID Connect (such as okta)

vouch:
  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  domains:
  - yourdomain.com
  - yourotherdomain.com

  # - OR -
  # instead of setting specific domains you may prefer to allow all users...
  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  # allowAllUsers: true

oauth:
  # Generic OpenID Connect
  # including okta
  provider: oidc
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxx
  auth_url: https://{yourOktaDomain}/oauth2/default/v1/authorize
  token_url: https://{yourOktaDomain}/oauth2/default/v1/token
  user_info_url: https://{yourOktaDomain}/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
    - profile
callback_url: http://vouch.yourdomain.com:9090/auth

**Comment by libussa** [comment]
Not in its current form, no
https://github.com/vouch/vouch-proxy/issues/79

**Comment by bnfinet** [comment]
yes that's right, redundant with #79 
@jayb1122 @libussa lets take the conversation there please
