### ISSUE TITLE
Customize messaging?

### ISSUE THREAD

**Issue by nromanel** [vouch/vouch-proxy#136]
Hi,

Could you provide any guidance on customizing responses? Specifically looking to update the response when a user logs in but is not on the whitelist.

Thanks!

**Comment by bnfinet** [comment]
Hi @nromanel 

That certainly could be improved upon.

Currently the error is generated here..
https://github.com/vouch/vouch-proxy/blob/master/handlers/handlers.go#L481
With the call to `RenderIndex(w, msg)` and the `Msg` var is inserted into this template..
https://github.com/vouch/vouch-proxy/blob/master/templates/index.tmpl#L21

You could customize the templates in a fork or perhaps in a `Dockefile` which uses `FROM voucher/vouch-proxy`. `vouch-proxy` looks for the template at `$VOUCH_ROOT/templates/index.tmpl` which defaults to wherever the binary runs from.  If you set VOUCH_ROOT you'll need to also have `$VOUCH_ROOT/config/config.yml` in place.

Feel free to suggest any improvements in this setup.  I haven't put much thought into this aspect of the flow in a while.

**Comment by nromanel** [comment]
Thanks for the quick reply! I'll start poking around.
