### ISSUE TITLE
supporting passing basic-auth

### ISSUE THREAD

**Issue by Gauravshah** [vouch/vouch-proxy#143]
**Describe the problem**
Is there a way to pass authentication info as http basic auth instead of just headers to downstream application ?

**Additional context**
We are moving from bitly oauth proxy to vouch. There are multiple applications that do not support headers based auth for example zeppelin. https://zeppelin.apache.org/docs/0.8.0/setup/security/shiro_authentication.html . It does support use of http basic auth, we did use it when we were using https://github.com/bitly/oauth2_proxy which supported an option for `pass-basic-auth` .

**Comment by artagel** [comment]
Not that I am aware of. Vouch doesn’t capture the credentials, that is the auth provider, so vouch wouldn’t have any way to pass down the basic auth. If somehow your auth app would pass back the basic auth to vouch, then you could pass it down using nginx.

**Comment by aaronpk** [comment]
You would never want Vouch to pass credentials back, and in many cases that would be impossible.

But, you can configure nginx to set the HTTP Authorization header to the username returned by Vouch and a blank or hard coded password. Your backend would then look for the username part of HTTP Basic auth and it would work. This is doable right now with some nginx config, no code changes necessary. I don't have a setup right now to try it and tell you exactly how to do it, but maybe someone else can.

**Comment by Gauravshah** [comment]
@aaronpk I should have explained better. I do not want to send back credentials. I want to send back username to downstream application so that it can identify who is authenticated. One way is to send via headers which vouch supports. Other way is to send via the Authorization header with a blank or dummy password.

Yes I also assumed that nginx should be able to read header sent from vouch and convert it to Authorization header. The problem is that Authorization header is suppose to be base64 encoded and nginx doesn't seem to support that kind of header manipulation. I'll try looking more from nginx route.

**Comment by Gauravshah** [comment]
@artagel my question was instead of using `gaurav` as header , can it send `base64_encoded("gaurav:dummy")` so that at nginx I can use it as authorization header

**Comment by aaronpk** [comment]
Yes great, I'm glad we're on the same page. I thought there was a base64 function available in nginx. If not, that seems like a good feature request for Vouch to handle!

**Comment by Gauravshah** [comment]
Thanks @aaronpk I will look for some more time on nginx if not will open a separate issue with feature request tag.

**Comment by artagel** [comment]
This is exactly why I created all the documentation around openresty. It’s nginx with lua scripts, and will give you the ability to mangle or change anything with a lot more power than nginx has.  Check out the openresty examples, and you can change them from authentication using a header to simply changing or adding a header once you encode it.

**Comment by artagel** [comment]
Here is the lua module that would encode the string. https://github.com/spacewander/lua-resty-base-encoding
