### ISSUE TITLE
Infinity auth loop

### ISSUE THREAD

**Issue by dzirg44** [vouch/vouch-proxy#148]
https://gist.github.com/dzirg44/86d4488663ab88b8e8b3913a777df996

**Infinity auth loop** 
I have read all similar issues are connected with  such problem, but didn't find  solution.

**Current behavior**
cannot login , return back to the login page again and again

**Expected behavior**
Authorization without loop

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: firefox, chrome, safari
 - Version: latest

It works only if i use one domain for the vouch  and  for the service and use different port without https for the vouch container. 

Sorry , i am not so good at English

**Comment by bnfinet** [comment]
Your configuration is for 'oidc' but your urls are google.  You should use
the Google specific config.  Start with the minimum config for Google
example in the config directory of this repository.

For domains, you just need 'mydomain.io'.

**Comment by bnfinet** [comment]
If you have further problems, please post your logs, with debug and testing
set to true

**Comment by dzirg44** [comment]
@bnfinet thank you for your help. Yep , I used the wrong provider, my mistake I thought that I  can use google with oidc, because when I used oicd with alb (as an auth rule) i didn't have any problem.
 
Also, if you don't mind I have a question , how  can  I use nested items like teams ? 
https://api.github.com/user/teams
I created the claim 
```
  headers:
    claims:
     - user/teams
```
but i don't have any ideas how I can access to this values, because I am not able to use `$upstream_http_x_vouch_idp_claims_user/team`

or I can create another Issue with this question.

**Comment by bnfinet** [comment]
@dzirg44 Github teams is not supported at this time.  An additional call to the github api would need to be made and some config in Vouch Proxy would need to be setup to filter on teams but none of that has been implemented.  Do let me know if you're at all interested in working on this feature :) 

https://developer.github.com/v3/teams/#list-user-teams
