### ISSUE TITLE
restrict accepted logins by GitHub organization

### ISSUE THREAD

**Issue by RyanGannon** [vouch/vouch-proxy#150]
Is it possible to restrict accepted logins by GitHub organization? That is, instead of restricting by email address domain or just allowing anyone on GitHub access to my site, can I set Vouch to only allow members of a specified GitHub organization to access my site?

I feel I'm missing something simple.

**Comment by bnfinet** [comment]
To the best of my understanding, no it is not possible.

If github provided any Oauth claims in their token which indicated organizational status it should be possible to use Openresty to fiiter users 
https://github.com/vouch/vouch-proxy#advanced-authorization-using-openresty 

Github team membership is a separate api call
https://developer.github.com/v3/orgs/members/#check-membership

It's possible this api call could be added to the auth/userinfo logic but it would require some thought.  We don't have anything like that in the code base at this point.

**Comment by RyanGannon** [comment]
Thank you. This answers my question.

**Comment by bnfinet** [comment]
@RyanGannon FYI - @eikehartmann has submitted a PR which supports GitHub orgs and teams

If you were in a position to help test it would be much appreciated :)
