### ISSUE TITLE
Allow scopes to be set for Google OAuth config

### ISSUE THREAD

**Issue by leshik** [vouch/vouch-proxy#156]
I'm unable to set scopes (and other options) for Google provider. Others have something like `if len(GenOAuth.Scopes) == 0 { ... }` but for Google, it seems that it's hardcoded. Is this intentional and am I missing something?

**Comment by bnfinet** [comment]
yep, looks like its hard coded.  Google OAuth was the very first implementation for VP, when most of what were concerned with from the IdP was can the user authenticate.

It's probably a quick fix, care to submit a PR?

**Comment by leshik** [comment]
@bnfinet sure, I pushed the trivial fix in #159.
