### ISSUE TITLE
vouch nginx guacamole redirect with hash-mark # as URI separator

### ISSUE THREAD

**Issue by molndal** [vouch/vouch-proxy#157]
Hi

I'v setup an nginx+vouch solution that works just fine for most of my websites but when trying to protect an apache guacamole 1.0.x i get a problem with redirecting back to the guacamole URI that has an hash sign as an URI separator and not as a fragment delimiter. 

URL looks something like this: https://some.domain/#/client/ but vouch just redirects me to https://some.domain/

If I'm already logged in with vouch and just doing a validate I can reach the guacamole uri without any issues.

Been trying to find any info about this for a few days but I have not found any, not sure if the problem is in vouch or not either but maybe someone knows where the issue could be?

**Comment by artagel** [comment]
Can you provide logs and configs?
https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests

I'd be interested in also seeing the redirects in the debugging tab of Chrome, to determine if you are being redirected to the proper url, and which url you send in the request.

**Comment by molndal** [comment]
Hope this is what you need, I tried making them somewhat anonymous but wasn't really sure if I could cut out anything.

[vouch-guac-redirect-stripped.log](https://github.com/vouch/vouch-proxy/files/3710867/vouch-guac-redirect-stripped.log)
[config-stripped.yml.txt](https://github.com/vouch/vouch-proxy/files/3710876/config-stripped.yml.txt)
[chrome-log-stripped.txt](https://github.com/vouch/vouch-proxy/files/3710878/chrome-log-stripped.txt)

**Comment by molndal** [comment]
Here's the nginx configs, they are not running on the same nginx-instance.

[nginx-guac-conf-stripped.txt](https://github.com/vouch/vouch-proxy/files/3711100/nginx-guac-conf-stripped.txt)
[nginx-vouch-conf-stripped.txt](https://github.com/vouch/vouch-proxy/files/3711102/nginx-vouch-conf-stripped.txt)

**Comment by molndal** [comment]
Not really related to the issue but I created an ugly workaround. The /#/client uri works when not doing redirects through vouch and nginx seems to remember a previous auth-request in the server context so i used vouch to auth this url: https://guacamole.somedomain/guacamolehost and I let nginx serve a html file with a meta http-equiv="refresh" content="0; url=https://guacamole.somedomain/#/client 

It is not the prettiest thing but it works. I first tried with nginx rewrite/return but seems nginx processes those statements before doing auth-request.

**Comment by bnfinet** [comment]
This is a limitation of the browser and http spec.  The browser does not send the "target" portion of the requested URI which includes the the `#` mark and everything afterwards.  Ngxinx's `$request_uri` variable does not represent the target because it never receives it in the request header.

https://stackoverflow.com/questions/940905/can-i-read-the-hash-portion-of-the-url-on-my-server-side-application-php-ruby

**Comment by aaronpk** [comment]
You might be able to get away with URL-encoding the `#` character, using `%23` instead. 

But in any case, the technique of using `#` for single-page apps is extremely dated and serves no real purpose anymore and that software should be updated to use real URLs and the Session History Management API.

**Comment by artagel** [comment]
Also, I noticed that the app uses username and password in get params, which is also extremely dated. That means your nginx logs will log all these passwords.  That is no good.

**Comment by molndal** [comment]
Thank you for the information, I will use the workaround, I know that username/password in uri is bad practice but I don't care about login for the application at all, apache have disabled the option of using no-auth since a couple of versions back. I agree the app seems a bit dated but it is the best one I have found for html5 rdp gateway and https://guacamole.apache.org/ released this version (1.0.0) in januari 2019.
