### ISSUE TITLE
ADFS custom claims sending X-Vouch-IdP-Claims-xx headers do not work 

### ISSUE THREAD

**Issue by twelve34** [vouch/vouch-proxy#158]
Adding custom claims on ADFS and configure Vouch to send them didn't work.
After debugging  we found that into function handlers/handlers.go the customer claims are not found.

inside function:
handlers/handlers.go

`funcgetUserInfoFromADFS(r *http.Request, user *structs.User, customClaims *structs.CustomClaims, ptokens *structs.PTokens) (rerr error) {`
....
 `req, err := http.NewRequest("POST", cfg.GenOAuth.TokenURL, strings.NewReader(formData.Encode()))`
....
  `ptokens.PAccessToken = string(tokenRes.AccessToken)`
  `ptokens.PIdToken = string(tokenRes.IDToken)`

After this Request  data contains the complete reply from ADFS:
 
`{\"access_token\":\"eyJ0e.....xzuZ_TQ\",\"token_type\":\"bearer\",\"expires_in\":3600,\"resource\":\"http://a.b.intern/auth\",\"refresh_token\":\"aZGO18.........1HSfEw\",\"refresh_token_expires_in\":28799,\"scope\":\"openid\",\"id_token\":\"eyJ0eX.....kvIRuKNG-FhH8CzA\"}"}`

....
` if err = mapClaims(data, customClaims); err != nil {`

mapClaims is searching into "data" for custom claims but didn't find it, in previous commit there was only a check for the idToken part

` if err = mapClaims([]byte(idToken), user); err != nil {`

In our situation the customclaims are supplied into the accessToken. After changing the code to use accessToken the custom claims and sending X-Vouch-IdP-Claims-xx headers are working.

` if err = mapClaims([]byte(accessToken), user); err != nil {`

Before submitting a merge request I would like to address this issue and understand why "data" is used in the last commit.

**Comment by artagel** [comment]
Give me a few days, I'm out of town.  But I'll take a look.

**Comment by artagel** [comment]
I tested this at one point, I'll kick my lab VMs up again after the weekend and test it.
ADFS is freaking weird, so It doesn't surprise me that it is different.

**Comment by twelve34** [comment]
If you need more info or something to test let me know

**Comment by artagel** [comment]
So here are a couple of things I've noticed:
In my testing, I don't get an 'email' address from ADFS.  
```
{"level":"info","ts":1570976583.914297,"msg":"adfs adfsUser: {User:{Username: Name: Email: CreatedOn:0 LastUpdate:0 ID:0} Sub:wIhx7njjkpMKRu3yKonZ8yPOxnW3dSIRvASLpd0nKyY= UPN:mrtester@awesome.lol}"}
{"level":"debug","ts":1570976583.914539,"msg":"User Obj: &{Username:mrtester@awesome.lol Name: Email: CreatedOn:0 LastUpdate:0 ID:0}"}
```
I'm not sure if anyone else that uses ADFS sees the same thing. 

The email is only passed down in the id token as far as I can tell:
```
{"typ":"JWT","alg":"RS256","x5t":"7GUXy9d9kJ0RLqiIuduwrd1GAFQ"}{"aud":"http://vouch.awesome.lol:9090/auth","iss":"http://pdc.awesome.lol/adfs/services/trust","iat":1570975414,"exp":1570979014,"email":"mrtester@awesome.lol","group":["CN=Some\\, group,CN=Users,DC=awesome,DC=lol","CN=Website Users,CN=Users,DC=awesome,DC=lol","CN=Test Group,CN=Users,DC=awesome,DC=lol","CN=Key Admins,CN=Users,DC=awesome,DC=lol"],"given_name":"John","apptype":"Confidential","appid":"822956e8-3066-4e59-b47a-ae4ce540625b","authmethod":"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","auth_time":"2019-10-13T13:53:05.926Z","ver":"1.0","scp":"profile email openid"}
```

The id token is also where the claims are passed.  So that means changing line 823 to ```if err = mapClaims(data, customClaims); err != nil {``` with data was incorrect.  Seems like my original code using idtoken was correct, because the body returned from ADFS User Info is not like other providers, and it has several parts.  
This is the body in case anyone is wondering:
```
{"level":"debug","ts":1570976583.914317,"msg":"{\"access_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjdHVVh5OWQ5a0owUkxxaUl1ZHV3cmQxR0FGUSJ9.eyJhdWQiOiJodHRwOi8vdm91Y2guYXdlc29tZS5sb2w6OTA5MC9hdXRoIiwiaXNzIjoiaHR0cDovL3BkYy5hd2Vzb21lLmxvbC9hZGZzL3NlcnZpY2VzL3RydXN0IiwiaWF0IjoxNTcwOTc2NTgzLCJleHAiOjE1NzA5ODAxODMsImVtYWlsIjoibXJ0ZXN0ZXJAYXdlc29tZS5sb2wiLCJncm91cCI6WyJDTj1Tb21lXFwsIGdyb3VwLENOPVVzZXJzLERDPWF3ZXNvbWUsREM9bG9sIiwiQ049V2Vic2l0ZSBVc2VycyxDTj1Vc2VycyxEQz1hd2Vzb21lLERDPWxvbCIsIkNOPVRlc3QgR3JvdXAsQ049VXNlcnMsREM9YXdlc29tZSxEQz1sb2wiLCJDTj1LZXkgQWRtaW5zLENOPVVzZXJzLERDPWF3ZXNvbWUsREM9bG9sIl0sImdpdmVuX25hbWUiOiJKb2huIiwiYXBwdHlwZSI6IkNvbmZpZGVudGlhbCIsImFwcGlkIjoiODIyOTU2ZTgtMzA2Ni00ZTU5LWI0N2EtYWU0Y2U1NDA2MjViIiwiYXV0aG1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0IiwiYXV0aF90aW1lIjoiMjAxOS0xMC0xM1QxMzo1MzowNS45MjZaIiwidmVyIjoiMS4wIiwic2NwIjoicHJvZmlsZSBlbWFpbCBvcGVuaWQifQ.D3NxgUksN2BO00nTZNxKXZ8vnZ-UHbTlcWO2kgPrrqAvQj7Etoe_Jb6r0Ee7YuA8HUWyMYTZxnLqPIpXgHZ4YDmTiaERs1LWGzGWxBfdcpR97ZR_G4KpPY8WCaUQ2vizvG50i17BzW_nFSdc6l2G7OFhASGJi1LOT3vgFvX1WqJmu5--a-lc9LdmS0H6xa1LVI2LOPOS5bGbMvJMfre5nRPdjC2GOXsiVf598dkfjpUczkH5ukWkn1BHymR5hLEnbRqrndrXyJvbdQhyXNex0sUh03JJcpkSVqvye0d85HOyag3rGmzPEmQFlnLY3_8QL3mxQUgvTXT4Wr7Dz67Pbg\",\"token_type\":\"bearer\",\"expires_in\":3600,\"resource\":\"http://vouch.awesome.lol:9090/auth\",\"refresh_token\":\"fakZSmLcglbFnVFJFr94HZF1402uItMl-R047uOishYAAQAAYDrhOHG_HCOP3IXH2mcQh5mHVX4y9AsP1jLyn6a-GA2OKtHg47gEe7GsemFBzfohIC16Wop-ltS0rfpEJfTZhbJF83xEPPzFWLSbdgxr93n1MyY9JTwK8msdMd5d-CbYaPEOtMTVliWTDUOnSNw72GNpS15rwlZlz0-AnS9Rtn6bmQReX4E2dU9jCXYZfA6LIKTQXvlsQmxZyVyGCJ2npLBZCuZooHor0jElZQ5Tw_b8Dl9ryte6PVMtzGTTaGR1PyPf-yso9Ju4rG30CkyDKQ8x3_Cczl88ZJ0-DQE1YuDKHdal1PhbhPbhbe9qjUiH6p4n0T01PjEFd1TStl_M7gAGAADg8G-KJp40X-4YROGFVnsANxB5fUCeU5BwtGZGP_OSKvVu3uW2f1XnSr-zX8CtD8mJ9ndwRkZY5lEkksdw1gXepS2ZvRmO6oazwLU0rGtIcl9Ad6f-w3nlBhF9V3yTU1HC12VosvePNH1dtBvf6vmp9XSQDwwZsQjfqY1_5ar7yLgkCLoSJvwAbWvKiAay0A5veI3Ra4L50gDRMBjsLPT9HKrz9HK-_4cMZ6isXuWRF2j_015lSdC4zXBin6YsQlNjvEySwxA52LEKWXZcc-rPKRMiVeU3h8t1ApygOVWfJSAyE1jvoLnzK_moGVmdyKLUVfknw6MZN-4CCiwz7wmqw6phuylnVUnRwSjhVWu8NEXxUK7V4Aps2319_ZyuXRcy5iJE9F_um_3UT9Yag1hRJulujvfasvx1kR-LXU1jTAe-6QT-t7XQcqJqi68fSFRepSPHEYJ7e2Yj1POATTu0ihduD7NlNWy60Dk3xvKGXwE6qohkvU1t5TEuF8Jqu0RiwfOAiTbdi2YcNab4TCg1JmDxw849kJsTP1258OT5OhbpkEo2LAOO4zbNrFAZESdmnOjUaFdOs_5KgIiJ7KVMOevVQS7_ksYyNgyqyumDKiMwUosi4cVUfUBJpRfxuvoUFOiBvITeg51-JOCuiblYQbSZf36n8SKdZWgwj_Ko6V7spRzXRHOEAPhRqr0cLDSMfOjwEv76Hv2N5okV2lYxITAovnCiydW6WmHnGHgaocWcCo85ZWK5bBdl6X7SvjAcJJ9a6dpRzmLfFmWpb3Oj-AclYg8_trWIP5u1DHlnxRgFsW0_7lXiLYlh86TctfZkr8doZyMPIOu2jlAOCmrjCHhazZ81j0Gj61_fXQYU-8dZV_DZvZY7r9dzaCJrTQILalCHQJFVyUEtEiFv7pnNMFk7xZoXRtx_0ryQ-p3SmKeHvt-53dN_iVN05pAXLG2aZRzMfT59Jc8X7-99ML5VmfiMqpzl1YqyCRZYMkA25t6Q9aaM1yfC2u68gzngs4hhctqPv5W0q9JhNz4scxMQ433oX507Bhm3XActsPWZTXaJ-AMs1KOUD35hZOwv6jKd8gspVjKUKQscuNXNqXeQb3-LROTul3dXKbTiBAV1ICklg4WId6E-FBJIY_V7028zBVPP2wJFMzCd5RvQ1EMfBVLglF1mP9DVbJWGORkikClZDbOeuRUhOWFc5OqppCKt1jx3nB_LIvvbLZNv4C7_bmkpAgK8UrVffw6xwrZBEJhYU-xQyvgSADGfCR4ZPAI2O0jLCnOQk9HPuv-z6ziWCDgb97phsLFoM1h_Zijd8LRcNiqxNtNhIQt2y2S8Hee2H5XVoQG2j3iSi_eWilaLM6plfWBDf6J0BjILE03o5Lnd61RJgNGdBBnS9MjEyfuWsWQy_RpbItWco6TOc0JLoAtvbayYl8bS-z16as0F1BOUQPtPIKIvD09CrK3DdlBiQfXhpC9HrPum6WiN1jjBpdQT_2TrSms5-fgerckqm6gydiqgsSP5Ehq_Mg0HnHk4FA1GiA134oadb0PLhxMwparcmN5EeIJo6XvfnC_pVivF_N_KK-aVgJ8PXbXYUxpAqiw-2yaiy4wldn4Da7uehxmgWqKO60BS8pVEwM6F2pKNWW-moywui_6svMMDsnpkQV7QaIklb9oBseMC-8nwAu3Cb6HgE4OwlqJc3E2vx8PHCDh-itFHeRp-uAuNvSu8ImHlnHqAlbTK161IAVTw8BInDuhr2RP0o21k3TgFuKlAVAf2Lupw6ekOREHYLGg5mVoCC0AZQkivsRiBwvbE4OJyYAEKUWkDN2XBPfXVJTkRds0KLNSIVcBr4LUWPWGPdvEJfUN927-6MJYOaIaOu6nO1nhLaFbiQ1JSfFRtOZlB5VXsquqZbpWFczIhBgjAo_u7dwMAwxc_2PY0L_jqkwXxogDpzAwZjKNXaWnN0EsJ-BDqb_mcfpSo8UCMynNhQi1likLKKwKLg6Ymatljgn6ad703vUCCbJSYupW9sEO4uKrePfMmbkWD3E_0aEc.NAc-_2UYouWuqr489I-Qjdh9mEyAu6-rslaS42cHLRV4mjMhASxor3WyLuaktNwioiBJbrR7Ka4_RCOVx6j_t8xq9Dy1_OE2IOKN038ThypiXpW_js3_n525xrOeLuLt50_hWL17Uxc-oc9FXAGqMX6zsBKn_MAgs_H_ht4Ss9NaZBx4XfJW-tlNxUpq8O23HJ2S6vCT9q-a8heUAmphVSBXFRCYeSR_6UgWTS_WeSaH18i6acGeov9cLMRuW9mnt7n8p1j93P1J9w-WBLjLjVHVcYyYuUqvKpIztd0Pz053E1dKDxGhzr1ZEnqPaxYD7xCIBSuZ5xsHbKQyXxCyjA\",\"refresh_token_expires_in\":27001,\"scope\":\"profile email openid\",\"id_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjdHVVh5OWQ5a0owUkxxaUl1ZHV3cmQxR0FGUSIsImtpZCI6IjdHVVh5OWQ5a0owUkxxaUl1ZHV3cmQxR0FGUSJ9.eyJhdWQiOiI4MjI5NTZlOC0zMDY2LTRlNTktYjQ3YS1hZTRjZTU0MDYyNWIiLCJpc3MiOiJodHRwczovL3BkYy5hd2Vzb21lLmxvbC9hZGZzIiwiaWF0IjoxNTcwOTc2NTgzLCJleHAiOjE1NzA5ODAxODMsImF1dGhfdGltZSI6MTU3MDk3NDc4NSwic3ViIjoid0loeDduamprcE1LUnUzeUtvblo4eVBPeG5XM2RTSVJ2QVNMcGQwbkt5WT0iLCJ1cG4iOiJtcnRlc3RlckBhd2Vzb21lLmxvbCIsInVuaXF1ZV9uYW1lIjoiQVdFU09NRVxcbXJ0ZXN0ZXIiLCJzaWQiOiJTLTEtNS0yMS0xODIyMjIyMTUtNTM0NjAwMDc5LTE0Njg3ODQ4Mi0xMTA1In0.OUbUjBP-xz0Q9d5Dephr8JTDfJy5xAEARX_jxuIIYJ7MLi8JMIxKVjswRSz6hxuG7DSaNqm3otWX3BELxx1bqJ09RlBeewlEaKIYw51GQoDUop7HO4j3rdtt8M91y4BQwXpgsowcpMZxyOiA0aAAeNiQIJe3-Soyl0is78KVWT2Rhp56xuLaywNlugSI_S5-2YCMqVYovM54Tm80jdRyMX2Qa9tZr2FyZyRsj8YJctOOUzSIx8VmG0_ovh1-54p4YVw5dEU96hY3pdtDc1bf_ZegTm6hYSiAfedY8lwpEXQOta547utqWwSs6fz99INRjQmmYCKiuC2-hD-fZP0jfQ\"}"}
```

Now, the access token is a JWT, which technically also contains the same info.  Here is the access_token decoded:
```
{
  "aud": "http://vouch.awesome.lol:9090/auth",
  "iss": "http://pdc.awesome.lol/adfs/services/trust",
  "iat": 1570976583,
  "exp": 1570980183,
  "email": "mrtester@awesome.lol",
  "group": [
    "CN=Some\\, group,CN=Users,DC=awesome,DC=lol",
    "CN=Website Users,CN=Users,DC=awesome,DC=lol",
    "CN=Test Group,CN=Users,DC=awesome,DC=lol",
    "CN=Key Admins,CN=Users,DC=awesome,DC=lol"
  ],
  "given_name": "John",
  "apptype": "Confidential",
  "appid": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2019-10-13T13:53:05.926Z",
  "ver": "1.0",
  "scp": "profile email openid"
}
```

Notice this is identical to what we find in the id token:
```
{
  "aud": "http:\/\/vouch.awesome.lol:9090\/auth",
  "iss": "http:\/\/pdc.awesome.lol\/adfs\/services\/trust",
  "iat": 1570975414,
  "exp": 1570979014,
  "email": "mrtester@awesome.lol",
  "group": [
    "CN=Some\\, group,CN=Users,DC=awesome,DC=lol",
    "CN=Website Users,CN=Users,DC=awesome,DC=lol",
    "CN=Test Group,CN=Users,DC=awesome,DC=lol",
    "CN=Key Admins,CN=Users,DC=awesome,DC=lol"
  ],
  "given_name": "John",
  "apptype": "Confidential",
  "appid": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2019-10-13T13:53:05.926Z",
  "ver": "1.0",
  "scp": "profile email openid"
}
```

In my instance, since the email isn't passed, I still don't get verified as a user.  So I propose the following 2 changes:

1. Revert the mapClaims back to idToken.  @twelve34 Do you not see the claims in idToken?  If not, then we can make mapClaims accessToken by default.  Either should work though.
2 Op1. Add logic to mapClaims that if there is an email in the claims and userdata doesn't have the email populated, we use the claim email.
2 Opt2. Add logic to func (u *ADFSUser) PrepareUserData()  (structs.go) to set user.email as u.UPN if UPN is an email address.

**Comment by artagel** [comment]
@simongottschlag Do you have any comment on this?

**Comment by simongottschlag** [comment]
@artagel I was debugging the mapClaims and saw that none of my claims were added at all previously. Since I don't use it myself I asked (https://github.com/vouch/vouch-proxy/commit/e24bd0276b1d57459fc9846266e745ad250415e2#r35000945) and changed it according to the discussion.

If I remember correctly, nothing were ever mapped with the way we did it before - but I may be mistaken here.

I'm always seeing upn though, my id_token looks something like this:
```
{
  "aud": "<clientId>",
  "iss": "https://adfs.domain.com/adfs",
  "iat": <int>,
  "exp": <int>,
  "auth_time": <int>,
  "nonce": "<string>",
  "sub": "<sub>",
  "upn": "simon@domain.com",
  "unique_name": "DOMAIN\\simon",
  "pwd_url": "https://adfs.domain.com/adfs/portal/updatepassword/",
  "pwd_exp": "4828940",
  "sid": "<sid>",
  "groups": "<groupName>",
  "apptype": "Confidential",
  "appid": "<clientId>",
  "authmethod": "http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows",
  "ver": "1.0",
  "scp": "profile openid"
}
```
Are you allowing the following scopes? 
allatclaims
profile
openid

**Comment by artagel** [comment]
@simongottschlag I didn't have atallclaims set.
```
{
  "aud": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "iss": "https://pdc.awesome.lol/adfs",
  "iat": 1571063669,
  "exp": 1571067269,
  "auth_time": 1571063669,
  "sub": "wIhx7njjkpMKRu3yKonZ8yPOxnW3dSIRvASLpd0nKyY=",
  "upn": "mrtester@awesome.lol",
  "unique_name": "AWESOME\\\\mrtester",
  "sid": "S-1-5-21-182222215-534600079-146878482-1105",
  "apptype": "Confidential",
  "appid": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "ver": "1.0",
  "scp": "profile email openid"
}
```
But still UPN maps to username, and not email. And the code validates email against domain.  You might have 'whitelist' enabled to allow a specific user?
If I map ldap claims in ADFS for email, then yes my validation is working.

```
{
  "aud": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "iss": "https://pdc.awesome.lol/adfs",
  "iat": 1571063922,
  "exp": 1571067522,
  "auth_time": 1571063669,
  "sub": "wIhx7njjkpMKRu3yKonZ8yPOxnW3dSIRvASLpd0nKyY=",
  "upn": "mrtester@awesome.lol",
  "unique_name": "AWESOME\\\\mrtester",
  "sid": "S-1-5-21-182222215-534600079-146878482-1105",
  "email": "mrtester@awesome.lol",
  "group": [
    "CN=Some\\\\, group,CN=Users,DC=awesome,DC=lol",
    "CN=Website Users,CN=Users,DC=awesome,DC=lol",
    "CN=Test Group,CN=Users,DC=awesome,DC=lol",
    "CN=Key Admins,CN=Users,DC=awesome,DC=lol"
  ],
  "apptype": "Confidential",
  "appid": "822956e8-3066-4e59-b47a-ae4ce540625b",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "ver": "1.0",
  "scp": "profile email openid"
}
```

Also, in this instance, mapclaims(data) is working for me.   We should probably add some reference somewhere to make sure people know to use atallclaims :)  

So I consider the change you made from idToken to data valid, but I'll at the very least update some docs somewhere to ensure people use atallclaims.

Now, for the username mapping if no email exists.  I think detecting to see if a username is an email in that situation, and using it to validate the username against a domain should be fine.  Unless @bnfinet has any objections to that logic, I can submit a PR for these changes in a day or two.

**Comment by artagel** [comment]
@twelve34 are you using atallclaims?

**Comment by twelve34** [comment]
@artagel I didn't use atallclaims.
We added custom claims into our ADFS configuration and the result is that these custom claims (Groups and department) are seen into the access_token and not into the id_token
Example (somewhat anonymised) 

```
Access-token:
{
  "aud": "http://vouch.domain.intern/auth",
  "iss": "http://a.b.nl/adfs/services/trust",
  "iat": 1571074244,
  "exp": 1571077844,
  "upn": "x@a.b.c",,
  "email": "xxxx@a.b.c",
  "given_name": "Name",
  "unique_name": "Name Name2",
  "department": "TestDepartment",
  "groups": "group1",
  "apptype": "Public",
  "appid": "18679fec-6f44-4d7b-863f-a8943800902a",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2019-10-14T17:30:44.093Z",
  "ver": "1.0",
  "scp": "openid"
}
```

```
ID-token:
{
  "aud": "18679fec-6f44-4d7b-863f-a8943800902a",
  "iss": "https://a.b.nl/adfs",
  "iat": 1571074244,
  "exp": 1571077844,
  "auth_time": 1571074244,
  "sub": "LoLTl5qDNEDkldeojdednqSSYxm1KvGCzp5EM30=",
  "upn": "x@a.b.c",,
  "unique_name": "XXX\\x",
  "pwd_exp": "4643355",
  "sid": "S-1-5-21-222222-333331-11111111-1412"
}
```

**Comment by bnfinet** [comment]
@artagel no real objections, thanks.  That's consistent with how some of the others providers are handled at this point.

I'll add just the caveat that I have wondered for some time if we should move to using `sub` instead of `username`, which conforms to the OIDC spec, probably as a `v1.0.0` breaking change.  I suspect we'd still have to check for "sub" and fall back for a few of the providers.

see ID Tokens..
https://oauth.net/articles/authentication/

Thanks as always @artagel and @simongottschlag for keeping a watchful eye on ADFS issues in VP.

**Comment by artagel** [comment]
@twelve34 so the point is if you simply turn on allatclaims then you should see the claims in the ID token and it will map your claims properly.  
https://blogs.technet.microsoft.com/piameruo/2017/10/22/custom_idtoken/

**Comment by twelve34** [comment]
@artagel allatclaims did indeed the trick,  now ID token contains all the custom claims. So we can revert back to use ID token

**Comment by bnfinet** [comment]
@twelve34 good to close?  Sounds like yes :)

**Comment by twelve34** [comment]
@bnfinet No, after add allatclaims the custom claims are indeed into the ID token but mapclaims(data) doesn't fil the custom cleams headers.

after changing it to ID token it works
```
//      if err = mapClaims(data, customClaims); err != nil {
        if err = mapClaims([]byte(idToken), customClaims); err != nil {
```

`{"level":"debug","ts":1571293585.9531293,"msg":"response header","all headers":{"X-Vouch-Idp-Claims-Department":["TestDepartment"],"X-Vouch-Idp-Claims-Given_name":["twelve"],"X-Vouch-Idp-Claims-Groups":["group1"],"X-Vouch-Idp-Claims-Pwd_exp":["4424014"],"X-Vouch-Success":["true"],"X-Vouch-User":["twelve@a.b.com"]}}`

**Comment by artagel** [comment]
@twelve34 I don't think that's right.  On my test environment, I get the claims once I add the allatclaims config.

**Comment by twelve34** [comment]
@artagel first of all thanks for your help.  There must be something in my ADFS configuration. attalclaims did indeed the trick that it add the customClaims to the ID token but I think there must be another config part that forces to place the custom claims also outside the ID token into the reply.
Can you share the value of data before entering the mapClaims function ?

**Comment by artagel** [comment]
Ok, I pushed a fix after testing this again with some detail and some sleep :)

**Comment by twelve34** [comment]
Thanks I did some testing and work fine now.
