### ISSUE TITLE
/auth Invalid session state: stored %!s(<nil>), returned even with successful 200 status code

### ISSUE THREAD

**Issue by ryan-boyle** [vouch/vouch-proxy#165]
**Describe the problem**
I am trying to use Vouch to integrate Nginx web application into my Okta authentication, but I can not seem to get past this issue. I am using ssl, with cookies turned on, so I can't seem to see where this issue could be coming from. Any direction would be much appreciated!

**Expected behavior**
To be directed to my protected.domain.com

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Testing with Chrome and Safari
 - Version 77.0.3865.90

**Comment by bnfinet** [comment]
@ryan-boyle could you please follow the instructions in the README regarding troubleshooting and posting your configs and logs

kind regards

**Comment by bnfinet** [comment]
@ryan-boyle would you like to continue with this issue?  If not, could you please take a moment to close it.
