### ISSUE TITLE
Support multiple clientId

### ISSUE THREAD

**Issue by mirzakhany** [vouch/vouch-proxy#168]
We use vouch to proxy requests to our services and keycloak as openid provider with ingress.
Is it possible to handle more than one client  with single installation? For example with passing clients specific configs with nginx annotations?

**Comment by artagel** [comment]
What do you mean by more than one client?  Like multiple websites?

**Comment by bnfinet** [comment]
@halkeye is there a way in which multiple VP instances could be configured for the same Nginx ingress?  I'm guessing no.

**Comment by halkeye** [comment]
Uh? I'm think you can set different auth request services per location/server block. I'm far from an expert though.

How would a single instance know which client id to use? If it's per domain wouldn't it make sense to install multiple instances then?

**Comment by bnfinet** [comment]
@mirzakhany VP only supports one configured [oauth config](https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example_oidc#L18-L31) at this time.  However you can set multiple `callback_urls` and multiple `vouch.domains`.  As long as each `yourdomainA.com` has a corresponding `vouch.yourdomainA.com` and that VP is configured with a list of `callback_urls` which includes `vouch.yourdomainA.com/auth`,  VP will provide the correct `callback_url` which corresponds to the requested domain.  With all of those stars in alignment you would be able to use one VP instance to service all domains which you would like to enforce login to Keycloak.

Does that answer your question?

**Comment by halkeye** [comment]
oh! in k8s? its up to your ingress provider, but yea, its an annotation done per ingress

**Comment by mirzakhany** [comment]
Imagine that you what protect many applications in a cluster. So for now we should install an instance of vouch for each of them if they use different clientId.
I look for a way that we can deploy one vouch (that may replicated) and pass configurations from ingress anotations. 

For example if vouch can watch for ingres resources and if find an ingress resource with a special lable or annotations then it can read configoration for that service or domain and inject required settings.

**Comment by halkeye** [comment]
That does sound like a great feature, but unless something drastically changed since I last looked at the code, vouch knows nothing about k8s.

**Comment by bnfinet** [comment]
@mirzakhany I like the concept, though we'd have to be really clear about how the configs would work, with a particular eye towards not breaking existing setups.

Please also consider #132 / #134 if you go down this route.

And I can imagine having an `include` directive in the `config.yml` such as `vouch.include: config.d/otherconfig.yml` or ``vouch.include: config.d/otherconfig.yml`.

Cheers.
