### ISSUE TITLE
Social Login/Authentication using Kubernates built in nginx and Vouch 

### ISSUE THREAD

**Issue by gbajaj** [vouch/vouch-proxy#173]
**Describe the problem**
I have a Web application deployed using Kubernetes with built in nginx support.
I want to enable Social Auth using vouch, however I failed to find out any step by step guidance on how and where to update the configuration for such a setup? Could some please point me to a such a link with instructions.

I am using Google Login as OAuth Provider

**Comment by bnfinet** [comment]
@gbajaj there is no article or HOWTO for Kubernetes to the best of my knowledge.

I expect to write a blog post in Q12020 that will outline some of what you're seeking after the deployment of a separate project that uses VP for login.  If you would like to assemble example configs and such I'd be happy to support your efforts.

The basic tools are in place to accomplish what you'd like including

Ingress Configuration
https://github.com/vouch/vouch-proxy#kubernetes-nginx-ingress
https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/

and passing custom claims headers to your application during the request  
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L95-L113
https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/multi-file/conf.d/app2.yourdomain.com.conf
