### ISSUE TITLE
Support custom landing page in case of errors and during logout 

### ISSUE THREAD

**Issue by sameershivle** [vouch/vouch-proxy#174]
**Current behavior**:
OOTB vouch-proxy redirects to the indexTemplate file with appropriate message during any error or after logout (if no landing page is provided as part of logout call).

**Expected behavior**:
Is there a way to configure vouch-proxy to not use the default indexTemplate file (called by renderIndex()) and instead have my custom indexTemplate file? I want a different customized landing page in case of logout and for errors.
Also, is there a way wherein I do not want to render an error page but instead return http server error code in response header along with error information in response body? Can I opt for not referencing the static and template files at all?

**Comment by artagel** [comment]
Just update templates/index.tmpl, you can customize it as much as you want.

**Comment by bnfinet** [comment]
> Also, is there a way wherein I do not want to render an error page but instead return http server error code in response header along with error information in response body? Can I opt for not referencing the static and template files at all?

I'm curious why you would care to do that.  Are you using Nginx and the `auth_request` module?  If VP returns a 200 (or any 20x) Nginx will allow the original request through to the protected back end service.
