### ISSUE TITLE
Add arm and arm64 docker images. 

### ISSUE THREAD

**Issue by Herdinger** [vouch/vouch-proxy#178]
I'm currently running vouch and an ARM homeserver and have to build it myself. Which makes updating a bit cumbersome.
Should be as easy as using buildx instead of push and build.

**Comment by bnfinet** [comment]
thanks @Herdinger, would you care to submit a PR with such a Dockerfile?  Perhaps names `Dockerfile.arm` and `Dockerfile.arm64`?

**Comment by Herdinger** [comment]
I didn't realy look into it because of time constraints, but it seemed like the only changes would be to your ci rather than the actual dockerfiles. I'll look into it, especially since there might be alternatives with go's native cross compilation.

**Comment by svrooij** [comment]
We are running a Github workflow for this [see here](https://github.com/svrooij/sonos2mqtt/blob/master/.github/workflows/docker-release.yml).

It just takes the normal Dockerfile and builds the image using buildx for multi architectures.

Really easy (once configured correctly).

**Comment by svrooij** [comment]
@bnfinet is there a way we can help with this issue?

The above Github workflow would do the trick, not sure about travis though. Mayba as a way in between is keep the regular image and start with Github actions to build and push an **arm and arm64** image next to your current image.

**Comment by bnfinet** [comment]
I'm not an arm user so I'm not in a position to test such a flow.

Could you please submit a PR and describe how you have tested it and what further setup is required.

And, would you be willing to support any arm related questions for some period of time?  I'm thinking three years.

If you can make it easy on me I'm happy to add it. :)

**Comment by bnfinet** [comment]
I'm more hoping someone can chime in on docker related arm issues, help determine if it's a platform issue.  If it's a code and config related issue then there wouldn't be an expectation.

For the various IdPs it's been helpful to have the original PR submitter be available to answer the occasional question concerning OAuth/OIDC setups.

**Comment by svrooij** [comment]
@Herdinger can you maybe comment on this question?

> I'm more hoping someone can chime in on docker related arm issues, help determine if it's a platform issue. If it's a code and config related issue then there wouldn't be an expectation.

Maybe we can do it together, supporting those arm related questions?

**Comment by bnfinet** [comment]
It worked!  `voucher/vouch-proxy:latest-arm` is now available.

@svrooij thanks much for setting up the build

**Comment by svrooij** [comment]
Glad I could help!

This will make my home automation one step less complex to rebuild.
