### ISSUE TITLE
Too many redirects vouch nginx on same server.

### ISSUE THREAD

**Issue by groundswel** [vouch/vouch-proxy#179]
Sorry but I am also new to the entire authentication field but I am getting a too many redirect errors. My vouch and nginx servers are running in the same box. The goal is to authenticate a user via vouch and then nginx will let the user go to any url served by nginx as proxy. My nginx and vouch config is here https://gist.github.com/groundswel/ed298d078105009dd6946c67bc457050

I am trying through chrome and I get redirected to the Cognito login page correctly. I am able to login but then chrome throw up this error:

This page isn’t working34.224.17.108 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

I tried to clear cookies and use incognito  window without any success. 

Appreciate any help.

**Comment by artagel** [comment]
Please follow the directions in the readme about the info to provide for help.
A quick look, and I think your callback url is incorrect.

**Comment by groundswel** [comment]
Thanks for your response. May I know why the callback url is wrong and what it should be? I want user to be redirected to that url after successful login. I tried to explicitly define the proxy block in Nginx.conf (see commented lines) to proxy the request to a backend server but it still gives me too many redirect errors. Please let me know if there is additional information I can provide to help troubleshoot this issue.

**Comment by artagel** [comment]
Check the examples, it should be your vouch  url.  That’s how Vouch takes the next steps to validate you and issue the cookie. Then once vouch validates, it sends a 200ok for the /validate request, and then it will allow the request to the downstream app.

**Comment by groundswel** [comment]
Thank you that was indeed it. Ultimately I ended up using a Nginx configuration similar to the one described in  https://github.com/vouch/vouch-proxy/issues/64.
