### ISSUE TITLE
How to use vouch cookie for AWS API Gateway?

### ISSUE THREAD

**Issue by groundswel** [vouch/vouch-proxy#181]
From chrome browser I can see that there is a cookie called VouchCookie that is set up (on successful login) with what seems to be a JWT token string.  However since it is httponly by default (and I don't want to change vouch default configuration to make it less secure) - is there any way I can use the JWT token in my application (Specifically to authorize against AWS API Gateway)?

**Comment by bnfinet** [comment]
The VouchCookie JWT is specific to Vouch Proxy and won't be useful for authorizing to any other service, including AWS.

If you're just looking to protect access to AWS API Gateway calls you could build into your app a sidecar forward of the cookie/headers from your application to the Vouch Proxy `/validate` endpoint and Vouch Proxy will return `200 OK` if Vouch Proxy sees that jwt as valid (or it will return 402).  You could use that as assurance that the user has logged in.

Does that answer your question?

**Comment by groundswel** [comment]
Thanks for your response. May I know how to add the X-Vouch-user header to the upstream proxy request from nginx? I already have this in the /validate section in nginx configuration but on the 10.0.2.30 server I don't find anything in the request headers except VouchCookie. :

auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user

and

```
location / {
    auth_request /request_validate;
    auth_request_set $auth_user $upstream_http_x_vouch_user;
    proxy_set_header REMOTE_USER $auth_user;
    proxy_pass http://10.0.2.29:9443;
    #root /usr/local/nginx/html;
    }
```

**Comment by bnfinet** [comment]
Assuming vouch is running at vouch.yourdomain.com you can use developer tools to see if vouch.yourdomain.com/validate returns `X-Vouch-User` 

You should inspect the headers that are received by your service at http://10.0.2.29:9443 to check for `REMOTE_USER`

Alternatively, you could log the value of `$auth_user` at nginx.
https://docs.nginx.com/nginx/admin-guide/monitoring/logging/

For any further support I would ask you to please supply your complete config and logs as is described in the README.

**Comment by groundswel** [comment]
Thanks based on your pointers I was able to get the REMOTE_USER to work with the following two lines in / location

```
auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
 proxy_set_header REMOTE-USER $auth_resp_x_vouch_user;

```

Seems like a known issue that variable scopes are limited to the block within which they are defined in nginx.

Reference: https://github.com/vouch/vouch-proxy/issues/26#issuecomment-425215810

I will continue to investigate your other suggestion regarding using a custom authorizer to validate the Vouch Cookie against /validate endpoint. 

Thanks a bunch for your helpful suggestions. 👍
