### ISSUE TITLE
Unable to get vouch-proxy up and running - access to the homepage keeps downloading a 'download' file. 

### ISSUE THREAD

**Issue by olefemmy** [vouch/vouch-proxy#182]
I expect to be redirected to auth0 login, but that does not happen

OS: Docker version 19.03.5, build 633a0ea838
Browser Chrome, Firefox, IE

# Vouch Config is the following:

vouch:
   logLevel: debug

  testing: true

  listen: 0.0.0.0
  port: 9090

  domains:
  allowAllUsers: true

  jwt:
    secret: 
    issuer: Vouch
    maxAge: 240
    compress: true

  cookie:
    # name of cookie to store the jwt
    name: VouchCookie
    # optionally force the domain of the cookie to set
    # domain: yourdomain.com
    secure: false
    httpOnly: true
    # Set cookie maxAge to 0 to delete the cookie every time the browser is closed.
    maxAge: 14400

  session:
    # name of session variable stored locally
    name: VouchSession
    # key - a cryptographic string used to store the session variable
    # if the key is not set here then it is generated at startup and stored in memory
    # Vouch Proxy complains if the string is less than 44 characters (256 bits as 32 base64 bytes)
    # you only want to set this if you're running multiple user facing vouch.yourdomain.com instances
    key:

   db:
    file: /data/vouch_bolt.db

  oauth:

  provider: oidc
  client_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXXX
  auth_url: https://XXXXXXXXXXXXX/authorize
  token_url: https://XXXXXXXXXXXXXX/oauth/token
  user_info_url: https://XXXXXXXXXXX/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://localhost:9090/auth

###### nginx.root configuration

user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    #default_type  text/html;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log;
    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout  65;
    include /etc/nginx/sites-enabled/*;
}

#### nginx main configuration:

server {
      listen 80 http2;
      server_name _;
      auth_request /validate;
      location = /validate {
      proxy_pass http://localhost:9090/validate;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
}

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 https://localhost:9090/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    # proxy pass authorized requests to your service
    location / {
          proxy_pass http://localhost:8080;
    }

    #location /nginx_status {
    #    stub_status;
    #    allow localhost;        #only allow requests from localhost
    #    deny all;               #deny all other hosts
    #    access_log off;
    #}
}

#### Extra information:
nginx, vouch-proxy and application are all running in docker (three separate containers)

#### Log information

Attaching to corp-tileserver_nginx_1_b11be6eca1fe, corp-tileserver_trex_corp_1_ce89a952ce4a, corp-tileserver_vouch-proxy_1_76b8dc8df43e
nginx_1_b11be6eca1fe | 2019/12/04 15:21:12 [warn] 1#1: conflicting server name "_" on 0.0.0.0:80, ignored
nginx_1_b11be6eca1fe | nginx: [warn] conflicting server name "_" on 0.0.0.0:80, ignored
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.189Z   INFO    testing: true, using development console logger
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.189Z   DEBUG   logLevel set to debug
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.189Z   WARN    setting `vouch.cookie.maxage` to `vouch.jwt.maxage` value of 240 minutes (curently set to 14400 minutes)
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.189Z   WARN    generating random session.key
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   INFO    configuring oidc OAuth with Endpoint https://wspdigital.eu.auth0.com/authorize
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   DEBUG   vouch.jwt.secret is 44 characters long
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   DEBUG   vouch.session.key is 44 characters long
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   DEBUG   checking availability of tcp port: 0.0.0.0:9090
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   DEBUG   viper settings map[vouch:map[cookie:map[httponly:true name:VouchCookie maxage:14400 secure:false] port:9090 loglevel:debug db:map[test_url:http://corp-tileserver.test.apps.wsp-lattice.io/ file:/data/vouch_bolt.db] jwt:map[maxage:240 compress:true issuer:Vouch secret:gxxxxxxxx] allowallusers:true listen:0.0.0.0 testing:true session:map[name:VouchSession]] oauth:map[client_secret:xxxxxxxxxx token_url:https://wspdigital.eu.auth0.com/oauth/token user_info_url:https://xxxxxxxx/userinfo callback_url:https://localhost:9090/auth auth_url:https://xxxxxxxxx/authorize scopes:[openid email profile] provider:oidc client_id:xxxxxx]]
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.190Z   DEBUG   opening dbfile /data/vouch_bolt.db
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.200Z   INFO    starting Vouch  {"version": "ded2e25", "buildtime": "2019-11-06T18:49:51Z", "buildhost": "34aaf0ef2df3", "branch": "heads/v0.6.16", "semver": "v0.6.16", "listen": "0.0.0.0:9090", "oauth.provider": "oidc"}
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:21:10.201Z   DEBUG   serving static files from /static
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:22:10.736Z   DEBUG   Request received : &{GET /healthcheck HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1] Accept-Encoding:[gzip]] {} <nil> 0 [] false 0.0.0.0:9090 map[] map[] <nil> map[] 127.0.0.1:54214 /healthcheck <nil> <nil> <nil> 0xc4201b4150}
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:22:10.736Z   DEBUG   CaptureWriter.Write set w.StatusCode 200
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:22:10.736Z   DEBUG   Request handled successfully: 200
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:22:10.736Z   INFO    |200|   13.124µs /healthcheck   {"statusCode": 200, "request": 1, "latency": "13.124µs", "avgLatency": "13.124µs", "ipPort": "127.0.0.1:54214", "method": "GET", "host": "0.0.0.0:9090", "path": "/healthcheck", "referer": ""}
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:23:11.267Z   DEBUG   Request received : &{GET /healthcheck HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1] Accept-Encoding:[gzip]] {} <nil> 0 [] false 0.0.0.0:9090 map[] map[] <nil> map[] 127.0.0.1:54216 /healthcheck <nil> <nil> <nil> 0xc4201b4420}
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:23:11.267Z   DEBUG   CaptureWriter.Write set w.StatusCode 200
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:23:11.267Z   DEBUG   Request handled successfully: 200
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:23:11.267Z   INFO    |200|    8.807µs /healthcheck   {"statusCode": 200, "request": 2, "latency": "8.807µs", "avgLatency": "10.966µs", "ipPort": "127.0.0.1:54216", "method": "GET", "host": "0.0.0.0:9090", "path": "/healthcheck", "referer": ""}
vouch-proxy_1_76b8dc8df43e | 2019-12-04T15:24:11.813Z   DEBUG   Request received : &{GET /healthcheck HTTP/1.1 1 1 map[User-Agent:[Go-http-client/1.1] Accept-Encoding:[gzip]] {} <nil> 0 [] false 0.0.0.0:9090 map[] map[] <nil> map[] 127.0.0.1:54218 /healthcheck <nil> <nil> <nil> 0xc4201b46c0}

**Comment by bnfinet** [comment]
@olefemmy please use a paste service or a gist as per the README.  It is impossible to determine if your configs are properly formatted when they are pasted as such.

https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests

**Comment by olefemmy** [comment]
Thanks @bnfinet - I have decided to use my own authentication with nginx, so I don't have to get this working again. Thanks for your help though.

**Comment by olefemmy** [comment]
Used a different method
