### ISSUE TITLE
Decrease size of the vouch cookie

### ISSUE THREAD

**Issue by eddjlam** [vouch/vouch-proxy#188]
Is there a way to decrease the size of the vouch cookie? currently it's at 2.4KB and i do not see any documentation about this.

**Comment by bnfinet** [comment]
My headers are about 2K including the Vouch Proxy cookie.

Nginx is generally fine out of the box for 4K on total size of request headers and can be configured for much higher than that if desired.
https://stackoverflow.com/questions/686217/maximum-on-http-header-values
http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

Is 2.4KB a problem for you?  Are you running into a specific problem?

**Comment by eddjlam** [comment]
My headers are approaching 8K with the addition of the vouch proxy.  while nginx and apache can be updated to accept a larger header size i'm not sure this is the correct solution as what happens when i have multiple vouch proxies each with a diffferent vouch header that gets appended the size will continue to grow.

**Comment by bnfinet** [comment]
how many Vouch Proxies do you expect to run to service a single domain?  I'd be curious to hear your use case for that?

The JWT stored in the cookie is compressed prior to encryption.

Perhaps you could utilize the `vouch.cookie.domain` config option to ensure that the cookie is being stored in a specific domain.

If you'd like to look at specific strategies to your setup please post your configs to a gist in the manner outlined in the README.

**Comment by bnfinet** [comment]
@eddjlam I'm inclined to close this conversation for now, if you'd like to look at this closer, please do post to the thread and we can open up the conversation again
