### ISSUE TITLE
Is vouch-proxy honouring logLevel?

### ISSUE THREAD

**Issue by dontoverthinkit** [vouch/vouch-proxy#192]
Hi, 

firstly thank you for putting this cool util together - makes it easy for me to protect a number of sites that I use just for my own self hosted stuff.

I *think* that vouch-proxy is not honouring the log level setting and/or there are direct log debug statements being written without checking the log level. 

I have had a look through the internet, the README's, poked through the source code (in what I think are the relevant places IMHO)

I haven't provided logs, or config as I am not sure they are relevant for this question, but happy to do so if I have that wrong.

What I am seeing is a lot of log data being written at the info level -despite me setting logLevel: error in config.yml

In the last 8 hours, I have 37,950 entries that look like this:
{"level":"info","ts":1577634881.070128,"msg":"jwt cookie","username":"email@address.com"}

I *think* the line generating this is in handlers.go (line 187) but it has been years since I coded in anger, and it could be that fastLog is checking log levels somewhere else.

>	fastlog.Info("jwt cookie",
>		zap.String("username", claims.Username))

Once again, thanks for an awesome util!

**Comment by bnfinet** [comment]
Yep, looks like it only checks for `loglevel` set to Debug
https://github.com/vouch/vouch-proxy/blob/master/pkg/cfg/cfg.go#L209-L215

**Comment by bnfinet** [comment]
@dontoverthinkit would you be able to test the feature branch I just pushed as `bug/192_loglevel` ?

**Comment by dontoverthinkit** [comment]
@bnfinet More than happy to, having a look now

**Comment by dontoverthinkit** [comment]
@bnfinet - I am running vouch-proxy via docker container (on UNRAID not that that matters) - is there any way to grab a docker container off that branch? Or would I need to pull the source and build a container from the branch?

**Comment by bnfinet** [comment]
@dontoverthinkit thanks for that.. the Travis tests didn't pass for that branch (though they did pass locally for me).

You're welcome to test now if you like however I may ask you to test again once I've fixed those.

I suspect it's something to do with my local environment being `golang 1.13` based and the tests configured for `1.10`.  I've poked at it a bit here but I'll have to leave it for the weekend.

**Comment by bnfinet** [comment]
yes you'd need to grab source and build.  You can build the container locally with `./do.sh dbuild`

**Comment by dontoverthinkit** [comment]
ok thank you - prob take me a little bit to get build environment set up as I don't code these days, but happy to do so, will keep you posted.

**Comment by bnfinet** [comment]
@dontoverthinkit I've just pushed an updated branch

could you pull the new code, build and test?  With `docker` installed it should be pretty simple to pull and build
