### ISSUE TITLE
issue with android

### ISSUE THREAD

**Issue by rcastberg** [vouch/vouch-proxy#194]
i have successfully  manager to implement  vouch proxy and have manage  to test with chrome on my desktop and tested  .  

unfortunately both on my Android phone and chrome book I get passed to the account page when I try to log into a website.

has anybody managed to work arond this problem?

**Comment by ngardiner** [comment]
I have worked around this issue by using a different browser than chrome on Android (firefox, edge, the built in webkit browser or opera may work).

**Comment by rcastberg** [comment]
I am able to log in with incognito mode, but it would be nice to be able to do this directly in chrome.

**Comment by bnfinet** [comment]
@rcastberg could you please provide your configs and logs as per the README

And, how many Google accounts do each of your devices have configured?

**Comment by bnfinet** [comment]
@rcastberg I use VP with Android every day.  I feel like if there were a real issue here we'd be getting more reports of problems.

Can I ask you to please provide configs and logs as requested?  I suspect this is config related and perhaps a documentation issue.

However without understanding more about your setup I'm inclined to close the issue.

**Comment by rcastberg** [comment]
Thanks, i will try to get the logs and config posted at some point today.

**Comment by rcastberg** [comment]
Configs and log : https://gist.github.com/rcastberg/bcad6b5ef3f00395197961df270a4a47
There doesn't seem to be much information in them.

A note that i only get forwarded to the accounts page on android if i use chrome as the browser, if i use firefox or an incognitio tab i can use vouch proxy as normal.

**Comment by ngardiner** [comment]
I also see the same behaviour in Chrome on Android. The browser will open
the Accounts page of the Settings menu in Android, with no apparent way to
progress (going back to Chrome just redirects to Accounts again). I have
installed other browsers for the purpose of getting around this.

**Comment by bnfinet** [comment]
@rcastberg try commenting out `preferredDomain:` and then try again

Can i ask how many Google Accounts this device is logged into?  And are any of them **not** in the `preferredDomain`?

**Comment by rcastberg** [comment]
Only one account is logged in on android.

Removing prefered domains seems to have fixed the issues. Thanks

**Comment by bnfinet** [comment]
I'm glad it's working for you.  The relatively new feature of tight integration between Android system accounts and Chrome mobile for Google accounts has caused a variety of problems for many web based applications.
