### ISSUE TITLE
Nginx - Vouch - Okta connectivity

### ISSUE THREAD

**Issue by jessetandor** [vouch/vouch-proxy#196]
I'm having some issues getting my local page to authenticate with Okta. Ive setup vouch as well per the okta documentation (unsure if that is even up to date) plus the config provided here. I've provided both below and getting the same problem. 

- Running Nginx on OS X and vouch from docker (same machine)
- Using the same self-signed Cert for both server blocks (Common name *.jesse.test)
- I've turned on testing mode as well.

Everything:
https://hasteb.in/iboculoy.bash

Error's:
```
sseTan-MBP:infra-fort-knox jesse$ dol 067f611ab63570202ff43db543ad9f0905eb0a723d9939c285c006f5f80f698f
2020-01-09T18:41:03.116Z	INFO	testing: true, using development console logger
2020-01-09T18:41:03.119Z	INFO	jwt.secret read from /config/secret
2020-01-09T18:41:03.119Z	WARN	generating random session.key
2020-01-09T18:41:03.120Z	INFO	configuring oidc OAuth with Endpoint https://pipedrive.okta-emea/oauth2/v1/authorize
2020-01-09T18:41:03.133Z	INFO	starting Vouch	{"version": "14b5740", "buildtime": "2019-12-19T19:29:27Z", "buildhost": "453007767e95", "branch": "master", "semver": "v0.6.17", "listen": "0.0.0.0:9090", "oauth.provider": "oidc"}
2020-01-09T18:41:13.548Z	ERROR	no jwt found in request
2020-01-09T18:41:13.548Z	WARN	domain 127.0.0.1:9090 not found in any domains [jesse.test]
2020-01-09T18:41:13.548Z	INFO	|401|  424.185µs /validate	{"statusCode": 401, "request": 1, "latency": "424.185µs", "avgLatency": "424.185µs", "ipPort": "172.17.0.1:48738", "method": "GET", "host": "127.0.0.1:9090", "path": "/validate", "referer": ""}
2020-01-09T18:41:13.584Z	WARN	couldn't find existing encrypted secure cookie with name VouchSession: securecookie: the value is not valid (probably fine)
2020-01-09T18:41:13.585Z	INFO	|200| 1.029927ms /login	{"statusCode": 200, "request": 2, "latency": "1.029927ms", "avgLatency": "727.056µs", "ipPort": "172.17.0.1:48740", "method": "GET", "host": "login.jesse.test", "path": "/login", "referer": ""}
```
Mostly getting the 302 redirect error from the page -**302 redirect to: https://pipedrive.okta-emea/oauth2/default/v1/authorize?client_id=0oa3h5bq3zL2o0M700i7&redirect_uri=https%3A%2F%2Flogin.jesse.test%3A9090%2Fauth&response_type=code&scope=openid+email+profile&state=h97vRm7OatiO6XaUB8i1c7Wbwc4cIM**

I think there is something wrong with the cookie, but I can't determine what. Im also using a non developer Okta account if that makes a difference.

Any advice or tips would be greatly appreciated. 

Thanks.

**Comment by bnfinet** [comment]
welcome back @jessetandor :)

This domain does not appear to be valid: `pipedrive.okta-emea`.  What happens when you go directly to https://pipedrive.okta-emea/oauth2/default/v1/authorize ??

Are you familiar with `dig` and other tools that help diagnose dns lookup issues?  That's a good place to start with these sorts of issues.

For future items it would be helpful to me if you provided the logs in a hastebin as well, and also use separate `hasteb.in`s for each of nginx, vp config and the logs.

**Comment by jessetandor** [comment]
Ok, will provide separate file's next time.

In okta, the only address i see for the OpenID app is 'Issuer: https://pipedrive.okta-emea.com'.

It seems ill need to do some digging on Okta's side cause from their docs:

"If you have a developer account, you can use the default authorization server that was created along with your account, in which case the full URL looks like this - https://${yourOktaDomain}/oauth2/default/v1/authorize"

Most likely this wont work with a non developer account.

**Comment by aaronpk** [comment]
I believe with a non-developer account you'll need the "API Access Management" feature enabled for your organization.

**Comment by jessetandor** [comment]
I setup a Dev account to make life easier and got these:

```
  auth_url: https://dev-708129.okta.com/oauth2/default/v1/authorize
  token_url: https://dev-708129.okta.com/oauth2/default/v1/token
  user_info_url: https://dev-708129.okta.com/oauth2/default/v1/userinfo
```
Going to https://dev-708129.okta.com/oauth2/default/v1/authorize results in bad request so it does seem to be working. I also confirmed the app from Okta's side and it's running.

**Comment by bnfinet** [comment]
Please offer your complete configs and logs as requested.  Most of the time this is alignment between the configured domains.  The README portion "think like a cookie" might be helpful.

**Comment by jessetandor** [comment]
Here are my current settings:
https://hastebin.com/hemikamece.nginx

Logs and error's are the same as above.

**Comment by bnfinet** [comment]
What problem are you currently having?  What has changed since the last
time you posted?

**Comment by jessetandor** [comment]
The only change is that im using an Okta Dev account and updated endpoint's. So vouch is giving me a 302 when i aceess mypage.jesse.test, im assuming because of this:

```
2020-01-12T15:44:51.752Z	ERROR	no jwt found in request
2020-01-12T15:44:51.752Z	WARN	domain 127.0.0.1:9090 not found in any domains []
2020-01-12T15:44:51.753Z	INFO	|401|  406.854µs /validate	{"statusCode": 401, "request": 1, "latency": "406.854µs", "avgLatency": "406.854µs", "ipPort": "172.17.0.1:35432", "method": "GET", "host": "127.0.0.1:9090", "path": "/validate", "referer": ""}
```

**Comment by bnfinet** [comment]
You need to proxy-pass the $host header in the nginx validate block.  See
the nginx config in the README

**Comment by jessetandor** [comment]
Ok, by that you mean adding 
```
proxy_set_header Host $http_host;
```
to the local page's section: location=  /vouch-validate...?

Also do i need this :

    location / {
      proxy_pass http://127.0.0.1:9090;
      # be sure to pass the original host header
      proxy_set_header Host $http_host;

Current config: https://hastebin.com/rapoheqaya.nginx

**Comment by jessetandor** [comment]
I would appreciate it if anyone can tell what I'm doing wrong here. Thanks..

**Comment by bnfinet** [comment]
What happened when you added the host header?

 Take a close look at the differences between your nginx config and the
ones in the repo and the README.  If you still have problems, turn on
debug.  After that, post full logs and configurations.

**Comment by jessetandor** [comment]
Im abit confused on what you suggested tbh:

You have the proxy_set_header Host $http_host; flag in two separate locations. One under ' location = /validate ' and the other blocked out under # Vouch Proxy can run behind the same Nginx reverse proxy....

I have the same error after adding the host header to both sections as I've seen from your README.

Please, look at my config and specify where this header should be put: https://hasteb.in/eluhunun.nginx and then I will provide logs if still not working.

**Comment by bnfinet** [comment]
That configuration looks correct to me.

Please do turn on debugging and post your VP config and logs.

Benjamin Foote
bnf Systems LLC
Linux and Cloud Consulting
http://bnf.net
ben@bnf.net
@bnf

Currently working on:
Vouch Proxy
an SSO solution for nginx using the auth_request module
https://github.com/vouch/vouch-proxy

**Comment by jessetandor** [comment]
Im getting a 302 from Vouch but when I actually click on the link presented - it does take me to Okta..

SS: https://ibb.co/QbZqjBh

Vouch for nginx config - https://hastebin.com/mazenumoxu.nginx
Local site nginx config - https://hastebin.com/iturijalex.nginx
VP Config - https://hastebin.com/pidetexazu.shell
VP Logs - https://hastebin.com/gujivojeta.rb

Thank you.

**Comment by bnfinet** [comment]
@jessetandor thanks, a few things I notice...

* it looks like you never log in at okta, since the logs don't include a call to `/auth`
  * are you able to log into Okta?
  * what happens after you log into Okta?
 * the logs include `domain login.jesse.test not found in any domains []`.  What happens when you add `jesse.test`?
 * your logs include your secrets in the clear, you should change those :), `./do.sh bugreport` can help with that

**Comment by jessetandor** [comment]
I see, apologies! 
I did not read the #testing: true section thoroughly. This show's the redirect page (302).

With that turned off, the config seems to be correct - I am taken straight away to the Okta login page. Now after logging in, I am seeing `Err too many redirects` - and then a few seconds late I get :
```
oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."}
```

Clearing my cookies does fix the problem of presenting the Okta login page again, but it still fails with the too many redirects error..

**Comment by bnfinet** [comment]
Glad to hear it.

Did you update your config as per the log message?  What happened?

Every time you post to this thread from here on out could you please post
fresh logs and configs if there has been any change.

**Comment by jessetandor** [comment]
Seem's its working now. The key was using 
```
  domains:
  - jesse.test
```
with 
```
  allowAllUsers: true
```
Since in the VP documentation - you've put ** OR ** in the Vouch section it would suggest it's one or the other. Perhaps this can be changed or a note can be put there to help others :)

**Comment by jessetandor** [comment]
Hi @bnfinet, could you please replace your second post with 'company.okta-emea' and 'https://company.okta-emea/oauth2/default/v1/authorize'. Thanks.
