### ISSUE TITLE
Return the refresh token from Google Oauth2

### ISSUE THREAD

**Issue by tsandor** [vouch/vouch-proxy#197]
I wonder if there's a way to retrieve and expose a vouch endpoint that could request for a new access token (if the previous is expired) using the refresh token Google can send when access_type is offline.

Sources:
 - https://developers.google.com/identity/protocols/OAuth2WebServer#offline
 - https://tools.ietf.org/html/rfc6749#section-6

**Comment by bnfinet** [comment]
What's your use case?  Whenever we've discussed refresh token we've come
down on the side of not wanting to be exposed to handling refresh.  The
thinking it's that it's not onerous to have the end user periodically authn
at the IdP.

**Comment by tsandor** [comment]
When Google responds with the access token it expires after a few minutes. I thought I can refresh the token using the refresh_token silently and not sending the user back to /login.

**Comment by bnfinet** [comment]
The Google access token expiration should not have any bearing on the Vouch Proxy token expiration.  You should only need a few seconds to validate the return to `/auth` and to then fetch the user information.  Then you've cleared Google authn and it's on VP's side.

I'm going to close this for now.  If we find a clear need/desire for refresh token support then perhaps we'll revisit this feature once again.
