### ISSUE TITLE
When domains configured, access via email on different domain should not be possible.

### ISSUE THREAD

**Issue by eikehartmann** [vouch/vouch-proxy#198]
**Problem**: Came across some lines of code that look like the check of email against configured domain(s) is not tight enough (`strings.Contains`), which is provable by a simple test written around the involved methods.

**Expected behaviour**: When I have `vouch.github.io` configured in `vouch.domains`, I would want to authorise only `test@vouch.github.io`, but _not_ `vouch.github.io@example.com` _nor_ `test@some-vouch.github.io`.

Local test configuration against GitHub OAuth app and log:
https://hasteb.in/soguvede.yaml

**Comment by bnfinet** [comment]
thanks @eikehartmann 

nice catch!

**Comment by eikehartmann** [comment]
👍
