### ISSUE TITLE
Logic to support boolean claim values is causing all claim values to be treated as strings

### ISSUE THREAD

**Issue by rmak-cpi** [vouch/vouch-proxy#200]
First of all, thanks to all the contributors who help to create and maintain vouch-proxy, it has definitely made my job easier! So in the spirit of contributing in whatever minor way I can, I would like to report that the following logic at https://github.com/vouch/vouch-proxy/blame/master/handlers/handlers.go#L213 intended for supporting boolean claim values:
```
	val := fmt.Sprint(v)
	if reflect.TypeOf(val).Kind() == reflect.String {
		// if val, ok := v.(string); ok {
```
seems to be causing all claim values to be treated like a string since the output of fmt.Sprint is always a string. In particular, handling of groups claims (which are slices of strings) has become rather awkward as there is no unambiguous way to differentiate spaces between strings in the slice and spaces embedded in individual strings.

Please let me know if more information is needed from me or if a PR is preferred.

**Comment by bnfinet** [comment]
@rmak-cpi sorry for the delay in getting back to you

A PR is preferred.  Are you in a position to cut one?

thanks for the kind words about VP

**Comment by rmak-cpi** [comment]
Hi @bnfinet, sorry for the delayed response. I was hoping to come up with some test coverage for the code that I have changed which turned out to be a bit more challenging than I anticipated. I should be able to come up with something by the end of this week (2/14) if not sooner.

**Comment by rmak-cpi** [comment]
Hi @bnfinet, I have created https://github.com/vouch/vouch-proxy/pull/209 as an attempt to address this issue.

**Comment by bnfinet** [comment]
Sorry for the delay @rmak-cpi.  I need to figure out how best to test this PR, and really how best to test custom claims going forward.

My gut is telling me is time to start building a set of good mocks for each IdP's return values for `oauth.user_info_url`.  The tests you created in #209 are a step in that direction.  But that's a bit of a heavy lift.

@artagel would you be in a position to evaluate this PR?  It'd be nice to get extra eyes on it.

FWIW here's the compare of the relevant change that introduced the bug..

https://github.com/vouch/vouch-proxy/compare/v0.6.15...v0.6.16#diff-86dfd2701799f0e8216ef67a88e1e12eR209-R218

and here's the commit..
https://github.com/vouch/vouch-proxy/commit/80fcfdb95d0d9f4f8582a5cbbdbb871ed635b0f4

**Comment by bnfinet** [comment]
thanks again for the fix @rmak-cpi
