### ISSUE TITLE
Nginx not redirecting to Vouch correctly

### ISSUE THREAD

**Issue by jessetandor** [vouch/vouch-proxy#211]
Hello,

I'm back with another problem and hoping for some clarity. My current config does not seem to redirect to the vouch login page (302) and I'm unsure why. The URL I am getting is `https://login.vouch.okta/login?url=https://kafka-ui.tll-m3.company.dev/dev-tln-ite-cluster/topic&vouch-failcount=&X-Vouch-Token=&error=`

Nginx Config: Ubuntu Default and pointing to a folder where the two nginx files below sit (include /x/x/x*.conf)
Web Site Config: https://hasteb.in/duwotupe.pl
Nginx Vouch Config: https://hasteb.in/xetovigi.nginx
Vouch Config: https://hasteb.in/nudicagu.yaml
Vouch Logs: https://hasteb.in/jawuwaso.lua

The initial *login.vouch.okta* is picked up and looking at Vouch logs - the domain seems incorrect. I've tried to fix but nothing has worked.

I should be redirected to the Vouch Login Page but haven't been successful so far. I had to remove some IP's due to security.

**Comment by bnfinet** [comment]
@jessetandor IIRC from the last ticket you submitted you don't have access to the DNS settings for your domain, is that correct?

If you are restricted to one domain then you will need to configure VP for a passthrough setup.

see this config..
https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/single-file/nginx_with_vouch_single_server.conf

**Comment by bnfinet** [comment]
@jessetandor I'm going to close this for now.  Feel free to repost to this thread if you need further support.
