### ISSUE TITLE
versioned alpine builds do not exist

### ISSUE THREAD

**Issue by martinwaite** [vouch/vouch-proxy#217]
**Describe the problem**
Section 'Running from Docker' in the overview page on Docker Hub states that versioned alpine images are available as voucher/vouch-proxy:x.y.z_alpine.  This does not appear to be true.

**Comment by bnfinet** [comment]
thanks @martinwaite do you have particular need for these?  I don't use the Alpine based builds.

Since you're the first to notice this I'm inclined to drop support.

Is there a reason you're looking for a particular version?  Are you having problems with the `latest` alpine build?

**Comment by martinwaite** [comment]
I'm using the alpine build as the base of a new container that uses confd to build the config file from environment variables. Having the versioned build would give me better traceability - but it's not a must have. I can probably get the version number from the vouch-proxy executable.

**Comment by bnfinet** [comment]
I fixed this as a docu-bug.  If anyone would like to support a versioned alpine based build at Docker Hub I'd be happy to link to it from the README.
