### ISSUE TITLE
Looking for some help with AWS Cognito.

### ISSUE THREAD

**Issue by rogerscuall** [vouch/vouch-proxy#220]
**Describe the problem**
Trying to use vouch with AWS Cognito, the pool is already working with other applications and the authentication looks to be successful according to the logs in CloudWatch.

**Expected behavior**
User to get authenticated with access to the service protected by vouch.

**Desktop (please complete the following information):**
 - Browser: Chrome, or Firefox

**Smartphone (please complete the following information):**
 - OS: MacOS

**Additional context**
The authentication process looks like its working, AWS Cognito redirect back to vouch but after the redirect, Vouch throws a 400 error with this description`invalid character '<' looking for beginning of value`
Configuration of the Vouch using helm:
https://gist.github.com/rogerscuall/250bad0409284db6157deaf24f1ec607
Errors in the console of the pod:
https://gist.github.com/rogerscuall/a00a81c6d9d10f1f1e9c117ac37415d9
I followed this to configure Cognito:
https://github.com/vouch/vouch-proxy/issues/105
Vouch is creating a cookie with name VouchSession.

**Comment by bnfinet** [comment]
Please double check your urls in your oauth config.  IIRC one of them must
be capitalized.  I think it's the user info one.

**Comment by rogerscuall** [comment]
That worked, I actually had a typo in user_info_url.
