### ISSUE TITLE
Can't make CORS work with my page

### ISSUE THREAD

**Issue by therealpaulgg** [vouch/vouch-proxy#223]
**Use a Paste Service**
Vouch logs:
https://hasteb.in/basasara.rb

Vouch Config:

https://hasteb.in/ruvuzaco.yaml

Nginx Config for Vouch is identical to the one in the main README

My config for my static resource includes 'Access-Control-Allow-Origin':

```
 location / {
        root /var/www/static;
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
    }
```

Chrome Console logs:
https://hasteb.in/ebabesup.nginx

**Describe the problem**
(I am using Gitea as my oauth provider)
I travel to docs.mydomain.com, and it is not able to load resoruce from static.mydomain.com due to CORS error (not preflight, it just says that Access-Control-Allow-Origin is not set)

**Expected behavior**
When I travel to my page docs.mydomain.com, I expect it to be able to load a CORS resource from static.mydomain.com. In the nginx config for static.mydomain.com, a CORS * header is already set. This page worked before I began using Vouch. 

**Desktop**
 - OS: Windows
 - Browser Microsoft Chromium Edge

**Server**
- OS: Ubuntu 18.04 LTS

**Comment by bnfinet** [comment]
Please search the issues for OPTIONS

**Comment by therealpaulgg** [comment]
I have tried this solution. put it on docs and static nginx config under location /validate. No dice.

**Comment by bnfinet** [comment]
Please post your full nginx config

Does it work for non CORS sites?

**Comment by therealpaulgg** [comment]
Yes. I am able to access the static resource and docs resource through the browser, but when docs tries to load the static resource through a async get request, it fails.

Nginx config for docs: 

https://hasteb.in/fisufubi.nginx

Nginx config for static:

https://hasteb.in/qumeyani.nginx

Nginx config for Vouch:

https://hasteb.in/uyadelob.php

Nginx config for Gitea (if relevant):

https://hasteb.in/ticixita.nginx

**Comment by bnfinet** [comment]
please post full VP logs with `loglevel: debug`

**Comment by therealpaulgg** [comment]
here's a logfile since I restarted the server and tried to test again:

https://hasteb.in/ularirej.yaml

Not sure if you need older logs than this, I can't include my entire logfile as its too long

**Comment by bnfinet** [comment]
`domain 127.0.0.1 not found in any domains []`

Why aren't your requests showing up as requests for `docs.vilagesocial.app`?  Looks like Host header is not being forwarded to VP properly. 

have you tried setting `vilagesocial.app` in `vouch.domains`?  What happens?

These are XHR requests, yes?  Are you setting `withCredentials`?
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by therealpaulgg** [comment]
Ok, I kinda gave up. Not totally sure what the issue is. I'm using SwaggerUI as a React component (https://www.npmjs.com/package/swagger-ui-react) in this docs app, and when I thought about what you said about XHR requests, I noticed on their site that they say that OAuth redirection handling is not supported. I just put the JSON resource on the same domain as my docs site and called it a day.

If anyone else has CORS issues in the future please feel free to reopen, or if a solution is found.
