### ISSUE TITLE
Vouch Proxy with Nginx and Keycloak throwing 'no jwt found in request' error

### ISSUE THREAD

**Issue by GauravAshara** [vouch/vouch-proxy#224]
Please check my configuration with below link 

Here are my logs. 
Vouch  : https://hasteb.in/egagixog.http
Nginx :  https://hasteb.in/obetemeb.nginx
logs : https://hasteb.in/pidakeqa.yaml

**Comment by bnfinet** [comment]
your nginx config is not aligned with your VP config..

* no `auth_request` module being used
* `/auth` endpoint forwards to 8080 not 9090
* `callback_url: http://localhost/auth` is http but will get forwarded to https
* no error block to catch the 401 redirect

plus its unusual to do this all through `localhost`.  You're better off IMHO mapping a domain to 127.0.0.1 using `/etc/hosts`

Please re-read the documentation concerning nginx and work on your config.

**Comment by bnfinet** [comment]
this might be a good starting point for you nginx config...

https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/single-file/nginx_with_vouch_single_server.conf
