### ISSUE TITLE
Home Assistant config help - auth does not redirect back

### ISSUE THREAD

**Issue by mjnaylor8** [vouch/vouch-proxy#226]
I am trying to get Vouch working with my home assistance instance.  The 302 redirect works fine to the homeassistant login but I do not get redirected back after the login and continue to Homeassistant. 
I have got it working fine using Okta which suggests I have the config correct?
Vouch is running on Docker @ vouch.thenaylors.co.uk
Homeassistant is running @ homeassistant.thenaylors.co.uk with a 
301 redirect to port 8123 on the local server.
I have put on testing in vouch and have pasted the results here
https://hasteb.in/obuvacuj.lua

I think this is probably a home assistant problem and not a vouch one but hoping perhaps someone like @talltechdude might explain what I am doing wrong.

the 302 is like this
https://homeassistant.thenaylors.co.uk/auth/authorize?client_id=https%3A%2F%2Fvouch.thenaylors.co.uk&redirect_uri=https%3A%2F%2Fvouch.thenaylors.co.uk%2Fauth&response_type=code&state=zMD548Obx9OsRLynb59YMc7f9BYfRYxW

the config.yaml is exactly like the example.

**Comment by bnfinet** [comment]
please upgrade your VP and post your (redacted) VP config

This line implies that the HA is forwarding back to VP.  Are you able to login to HA? 
`ERROR	/auth Invalid session state: stored zMD548Obx9OsRLynb59YMc7f9BYfRYxW, returned  ,`

**Comment by talltechdude** [comment]
@mjnaylor8, if you are using the Supervisor based version of HomeAssistant, I've developed some plugins that may make your life easier. Check the start of my repo here: https://github.com/talltechdude/hassio-addons.

Its got a standalone Vouch plugin and also Vouch integrated into Nginx Proxy Manager community plugin. You can have a look at the various config files and see if they help at all.

**Comment by mjnaylor8** [comment]
@bnfinet Thanks.  Updated VP.  Tried with Nextcloud locally hosted and this config works OK too however still no joy with HA.  I can log into HA.
My redacted VP config is here
https://hasteb.in/analuqim.yaml
Is there some config needed in HA.  I have looked in the HA documentation on authentication and can't see anything needed to the config.  Maybe I missed something?
@talltechdude not using that version of HA but the plugins look neat.  Maybe I'll switch

**Comment by bnfinet** [comment]
are you still getting errors such as...
`ERROR	/auth Invalid session state: stored zMD548Obx9OsRLynb59YMc7f9BYfRYxW, returned ,`

This is saying that HA is not passing the state variable back to VP which it received from VP in the request to https://homeassistant.thenaylors.co.uk/auth/authorize (state is a nonce).

Please post updated logs.

**Comment by mjnaylor8** [comment]
Hi - still have the same problem HA does not return back to Vouch.
Here is the log from Vouch.  This was done on a new session using Firefox with all cookies and history purged.
https://hasteb.in/odikalet.lua
I have checked the HA logs too and there is nothing there either.
Could it be something in the NGINX config in Content-Security-Policy headers?

**Comment by bnfinet** [comment]
That's a regression.  Your prior log did include a return to /auth and
showed an Error (no state).

Assuming your VP config is the same this is on the HA side.  If it has
changed then please post it.

**Comment by mjnaylor8** [comment]
I have recreated the /auth.  It was not part of the HA login process but from navigating to https://vouch.thenaylors.co.uk/auth.
So problem is still there.  I have a hassbian pi somewhere.  I'll see if that gives a similar error and if not then will look more into my the HA implementation on Debian.

**Comment by mjnaylor8** [comment]
Further review.... tried Hassbian - same problem.  Tried using vouch infront of another app - same problem. 
The URL generated by vouch is 
https://homeassistant.thenaylors.co.uk/auth/authorize?client_id=https%3A%2F%2Fvouch.thenaylors.co.uk&redirect_uri=https%3A%2F%2Fvouch.thenaylors.co.uk%2Fauth&response_type=code&state=j5x54W7kAcZQno4btL126mrzYMO4GdE

However the login url for HA is 
https://homeassistant.thenaylors.co.uk:8123/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fhomeassistant.thenaylors.co.uk%3A8123%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fhomeassistant.thenaylors.co.uk%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9ob21lYXNzaXN0YW50LnRoZW5heWxvcnMuY28udWs6ODEyMyIsImNsaWVudElkIjoiaHR0cHM6Ly9ob21lYXNzaXN0YW50LnRoZW5heWxvcnMuY28udWs6ODEyMy8ifQ%3D%3D

if I alter the URL to remove authorize?response_type....etc from the HA URL and replace with the Vouch URL I can login and get redirected back to vouch.  I then get another error from vouch.thenaylors.co.uk/auth like this
`invalid character '<' looking for beginning of value`

So on the face of it,  not techie enough to understand this HA is not taking the URL passed to it but transforming it for some reason and loosing the redirect.

**Comment by bnfinet** [comment]
> However the login url for HA is
> https://homeassistant.thenaylors.co.uk:8123/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fhomeassistant.thenaylors.co.uk%3A8123%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fhomeassistant.thenaylors.co.uk%3A8123%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9ob21lYXNzaXN0YW50LnRoZW5heWxvcnMuY28udWs6ODEyMyIsImNsaWVudElkIjoiaHR0cHM6Ly9ob21lYXNzaXN0YW50LnRoZW5heWxvcnMuY28udWs6ODEyMy8ifQ%3D%3D

this URL includes port `:8123` is that reflected in your VP config?

this URL includes

**Comment by mjnaylor8** [comment]
Hurray!  Thank you @bnfinet .
So very important that the url in vouch also includes any port number.
This now works fine.

**Comment by mjnaylor8** [comment]
and a thank you to all who created vouch!

**Comment by bnfinet** [comment]
glad it's working for you @mjnaylor8 and thanks for the kind words

**Comment by mjnaylor8** [comment]
It might be worth updating the homeassistant config example to include port 8123.  Generally the NGINX setup for HA is either
location / {
 proxy_pass https://ipaddress:8123;
}
or 
location / {
   return 301 https://$host:8123/;
}

**Comment by bnfinet** [comment]
Feel free to submit a PR

**Comment by mjnaylor8** [comment]
GitHub newbie with lots to learn. Nothing like being retired and @home at this weird time.
Will look up how to do so and will!


Thanks (again) Michael
Sent from my iPhone

On 26 Mar 2020, at 17:27, Benjamin Foote <notifications@github.com> wrote:

﻿

Feel free to submit a PR
