### ISSUE TITLE
CustomClaims Groups joins on " " and not "," starting in 0.6.16

### ISSUE THREAD

**Issue by oferrigni** [vouch/vouch-proxy#227]
**Describe the problem**
When using custom claims, "groups", groups are returned joined by a " " and not by a ",". This results in an unusable headers as our groups can have " " in them. This appears to have changed from 0.6.15 to 0.6.16.

**Expected behavior**
Either the header delimiter should be configurable or default to ","

**Comment by bnfinet** [comment]
This is probably a dup of #200 addressed by #209 (HT @rmak-cpi)

@oferrigni would you be able to test #209 and see if it fixes your issue

If it does, could you please mark this as dup (close) and lets continue the discussion there

also in the mix of claims is #221 though that's probably a separate issue.

**Comment by bnfinet** [comment]
@oferrigni this should be fixed in `v0.10.1`, do let me know if that is not the case
