### ISSUE TITLE
Vouch Proxy Cookie too large for protected app 

### ISSUE THREAD

**Issue by p-doyle** [vouch/vouch-proxy#229]
[Vouch config](https://hasteb.in/bugukiru.yaml)
[Nginx config](https://hasteb.in/facimusi.nginx)

**Describe the problem**
The authentication flow works fine and I am redirected back to the original URL, https://subdomain.mydomain.com:8444.  When in Firefox, nothing at all returns and the page is blank.  When in Chrome, the page just displays [this](https://hasteb.in/mosopiyo.yaml), which seems to have a truncated copy of the vouch cookie.  If I remove the authentication requirement from Nginx the page loads fine.

**Expected behavior**
I would expect to be able to view the page being proxied by Nginx.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.149
 - Browser: Firefox
 - Version: 74.0

**Server**
- OS: Ubuntu 18.04.4
- Nginx Version: 1.14.0

**Comment by bnfinet** [comment]
What happens when you put the 'auth_request' directive in the server block
as per the README?

If that doesn't work please post your VP log and describe/show the request
from the browser as seen in developer tools.

And try the samesite stuff in #210.  That failed request mentions samesite.

**Comment by bnfinet** [comment]
@p-doyle any progress?  If not I'm inclined to close the issue

**Comment by p-doyle** [comment]
Moving the auth_request didn't change anything.

Here is the vouch log: https://hasteb.in/ilexuxid.json

Here are the headers from the Network tab in Chrome's dev tab.  https://hasteb.in/ogobotac.yaml 
Is that what you were looking for from the dev tools or was there something else?

Thank you for looking into this.

**Comment by bnfinet** [comment]
@p-doyle my apologies those `hasteb.ins` are no longer active.

Are you still working this issue?  Could you please try again with the most recent version of VP and repost your config and logs.

**Comment by p-doyle** [comment]
Updated to 0.9.2

[Nginx Config](https://hasteb.in/amovosay.nginx)
[Vouch Config](https://hasteb.in/juzefumo.yaml)
[Chrome Dev Headers](https://hasteb.in/olizugux.yaml)
[Vouch Log](https://hasteb.in/hojoquye.json)

**Comment by bnfinet** [comment]
with debug and testing please (see the README)

**Comment by p-doyle** [comment]
Sorry about that, see https://hasteb.in/vihikuza.pl

**Comment by bnfinet** [comment]
> When in Chrome, the page just displays "this"
can you please repose the chrome response

It appears that VP is working as expected.  Is there anything else about your nginx setup that is noteworthy?  Are there other proxies involved?  Are your buffers set odd?

It might be worth trying to adjust your buffers..
http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size

I notice that the headers include `status: 000` which could indicate some general network error. 
https://stackoverflow.com/questions/9791684/what-is-http-status-code-000

what happens when you remove `client_max_body_size 0;`??

**Comment by p-doyle** [comment]
This is what is displayed in Chrome https://hasteb.in/depewecu.yaml  In Firefox its just a blank page.

I tried removing client_max_body_size but that did not change anything,  I'll look into the buffers and status code.

Thanks for the help.

**Comment by bnfinet** [comment]
what is `Server: Acadia Server - v2.0`?

**Comment by p-doyle** [comment]
I really have no idea.  Its not related to the proxied webpage or anything else I have running.  I tried searching online for it but couldn't find anything....

**Comment by p-doyle** [comment]
It looks like the issue is with the proxied web server being unable to handle the size of the vouch cookie... If I add `proxy_set_header Cookie "";` inside the location in the nginx config it works fine.  Sending a manual request directly to the web server with a large cookie returns a blank response.

I realize the issue isn't technically with Vouch but Is there anyway to reduce the size of the vouch cookie somehow?

**Comment by bnfinet** [comment]
What is the proxied app?

**Comment by p-doyle** [comment]
Its the webpage for a 3rd party water treatment controller.  Unfortunately I don't have access to the code or anything else that might help troubleshoot that further.

**Comment by bnfinet** [comment]
How about trying to remove the Vouch Proxy Cookie in nginx before passing it to the app..
https://librenepal.com/article/remove-specific-cookies-with-nginx/

**Comment by p-doyle** [comment]
Ah wow that is perfect.  I had searched for something like that but must not have used the right wording so had to settle for removing the entire cookie...  Thanks!

**Comment by bnfinet** [comment]
My pleasure.  Closing for now, but please do let us all know if that solution does not work.  I'm sure others will run into this issue.
