### ISSUE TITLE
Log out with Okta

### ISSUE THREAD

**Issue by psmod2** [vouch/vouch-proxy#231]
Hi,

I'm trying to perform a logout however however a few questions/really not clear what needs to be done from my side and what is handled by vouch:

- I'm using Okta which states the logout url is `https://{oktaBaseUrl}/logout?id_token_hint=${id_token}`. Is that id_token provided by vouch or do I need to specify.
- I presume the URL i need to hit is `https://{myvouchproxy}}/logout?url={URL above (not sure if id_token_hint}`
- Do I need to add a location in my nginx config to handle that `/logout` path like:
```
location /logout/ {
             return 302 https://{myvouch}/logout?url={url from point 2};
    }
```

Really quite confused about all this so any help would be appreciated - even with Okta - what is that required `id_token_hint` no idea where thats coming from.

Regards.

**Comment by bnfinet** [comment]
please see #40

**Comment by psmod2** [comment]
I've read that comment however I'm still unsure whether I need a nginx config something like:

```
location /tools/app/logout {
    	return 302 https://vouc.mydomain.com/logout?url=https://x.okta.com//oauth2/default/v1/logout?id_token_hint={sometoken}
    }
```

Is there an existing example for Okta if this is required?

**Comment by bnfinet** [comment]
That is not implemented, I'm hoping someone will submit a PR after further discussion.  If you have any further questions please ask it in that thread.
