### ISSUE TITLE
Type of OAuth Flow

### ISSUE THREAD

**Issue by tangel0v** [vouch/vouch-proxy#233]
## Question about type of OAuth flow

Hi to all, thanks for your great work. I only have a question to do: Which type of OAuth flow does support _vouch-proxy_ ? Implicit? Codegrant? Codegrant + PKCE?

I am trying to setup it with an ADFS server and I don't have found any documentation about it.

Thank you very much again!

**Comment by bnfinet** [comment]
It's code grant

https://oauth.net/2/grant-types/authorization-code/

**Comment by tangel0v** [comment]
Thank you very much! I will close this issue.
