### ISSUE TITLE
getting invalid_grant with AWS cognito

### ISSUE THREAD

**Issue by arghyanator** [vouch/vouch-proxy#237]
Hello,

I need some help in figuring out the issue with integrating a Nginx proxied web site and authentication with AWS cognito for the app using Vouch (vouch, app and nginx are all running on same instance).

I am getting invalid_grant. However, in the logs I do see a token with username, etc.

Vouch config: https://hasteb.in/kamejiqi.yaml
Nginx configs: https://hasteb.in/arayiyoy.nginx, https://hasteb.in/rewadose.nginx

vouch Log snippets: https://hasteb.in/isicowen.json

Appreciate your help,
Thank you,
Arghya

**Comment by bnfinet** [comment]
Please turn on `testing` as per the README and post full logs.  It's hard for me to see coming through nginx and what's not.

You have `vouch.cookie.secure: false` but you're using https.  That should be true.  That might be enough to get the cookie/jwt in place and for `/validate` to return 200.

Are you trying to pass claims or tokens back to your app?  That does not appear to be configured.

**Comment by arghyanator** [comment]
Hello @bnfinet ,

Thank you for the quick response. I tried again after setting `vouch.cookie.secure: true ` and `testing` to true. 

New logs - https://hasteb.in/agadicud.yaml

I currently dont have an app - just trying to see if I can protect an html page behind the nginx server (instead of using .htpasswd - use cognito for authentication).

Thank you,
Arghya

**Comment by arghyanator** [comment]
<img width="1140" alt="Screen Shot 2020-04-01 at 9 12 50 PM" src="https://user-images.githubusercontent.com/20214427/78210205-503acc80-745e-11ea-8837-7ea1b0875854.png">
this is the cognito app client settings. 
Thank you,
Arghya

**Comment by bnfinet** [comment]
that log does not show the `/auth` endpoint (`callback_url`) getting hit whereas your prior log does.  What happens when you log into cognito?

**Comment by bnfinet** [comment]
try this config..
https://hasteb.in/yunopere.yaml

the README includes a section "think like a cookie" that may be helpful

**Comment by arghyanator** [comment]
I am all set.
Since I dont have a DNS system for my testing right now, I am using local `/etc/hosts` file to set `<serverIP> mytestdomaindunamis.com regular.mytestdomaindunamis.com vouch.mytestdomaindunamis.com` (which are all running on the same testing instance).

regular = my app or web page (on TCP:80)
vouch = vouch  (on TCP:9090)

vouch config.yml - https://hasteb.in/ejobukod.yaml
nginx config - https://hasteb.in/dikiwiki.nginx

Cognito settings as posted earlier.

Thank you for your help,
Arghya

**Comment by arghyanator** [comment]
I am all set - I have updated the issue with the working cognito app client configuration and configuration files (nginx as well as vouch config). Closing the issue - thank you for your help and guidance.

**Comment by bnfinet** [comment]
You're very welcome.  Thank you for sharing your working configuration.
