### ISSUE TITLE
Google Oauth callback_url

### ISSUE THREAD

**Issue by mindfuucker** [vouch/vouch-proxy#239]
I've successfully setup vouch at vouch.domain.nl with docker and put it behind my reverse proxy (Nginx) with some nice HTTPS certificates. 

Vouch will be used at three domains, vouch.domain1.nl, vouch.domain2.nl and vouch.domain3.nl. They all have certificated and point to the same local internal location: 127.0.0.1:9090. 

For testing purposes I've put my torrent client Deluge on deluge.domain1.nl. It's Nginx config is located [here](https://hastebin.com/lokavaxene.nginx). The Nginx config for vouch looks like [this](https://hastebin.com/katujojiga.nginx). 

My .yml config uses Google as OAuth provider, the total config looks [like this.](https://hastebin.com/dikobucizi.php) 

**Describe the problem**
After successfully entering my credentials it returns me to vouch.domain1.nl and not deluge.domain1.nl. There it shows me 404 page not found and[ the following state](https://hastebin.com/awesatupaf.pl) in the URL.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10 (docker)
 - Browser Multiple

**Additional context**
I've put the docker output into a hastebin: [link](https://hastebin.com/mexaheceze.pl). 

**My thoughts**
I think I put the wrong redirect URL somewhere. My Google Oath screen looks like this:
![image](https://user-images.githubusercontent.com/5075692/78290662-58f5d600-7524-11ea-81c0-c6719554e654.png)

**Comment by bnfinet** [comment]
as per the README "be sure to direct the callback URL to the /auth endpoint"
https://github.com/vouch/vouch-proxy#installation

for further support please turn on `testing` and repost full logs (also as per the README)

**Comment by bnfinet** [comment]
@mindfuucker Is this issue resolved?
