### ISSUE TITLE
Whitelist case-sensitive?

### ISSUE THREAD

**Issue by mindfuucker** [vouch/vouch-proxy#241]
For my configuration I'll refer to this Issue: [Link](https://github.com/vouch/vouch-proxy/issues/239). 

My friend called Sytze tried to enter my whitelist-protected subdomain. His email is Sytze@domain.com. 
I've put sytze@domain.com in the whitelist and Vouch barred him from entering. 

Why is the whitelist case-sensitive for email addresses? I can understand it for usernames.

**Comment by bnfinet** [comment]
How hard is it for you to enter his preferred email address or to whitelist
a few permutations?

According to the RFC the username (host local portion) is case sensitive.

https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive

I agree in practice that email addresses tend to be case insensitive.
However the email address in this case is what's returned by the IdP and
the IdP can be considered an authoritative database for this purpose.  Just
use whatever the IdP returns for the user.

**Comment by mindfuucker** [comment]
Hello @bnfinet,

It's not hard to do, it's just not something I expected. I've searched the Github Issues but couldn't find someone with the same problem. 

I will make a pull request for the example config showing multiple permutations.

**Comment by bnfinet** [comment]
No thank you.  I don't think a PR is necessary.

**Comment by mindfuucker** [comment]
Then you can reject it.
