### ISSUE TITLE
Application 1 functions perfectly, Application 2 fails

### ISSUE THREAD

**Issue by mindfuucker** [vouch/vouch-proxy#243]
Hi,

I've been using Vouch together with Gitea perfectly for application1 on deluge.domain1.com

Using application2 should be as simple as copy-paste from the app1 nginx config. So I did. 

The thing is: application2 keeps me redirecting in a loop even after a successful verification by Gitea.

**Docker output:** [link ](https://hastebin.com/cefitazexe.sql)
**Nginx config app1:** [link](https://hastebin.com/sanuziruse.nginx)
**Nginx config app2:** [link](https://hastebin.com/yulumaruri.nginx)

**Describe the problem**
With testing set to true I find myself clicking endlessly. Without testing set to true it's too many redirects error. 

**Desktop:**
 - Docker latest
 - Chrome version 80

**Additional context**
Is the cookie set on the wrong host?

**Comment by bnfinet** [comment]
please post your VP config

**Comment by bnfinet** [comment]
@mindfuucker feel free to repost here and I'll reopen the issue
