### ISSUE TITLE
Segmentation fault when no domain is set in config.

### ISSUE THREAD

**Issue by vishalg** [vouch/vouch-proxy#244]
**Logs**
[here](https://hastebin.com/kilunadifu.rb)

**Describe the problem**
vouch-proxy fails to start and exits with a segmentation fault. I have previously been running with the same config upto version 0.8.0 using the docker image from docker hub. Since 0.9.0 (includin 0.9.1) it has stopped working. I then rebuilt binary locally and get the same error

**Server**
- OS: Ubuntu 18.04.1 x86_64, Go1.14.2 linux/amd64
- Also tried the pre-built docker hub images both the latest and alpine builds

**Expected behavior**
Expect vouch proxy to start and run

**Additional context**
I have `allowAllUsers` set to `true` without any `domains` configured in the config (as per the documentation). If I add a domain to the config file it works fine, however, that will not work for all usecase.

**Comment by bnfinet** [comment]
thanks for the report @vishalg sorry for the regression

Could you please test `v0.9.2` and confirm the fix?

**Comment by vishalg** [comment]
Confirmed v0.9.2 fixes the issue. Thank you @bnfinet for the quick turn-around.
