### ISSUE TITLE
Question on Refresh Tokens

### ISSUE THREAD

**Issue by reverendpaco** [vouch/vouch-proxy#245]
I have surmised by reading through Vouch's repository that Vouch issues cookie JWT tokens that it creates, even if Vouch ultimately uses another OpendId identity provider to do the auth.

What I'm curious about is how refresh tokens are handled?  Using Cognito as an example, which returns the refresh token along with authorization token, does Vouch maintain internal state and periodically call the upstream Cognito refresh API to reacquire an AWS supplied token?  Or is Vouch's model "one and done" with respect to the originating authorizer?

Sorry for such a basic question, but I'm trying to understand how revocation would work with respect to Vouch and an upstream Idp.

**Comment by bnfinet** [comment]
Refresh tokens are not handled.

Whenever we've discussed refresh token we've come down on the side of not wanting to be exposed to handling refresh.  The thinking is that it's not onerous to have the end user periodically authn at the IdP.

For revocation of the JWT you can use the `/logout` endpoint as per the README, or if you need to remove access for a user immediately (how to fire bob) then after you update the user's permissions at the IdP you change the Vouch Proxy secret (either in config.yml or with `rm ./config/secret`) and restart VP.  This will cause all users to reauth.

related: #197
