### ISSUE TITLE
no jwt found in request

### ISSUE THREAD

**Issue by d875167** [vouch/vouch-proxy#246]
Hi

I'm trying to setup my site with following config https://github.com/vouch/vouch-proxy/tree/master/examples/nginx/multi-file but it keeps redirecting after authenticating with azure.
Any idea what can be wrong?

Nginx and docker container for vouch are running on the same host.
config https://hasteb.in/amohepas.yaml
nginx app1 https://hasteb.in/aximobaj.nginx
nginx vouch https://hasteb.in/vivalago.nginx
log https://hasteb.in/elutuhiw.lua

**Comment by bnfinet** [comment]
Your 'vouch.domains' should be mydomain.com

Please do let me know if that doesn't work for you.

**Comment by d875167** [comment]
Thanks that solved the problem.

Where can I find an example of nginx config for logout? 
"https://vouch.mydomain/logout?url=https://login.microsoftonline.com/common/oauth2/v2.0/logout" just logs me out at azure but app1 stays accessible.

**Comment by bnfinet** [comment]
Which browser? Try doing a hard refresh Shift+f5 of app1.  I suspect you're
seeing a local cached copy.

If not please post logs of the logout.
