### ISSUE TITLE
Unable to build any release since 0.7.1

### ISSUE THREAD

**Issue by p-doyle** [vouch/vouch-proxy#248]
This is what I get when running `go build` for every version after 0.7.1:

```
pkg/cookie/cookie.go:35:14: undefined: http.SameSite
pkg/cookie/cookie.go:39:15: undefined: http.SameSiteLaxMode
pkg/cookie/cookie.go:41:15: undefined: http.SameSiteStrictMode
pkg/cookie/cookie.go:46:15: undefined: http.SameSiteNoneMode
pkg/cookie/cookie.go:58:11: unknown field 'SameSite' in struct literal of type http.Cookie
pkg/cookie/cookie.go:81:13: unknown field 'SameSite' in struct literal of type http.Cookie
pkg/cookie/cookie.go:93:12: unknown field 'SameSite' in struct literal of type http.Cookie
```

I've tried downloading the releases manually as well as using `go get` to get the latest release.  Any idea what I could be doing wrong...?

**Comment by bnfinet** [comment]
what version of go are you using, what is your build environment?

**Comment by p-doyle** [comment]
Ubuntu 18.04.4
go 1.10.4

**Comment by bnfinet** [comment]
you'll need a more recent Go

on the path to fixing logging and other cleanup an upgrade of Go was necessary

see #240
