### ISSUE TITLE
Can not use google auth2.0 

### ISSUE THREAD

**Issue by ibotheperfect** [vouch/vouch-proxy#249]
Hi.
I installed vouch-proxy via docker and configured my server and vouch config properly. 
When I try to use it, after I login nginx returns below error 

`2020/04/15 14:22:12 [error] 9789#9789: *3 upstream prematurely closed connection while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: vouch.mydomain.com, request: "GET /auth?`

and vouch log show this 

`{"level":"error","ts":1586960598.77561,"msg":"Post https://oauth2.googleapis.com/token: dial tcp: lookup oauth2.googleapis.com on 8.8.4.4:53: read udp 172.17.0.2:46999->8.8.4.4:53: i/o timeout"}
{"level":"debug","ts":1586960598.7756293,"msg":"CaptureWriter.Write set w.StatusCode 400"}
{"level":"debug","ts":1586960598.7756362,"msg":"Request handled successfully: 400"}
{"level":"info","ts":1586960598.7756407,"msg":"|400| 20.001218278s /auth","statusCode":400,"request":12,"latency":20.001218278,"avgLatency":6.667136608,"ipPort":"172.17.0.1:52040","method":"GET","host":"vouch.mydomain.com","path":"/auth","referer":""}
`

I couldn't figure out why it is not work. Any help?

**Comment by bnfinet** [comment]
That looks like a dns error (Port 53).  Can the container which runs VP
resolve the URL?  Looks like it can't reach 8.8.4.4.

**Comment by ibotheperfect** [comment]
My host that container run on can connect to 8.8.4.4. How can I test if container connect?

**Comment by bnfinet** [comment]
That's a bit outside of the support we usually provide here.  Try running
another container, maybe just bash, and see if it can curl one of the URLs
(even for 404 error).  If not you'll need to manage your firewall or docker
dns config or something like that.

Or you can use the alpine based VP image and then docker exec into see if
you can resolve the domain.

**Comment by ibotheperfect** [comment]
I tried to ping with alpine base container and realized it really can not connect outside. I added below iptables rules and problem solved. thanks
`iptables -A POSTROUTING -t nat  -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE`

**Comment by bnfinet** [comment]
So glad it's working for you!

**Comment by vkopio** [comment]
I had this exact problem and adding the above iptables rule solved it for me. Even though this is not directly related to the project it would be beneficial to have a mention about this in the documentation as Docker is the main way of using the proxy.

**Comment by bnfinet** [comment]
@vkopio where in the documentation would you suggest this be mentioned?  In the `Docker` section?

Would you care to submit a PR to update the PR with a note that links to this issue?
