### ISSUE TITLE
KeyCloak + Vouch Proxy = "We are sorry... Invalid 

### ISSUE THREAD

**Issue by ansuz07** [vouch/vouch-proxy#250]
Struggling to get this set up properly.

Running both KeyCloak and Vouch Proxy in Docker, with everything configured.  When I log in to my protected site, I am correctly forwarded to the KeyCloak Auth page, where I can successfully login.

However, I am brought to a page that just says "We are sorry... Invalid Request"

Logs from both containers are less than helpful:

Vouch Proxy:  

{"level":"debug","ts":1587413840.815684,"msg":"redirecting to oauthURL https://auth.domain.com/auth/realms/realm/protocol/openid-connect/auth?client_id=Vouch&redirect_uri=https%3A%2F%2Fauth.domain.com%2Fauth%2Frealms%2Frealm%2Fprotocol%2Fopenid-connect%2Fauth&response_type=code&scope=openid+email+profile&state=dACsATpXeo6QzPWlXmr0EJ0FmNFlpTF"}
{"level":"debug","ts":1587413840.8157814,"msg":"CaptureWriter.Write set w.StatusCode 302"}
{"level":"debug","ts":1587413840.8158388,"msg":"Request handled successfully: 302"}
{"level":"info","ts":1587413840.815862,"msg":"|302| 1.538112ms /login","statusCode":302,"request":47,"latency":0.001538112,"avgLatency":0.000497638,"ipPort":"192.168.50.101:49020","method":"GET","host":"vouch.domain.com","path":"/login","referer":""}

KeyCloak:

20:17:20,900 WARN  [org.keycloak.events] (default task-75) type=LOGIN_ERROR, realmId=realm, clientId=null, userId=null, ipAddress=auth.domain.com, error=invalid_request

Can anyone help me figure out what is going wrong here?  Thanks!

**Comment by bnfinet** [comment]
please read the README for how to file an issue to receive support

**Comment by ansuz07** [comment]
Forgive my ignorance, but how do I run this command:

./do.sh bug_report yourdomain.com [yourotherdomain.com]

if Vouch is running in Docker?  Thanks

**Comment by bnfinet** [comment]
Folks have used the voucher/vouch-proxy:alpine-latest image to run do.sh.
If you aren't able to do that, please post your logs and configs in the
manner described.

**Comment by ansuz07** [comment]
Thanks.  As an FYI, the do.sh is throwing an error in the Alpine Image:

/do.sh: line 122: syntax error: unexpected "(" (expecting "}")

Here are the logs as requested:

Vouch Logs:  https://gist.github.com/ansuz07/bdf0cf86f476c7f504a8d1ed3654a514

Keycloak Logs:  https://gist.github.com/ansuz07/af9e90a900c7da51a482c1fade8ee636

Nginx Config:  https://gist.github.com/ansuz07/e65e567d79d6fd7f0b968ff99748a2cc

Vouch Config:  https://gist.github.com/ansuz07/e365d2db7211cd1d7e9ea138624095cc

**Comment by bnfinet** [comment]
"We are sorry... Invalid Request" must be on the KeyCloak side.

Your vouch config should have only two top level keys.. `vouch` and `oauth`.  However that's unrelated to your problem.

From your logs the round trip for OAuth/OIDC login is never completed with a request to the `callback_url`'s  `/auth` endpoint.

By "successful login" you're saying that KeyCloak provides some indication to you that it has logged you in and then forwards you back to vouch?

Unfortunately I don't use KeyCloak so I'm not in a position to provide support for KeyCloak.

**Comment by ansuz07** [comment]
Yes - when I open up the admin panel in KeyCloak, the user is successfully logged into my "Vouch" session.

The issue does seem to be with the round trip, but I can't find anything on the "invalid_request" error, and without a description I have no idea what is actually causing the issue...

**Comment by bnfinet** [comment]
Yes, but you're saying you click on "Login" and then are presented with "We are sorry".. before any other indication of successful login in the browser, is that correct?  What URL is in the browser at that time?

**Comment by ansuz07** [comment]
Here is the flow:

- access paperless.redacted.com in my browser
- Vouch successfully redirects me to the KeyCloak login screen, with the following URL:  https://auth.redacted.com/auth/realms/LannisterSSO/protocol/openid-connect/auth?client_id=Vouch&redirect_uri=https%3A%2F%2Fauth.redacted.com%2Fauth%2Frealms%2FLannisterSSO%2Fprotocol%2Fopenid-connect%2Fauth&response_type=code&scope=openid+email+profile&state=b9D1kcvqUdvCoNISGjywxgPI2O3SHyLg

- Log in as usual

- Remain on KeyCloak, where the "We are Sorry... Invalid Request page shows, with the following url:  https://auth.redacted.com/auth/realms/LannisterSSO/protocol/openid-connect/auth?state=b9D1kcvqUdvCoNISGjywxgPI2O3SHyLg&session_state=e5751ca5-5f5d-48eb-a16d-7c67f2667589&code=e5de9268-ff55-4e7f-9f25-c263814949de.e5751ca5-5f5d-48eb-a16d-7c67f2667589.953e4ac1-cbf7-46c9-b192-f14edc32deaa  

- In the KeyCloak admin panel, the use is shown as logged in to the Vouch session.

**Comment by bnfinet** [comment]
The KeyCloak community does seem to respond well to folks on the message boards.  I'd suggest posting about your problem there.
https://keycloak.discourse.group/

I'm going to close this for now but please do post back here if you have a problem once you get to the VP `/auth` step.

**Comment by ansuz07** [comment]
As an FYI, I figured out what was wrong - my callback_url was set to the KeyCloak URL, not the Vouch URL.  Once I set it to https://vouch.redatcted.com/auth it is redirecting properly.

**Comment by bnfinet** [comment]
I'm so glad you were able to get it to work properly.
