### ISSUE TITLE
Host name could not be resolved (Host not found) problem using Vouch in Kubernetes.

### ISSUE THREAD

**Issue by TroyPang** [vouch/vouch-proxy#252]
Hi,

I'm new to Vouch and using Vouch in Kubernetes along with nginx-ingress. I follow the instruction in README page and assign annotations in ingress:
```
nginx.ingress.kubernetes.io/auth-signin: "https://vouch.somedomin.test/login? 
      url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch- 
      Token=$auth_resp_jwt&error=$auth_resp_err"
nginx.ingress.kubernetes.io/auth-url: https://vouch.somedomin.test/validate
nginx.ingress.kubernetes.io/auth-response-headers: X-Vouch-User
nginx.ingress.kubernetes.io/auth-snippet: |
      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
```
The host name for this ingress is the entry of nginx (e.g. entry.ourdomin.test). For test purpose, host name and certificate is self-signed. The problem is when access the entry host name in broswer, nginx will return 500 error, and logs in nginx controller shows like:
`2020/04/28 03:28:20 [error] 188#188: *2097 vouch.somedomin.test could not be resolved (3: Host not found), subrequest: "/_external-auth-Lw"
2020/04/28 03:28:20 [error] 188#188: *2097 auth request unexpected status: 502 while sending to client`

I think probably the nginx controller search host following /etc/resolv.conf whcih actually is kube-dns, and it follow somename.<namespace>.svc.cluster.local for looking up resources inside kubernetes. I also tried to mount /etc/hosts file to nginx-controller pod to add <IP hostname>, but it still doesn't work.

Enviroment:
Platform: AKS
Orchestrator: Kubernetes 1.14.8
Operating system: Linux
Broswer: Chrome/81.0.4044.122
Nginx: nginx-ingress-controller:0.30.0
Vouch: Chart vouch-0.1.4, APP Ver:0.6.19 

Any idea on this?

**Comment by bnfinet** [comment]
@TroyPang This seems like a dns issue within your cluster and not related to Vouch Proxy.  If you feel that there's a VP issue I'd need to see your VP logs and config.

**Comment by TroyPang** [comment]
@bnfinet Thanks for reply. I think you are right and this is fixed by trying to assign IP address to a wildcard public domain name. Nothing abnormal shows in VP logs since traffic can not reach Vouch under DNS problem.
