### ISSUE TITLE
Avoid cookie in response header

### ISSUE THREAD

**Issue by b3j0f** [vouch/vouch-proxy#254]
Is there a way to avoid cookies in request response without configuring nginx ?

**Comment by bnfinet** [comment]
I think the short answer is "no" but I'm not sure I understand the question.  Could you expand on that?

Do you mean the response to the browser from `/auth`?  Do you mean the downstream request passed after `/validate`?  Could you please provide some context including describing the problem that your are trying to solve.

**Comment by bnfinet** [comment]
see #229 for how to remove the cookie in nginx post `/validate`

**Comment by b3j0f** [comment]
I think my short answer is "thanks" for the answer :-) 

Once I am authenticated, I want to retrieve the jwt token only through the response header "X-Vouch-Token"

I already use the config property header `jwt` in this way, and do not add configuration to cookie.

Once I am authenticated, I see both headers `Set-Cookie` and `X-Vouch-Token`

According to configuration, is it possible to avoid the header Set-Cookie at config/vouch level ? 

Or do I have to modify the code in forking the project ?

**Comment by bnfinet** [comment]
You should be able to manage the headers which are passed downtream from vouch to the app using Nginx.

But the cookie holds the JWT which then offer the token (I think you mean the IdP's token) downstream, so VP needs to see the cookie.

**Comment by bnfinet** [comment]
closing

do let me know if you have any further questions
