### ISSUE TITLE
Debug logging is enabled when logLevel is set to info

### ISSUE THREAD

**Issue by grglnd** [vouch/vouch-proxy#255]
Running vouch-proxy in Docker using the latest image built 2020-04-23T22:16:45.871740867Z. 

When setting the vouch.logLevel to **info**, the process logs at a debug level.  If vouch.logLevel is set to warn, the process correctly sets the log level to warn.  

I've tried overriding the config by passing the level on the cmd line, which results in the same behavior, for example: 

The following will log at a debug level:

docker run  -p 9090:9090 --name vouch-proxy -v /etc/vouch.yml:/config/config.yml voucher/vouch-proxy -loglevel info

while the following logs at a warn level:

docker run  -p 9090:9090 --name vouch-proxy -v /etc/vouch.yml:/config/config.yml voucher/vouch-proxy -loglevel warn

**Comment by bnfinet** [comment]
@grglnd thanks for the report!
