### ISSUE TITLE
404 instead of proper error page on error to /auth

### ISSUE THREAD

**Issue by airbornemint** [vouch/vouch-proxy#256]
URLs of the form `https://<vouchHost>/auth/#state=<anything>&error=<errorID>&error_description=<errorDescription>` generate a raw 404 error instead of a proper error page. 

I got into this situation via

 * Vouch configured with Okta
 * Okta configured to use LinkedIn as IdP
 * User accesses my app hosted with nginx subrequest auth
 * nginx subrequest goes to Okta
 * Okta redirects to LinkedIn
 * LinkedIn auth completes successfully, redirects to Okta
 * Okta authentication completes successfully, but user does not have privileges in Okta to access the app
 * Okta redirects to vouch with an error: `https://<vouchHost>/auth/#state=WM6D&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.`
 * Vouch returns a 404 to the browser instead of rendering a useful error page

but any error to `/auth` is sufficient to repro this, you don't have to go through any of the other steps.

**Comment by bnfinet** [comment]
@airbornemint thanks for the report

This is related (perhaps duplicate) of #53
