### ISSUE TITLE
"no jwt found in request" and multiple redirects hopto.org

### ISSUE THREAD

**Issue by lothi** [vouch/vouch-proxy#259]
I am having the same issue as it has been described before in issue #84:
["no jwt found in request" and multiple redirects #84](https://github.com/vouch/vouch-proxy/issues/84), however there is one major difference in my setup to issue #84. I am using ssl in my configuration, and therefor the resolution from issue #84 will not work for me. 

My virtual host configuration:
- XXXXXXXXXXX.hopto.org (app server)
- XXXXXXXXXXX-login.domain.org (vouch proxy)

As also described in issue 84, the redirect from my appserver -> vouch proxy -> dev-XXXXXX.okta.com works and the login at Okta also works. Then the redirect goes back to 
vouch proxy and subsequently there is another redirect to Okta, and then back to vouch proxy. 
This goes on until the browser stop with a message "Too many redirects". 

I also was able to verify this scenario by setting ```vouch: testing: true```.  The generated links alternate between "app server" and "Okta-dev authentication".  

In this gist you find the [Nginx configuration, the vouch-proxy configuration and the vouch log output](https://gist.github.com/lothi/95b61449542efa3196be33bf04f3aa83)

In the log file the problem shows at line #25 and #62:
```2020-05-01T14:16:15.663+0200	ERROR	no jwt found in request```

I first started with a more comprehensive Nginx and vouch configuration, but during troubleshooting the issue I striped the configuration gradually back to the bare minimum - but the issue still persists. 

I would appreciate any help in solving this issue. Thanks a lot.

**Comment by bnfinet** [comment]
Please read the readme on how to properly post an issue

**Comment by lothi** [comment]
@bnfinet , thanks for the quick response. I updated the original issue post according to the README. All relevant config and log files are now redacted and available on [gist.github](https://gist.github.com/lothi/95b61449542efa3196be33bf04f3aa83)

**Comment by bnfinet** [comment]
Thanks for that.

`vouch.domains` should be `hopto.org`.  If that doesn't work try `vouch.cookie.domain` as `hopto.org`

above you show
> My virtual host configuration:
>
>   XXXXXXXXXXX.hopto.org (app server)
>   XXXXXXXXXXX-login.domain.org (vouch proxy)

vouch will need to be within the `hopto.org` domain in order to set the cookie that holds the JWT

**Comment by lothi** [comment]
Sorry, my bad, that was a documentation bug in my original posting.  
Both app server and vouch are in the same domain, hopto.org. 
```
AppServer: XXXXXXXX.hopto.org = birdwatcher.hopto.org
Vouch: XXXXXXXX-login.hopto.org = birdwatcher-login.hopto.org
```
My suspicion is, that there is something wrong with the domains configuration, but everything is in the hopto.org domains so it should really work, but it doesn't.  Have I missed anything in the vouch configuration ?

**Comment by bnfinet** [comment]
yes, `vouch.domains` should be `hopto.org` and just `hopto.org` not the sub domains

**Comment by lothi** [comment]
Unfortunately this did not fix the problem. ```ERROR	no jwt found in request``` still persists. 

Steps I took to further analyse / eliminate the problem: 
- New Nginx configuration based on [Example Nginx with ssl](https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/single-file/nginx_with_vouch_ssl.conf). 
- Replaced  ```server_name protectedapp.yourdomain.com;``` with ```server_name protectedapp.hopto.org```; in Nginx config
- Replaced ```server_name vouch.yourdomain.com;``` with ```server_name vouch.hopto.org```; in Nginx config
- Replaced example certificates with own certificates 
- Updated callback_url in vouch config to ```callback_url: https://vouch.hopto.org/auth```
- Verified vouch setting: vouch: domains: hopto.org
- Add vouch setting: vouch: cookie: domain: hopto.org
- Updated ```Login redirect URIs https://vouch.hopto.org/auth``` in okta to match vouch configuration
- Updated ```Initiate login URI https://vouch.hopto.org/login``` in okta

After restarting Nginx and vouch the "no jwt found in request" still is logged. 
```
2020-05-02T08:08:50.245+0200.   ERROR   no jwt found in request
2020-05-02T08:08:50.245+0200    DEBUG   domain protectedapp.hopto.org matched array value at [0]=hopto.org```

But domain match was detected, at least something:
```
2020-05-02T08:08:50.351+0200    DEBUG   domain vouch.hopto.org matched array value at [0]=hopto.org
2020-05-02T08:08:50.351+0200    DEBUG   setting the cookie domain to hopto.org
2020-05-02T08:08:50.352+0200    DEBUG   session state set to CcN80m4ldvUqv0LZJxFnjVxgkBzLBXf4
```

The question still is, why is there no "jwt in request" ? 

Here again the [updated configurations and logs](https://gist.github.com/lothi/4ca3977a6b347e5ea3ce8e9e29a11117) on gist

**Comment by bnfinet** [comment]
VP appears to be working.

What are you seeing in your browser with developer tools?  Is the cookie getting set in the browser at /auth?  Is it getting returned on the next request?  Have you tried a different browser?

Is there any other proxy or an odd nginx config at play?

**Comment by lothi** [comment]
> VP appears to be working properly.
I'm very pleased about that 

Re browsers: Checked with Safari, Firefox and Chrome. 

They all behave exactly the same: 

- /auth request: only VouchSession cookie is set.
- /auth respones: VouchSession and VouchCookie (domain hopto.org) is set. 
- next response: Only VouchSession, no VouchCookie anymore.

Since VP is obviously working, and all browsers behave the same way, it all points to nginx. 
I'm going to check the nginx config again and will report. 



-

**Comment by lothi** [comment]
Next update: 

Created a new Nginx config file which is in essence identical to the provided vouch [example here.](https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/single-file/nginx_with_vouch_ssl.conf)

And here the [Nginx.conf gist](https://gist.github.com/lothi/0bf4d1cad27bc5ec10ed6ab22e4f8ad2)

There is no other proxy or no other Nginx configuration in place anymore. 

Unfortunately the behaviour is still the same. No "jwt found in request" and VouchCookie disappearing after the /auth response.

**Comment by bnfinet** [comment]
are you running this on a pi? I notice that your path to VP includes `/home/pi/go`

What version of nginx are you running?  What OS?

Have you tried setting your nginx buffers (proxy, header) to be larger?

**Comment by lothi** [comment]
yes, nginx and vp are running on a pi.
```"Raspbian GNU/Linux 9 (stretch)"```


```nginx version: nginx/1.10.3```

Changed the proxy_buffer values in the context below to:
```
       server_name vouch.hopto.org;

        location / {
           proxy_buffers 8 8k;
           proxy_buffer_size 8k;
           proxy_pass http://127.0.0.1:9090;
```
But this did not make any difference. 

Here the /auth request:
```
:method: GET
:scheme: https
:authority: vouch.hopto.org
:path: /auth?code=XXXXXXXXXXX&state=YYYYYYYYYYYYY
Pragma: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cookie: VouchSession=MTU4ODUzODA4MHxE....................dkxA==
Accept-Encoding: gzip, deflate, br
Host: vouch.hopto.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Accept-Language: en-au
Cache-Control: no-cache
Connection: keep-alive
```

and the /auth response:
```
:status: 200
Set-Cookie: VouchCookie=H4sIA.........................hD1QKAAA=; Path=/; Domain=hopto.org; Max-Age=14400; HttpOnly; Secure
Set-Cookie: VouchSession=MTU4ODUz............zSa07WMCv0=; Path=/; Expires=Tue, 02 Jun 2020 20:38:10 GMT; Max-Age=2592000; HttpOnly; Secure
Content-Type: text/html; charset=utf-8
Date: Sun, 03 May 2020 20:38:10 GMT
Server: nginx/1.10.3
```

And then the next link in testing mode is  ```https://protectedapp.hopto.org ```. 
Clicking on it redirects to ```https://vouch.hopto.org/login``` as it should. 
The request details are:
```
:method: GET
:scheme: https
:authority: vouch.hopto.org
:path: /login?url=https://protectedapp.hopto.org/&vouch-failcount=&X-Vouch-Token=&error=
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Pragma: no-cache
Cookie: VouchSession=MTU4ODUzODI5MHxEdi1C....................zSa07WMCv0=
Referer: https://vouch.hopto.org/auth?code=XXXXXXXXXXX&state=YYYYYYY
Cache-Control: no-cache
Host: vouch.hopto.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Accept-Language: en-au
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

and the response of the ```vouch.hopto.org/login``` is:
```
:status: 200
Set-Cookie: VouchSession=MTU4O.............HA==; Path=/; Expires=Tue, 02 Jun 2020 20:46:41 GMT; Max-Age=2592000; HttpOnly; Secure
Content-Type: text/html; charset=utf-8
Date: Sun, 03 May 2020 20:46:41 GMT
Server: nginx/1.10.3
```

I'm not sure if I tuned the proxy_buffers at the right context or if I should increase the buffer values even more or if I should try another nginx version.
One other thing I could try is to set it all up with docker and test this outside of the raspberry pi to see if this makes any difference.

**Comment by bnfinet** [comment]
> Clicking on it redirects to https://vouch.hopto.org/login as it should.

After you have been issued the `jwt` (in the cookie) you should be able to pass `/validate`

What are the headers being sent to the https://protectedapp.hopto.org request?

Have you tried adjusting header or cookie related nginx vars such as...
http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

**Comment by lothi** [comment]
Well, it seems not to pass validation, because I always straight go to [https://vouch.hopto.org/login](https://vouch.hopto.org/login) no matter what. 

My plan to go forward: 

1. Check if it is possible to log the Cookie names in Nginx' access.log, if yes, it should give me some clues. 

2. Move Nginx away from the pi and if problem still persists, look into tuning the large_client_header_buffers. 

Once I have some more information I will certainly report it back.

**Comment by lothi** [comment]
OK, here are some updates: 

1. Migrated Nginx from pi to run on local machine in Docker, but left VP on pi. Still no jwt header. 
:-(

2. Then migrated VP also to local machine / Docker , et voila : I've got an jwt header and finally I've got the entire authentication working. 

Apart from the more powerful machine with more resources, what were the differences between PI and Docker ? 
- compared the Nginx configuration between pi and local machine, and apart from domain names they are identical. 
- also compared the VP config, and the only difference between PI and local machine are again the domain names. 
- docker Nginx version is 17.10 and on raspberry pi 10.x 

Although these are some good news that I have Nginx - VP now principally working, I still need to get Nginx and VP working on the raspberry pi. 

My next steps to figure out the root cause of the problem will be: 
- use Nginx on raspberry pi and VP on local machine
- upgrading Nginx version on PI
- looking again into large_client_header_buffers

and if this then still doesn't work, I may have to invest in a Raspberry PI 4B

**Comment by bnfinet** [comment]
What were the various permutations/setups wrt to domain names?

Benjamin Foote
bnf Systems LLC
Linux and Cloud Consulting
http://bnf.net
ben@bnf.net
@bnf

Currently working on:
Vouch Proxy
an SSO solution for nginx using the auth_request module
https://github.com/vouch/vouch-proxy

**Comment by lothi** [comment]
OK, @bnfinet  your questions is quite a valid one. 
I could not believe that it was working in a docker setup on my local machine and not on the pi. 
So I started to migrate back to the pi, step by step with verification after each step. 

1. vouch-proxy on pi, niginx on local docker - result OK
2.  vouch-proxy on pi, niginx on pi - result OK !!!!!!!!

It was working !!!! 

I do have a jwt and logging is working. I do not have an explanation, but I am going to add my configuration to gist as a reference. 

[nginx-vouch-config-gist](https://gist.github.com/lothi/0375386be7cb94eda7d4fb1440f9435f)

No need to buy a raspberry pi 4B (although I might still do that anyway)

@bnfinet thanks for listening and sorry for taking your time. Ticket can be closed.

**Comment by bnfinet** [comment]
I'm glad that it's working for you now.

**Comment by MCOfficer** [comment]
For the benefit of any future developer: in my case, it was privacy badger that had blocked okta's cookies. This can probably happen with other privacy addons, and other vouch backends. To be sure, try in a clean browser or in incognito mode.
