### ISSUE TITLE
Broken nginx/single-file examples

### ISSUE THREAD

**Issue by bgehman** [vouch/vouch-proxy#260]
**Describe the problem**
The [nginx/single-file](https://github.com/vouch/vouch-proxy/tree/master/examples/nginx/single-file) examples are not valid nginx config files.  Seems all the single-file nginx examples suffer the same problem: `server` blocks are supposed to be inside the `http` block.

Let me know if you want a PR, thanks!

**Expected behavior**
Valid (parseable) nginx.conf examples.

**Additional context**
```
2020/05/12 16:04:17 [emerg] 1#1: "server" directive is not allowed here in /etc/nginx/nginx.conf:28
nginx: [emerg] "server" directive is not allowed here in /etc/nginx/nginx.conf:28
```

**Comment by bnfinet** [comment]
sure that'd be welcome
