### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by pavankoppolu** [vouch/vouch-proxy#262]
I have been trying to get this up and running for the last couple of days, but have been unsuccessful. Can someone point out what I am doing wrong?

I am running oktasso in docker and encounter a 502 error when I am redirected to the Okta login. I am trying to authenticate using nginx. It looks like the none of the upstream variables are being set properly, but I am quite new to this area.

`Recreating portal_nginx_nginx_1 ... done
Attaching to portal_nginx_nginx_1
nginx_1  | 2020/05/13 17:01:55 [info] 17#17: *1 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:8443
nginx_1  | 2020/05/13 17:01:55 [error] 17#17: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /validate/ HTTP/1.1", subrequest: "/validate", upstream: "http://127.0.0.1:9090/validate", host: "localhost:8443"
nginx_1  | 2020/05/13 17:01:55 [error] 17#17: *2 auth request unexpected status: 502 while sending to client, client: 172.18.0.1, server: localhost, request: "GET /validate/ HTTP/1.1", host: "localhost:8443"
nginx_1  | 2020/05/13 17:01:55 [info] 15#15: *4 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:8443
nginx_1  | 2020/05/13 17:01:55 [error] 14#14: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", subrequest: "/validate", upstream: "http://127.0.0.1:9090/validate", host: "localhost:8443", referrer: "https://localhost:8443/validate/"
nginx_1  | 2020/05/13 17:01:55 [error] 14#14: *5 auth request unexpected status: 502 while sending to client, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8443", referrer: "https://localhost:8443/validate/"
nginx_1  | 2020/05/13 17:02:37 [info] 19#19: *7 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:8443
nginx_1  | 2020/05/13 17:02:37 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", subrequest: "/validate", upstream: "http://127.0.0.1:9090/validate", host: "localhost:8443"
nginx_1  | 2020/05/13 17:02:37 [error] 14#14: *8 auth request unexpected status: 502 while sending to client, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8443"
nginx_1  | 2020/05/13 17:02:37 [info] 14#14: *10 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:8443
nginx_1  | 2020/05/13 17:02:37 [error] 18#18: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", subrequest: "/validate", upstream: "http://127.0.0.1:9090/validate", host: "localhost:8443", referrer: "https://localhost:8443/"
nginx_1  | 2020/05/13 17:02:37 [error] 18#18: *11 auth request unexpected status: 502 while sending to client, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8443", referrer: "https://localhost:8443/"`

Here is Nginx.conf

`server {
        listen 8080;
        listen 8443 ssl;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # where the root here
        root /usr/share/nginx/html;
        # what file to server as index
        index index.html index.htm;

        server_name localhost8443;

        set $ui_host ${UI_HOST};
        
        large_client_header_buffers 4 32k;

        # Any request to this server will first be sent to this URL
        auth_request /validate;

        location = /validate {
            # forward the /validate request to Vouch Proxy
            proxy_pass http://127.0.0.1:9090/validate;
            # be sure to pass the original host header
            proxy_set_header Host $http_host;

            # Vouch Proxy only acts on the request headers
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";

            # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
            auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

            # optionally add X-Vouch-IdP-Claims-* custom claims you are tracking
            #    auth_request_set $auth_resp_x_vouch_idp_claims_groups $upstream_http_x_vouch_idp_claims_groups;
            #    auth_request_set $auth_resp_x_vouch_idp_claims_given_name $upstream_http_x_vouch_idp_claims_given_name;
            # optinally add X-Vouch-IdP-AccessToken or X-Vouch-IdP-IdToken
            #    auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;
            #    auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;

            # these return values are used by the @error401 call
            auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
            auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
            auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;

            # Vouch Proxy can run behind the same Nginx reverse proxy
            # may need to comply to "upstream" server naming
            # proxy_pass http://vouch.yourdomain.com/validate;
            # proxy_set_header Host $http_host;
        }

        error_page 401 = @error401;

        # If the user is not logged in, redirect them to Vouch's login URL
        location @error401 {
        return 302 https://github.com;
        }

        location /ping {
            access_log off;
            return 200 'pong';
            add_header Content-Type text/plain;
            allow all;
        }

        location /health-check {
            access_log off;
            return 200 'ok';
            add_header Content-Type text/plain;
            allow all;
        }

        location /nginx_status {
          stub_status on;
          access_log  off;
          allow all;
        }

        location / {
            access_log off;
            proxy_set_header X-Forwarded-Host $host;	            
            proxy_set_header X-Real-IP $remote_addr;	            
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	
            proxy_set_header X-Forwarded-Proto $scheme;	
            proxy_set_header X-Forwarded-Port $server_port;	
            proxy_pass_request_headers on;	
            proxy_pass $ui_host;
        }
    }
    server {
        listen 8443 ssl;
        server_name localhost9090;

        # Proxy to your Vouch instance
        location / {
            proxy_set_header Remote-User $auth_resp_x_vouch_user;
            proxy_pass        http://127.0.0.1:9090/validate;
            # be sure to pass the original host header
            proxy_set_header Host $http_host;
        }
    }`

It would be great if someone will help on this.

**Comment by bnfinet** [comment]
please read the README wrt how to ask for help and post an issue

**Comment by bgehman** [comment]
```
SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking
```

I think that means that the client (web browser), does not trust the SSL cert that you have defined in nginx:

```
ssl_certificate /etc/nginx/ssl/nginx.crt;
ssl_certificate_key /etc/nginx/ssl/nginx.key;
```

You can probably get more details on the client/browser side about what it doesn't like about the server's cert.

**Comment by bnfinet** [comment]
@pavankoppolu if you are no longer working this issue could you please close it?
