### ISSUE TITLE
Unauthorized users can access protected resources without authentication

### ISSUE THREAD

**Issue by toxuin** [vouch/vouch-proxy#264]
**Problem description**

After single successful log-in through an IdP, seems like the resulting JWT is stored in internal cache and is "found" for all the subsequent requests to the same protected resource - even with no VouchCookie - resource just opens.

Either I've done something terribly wrong or a defect in JWT cache mechanism was introduced between versions [0.11.3 and 0.12.0](https://github.com/vouch/vouch-proxy/compare/7d4e4101022211f438c35c42c66a36d9a562ced2...546ec4d828fd4340b6d02a89ac0ef2bda907fe03): problem is totally gone if I specify `image.tag: 0.11.3` and is 100% reproducible with `0.12.0`.

With `logLevel: debug` I can see following line in vouch log:
```json
{"level":"debug","ts":111,"msg":"/validate found response headers for jwt in cache"}
```
that is having no cookies whatsoever – either in another browser or a new Incognito tab/window.

**Expected behavior**
Protected resource would redirect to IdP's log-in page.

**Environment**
- Kubernetes: v1.17.4
- Nginx Ingress Controller: `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0`
- Vouch Version: `voucher/vouch-proxy:0.12.0` - bug, `voucher/vouch-proxy:0.11.3` - no bug
- Identity Provider: Keycloak (`jboss/keycloak:10.0.0`) on the same domain name (`vouch.example.com` & `keycloak.example.com`)
- OS: Mac OS 10.15.4
- Browser: Safari 13.1, Chromium 75.0.37e70.100, most likely irrelevant

**Additional context**
Vouch is installed from Helm chart. I don't think it matters though.
Ingress for protected service was annotated with exact copy-paste from example in every way but domain name.
All the certificates are valid and are issued through Let's Encrypt. I hope it's obvious that I don't actually use `example.com` as a domain for the cluster.

[vouch config](https://hasteb.in/fojabewo.yaml)
[vouch log - 0.12.0](https://hasteb.in/joyonoqo.log) - with bug
[vouch log - 0.11.3](https://hasteb.in/ilegarup.log) - no bug

**Comment by bnfinet** [comment]
Please upgrade to v0.12.3 and check again.  The was an additional check
added to cacheing.  I suspect this resolves this issue.

**Comment by toxuin** [comment]
Yes, this indeed has resolved the issue. Thank you!

**Comment by bnfinet** [comment]
So glad to hear it's working properly.  Sorry for the regression.
