### ISSUE TITLE
Separate Cookies for subdomains

### ISSUE THREAD

**Issue by kennyparsons** [vouch/vouch-proxy#268]
**Describe the problem**
I'm currently using google as my oauth provider. It works as expected, but I was curious if it's possible to have separate cookies for subdomains of the same domain. For example, I protect `app1.example.com` and `importantapp.example.com` with [this config](https://gist.github.com/kennyparsons/f9267a610da16bf84a11c354c9a42423). When I successfully authenticate for `app1.example.com`, `importantapp.example.com` is by default also authenticated. For improved security, I would like to be able to set a different cookie for subdomains of the same root domain. From my understanding of [samesite rules](https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute), wouldn't `app1.example.com` and `importantapp.example.com` share the same cookie? 

**Expected behavior**
I'd like to specify separate cookies for specific subdomains. This would allow an added element of security (ie not allow one cookie to be used for all subdomains of a given root domain). 

Ideally, the `config.yml` would allow specification of a multiple cookie names to apply to a group of subdomains and allow the specification of another cookie/sub-domain list. 
```
vouch: 
  cookie: 
    name: name1cookie
    subs: *.example.com, example.com
```
and 
```
vouch: 
  cookie: 
    name: name2cookie
    subs: importantapp.example.com, app2.example.com
``` 

**Desktop:**
 - OS: windows
 - Browser: chrome
 - Version win10

**Additional context**
Currently running via docker (`latest` tag)

EDIT:
This originally was just a question, but after I posted, it looks like a feature request. Mods, this is not meant for a feature request. I apologize for the confusion. Is it possible to have separate cookies (and therefore separate authentication) for specific list of subdomains that are on the same root domain.

**Comment by bnfinet** [comment]
VP relies on sharing the cookie across the protected domain (`example.com`).

I'd suggest running separate VP instances restricted to your domain and changing the `vouch.cookie.name` and the `vouch.jwt.secret` to be distinct to each.  VP uses about 10M of memory, pretty slim by modern standards.

**Comment by kennyparsons** [comment]
Any good ideas on how to implement multiple instances? I’m fine with multiples. Easy enough. Would I just need multiple sever blocks for voucher? Like login1.example.com and login2.example.com?
