### ISSUE TITLE
Other data from IdP call to be made available in headers

### ISSUE THREAD

**Issue by sciphilo** [vouch/vouch-proxy#27]
Feature request:

In the same vein as X-Lasso-user holds the email/user info and this can be passed back to nginx and upstream, it would be nice if any other information made available via the identity provider such as first name etc could also be made available to nginx.

**Comment by bnfinet** [comment]
similar to #80

**Comment by bnfinet** [comment]
@sciphilo this was implemented in #97, feel free to reopen the issue if you feel otherwise
