### ISSUE TITLE
400 Bad Request - vouch with keycloak

### ISSUE THREAD

**Issue by thalesvalias** [vouch/vouch-proxy#272]
I apologize if this is too trivial and I might be missing obvious stuff here, but I've been struggling to get this stack working for a while (I started running in circles).

So I have Nginx with Vouch, Keycloak as my IdP, and a protected Java application. Nginx, Vouch and my application are deployed on a Linux remote server (Linode), while Keycloak is on an AWS ec2 instance.

Everything seems to work fine until I get authenticated by Keycloak, then sent back to vouch auth with my state, when I get a bad request msg. 

Also I could notice on the logs the error:
`no jwt found in request`

Here are my configs and logs as README suggests:
[Nginx (default file)](https://hasteb.in/nadedoso.nginx)
[Vouch config.yml](https://hasteb.in/iyakudah.yaml)
[Keycloak auth](https://hasteb.in/padocelo.cs)
[/validate](https://hasteb.in/iletigim.cs)
[/login](https://hasteb.in/uriratuv.cs)

As you can see I have set a reverse proxy on 9091 to be able to work with Vouch through https.

Let me know if there is any additional information I can provide to make it clearer. Thanks!

**Comment by bnfinet** [comment]
@thalesvalias 
- Be sure to include `proxy_set_header Host $http_host;`
- from the README.. 

    the `Host:` header in the http request, the `oauth.callback_url` and the configured `vouch.domains` must all align so that the cookie that carries the JWT can be placed properly into the browser and then returned on each request

Since you only have one `oauth.callback_url`, that's the only domain that the cookie can be configured into.

- try to keep the config really tight such as https://hasteb.in/wacohusi.yaml

**Comment by thalesvalias** [comment]
Thanks for your reply.

So I added Host header to the other requests and simplified my config.yml:

[Nginx](https://hasteb.in/itiwobun.nginx)
[Full logs](https://hasteb.in/luhanifi.swift)

The same issue so far. This is the last response I get on /auth step (not sure if I can post here the complete redacted request and response, let me know if I can)
[Last response](https://hasteb.in/mogaquva.yaml)

**Comment by bnfinet** [comment]
`dial tcp 3.9.19.30:8180: connect: connection refused`

VP can't contact the IdP.  Is this a firewall issue?

**Comment by bnfinet** [comment]
`ERROR	no destination URL requested` why is that?

**Comment by thalesvalias** [comment]
@bnfinet hey, yeah, you were right. The firewall was blocking my IdP and it was leading to the other errors. After making sure I have turned my firewall off, I could see the real issues and they were on the IdP side (The user was not set correctly there, missing some key information like email; then the email domain must be in the vouch domain). Finally I could get it working all the way (before open this ticket I'd faced other issues).

Many thanks and sorry for not notice it.

**Comment by bnfinet** [comment]
So glad it's working for you.  Do let me know if you have further issues.
