### ISSUE TITLE
Feature request: Do not log secrets from environment variables at all log levels

### ISSUE THREAD

**Issue by jal25jal25** [vouch/vouch-proxy#274]
**Summary**

When specifying configuration via environment variables, the values of `VOUCH_SESSION_KEY` and `VOUCH_JWT_SECRET` are output to the log, regardless of the log level specified in the environment. This is too big a security risk for us, and we would like to be able to have it only happen at debug level, if at all.

**Suggested explanation**

I believe this behaviour is due to this line in `configureFromEnv()`:

https://github.com/vouch/vouch-proxy/blob/ab753455d1b1113b6dfa8d1517746408ca0e9164/pkg/cfg/cfg.go#L197

While the above log statement is at level `Debug`, at this point in execution we haven't yet set the log level from its initial `Debug` level.

`cfg.configureFromEnv()` is being called from `cfg.Configure()`:
https://github.com/vouch/vouch-proxy/blob/ab753455d1b1113b6dfa8d1517746408ca0e9164/pkg/cfg/cfg.go#L161

But it is only later in `cfg.Configure()` that we execute `Logging.configure()`:
https://github.com/vouch/vouch-proxy/blob/ab753455d1b1113b6dfa8d1517746408ca0e9164/pkg/cfg/cfg.go#L169

The result is log output like the following:
https://hasteb.in/exapozak.json
(secrets obfuscated with `XXXXX`)

**Suggested solution**

I can see a couple of potential solutions, for which I am happy to attempt a PR, but would like a steer on whether one of them is most appropriate, or if I should do something else.

1) Within `cfg.Configure()`, move the call to `Logging.configure()` to be above the call to `cfg.configureFromEnv()`
2) Within `cfg.configureFromEnv()`, before the log statement, take a copy of `Cfg`, obfuscate the values of:
`vouch` -> `session` -> `VouchSession` -> `key`
and
`vouch` -> `jwt` -> `secret` 
then log the modified copy.

Your help is appreciated.

**Comment by bnfinet** [comment]
@jal25jal25 nice catch.

Option 2 would be better.  IIRC moving `Logging.configure()` will mess up the ability to set `logLevel` from the command line.

PR would be most welcome.  Thanks for that.

Env var support dropped a few weeks ago.  I did not account for this case.

Is env var support working out fine otherwise?  Are you using the binary or docker?

**Comment by jal25jal25** [comment]
Thanks @bnfinet - Understood. I'll look at creating a PR for option 2. 

We are using AWS ECS, so getting all configuration from the environment is ideal. We believe everything is working so far with the env vars in our sandbox environment, but we know we won't be able to move it any further with these secrets hitting the logs.

Thanks for your help.

**Comment by bnfinet** [comment]
fixed in `v0.15.6`

thanks for the PR @jal25jal25 

In addition to that I added..
- a check to see if the logLevel was changed, if so call setLogLevel($VOUCH_LOGLEVEL) 
- moved some of the debug logging to be later
- removed extraneous logging of `.defaults.yml` contents

**Comment by jal25jal25** [comment]
Many thanks for the quick turnaround @bnfinet !
