### ISSUE TITLE
Use Vouch on a specific locations in nginx

### ISSUE THREAD

**Issue by kennyparsons** [vouch/vouch-proxy#276]
**Describe the problem**
I've successfully been able to add vouch proxy to my subdomains to protect them with google oauth. The guides all walk through how to add this protection at `/` location level. I am trying to protect a different path. For example, I currently protect blog.example.com with vouch. All works as expected, But, I dont want to make the whole blog protected (it's a public blog), I only want to protect the `/wp-admin/*` location. Here's what I've tried: https://hastebin.com/yirayecali.nginx
After logging in to google oauth, I get a 404 nginx error.

**Expected behavior**
After logging in, I should be redirected back to blog.example.dev/wp-admin

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 81.0.4044.138

**Comment by bnfinet** [comment]
Welcome back @kennyparsons 

Try passing the `Host` header as the README shows for `/validate` (in your `/vouch-validate`)

If that does not work, please post full logs and configs as per the README.

**Comment by bnfinet** [comment]
@kennyparsons any progress?  If you are no longer working this issue could you please close it.

**Comment by kennyparsons** [comment]
Sorry. I will work on this. Got a bit tied up.
