### ISSUE TITLE
No Redirect_URI

### ISSUE THREAD

**Issue by Sharpz7** [vouch/vouch-proxy#277]
**Describe the problem**
I am using google OAuth and trying to get Vouch to authorize my code-server all in a docker-compose file. With Testing on, I get this 302 redirect.

```
https://accounts.google.com/o/oauth2/auth?client_id=XXXXX.apps.googleusercontent.com&response_type=code&scope=email&state=XXXX
```

It does not contain a redirect_uri, and that causes google to say "400: No redirect_uri"

**Configs and Logs**
Docker-compose logs from when I click the 302 redirects. 
https://hasteb.in/zijamuvi.coffeescript

With testing turned off this is my docker log:
https://hasteb.in/ceviqide.coffeescript

Docker-compose config
https://hasteb.in/uwenoked.yaml

site.conf (I use Certbot, so all listen '80s are changed to 443, and all requests to 80 are redirected to 443)
https://hasteb.in/eqatarik.nginx

**Desktop**
 - OS: Linux
 - Browser Vivaldi
 - Version Latest

**Additional context**
I moved from a version before env was supported. I have updated the site.conf file.. but this could be an issue somehow.

This has been me trying to fix it for 8hrs... I have very much given up ;D

**Comment by prupp** [comment]
Same Issue here. Did setup vouch-proxy and nginx according to the docs.
As soon as vouch-proxy redirects to Google OAuth, Google responds with "400: No redirect_uri".

I have set the redirect URI in docker-compose with OAUTH_CALLBACK_URL as well as Authorized Redirect URI in Google Console.
As @Sharpz7 mentioned, vouch-proxy won't pass redirect URI as parameter to Google, which probably causes this issue.

**Comment by Sharpz7** [comment]
I actually have managed to add the redirect Uri manually, Google then lets
you sign in, but then the auth says it is invalid

**Comment by bnfinet** [comment]
Hmm, that's not good.

Does it work if you use OAUTH_CALLBACKS=http://....??

**Comment by bnfinet** [comment]
And try 'v0.15.5' with OAUTH_CALLBACK_URL

**Comment by prupp** [comment]
@bnfinet Thanks for your answer, using OAUTH_CALLBACK_URLS instead of OAUTH_CALLBACK_URL works. Same goes for 'v0.15.5', google auth just works with OAUTH_CALLBACK_URLS. OAUTH_CALLBACK_URL leads to Error 400: invalid_request.

**Comment by bnfinet** [comment]
Okay, think I know what's going on.  Definitely a bug and regression.

Sorry to have you banging your head against the wall for eight hours
@Sharpz7

I'll get a fix in but I won't be able to do it today.

**Comment by Sharpz7** [comment]
Will your fix break the your current suggestion to get it working?

**Comment by bnfinet** [comment]
No you should be safe to deploy with one url for OAUTH_CALLBACK_URLS and
then receive the fix.

**Comment by Sharpz7** [comment]
Okay. Im using 0.15.5 with OAUTH_CALLBACK_URLS and it is working fine.

**Comment by Sharpz7** [comment]
I am using OAUTH_CALLBACK_URLS on latest, but now the cookie on mcaq.me has content "delete"? I can get to google and authenticate, but then stopped at https://vs.mcaq.me/login?to=%2F#

**Comment by bnfinet** [comment]
Please post logs and config.

**Comment by Sharpz7** [comment]
Okay, so on the latest, OAUTH_CALLBACK_URLS works fine.

A few things to note:

On your "single file" with SSL nginx example, this is here
```
        location ~ /(auth|login|logout|static) {
          proxy_pass http://vouch;
          proxy_set_header Host $http_host;
        }

```

This actually creates problems when the app *uses* one of these paths, and it is not needed

Also, in the debug options, config options like "whitelisted email" and "domain" are shown, but the callback is not, this put me completely off the trail xD.

Thanks for all your help and I am glad I can now continue to use Vouch

**Comment by bnfinet** [comment]
I've added the OAuth config to the debug logging, thanks for the suggestion.

> This actually creates problems when the app uses one of these paths, and it is not needed

Could you explain "and it is not needed".

If you are configuring one fqdn (app1.yourdomain.com) to serve both the protected app and vouch then there is no way to get around the overlap issue.  You may be able to disambiguate the `/login` etc paths with a fancy `proxy_pass` setup but that would be some nginx-fu.  If you do go down that path, please let me know so that we can add it to the docs.

I'm glad that it is working for you.

**Comment by Sharpz7** [comment]
By "not needed" I mean that other "configs" don't have that part of the
config and work fine
