### ISSUE TITLE
Vouch returns 200 for invalid JWT's as well

### ISSUE THREAD

**Issue by prateek2408** [vouch/vouch-proxy#278]
Support

**Describe the problem**
If you try to give an invalid JWT token for the first time vouch-proxy complains and gives an error which is legitimate.  Returns 401 which good.

However if you retry the same request, it passes and says that the JWT was found in the cache so returns 200 (OK) which should not be the case.

Logs- 
Request 1- https://hasteb.in/vecaselu.sql -- Proper Respose
Request 2- https://hasteb.in/gixifefu.coffeescript --- Returns 200 for the same request -- should return 401

**Expected behavior**
Ideally for both the request it should  return 401 which is unauthorized.

**Additional context**
After digging into the code it seems that every request is being cached into the memory. So ideally there should be 2 Solutions to this- 
1.  Do not cache 401 requests. 
2. If there is a need to cache then also store the status of the responses and return the exact same response even when it comes from cache system.

**Comment by bnfinet** [comment]
@prateek2408 thanks for the detailed report, please do test `v0.15.8` and confirm the fix

If you should encounter a bug of this nature again please do reach out on non-public channels.
