### ISSUE TITLE
Alternate domain not respected

### ISSUE THREAD

**Issue by sciphilo** [vouch/vouch-proxy#28]
In my Lasso config file I have:

```
allowAllUsers: true
```

and I've commented out the 'domains' part.  I hope this would allow users whose usernames are their emails and their emails are from different domains to login.  however it seems that lasso forbids this.  I can login fine if my email domain matches the domain of the server that lasso is protecting, but not if it's a alternate email domain (eg. gmail.com).

Have I configured something wrongly ?  Or is this expected behaviour ?

Thanks,
Phil

**Comment by sciphilo** [comment]
Actually this is nothing to do with the domains assignment in the config file,  it's to do with a timeout when lasso calls Okta and I've installed my own cname in the okta preview.  Even though I have installed correct SSL certs it seems to timeout.


Here's a snippet of lasso log

```
ERRO[0040] Post https://myokta.cname.alias/oauth2/default/v1/token: dial tcp: lookup myokta.cname.alias on 127.0.1.1:53: read udp 127.0.0.1:46474->127.0.1.1:53: i/o timeout 
```

Where myokta.cname.alias is a cname entry for an okta preview account.

I'm guessing this is due to slowness responding here by okta or some such, though logging in directly to 
myokta.cname.alias  works fine

**Comment by bnfinet** [comment]
because it has port `53` in there that might b a failed dns lookup for `myokta.cname.alias`

**Comment by sciphilo** [comment]
When I run an nslookup from the lasso server on myokta.cname.alias it resolves ok.

**Comment by sciphilo** [comment]
I can however sort my issue if I have the 

user_info_url
and
token_url

settings pointed at the Okta preview url and the 'auth_url' pointed at my nicer named cname

Then it works as I'd want with the login page having the myokta.cname.alias url and the other urls being used behind the scenes.

**Comment by bnfinet** [comment]
I've looked at the Oauth client [1] where the resolution is occurring.  There's a Context object [2] there however the full context config is not implemented in the Oauth code at this point [3].  That said, I don't see anything which would affect the dns resolution.

I strongly suspect that your browser is resolving the `auth_url` correctly while the lasso service is not seeing the CNAME resolution for `user_info_url` and `token_url`

Are you running lasso in a docker container?

[1] https://godoc.org/golang.org/x/oauth2#Config.Client  
[2] https://golang.org/pkg/context/#TODO

**Comment by sciphilo** [comment]
Yeah, that would make sense.
I'm not running in Docker.

**Comment by bnfinet** [comment]
were you able to discover anything more @sciphilo ?

**Comment by sciphilo** [comment]
No, I got it working as above with auth_url pointed to the non-okta-preview cname, and left the user_info_url and token_url settings pointed to the okta-preview url.  It works just fine then

**Comment by bnfinet** [comment]
@sciphilo I'm going to close this issue, please do open it back up if you feel there is something actionable
