### ISSUE TITLE
Vouch Proxy log file

### ISSUE THREAD

**Issue by kundanupadhyaya** [vouch/vouch-proxy#280]
Where does the log file of vouch proxy get generated in linux server ?
The question is very trivial one but i could not locate the generated log file.

**Comment by bnfinet** [comment]
The log is not written to a file.  The log is written to stdout.  The logging library is [uber's zap](https://github.com/uber-go/zap).

This is the standard practice for a [twelve-factor app](https://12factor.net/logs).
