### ISSUE TITLE
improve "Too many redirects" error after multiple unsuccessful login cycles

### ISSUE THREAD

**Issue by richjyoung** [vouch/vouch-proxy#282]
I have a setup using the following domains:

login.domain: Vouch proxy
iam.domain: Keycloak IAM
home.domain: Private static content

Under normal circumstances all of the above works fine, sessions and token refresh works great.

If a user visits home.domain, is redirected through login.domain to iam.domain, and then cancels the login process by navigating away, this causes no issues the first time or second time.

The third attempt to then log in results in the bounce through login.domain failing with the message: "/login too many redirects for requested URL for...", and they are then never redirected on to iam.domain.

The browser is then stuck in this error state until login.domain/logout has been manually visited which is not ideal user experience. Any advice on how to avoid this situation? Cancelling logon should not lead to a stuck state, even if this is a corner case.

**Comment by bnfinet** [comment]
@richjyoung right now `errTooManyRedirects` is hard coded at 3...

https://github.com/vouch/vouch-proxy/blob/master/handlers/login.go#L81-L85

That should probably be increased to something more like 5 or 8.

What do you think?

The solution you can offer your user right now is "wait five minutes and try again".  The session variable will timeout at five minutes and the errTooManyRedirects fail count will be cleared.

**Comment by richjyoung** [comment]
If the user manually visits the /logout endpoint this seems to clear the error state which is a reasonable workaround at present.

This seems to me like the error message is different to the error that is actually occurring if I have understood the code correctly? Is it possible to change the message to reflect its too many attempts on that URL without success, and then make the max count a value that can be modified in the configuration? In theory the number should be the maximum realistic number of logins expected in a 5 minute window.

**Comment by bnfinet** [comment]
What would be a better error message?

**Comment by richjyoung** [comment]
Have I understood correctly that the error scenario I have seen is unrelated to redirects?

**Comment by bnfinet** [comment]
I'm asking honestly, what should the error message be?  What is a better
error message in your mind?

**Comment by richjyoung** [comment]
I presume something related to attempts exceeded within a timeframe? I didn't write the code so I am not sure what the error is here, but it seems unrelated to redirects?

**Comment by bnfinet** [comment]
The common case which results in "too many redirects" is..
* visit http://protected.example.com
* redirected to http://vouch.example.com/login?url=http://protected.example.com
* redirected to IdP (OIDC login provider)
* user logs in (perhaps not successfully)
* redirected to the callback_url... http://vouch.example.com/auth
* but something is wrong, then end user is not issued a token by Vouch Proxy (often this is a misconfiguration of the VP cookie)
* the end user is forwarded to http://protected.example.com (in some cases, the error is caught and the user sees an error page from VP)
* and the redirection cycle starts again

"too many redirects" is indicative of the `fail_count` for http://protected.example.com being too high (3 or more).  Maybe "Too many unsuccessful authorization attempts for http://protected.example.com" would be better.  WDYT?

> If a user visits home.domain, is redirected through login.domain to iam.domain, and then cancels the login process by navigating away, this causes no issues the first time or second time.

home.domain is being redirect to vouch.domain/login and then to the IdP.  It may not be obvious but this error is triggered by redirection.

Here's the improvements which I can think of which would make this better...
* increase threshold to six or eight (no need for config element IMHO)
* better error message
* explain the session length "wait five minutes"
* provide link to `/logout` on the error screen
* ???

Would you care to submit a PR with those?  They should be minor edits.

**Comment by bnfinet** [comment]
@richjyoung the error is now triggered after six failures

I'd still love to get your opinion on what a better error would be, but if you have no opinion on that would you please close the issue.

**Comment by richjyoung** [comment]
> Maybe "Too many unsuccessful authorization attempts for http://protected.example.com" would be better. WDYT?

This would be great in my opinion.

**Comment by bnfinet** [comment]
thanks @richjyoung I've made that adjustment in `v0.16.3`

**Comment by richjyoung** [comment]
Great, thank you. When I have a chance, would you be open to a pull request that exposes this setting in the configuration file? I think 6 is a good number for now, but as you mentioned it's dependent on the session variable timeout. Is the session variable timeout exposed in the configuration as well or is that fixed?

**Comment by bnfinet** [comment]
@richjyoung The session timeout is fixed at five minutes.

I think the defaults are fine as is, I'd prefer to not add another knob to VP if necessary.  Lets see if anyone else chimes in on this issue over the coming months before adding an additional configuration option.
