### ISSUE TITLE
Problems using user_auth.lua

### ISSUE THREAD

**Issue by trasba** [vouch/vouch-proxy#284]
**Describe the problem**
I tried to use the examples from the lua folder namely vouch-proxy/examples/OpenResty/lua/**user_auth.lua**

**Expected behavior**
Well it should work :grin:

**Additional context**
Honestly I am not a pro using OpenResty so I am sure the failure is in my area :wink: I am just trying to understand what I've done wrong or where my brain took the wrong path

Anyhow I am using vouch as a docker container and everything is up and running. My webserver service is also hosted as a docker container it is this one [linuxserver/letsencrypt](https://hub.docker.com/r/linuxserver/letsencrypt)
Everything is working so far. Now I wanted to be able to create user based authentication.
But I couldn't get the example to work. I got a http 500 error messages until I deleted the `local authorized_users = Set {...` block I looked into the lua description but couldn't find a Set function for an array/table. So I went on and wrote a auser_auth.lua file of my own. And that is working like a charm.
```
-- ==============================
--     User Authentication
--      via X-Vouch-User
-- ==============================
-- Validate a user in nginx, instead of vouch
local authorized_users = {
        "<your-email>@gmail.com",
        "<another-email>@gmail.com"
}

local function has_value (tab, val)
        for index, value in ipairs(tab) do
                if value == val then
                        return true
                end
        end
        return false
end

if not has_value(authorized_users,ngx.var.auth_resp_x_vouch_user) then
        -- If not, throw a forbidden
        ngx.exit(ngx.HTTP_FORBIDDEN)
end
```
I ended up thinking maybe someone else ran into the same problem. Hence I worte this post.
Specifically maybe @artagel can you shed some light here for me as you are the author?

Let me know if I can help e.g. with input for the readme or anything else
cheers

**Comment by artagel** [comment]
I'm not clear why the Set isn't working for you.  I'd turn on syntax logging to see what the error might be.
Sets are documented here: https://www.lua.org/pil/11.5.html

**Comment by bnfinet** [comment]
@trasba were you able to resolve your problem?  If you're no longer working on this could you please close the issue?

**Comment by felixgeyer** [comment]
Sure! I just created a PR: #435
