### ISSUE TITLE
How to install/run without Docker

### ISSUE THREAD

**Issue by schristm** [vouch/vouch-proxy#286]
Hey guys, could you provide instructions for how to install outside of the ~/go/src/github.com/vouch/vouch-proxy directory? I saw that the systemd file provided references /opt, but I'm not sure how much of ~/go/src/github.com/vouch/vouch-proxy should be copied to /opt. 

Is this how to do it?

```bash
go get github.com/vouch/vouch-proxy
cd ~/go/src/github.com/vouch/vouch-proxy
go build
mv ~/go/src/github.com/vouch/vouch-proxy /opt/vouch-proxy
```

**Comment by bnfinet** [comment]
Ironically  the `Dockerfile` might be the best guide for what needs to be put in place...

You'll need to move the `.defaults.yml` file and the directories `templates` and `static` into the directory which contains the `vouch-proxy` binary.

You may also need to set `$VOUCH_ROOT`

Regarding build instructions please see the README.

The longer term solution is to build all these assets into the static binary, probably using [go.rice](https://github.com/GeertJohan/go.rice)
