### ISSUE TITLE
Stray param in login request (rd) when using nginx-ingress

### ISSUE THREAD

**Issue by zheker** [vouch/vouch-proxy#289]
Configuration setup: `nginx-ingress` (0.30.0) + `vouch-proxy` (latest) + `google auth`.
Ingress annotations are defined according to documentation. 

When I call protected location vouch-proxy returns 400 error:
`Not a valid login URL: requested destination URL appears to be invalid login request included unrecognized parameters`

vouch-proxy logs:
`"Stray param in login request (rd)"`
`Not a valid login URL: requested destination URL appears to be invalid login request included unrecognized parameters"`

nginx-ingress adds `&rd=$pass_access_scheme://$http_host$escaped_request_uri` to the auth-signing URL if it is not defined, so `auth-signing` changes from
`https://vouch.yourdomain.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err`
to
`https://vouch.yourdomain.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err&rd=$pass_access_scheme://$http_host$escaped_request_uri`

but vouch-proxy knows nothing about `rd` param. 

In result: vouch-proxy with ingress doesn't work.

Is there any way to make vouch-proxy ignore or accept this `rd` parameter?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by bnfinet** [comment]
@zheker #281 / #283 added more robust and tighter parsing and tracking of parameters passed to the `/login` endpoint. We did not account for the `rd` parameter used by `nginx-ingress`.  That's definitely a bug as `nginx-ingress` is documented as a supported platform.

@airbornemint FYI ^^

**Comment by bnfinet** [comment]
@zheker would you be in a position to test that branch ^^ against your Nginx Ingress env?

**Comment by zheker** [comment]
@bnfinet it works! Thank you!

**Comment by airbornemint** [comment]
Out of curiosity, do we know why this is even a thing? `rd` is not passed to auth provider nor is is used by vouch, so… why is anyone sending it along to begin with?

**Comment by bnfinet** [comment]
@zheker thanks for the report and for checking that the fix works.  Do let us know if you run into any other issues with Nginx Ingress + Vouch Proxy.

@airbornemint looks like `rd` is tacked on by Nginx Ingress in Kubernetes to handle redirection issues...

https://github.com/kubernetes/ingress-nginx/issues/1314
https://github.com/kubernetes/ingress-nginx/commit/51248f87f3892721cb76b00da98b8e6c2bff5da3

**Comment by airbornemint** [comment]
Ugh, if layers above vouch are expecting that the can put random params in a vouch URL and have vouch just drop them on the floor, then maybe my initial approach here was too conservative and we should generate a warning (rather than error) if unexpected params appear in `login` URL query.

**Comment by bnfinet** [comment]
@airbornemint yeah that seems prudent.  Though I conceptually see how allowing stray params could create vectors for attack, however it feels like the admin should be allowed to daisy chain services which might rely on additional params.

Would you be in a position to cut a PR to change these failures (`responses.error401`) to `log.warn`?

**Comment by airbornemint** [comment]
Can do.
