### ISSUE TITLE
Azure AD support

### ISSUE THREAD

**Issue by tomsmyers** [vouch/vouch-proxy#290]
i'm working on an integration with azure AD. after a successful login, vouch unpacks the body of the OIDC `/userinfo` response into a `structs.User` object, which takes values from fields `username`, `email` etc. 
https://github.com/vouch/vouch-proxy/blob/531fc6f980a0ca5eacf689f21153c51ff327e7fc/pkg/providers/openid/openid.go#L55

when constructing the jwt to store, the claims are constructed using this `structs.User.Username`.
https://github.com/vouch/vouch-proxy/blob/1f68466ac952725a58526fc5808580828902f15e/pkg/jwtmanager/jwtmanager.go#L81

later when checking the token in `/validate`, vouch checks if the username is populated and returns 401 if is not. 
https://github.com/vouch/vouch-proxy/blob/4b6d226ca3a36bd53d984182e4f1c2d5ffa29aab/handlers/validate.go#L48

this logic makes the assumption that `username` is included in the `/userinfo` response, which in my case it is not. 😞 

is there a way to take information like this from the ID token instead of the `/userinfo` response? in azure AD, i can't configure which fields are included in the `/userinfo` response (e.g. to add the user's email address), but i can configure which fields are included in the tokens.

vouch config for posterity:

```
VOUCH_JWT_MAXAGE=20
VOUCH_ALLOWALLUSERS=true
VOUCH_LOGLEVEL=debug
VOUCH_COOKIE_SECURE=false
VOUCH_COOKIE_DOMAIN=localhost

OAUTH_PROVIDER=oidc
OAUTH_CLIENT_ID=...
OAUTH_CLIENT_SECRET=...
OAUTH_BASEURL=https://login.microsoftonline.com/...
OAUTH_AUTH_URL=https://login.microsoftonline.com/.../oauth2/v2.0/authorize
OAUTH_TOKEN_URL=https://login.microsoftonline.com/.../oauth2/v2.0/token
OAUTH_USER_INFO_URL=https://graph.microsoft.com/oidc/userinfo
OAUTH_SCOPES=openid,profile,email
OAUTH_CALLBACK_URLS=http://localhost:9090/auth
```

**Comment by bnfinet** [comment]
@tomsmyers have you tried using the `adfs` provider? IIRC it uses the same interfaces as Azure AD.  A quick view of the `adfs.go` code shows it falling back to using the `UPN` if an email isn't present.

https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example_adfs

**Comment by tomsmyers** [comment]
unfortunately using the `adfs` provider does not work with azure AD; you get the error `The 'resource' request parameter is not supported.` when redirecting to the login page.

**Comment by bnfinet** [comment]
@simongottschlag do you have any insight into Azure AD setups? ^^

@tomsmyers if you'd care to add a new provider at `providers/azure/azure.go` I'd be happy to accept a PR.  I'm not a user of Azure so I'm not in a position to test/support Azure AD at this time.

**Comment by simongottschlag** [comment]
@bnfinet Azure AD has their own quirks compared to ADFS. The resource query parameter is required with ADFS to populate the claims correctly while causing issues with Azure AD.

There are also differences with using Azure AD with a single tenant and using the “multi-tenant” endpoints and may require additional configuration to get both working.

**Comment by tomsmyers** [comment]
thanks for the comments, i opened a PR to add support for my azure ad config by simply mapping `upn` claim to username and email (based on the docs, `upn` is an email address), unless the fields already exist in the token. 

https://github.com/vouch/vouch-proxy/pull/292

**Comment by bnfinet** [comment]
@tomsmyers thanks much for the addition to VP!

**Comment by sintaxx** [comment]
Has anyone any documentation on how to setup Vouch with Azure AD sitting behind an nginx reverse proxy ? This would be amazing.

**Comment by jastlw** [comment]
@simongottschlag Can I also configure azure_token through environmental variables for OAuth config?

I want to use it with docker compose:
`vouch-proxy:
    container_name: ex-vouch
    image: voucher/vouch-proxy:alpine
    restart: unless-stopped
#    ports:
#      - 9090:9090
    volumes:
      - nginx-config-data/vouch:/config
    enviroment:
      - VOUCH_DOMAINS=vouch.dockertest1.azurewebsites.net
      - VOUCH_ALLOWALLUSERS=true
      - VOUCH_COOKIE_DOMAIN=dockertest1.azurewebsites.net
      - VOUCH_SESSION_KEY=********
      - OAUTH_PROVIDER=azure
      - OAUTH_CLIENT_ID=123456789
      - OAUTH_CLIENT_SECRET=********
      - OAUTH_AUTH_URL=https://login.microsoftonline.com/.../oauth2/v2.0/authorize
      - OAUTH_TOKEN_URL=https://login.microsoftonline.com/.../oauth2/v2.0/token
      - OAUTH_SCOPES=openid,profile,email
      - OAUTH_CALLBACK_URL=https://dockertest1.azurewebsites.net/auth
      - OAUTH_AZURE_TOKEN=id_token`
With reference to [commit 568577c64c8ea7de7f904bd8720588ccc51ce206](https://github.com/vouch/vouch-proxy/commit/568577c64c8ea7de7f904bd8720588ccc51ce206) 
I think I am not sure yet, if I really need to set the "OAUTH_AZURE_TOKEN".

Thank you in advance.

**Comment by bnfinet** [comment]
@jastlw it should but that may have been overlooked when we implemented config via environmental variables.

Could you please test that, and open a new issue if it does not work?
