### ISSUE TITLE
configuring Vouch Proxy to use an outgoing proxy for access to the internet and IdP

### ISSUE THREAD

**Issue by stagging18** [vouch/vouch-proxy#291]
Hi Team,
I am getting the below error after successful authentication.

{"level":"error","ts"1594280010.3651514,"msg":"/auth Error while retreiving user info after successful login at the OAuth provider: Post \"https://dev-813551.okta.com...\": dial tcp: lookup dev-813551.okta.com on 10.65.0.33:67: no such host"}

dev-813551.okta.com is not reachable from my vouch-proxy server. if i have to access this then i have to use an outgoing proxy.

Please let me know how to set outgoing proxy in vouch server so that it can make request to my okta dev account.

Any help will be appreciated.

Regards,
Rajesh

**Comment by bnfinet** [comment]
@stagging18 this sounds like a firewall problem.  That error indicates a dns lookup failure.  You should check your dns settings and and firewall settings and confirm that you can resolve your okta domain from the same environment that VP is running in.

**Comment by stagging18** [comment]
Hi Benjamin,

I am using apache mod_oidc also in the same environment and from apache i
am able to access the url by using the proxy settings. Similar things i am
looking around for VP also. Means is there any way i can set the proxy in
VP and the request will  go through that proxy.

Regards,
Rajesh

**Comment by bnfinet** [comment]
@stagging18 are you saying you're using SOCKS proxy or another outgoing proxy for all tcp including DNS?

**Comment by bnfinet** [comment]
@stagging18 I think this should work...

`export HTTP_PROXY="http://proxyIp:proxyPort"`

https://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client

**Comment by stagging18** [comment]
Thanks Benjamin,

The given solution works for me. We can close this issue.

Regards,
Rajesh

**Comment by bnfinet** [comment]
@stagging18 so glad to hear that!
