### ISSUE TITLE
renderError is not picked up in /validate, so default nginx error page is displayed

### ISSUE THREAD

**Issue by Choo57** [vouch/vouch-proxy#293]
**Describe the problem**
We added the following code block to handlers/validate.go, just above the "if !claims.SiteInClaims(r.Host)" check:
```
if !cfg.Cfg.AllowAllUsers {
		log.Debug("\validate now inside this block: if !cfg.Cfg.AllowAllUsers")	
		if !claims.SiteInGroups(r.Host) {
			log.Debug("Found claims in config, finding specific keys...")
			send403or200PublicAccess(w, r, fmt.Errorf("http header 'Host: %s' not authorized for configured `vouch.domains` (is Host being sent properly?)", r.Host))
			return
		}
}

```
Here is the "send403or200PublicAccess" method:
```
func send403or200PublicAccess(w http.ResponseWriter, r *http.Request, e error) {
	log.Debug("send403or200PublicAccess function called")
	if cfg.Cfg.PublicAccess {
		log.Debugf("error: %s, but public access is '%v', returning OK200", e, cfg.Cfg.PublicAccess)
		w.Header().Add(cfg.Cfg.Headers.User, "")
		responses.OK200(w, r)
		return
	}

	responses.Error403(w, r, e)
}
```

**Expected behavior**
Whenever this code is executed (i.e. the Okta group user is assigned to is not found in the URL they are trying to access), we were expecting to see the responses.Error403 page that uses the index.tmpl (or the error.tmpl) file rendered in the browser, however we are ending up getting the default nginx error pages. I can see in vouch.proxy logs that the debug statements above are all getting executed, so the code does get executed, but the resulting error page is nginx's default error page.

When responses.Error403 is called from within /auth or /login, this works as expected. Can you advise what is different in the /validate route or is this something we can overwrite?

**Comment by bnfinet** [comment]
@Choo57 This is related to how the Ngixn `auth_request` module works.
https://nginx.org/en/docs/http/ngx_http_auth_request_module.html

for `responses.Error403` you'll need to accommodate the return with `error_page 403 = @error403;` similar to the README's `401` setup with an associated `@error401` block.  

However you won't be able to render the VP response without some additional Nginx setup.

> We added the following code block to handlers/validate.go, just above the "if !claims.SiteInClaims(r.Host)" check:

I'm curious, what are you trying to accomplish? What would you like VP to do that it doesn't do now?

If Validate fails with `403` what should happen next?  Should the user be forwarded to `/login`?

**Comment by Choo57** [comment]
Hi @bnfinet many thanks for the very fast response.

What would work very well for us would be to render the VP error page in case of a 403 Forbidden error that is captured in the /validate endpoint (i.e. be able to use "responses.Error403(w, r, e)" call inside handlers/validate.go). This would save us from configuring a separate `error_page 403 = @error403` in nginx. 

In the bigger picture, we have different subdomains for different customers (e.g. https://customer1.site.com, https://customer2.site.com, etc), and we want to use a single Okta application and only allow users who have an Okta group that matches the subdomain have access to that site (e.g. Okta users who are assigned a "customer1" Okta group will be able to access https://customer1.site.com, but not be able to access https://customer2.site.com).

We opted to add this check into the /validate route so users who can authenticate against Okta will not be able to access another customer's site after they obtain a valid cookie (e.g. they first login to customer1's site where they are permissioned for, get a valid cookie, and then access customer2's site, so to prevent this flow, we thought the group check should be done in the /validate route).

Here is what we added to jwtmanager/jwtmanager.go to accomplish this check:

```
// Check for Site matching group in the PAcess Token
func (claims *VouchClaims) SiteInGroups(site string) bool {
	log.Debugf("jwtmanager: SiteInGroups site: %s", site)
	token, err := jwt.Parse(claims.PAccessToken, func(token *jwt.Token) (interface{}, error) {
	    return []byte(cfg.Cfg.JWT.Secret), nil
	})
	log.Debugf("jwt.Parsed PAccessToken %v", token)
	log.Debugf("jwt.Parse error %s", err)
	paccess, ok := token.Claims.(jwt.MapClaims)
	log.Debugf("Group Claims: %v", paccess["groups"])
	log.Debugf("Ok:  %s", ok)
	for _, gr := range paccess["groups"].([]interface {}) {
	    if strings.Contains(site, gr.(string)) {
	        log.Debugf("site %s is found for group %s", site, gr)
	        return true
	    }
	}
	log.Debugf("site %s not found in groups %v", site, paccess["groups"])
	return false
}
```

and as mentioned in the first post, we call SiteInGroups inside validate.go.

**Comment by bnfinet** [comment]
@Choo57 that's interesting functionality which would be a nice addition to VP.  

Unfortunately architecturally that's not going to work to add it to `/validate`.  The `/validate` endpoint is evaluated once and then the response headers are cached for the jwt (see `/main.go`).  If that `/jwt` is offered once against a valid endpoint and then against an invalid endpoint (under your criteria) then the cached headers and 200OK response from the first request will be returned for the next 20 minutes.

Furthermore i encourage you to read the `auth_request_module` docs and my comment above again.  `auth_request` is a very particular kind of proxied request.  The response from VP to Nginx (401/403) is not offered to the end user by default.

**Comment by Choo57** [comment]
many thanks @bnfinet for the hints. Here is what we ended up making:

in the nginx conf file, right under README's error401 block, added the following error403 as you mentioned and redirected to the /auth endpoint with a state=forbidden parameter

```
    error_page 403 = @error403;
    location @error403 {
       set $target_uri $request_uri;
       if ( $request_uri ~ /dashboard/.* ) {
         set $target_uri /dashboard/;
       }
       return 302 https://vouch.oursite.com/auth?state=forbidden;
    }
```

to capture the forbidden state, added the following conditional check in auth.go just above the line where query state is validated against the stored state:

```
       // Pass state=forbidden to return 403 forbidden error of vouch
	if queryState == "forbidden" {
		log.Debug("/auth state=forbidden received ")
		responses.Error403(w, r, fmt.Errorf("/auth forbidden state received in query: %s", queryState))
		return
	}
```

All the best.
