### ISSUE TITLE
Slow load times after successful auth

### ISSUE THREAD

**Issue by jaken551** [vouch/vouch-proxy#294]
**Describe the problem**
When putting services behind the vouch proxy, everything is working as expected. Without a cookie, I get redirected to the OpenID provider. Login is successful and I am redirected to the service. 

While the vouch proxy annotations set on my service's ingress, load times are incredibly slow (45-120sec). There are occasional `upstream timed out` logs on the nginx-ingress as well that I am not sure are related.

See:

`*42103 upstream server temporarily disabled while connecting to upstream, client: 192.168.1.3, server: mongo-express.k8s.mydomain, request: "GET /public/img/mongo-express-logo.png HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.1.102.20:443/validate", host: "mongo-express.k8s.mydomain", referrer: "https://mongo-express.k8s.mydomain/db/config/"
[ingress-nginx-controller-68679c6884-gv6nb] 2020/07/15 12:39:55 [error] 37#37: *42103 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.3, server: mongo-express.k8s.mydomain, request: "GET /public/img/mongo-express-logo.png HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.1.102.20:443/validate", host: "mongo-express.k8s.mydomain", referrer: "https://mongo-express.k8s.mydomain/db/config/"
[ingress-nginx-controller-68679c6884-gv6nb] 2020/07/15 12:39:55 [warn] 37#37: *42103 upstream server temporarily disabled while connecting to upstream, client: 192.168.1.3, server: mongo-express.k8s.mydomain, request: "GET /public/database-ea9f483ec5a79aabee9d.min.js HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.1.103.175:443/validate", host: "mongo-express.k8s.mydomain", referrer: "https://mongo-express.k8s.mydomain/db/config/"
[ingress-nginx-controller-68679c6884-gv6nb] 2020/07/15 12:39:55 [error] 37#37: *42103 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.3, server: mongo-express.k8s.mydomain, request: "GET /public/database-ea9f483ec5a79aabee9d.min.js HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.1.103.175:443/validate", host: "mongo-express.k8s.mydomain", referrer: "https://mongo-express.k8s.mydomain/db/config/"`

Without the annotations, the service is loads instantly (a few ms). I have tried this with a few services now and loads time behind vouch are always bad.

**Expected behavior**
Vouch redirects are fast.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4 
 - Browser chrome
 - Version 83.0.4103.97

**Comment by bnfinet** [comment]
Please post  your logs and config in the manner described in the README.

**Comment by bnfinet** [comment]
@jaken551 are you still working this issue?  If not would you please close it.
