### ISSUE TITLE
token contains an invalid number of segments

### ISSUE THREAD

**Issue by nishthas** [vouch/vouch-proxy#295]
logs: https://hastebin.com/uqewodetop.js
nginx.conf: https://hastebin.com/uzegikepay.pl
vouch.conf: https://hastebin.com/ugevuyonuj.cpp

We have a requirement where we want multiple auth_request directives and hence used this approach. The auth_request is directed to vouch if the first server fails. 

All was working when it was straight forward like https://developer.okta.com/blog/2018/08/28/nginx-auth-request

Looks like some header missing issues but I am not able to solve this one. Any help will be very much appreciated.

**Comment by bnfinet** [comment]
@nishthas those hastebin.com links are empty.  :(

hastebin.com was down for a while, I'm not even certain if it's working properly.  https://hasteb.in/ seems to work fine, or a gist is fine too or another paste service of you're choosing.

**Comment by nishthas** [comment]
@bnfinet here [gist](https://gist.github.com/nishthas/72d1f75acfb034f3b5af634788c8e767)

**Comment by nishthas** [comment]
Hi @bnfinet, Team

Did you get a chance to look at the issue?

**Comment by nishthas** [comment]
got it working. the issue was having the error 401 page inside the upstream server and not the actual app server. Once taken to the correct location, it worked fine :)

**Comment by bnfinet** [comment]
@nishthas I'm so glad to hear it.  Sorry I wasn't in a position to offer support during these past days as I was away.
