### ISSUE TITLE
native TLS / SSL / https support (instead of relying on Nginx)

### ISSUE THREAD

**Issue by rickdonato** [vouch/vouch-proxy#297]
Is there a way to enable SSL on the Vouch Proxy. i.e Rather then just performing SSL up to NGINX and then sending it on as HTTP to Vouch?

Thanks,

**Comment by bnfinet** [comment]
@rickdonato there is no direct TLS/SSL/https support in VP at this time, however it shouldn't be too hard to add to VP with some minor modifications to `main.go` and `cfg.go`

This looks like a nice setup to mimic....
https://github.com/denji/golang-tls#perfect-ssl-labs-score-with-go

I'd suggest new config params `vouch.tls.cert` and `vouch.tls.key`

@rickdonato do let me know if this something you'd be interested in working on

**Comment by rickdonato** [comment]
Thanks. Unfortunately, as it stands I've not developed in Go.

**Comment by bnfinet** [comment]
@dafaizer thanks so much for the contribution!

Could you please add 
 * test coverage
 * a check in `cfg.basicTest` that if `vouch.tls.cert` or `vouch.tls.key` is set, then so is the other one
 * modification of startup log messages related to indicate that TLS is enabled and that VP is available at https://0.0.0.0:9090

I'll add a few quick notes to the PR for a couple things as well

FYI - I'm not quite in a position to look closely at outstanding PRs and merge, hopefully just a few more days here

**Comment by bnfinet** [comment]
@danfaizer ^^

**Comment by bnfinet** [comment]
@danfaizer excellent stuff.  Thanks again for the contribution.
