### ISSUE TITLE
return username and not useremail

### ISSUE THREAD

**Issue by nishthas** [vouch/vouch-proxy#299]
I want to return username to my django app behind nginx(by setting up REMOTE_USER variable)

I tried using `$upstream_http_x_vouch_idp_claims_preferred_username` but it looks to be setting the header
`2020-07-28T11:58:39.891Z	DEBUG	Adding header for claim preferred_username - X-Vouch-IdP-Claims-Preferred-Username: xyz.abc@domain.com`
i.e again the email and not the username
Is it possible to return the username?

**Comment by bnfinet** [comment]
@nishthas could you either post your config in the manner described in the README or at least describe your `idp`, operating environment and setup.  Which `claim` contains the `username` from your `IdP`?  Have you looked at the custom claims documentation in [config.yml_example](https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L122-L137)?

**Comment by nishthas** [comment]
@bnfinet apologies for not sharing the configs. 
Here- [gist](https://gist.github.com/nishthas/092f93d01a61662f31d4b630359fb320)

I have looked at custom claim and it looks to be setting the header, just not to username.

**Comment by nishthas** [comment]
It was a missing claim. Thanks for the help!

**Comment by bnfinet** [comment]
@nishthas so glad to hear it.  For future reference, what was the missing claim that corresponded to `username`?

**Comment by nishthas** [comment]
@bnfinet It was `samAccountName - X-Vouch-IdP-Claims-Samaccountname` for us
