### ISSUE TITLE
Auth Request unexpected status: 302   while using proxy_intercept_errors  on;  in Nginx config file

### ISSUE THREAD

**Issue by stagging18** [vouch/vouch-proxy#300]
In Nginx while i am Enabling the proxy_intercept_errors /login request is failed due to the below errors.
*926 auth request unexpected status : 302 while sending to client, client: client address, server: server address, request: "GET /portal/ HTTP/1.1" host:"host name"

While disabling the proxy_intercept_errors it is working fine.

**Comment by bnfinet** [comment]
Please read the README regarding submitting an issue.

**Comment by bnfinet** [comment]
@stagging18 lets work one issue at a time til you're up and running

closing in favor of #301
