### ISSUE TITLE
400 bad request: too many unsuccessful authorization attempts

### ISSUE THREAD

**Issue by stagging18** [vouch/vouch-proxy#301]
Some times i am getting 400 bad request error in my browser due to the below logs.

{"level":"debug","ts":1596090718.2467093,"msg":"saving session with failcount 12"}
{"level":"error","ts":1596090718.2467723,"msg":"/login Too many unsuccessful authorization attempts for the requested URL scheme://host/uri"}

Please let me know on which case i can see these errors and how prevent this in vouch.

**Comment by bnfinet** [comment]
Please read the README regarding posting an issue.
