### ISSUE TITLE
PKCE support

### ISSUE THREAD

**Issue by zenojll** [vouch/vouch-proxy#303]
Waiting for PKCE support (code challenge) to work with [IdentityServer4](https://identityserver4.readthedocs.io/en/latest/)

**Comment by bnfinet** [comment]
@zenojll thanks, is this something you'd be interested in working?  PRs welcome!

**Comment by bnfinet** [comment]
https://www.oauth.com/oauth2-servers/pkce/

https://pkg.go.dev/golang.org/x/oauth2?tab=doc#Config.Exchange

**Comment by zenojll** [comment]
Hey! Thanks for your prompt answer!
I wish I could help but, unfortunately, I am not into programming.
Hope someone will find this issue and help.

**Comment by Husseinfo** [comment]
#306

**Comment by bnfinet** [comment]
Thanks @Husseinfo for the PR!  Sorry for the delay in reviewing.  

This has been merged in `v0.18.0`

`oauth.code_challenge_method: S256` is enabled by default for the providers `google`, `github`, `azure`, and `indieauth`.

I'm tempted to enable it for `adfs` but they have only enabled PKCE in 2019.  I'd suspect there might be folks running VP against ADFS which doesn't have PKCE.
