### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by phlummox** [vouch/vouch-proxy#304]
A [Changelog](https://keepachangelog.com/en/1.0.0/) would be nice. So that people using Vouch proxy can tell why, for instance, v0.17.3 was released and what changed in it, rather than just seeing "Merge branch 'pr/martindb/298'" under that release.

**Describe the problem**

Difficult to work out what has changed between versions.

**Expected behavior**

It would be nice if it were possible to easily work out what has changed between versions.

**Comment by bnfinet** [comment]
@phlummox thanks for the suggestion.  Is this something you'd like to support?  I think it would be a wonderful addition to VP.

**Comment by phlummox** [comment]
I am not familiar with what has happened to VP over previous versions, unfortunately, as I have only just started using it - but I can certainly provide a template for a standard changelog.

**Comment by tmatilai** [comment]
To be fair, maintaining the changelog is quite difficult unless you are also maintaining the project and know what is going on.

But I would also find it valuable. Maybe at least an automated one with PR titles and links, if adding the bullets manually feels too much?

**Comment by bnfinet** [comment]
@phlummox @tmatilai the change you desire has come to pass :)
