### ISSUE TITLE
enable X-Vouch-IdP-AccessToken and X-Vouch-User on vouch which is sitting behind NGINX

### ISSUE THREAD

**Issue by vagharsh** [vouch/vouch-proxy#316]
i have a setup on AWS which has this flow
user request -> app ( nginx built-in ) -> forward the request to domain.com/vouch1/validate 

i have enabled the following lines in the Nginx conf of the application. in the /validate location
```
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
      auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;
      auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;
```

and the below in the / location
```
      proxy_set_header X-Vouch-User $auth_resp_x_vouch_user;
      proxy_set_header X-Vouch-IdP-AccessToken $auth_resp_x_vouch_idp_accesstoken;
      proxy_set_header X-Vouch-IdP-IdToken $auth_resp_x_vouch_idp_idtoken;
```

domain.com/vouch1/ : consists of the following 
ALB : to perform ssl termination ( passes everything as is to nginx )
NGINX in k8s : to proxy_pass the vouch1 to it's respective vouch pod
VOUCH in k8s : receives the request and validates it.
Note : vouch is configured with OKTA

vouch is validating and everything is working well.
but i am not able to return the following headers to the application they are getting dropped somewhere. 
- $auth_resp_x_vouch_idp_accesstoken
- $auth_resp_x_vouch_idp_idtoken
- $auth_resp_x_vouch_user

i check the vouch logs and i saw that the `email` field is present there 

what shall i do to pass the needed fields to the application ?

**Comment by bnfinet** [comment]
@vagharsh have you enabled those features in your config?

For further support please post your config and logs in the manner described in the README

**Comment by vagharsh** [comment]
Sorry for taking this long. I am trying execute that command inside the container but i can't get into the container to start with.. can you please assist me on how can i `exec` into the vouch container first ?

**Comment by vagharsh** [comment]
the issue has been resolved .. 
so my application ( frontend ) is hosted on the same nginx container .. which means i needed `add_header` and not `proxy_pass` once i replaced those i now get the headers. . 
my application nginx blocks is like this 

```
  location / {
    auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
    auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;
    auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;

    add_header X-Vouch-User $auth_resp_x_vouch_user always;
    add_header X-Vouch-IdP-AccessToken $auth_resp_x_vouch_idp_accesstoken always;
    add_header X-Vouch-IdP-IdToken $auth_resp_x_vouch_idp_idtoken always;

    try_files $uri $uri/ /index.html =404;
  }
```
