### ISSUE TITLE
302 loop when Vouch is accessed through nginx using upstream

### ISSUE THREAD

**Issue by alexkleinfig** [vouch/vouch-proxy#322]
Hello !

I am struggling about something: I want my vouch proxy server to be on his own, behing nginx and accessed only throught https.

I configured my nginx like this:
protected page:  https://hasteb.in/oheyojaz.nginx
vouch: https://hasteb.in/emusiwac.nginx

I now have a 302 loop based on the fact that my cookie domain is vouch.example.com https://hasteb.in/pexajuro.pl

If i adress vouch proxy directly on the /validate it's working smoothly (cookie domain on example.com):
protected page: https://hasteb.in/poqafoso.nginx
vouch page: https://hasteb.in/lekudipu.http

Here is my vouch configuration file: https://hasteb.in/ayejasoc.yaml

I am pretty sure i am missing something obvious but i can't figure it. Do you have any idea what is it ?
Thanks a lot.
Alex

**Comment by bnfinet** [comment]
@alexkleinfig here are some thoughts..

You're using bitbucket, is that right?  I haven't heard of another VP setup with BitBucket yet.  Is it working well otherwise?  It appears to have a working `userInfo` response and otherwise OIDC compliant.

Off the top I see you'll need a `callback_urls` entry for each domain.  What happens when you just limit it to the domain that the user is in (`exple.fr`) or to `example.com`?

see: https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L24-L25

I'm puzzled by this message.. why isn't a domain being offered?
`"msg":"domain  not found in any domains [dev.exple.fr exple.dev exple.fr example.com]"}`

from here on out...
- please post logs with 'testing: true' as per the README
- please send logs from the very beginning with one round trip, not in the middle of an active vouch session.. `"request":283,`

**Comment by bnfinet** [comment]
I wonder if it's something about the host header with upstream...
https://stackoverflow.com/questions/40206688/nginx-host-header-for-upstream

**Comment by alexkleinfig** [comment]
I am using Auth0 with bitbucket as a social connection (waiting for the dedicated team to configure ADFS).

I added the OIDC to make it works in a auth0 rule but it works when the /validate proxy_pass hit directly the vouch...:9090

If i force the cookie in the cookie.domain everything is working fine. But i want to be able dev.exple.fr, exple.dev; exple.fr to be able to use the same vouch-proxy server, if i force the cookie i will have to launch separated instances of vouch-proxy for my other domains (thanks for the callback_url tips)

I thought about the upstream but if i proxy_pass directly instead of upstream in the vouch nginx conf to the vouch server backend it doesn't work better.if i just limit the domain that the user is in (exple.fr) or to example.com?

Here are the complete logs with the "nonfunctional" configurations in my first post:
with "testing: true" : https://hasteb.in/adatalub.cs
The protected configuration nginx logs (custom json ones with a bunch of informations/headers): 
- protected.example.com: https://hasteb.in/etatibuf.json
- vouch.example.com: https://hasteb.in/xituzaco.json

my user is in exple and protected/vouch are une example.com, i will add a protected.exple.fr tomorrow morning to test this case.

Thanks

**Comment by alexkleinfig** [comment]
Hum if don't force the original header it works for protected.example.com

if i add callback_urls with dev.exple.fr and copy/paste my nginx configuration to add vouch.dev.exple.fr and protected.dev.exple.fr changing only the /validate proxy_pass and the 302 redirect:
It stills working works for protected.example.com
I have a 302 loop for protected.dev.exple.fr (cookie domain is set to vouch.dev.exple.fr and not dev.exple.fr)

I will do some tcpdump with direct access and throught nginx to deep dive into it

**Comment by alexkleinfig** [comment]
Problem solved. It seems i didn't need to replace the Host Value by the X-Original-Host when calling my external vouch server, i still don't get it but it works, the good cookie is set.

I noticed one weird thing but maybe it will be better in another question ? my $auth_resp_x_vouch_idp_claims_groups get escaped quoted groups: \"mygroup1\", \"mygroup2\"  (Some applications don't realy like it, like opendistro ou force me to have \"Devops\" backend_roles)

https://hasteb.in/lahenoda.pl
