### ISSUE TITLE
logout?url=[...] does not redirect (maybe caused by URL query params?)

### ISSUE THREAD

**Issue by FirefoxMetzger** [vouch/vouch-proxy#326]
I'm setting up vouch-proxy with Auth0. Login and validation are functional. I can call vouch-proxy's `/logout` endpoint, which will (as far as I understand) invalidate and remove the cookie vouch-proxy manages. All of this is works like a charm.

On top of this behavior, I want to also log out the user at Auth0. For this, Auth0 has the endpoint 

```
https://{auth0-domain}/v2/logout?client_id=<client-id>&returnTo=<URL>
```

I have verified that the URL itself works (if I am logged in, I can log out via this URL and be redirected to my app). From this I conclude that the Auth0 side is working properly. I've also added the URL to the `post_logout_redirect_uris` in the vouch-proxy config.

However, when I call `/logout?url=<above URL>` vouch-proxy merely logs me out, but doesn't redirect to Auth0. I'm not sure why. My guess/hypothesis is that the ampersand `&` in the URL throws vouch-proxy and it sees a different URL? Any pointers are highly appreciated.

Here is my current vouch.config: https://hasteb.in/omenayed.yaml

Edit: Addition.

I just tried redirecting to vouch-proxy itself via `/logout?url=http://localhost:9090/`, which redirects as expected. I then tested a redirect with URL parameters via `/logout?url=http://localhost:9090/?foo=2&bar=3` and got the same `400 Bad Request` response from vouch-proxy that I get with the Auth0 URL.

I could probably address this by adding Nginx in front of vouch-proxy (will do that anyway to serve the app). I could add something like 

```
location = /logoutAuth0 {
    return 302 https://{auth0-domain}/v2/logout?client_id=<client-id>&returnTo=<URL>;
}
```

followed by `/logout?url=localhost/logoutAuth0`. This seems quite hacky though, so I wonder if there is a smarter solution.

**Comment by bnfinet** [comment]
Please supply logs and config in the manner described in the README

**Comment by bnfinet** [comment]
@FirefoxMetzger I'm so glad you were able to get it to work, and I'm glad to hear that `X-Vouch-Error` was informative!

**Comment by bnfinet** [comment]
@FirefoxMetzger Nice blog post on your Auth0 setup btw!  Thanks for sharing and showing the love for VP!

SSO for your App via Auth0 + Nginx + Docker + Vouch-Proxy
https://sebastianwallkoetter.wordpress.com/2020/11/01/sso-for-your-app/

**Comment by dmueller1607** [comment]
> I found the issue when I checked the headers of the response in the chrome dev tool:
> 
> ```
> X-Vouch-Error: /logout The requested url is not present in `vouch.post_logout_redirect_uris`: https://{auth0-domain}/v2/logout?client_id={client-id}
> ```
> 
> which didn't include the part after the ampersand `&` (as suspected). After percent-encoding it as
> 
> ```
> http://{vouch-proxy-domain}/logout?url=https://{auth0-domain}/v2/logout%26client_id=<client-id>&returnTo=<URL>
> ```
> 
> the logout worked properly for both vouch-proxy, and auth0. So user error on my side.
> 
> Thank you for the help, and sorry for the noise :)

@FirefoxMetzger: It seems that you encoded the `?` instead of the `&` in the URL, right? Can you please provide your final URL? I'm getting a similar error in my logs when running the logout routine. Thank you.

**Comment by FirefoxMetzger** [comment]
@dmueller1607  This was my nginx config.

```nginx
location = /sso/logout {
      proxy_pass http://vouch:9090/logout?url=https://your-project-name-here.eu.auth0.com/v2/logout?client_id={client_id_from_auth0}%26returnTo=https://localhost/;
      proxy_set_header Host $http_host;
    }
```

In the comment above, I may have replaced the wrong character in the link. Also, the return URL itself should be fully encoded iirc (not just the `&`, but all special characters).

**Comment by dmueller1607** [comment]
@FirefoxMetzger I started your tutorial (https://sebastianwallkoetter.wordpress.com/2020/11/01/sso-for-your-app/), which is very interesting!

I haven't reached out to the "nginx" parts yet, I try to make a login (seems to work) and logout (here's the issue) using only a vouch instance on Docker compose, as described in your blog post.

Here are my settings (let's say my client id is 1234):

- Auth0 - Allowed Logout URIs:
  - ```  
    http://localhost,https://localhost,http://localhost/sso/validate,http://localhost:9090/validate,http://localhost:9090/validate/
    ```
- vouch config.yaml:
  - ```
    vouch:
      post_logout_redirect_uris:
        – https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http://localhost:9090/validate/
    ```

When I'm calling https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http://localhost:9090/validate in my Browser the Auth0 Logout works fine.

When I try to open http://localhost:9090/logout?url=https://dmueller.eu.auth0.com/v2/logout?client_id=1234%26returnTo=http://localhost:9090/validate in my Browser (Chrome), this does not work and my Docker Compose Log sais:

```
ERROR   /logout The requested url is not present in `vouch.post_logout_redirect_uris`: https://dmueller.eu.auth0.com/v2/logout?client_id=1234%26returnTo=http://localhost:9090/validate
```

But, as you can see in my configs above, the logout_redirect_uri is set correctly!

Do you have any clue on that? Thanks for your help.

**Comment by FirefoxMetzger** [comment]
> But, as you can see in my configs above, the logout_redirect_uri is set correctly!

It looks like your vouch proxy instance disagrees 😆

What do your logs in Chrome say? The request to `/logout?...` should produce some kind of error in the header that might be insightful. In addition, you can check if you are actually forwarded to Auth0 or and (if so) if it forwards to the correct address or a truncated one (which could give you further insight).

> I just tried redirecting to vouch-proxy itself via /logout?url=http://localhost:9090/, which redirects as expected. I then tested a redirect with URL parameters via /logout?url=http://localhost:9090/?foo=2&bar=3 and got the same 400 Bad Request response from vouch-proxy that I get with the Auth0 URL.

Do basic redirects (not involving Auth0) work as expected?

**Comment by dmueller1607** [comment]
All redirects (even if they don't involve Auth0) won't work:

- vouch config.yml:
  ```
  post_logout_redirect_uris:
    - https://google.com
    - https%3A%2F%2Fgoogle.com
  ```

Both URLs fail with the error `X-Vouch-Error: /logout The requested url is not present in `vouch.post_logout_redirect_uris`: https://google.com`:

* http://localhost:9090/logout?url=https://google.com
* http://localhost:9090/logout?url=https%3A%2F%2Fgoogle.com

**Comment by FirefoxMetzger** [comment]
Then your problem is not related to the substitution of characters. Potentially, it is due to the fact that `post_logout_redirect_uris` is not parsed correctly. Maybe it is in the wrong section (indentation level) of your vouch.conf?

**Comment by dmueller1607** [comment]
I also checked this :-/ Everything looks fine...

The vouch log also prints the correct values for the `post_logout_redirect_uris` URIs:

```
vouch_1  | {"level":"debug","ts":1617794244.2417617,"msg":"viper settings map[oauth:map[auth_url:https://dmueller.eu.auth0.com/authorize callback_url:http://localhost:9090/auth client_id:1234 client_secret:kvd5ve432R-OoOLI0YjjPLw6-lS3tEWOKXmp_DyD2IGMKmxHW6G9mBae6PSA06gg provider:oidc scopes:– openid – email – profile token_url:https://dmueller.eu.auth0.com/oauth/token user_info_url:https://dmueller.eu.auth0.com/userinfo] vouch:map[allowallusers:true cookie:map[domain:localhost name:my-vouch-ct secure:false] headers:map[accesstoken:X-Vouch-IdP-AccessToken idtoken:X-Vouch-IdP-IdToken jwt:X-Vouch-Token querystring:access_token redirect:X-Vouch-Requested-URI] jwt:map[compress:false issuer:Vouch secret:Your-64-character-secret-key-here] listen:0.0.0.0 loglevel:debug port:9090 post_logout_redirect_uris:– https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http://localhost:9090/validate/ - https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http://localhost:9090/validate - https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http%3A%2F%2Flocalhost%3A9090%2Fvalidate - https://google.com - https%3A%2F%2Fgoogle.com testing:true]]"}
```

**Comment by dmueller1607** [comment]
Finally, it worked for me! I guess the problem was a mixture of the points above. Seems like one of the URLs I provided in the `post_logout_redirect_uris` was somehow malformed.

Here my final configuration:

- Auth0 Logout URLs: <see the comments above>
- Vouch config.yml (the URLs must not be encoded here):
  ```
  vouch:
    post_logout_redirect_uris:
      - https://dmueller.eu.auth0.com/v2/logout?client_id=1234&returnTo=http://localhost:9090/validate
      - https://google.com?q=test
   ```

Then, use the Browser to submit the URL, with the part behind **?url=** as encoded string:

http://localhost:9090/logout?url=https%3A%2F%2Fdmueller.eu.auth0.com%2Fv2%2Flogout?client_id%3D1234%26returnTo%3Dhttp%3A%2F%2Flocalhost%3A9090%2Fvalidate

It works fine now, including the Auth0 Logout. 

@FirefoxMetzger Thanks for your time and your help! And the very helpful blog post, it's really intersting!

**Comment by bnfinet** [comment]
@FirefoxMetzger thanks so much for helping @dmueller1607 to find his way

During startup VP provides some messages which are helpful for Nginx configuration such as these for claims headers..
https://github.com/vouch/vouch-proxy/blob/master/pkg/cfg/cfg.go#L467-L468

I wonder if there's a similar opportunity here for providing a cleaned string which would be able to be cut and pasted into nginx config.

**Comment by Victordmz** [comment]
For those who copy from the tutorial https://sebastianwallkoetter.wordpress.com/2020/11/01/sso-for-your-app/, make sure you use `-` and not `–`! The copying from the website might go wrong.
