### ISSUE TITLE
Support for ECDSA (or RSA) signing of vouch JWT instead of HMAC

### ISSUE THREAD

**Issue by yannh** [vouch/vouch-proxy#327]
This is a stretch - *eventually* I could drive an implementation if this makes sense at all...
Let me start with the use case - I would like to secure an HTML website using Nginx + Vouch Proxy. This website is currently hosted on AWS S3 with Cloudfront in front of it. The workflow would be:.

user > Vouch Proxy > Cloudfront > S3  
                 |
               IdP

I have configured Vouch Proxy to use my iDP, and when accessing my domain that points to Vouch Proxy, I get successfully redirected to my idP for auth -  then Nginx correctly forwards the requests to Cloudfront. So - it "works".

Now I would like to only allow requests to Cloudfront that are coming from the nginx+vouch proxy, so it is not possible to access the restricted website by hitting Cloudfront directly.. 

 Luckily, Vouch Proxy sets a signed JWT on the browser, that it sends with each request. The JWT is signed by Vouch - so if I could verify the signature of the JWT (using AWS Lambda@Edge), it would be possible to guarantee that the requests come from  vouch proxy.

Unfortunately - if I read this line correctly, https://github.com/vouch/vouch-proxy/blob/f222fcbab200116bdf6a7328982c3bd0836c9126/pkg/jwtmanager/jwtmanager.go#L113 - the JWT is signed using HMAC HS256, a Symmetric-key algorithm - and would require the same JWT_SECRET_KEY to verify the signature of the JWT. However I would rather not share that private signing key with my validation logic in lambda@edge..

So - I am wondering whether tt would be possible to add an option to use ECDSA instead of HMAC to encrypt the JWT- which is also supported by https://godoc.org/github.com/dgrijalva/jwt-go . This would allow me to verify the signature of the JWT token of Vouch using a public key, ensuring in Cloudfront that all requests correctly come through the vouch proxy - and deny requests that are not.

An I making sense?

**Comment by yannh** [comment]
To clarify my request - is vouch only signing the JWT, as in - is the information contained in the JWT not secret? Or is the information contained in the jWT secret, should only ever be read by vouch, and needs to be encrypted as well?

This request only makes sense in the case of signing, which is what the documentation refers to :)

**Comment by bnfinet** [comment]
@yannh that's correct, the VP JWT is signed, not fully encrypted

The token is also encoded and compressed.. 
https://github.com/vouch/vouch-proxy/blob/master/pkg/jwtmanager/jwtmanager.go#L113

**Comment by yannh** [comment]
@bnfinet  Great! Let me know if you have any thoughts with regards to https://github.com/vouch/vouch-proxy/pull/331 - I'm happy to move this forward. Thanks!

**Comment by bnfinet** [comment]
@yannh thanks much for the contribution, I've left a few comments for minor issues.  I'm happy to review it again after you're reined in the tests and it is able to pass Travis CI.

**Comment by bnfinet** [comment]
@yannh I've left comments in #331 

Cheers!

**Comment by bnfinet** [comment]
merged in `v0.26.0`

thanks @yannh
