### ISSUE TITLE
json: cannot unmarshal array into Go struct field User.email of type string

### ISSUE THREAD

**Issue by Glowsome** [vouch/vouch-proxy#329]
In trying to get my Microfocus AccessManager IdP to work with vouch i am encountering issues on the 'vouch' end.

log of the operation is filed at : 
[https://hasteb.in/raw/uzopizug](https://hasteb.in/raw/uzopizug)

My vouch config : 
[https://hasteb.in/raw/uzeromic](https://hasteb.in/raw/uzeromic)

'mydomain' is a replacement of the domain i run it under .. so yes its correctly configured :)

Am i missing something ?

**Comment by Glowsome** [comment]
Seems i have stumbled upon a product ( Microfocus AccessManager 4.5.3.0-117) bug ... the userinfo endpoint doesnt seem to return valid json

**Comment by bnfinet** [comment]
@Glowsome those logs and config are now gone from `hasteb.in`.  Could you please repost as a gist in the manner described in the README

I suspect we may need to add Microfocus AccessManager as a new `provider`

**Comment by Glowsome** [comment]
@bnfinet i will have to regenerate them, seem to not have saved them on the testbox - will do so this weekend

In the mean time i have obtained a product-patch which reverses the seen effect ( better said the old behavior of email being sent as string is restored, and have an option to flip this behavior.

regarding this there is a dicussion going on about this change at the [Microfocus community](https://community.microfocus.com/t5/Access-Manager-User-Discussions/OAuth-userinfo-endpoint-attribute-format-and-NAM-4-5-SP3/m-p/2832612#M7156)

**Comment by Glowsome** [comment]
Also after some research this change on the AccessManager seems to violate [OIDC ](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims )standard, so until there's more clarity i would suggest parking this.

**Comment by bnfinet** [comment]
@Glowsome closing,

do repost here if you want it re-opened
