### ISSUE TITLE
running authenticated services on multiple hosts

### ISSUE THREAD

**Issue by rkamradt** [vouch/vouch-proxy#333]
I have a vouch proxy running on a cloud VM, and it is able to authenticate services on that VM. I have another VM with other services that I would like to authenticate via vouch. Should I configure vouch to run on both VMs? The 401 redirect specifies the FQDN of the first vouch host, is vouch stateless so that validate calls can take place on one VM, and login calls can take place on another?

**Comment by bnfinet** [comment]
@rkamradt yes, VP is stateless for all host names within the same domain.  `app1.yourdomain.com` and `app2.yourdomain.com` can both be protected by `vouch.yourdomain.com` regardless of which VM they each run on.

`vouch1.yourdomain.com/login` and `vouch2.yourdomain.com/validate` can each support `*.yourdomain.com` provided they share a common configuration.

Does that answer your question?

**Comment by rkamradt** [comment]
It's encouraging, but I'm still trying to get the configuration just right to make it happen. I'll try a few more tweaks to how it's configured to get it to work.

**Comment by bnfinet** [comment]
@rkamradt feel free to post your configs and logs to a gist in the manner described in the README

**Comment by rkamradt** [comment]
My use case is a little complicated. VM1 has a PHP app, database, Jupyter, vouch, and Nginx and everything works perfectly. I wanted to move the Jupyter server to a different VM which has a database, Nginx, Jupyter, and now a Vouch instance as suggested by your previous post. All of the configuration files that aren't sensitive are in GitHub. Here is the configuration for the original VM1 which is still running:
https://github.com/rkamradt/phpappprod

Here is the configuration that I'm trying to get working (I set the DNS to jupyter.kamradtfamily.net to this VM):
https://github.com/rkamradt/jupyter

And here is the config.yml for Vouch (minus the secret stuff)
https://gist.github.com/rkamradt/3b073be1a63ae78a2456875507286f22

Let me know if and which logs you would like to see.

**Comment by bnfinet** [comment]
@rkamradt please provide the VP logs for both instances.  One full round trip from startup.

What is the problem you are having?  I think I can surmise but I don't see it clearly stated here.

If you are using multiple VP configs then please read these carefully...
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L58-L67
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L98-L106

**Comment by rkamradt** [comment]
Setting the vouch.jwt.secret to be the same in both config.yml files worked! Thanks for pointing this out to me.
