### ISSUE TITLE
SSL handshake failed, alert for TLS v1?

### ISSUE THREAD

**Issue by cbruscato** [vouch/vouch-proxy#337]
I'm a new user to Vouch Proxy, and I need some assistance getting started. I reviewed all the documentation that is available, and I don't see anything specifically related to what I am experiencing. I also searched for any related issues. I'm afraid I don't know anywhere else to seek help for this issue. I would really appreciate it, if anyone could assist.

My scenario is a typical use case, I believe. I am trying to setup Google OAuth with Vouch Proxy and Nginx. I am however, using the Nginx built into linuxserver.io/swag, so I'm not sure if that complicates things further. My understanding is its a pretty stock nginx setup out of the box, just with letsencrypt mixed in, and a ton of proxy examples.

**Describe the problem**
I am receiving a 502 error when trying to authenticate. Upon further review, the root cause appears to be a SSL handshake issue. The relevant error message is:

`SSL_do_handshake() failed (SSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:SSL alert number 70) while SSL handshaking to upstream`

**Expected behavior**
I believe at this point, that I should be getting an authentication request to process and be redirected to Google for authentication. I'm obviously wrong, please forgive my ignorance.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Build 2004
 - Browser: Microsoft Edge (Chromium)
 - Version: 87.0.664.52 (Official build) (64-bit)

**Additional context**
I have multiple servers stacked into a single nginx.conf, one unprotected server for the root domain, one for the protected app which has multiple proxy locations, and one for the vouch proxy to be reverse proxied for SSL support through Nginx. The relevant config files are below, redacted for privacy.

[Nginx.conf](https://hasteb.in/ititexil.nginx)
[Nginx Error Log](https://hasteb.in/ekejuriq.lua)
[docker-compose.yml](https://hasteb.in/rimimalu.yaml)
[config.yml](https://hasteb.in/koruyiqi.yaml)

Please know I tried my best to resolve this on my own before requesting assistance. If it's something dumb, I apologize.

Edit: Just realized that ssl.conf may be relevant since it is included in the nginx.conf. This is the stock version that ships with Swag, I have not modified it:
[ssl.conf](https://hasteb.in/busigobe.shell)

**Comment by bnfinet** [comment]
@cbruscato please post your Vouch Proxy logs in the manner described in the README

**Comment by cbruscato** [comment]
@bnfinet  So I'm having trouble following those instructions. It says to run ./do.sh bug_report yourdomain.com [yourotherdomain.com] which will create a redacted version of your config and logs and follow the instructions at the end to redact your Nginx config. That's why I grabbed as many relevant logs as I could and linked them.

Sorry, I've tried to provide what I can, but that command cannot be run on the docker image. Not everyone is running Vouch on a Linux host natively. My Nginx is running inside of a separate image. I located in another thread you advised to try voucher/vouch-proxy:alpine-latest, but I get a manifest-unknown error trying to use it. I'm not seeing that vouch logs anywhere on the actual host, and if I open a command window it immediately closes. Could you explain how I can generate the needed logs?

**Comment by bnfinet** [comment]
@cbruscato Vouch Proxy logs are sent to `stdout` of the `./vouch-proxy` process.  In the case of the docker containers you should be able to access the logs with `docker logs -f $VP_CONTAINER_NAME`  You may not be able to use `./do.sh bug_report` in this case.  If you look at the `./do.sh` script it might offer you some guidance on how you can use `sed` to redact the information before posting it to a `gist`.
