### ISSUE TITLE
Add the ability to customise the error page on IDP Error

### ISSUE THREAD

**Issue by punkle** [vouch/vouch-proxy#338]
**Describe the problem**
Where email verification is enabled on auth0, vouch shows the error: "/auth Error from IdP: unauthorized - Please verify your email before logging in.". It is formatted as text/plain.

**Expected behavior**
 It would be nice if this error page could be customised and formatted similar to the other failure pages.

**Comment by bnfinet** [comment]
@punkle I think this call to `responses.Error401()` should probably be a call to `responses.Error403()`.  Or perhaps there should be an `responses.Error401HTTP()` version which doesn't call `http.Error` which apparently sets `context-type: text`.  

Would you care to submit a PR?

https://github.com/vouch/vouch-proxy/blob/master/handlers/auth.go#L56

**Comment by punkle** [comment]
Hey. I will certainly try submit a request. Thinking out loud, I wonder would swapping the comment on line 103 and 102 of responses.go fix this.

**Comment by bnfinet** [comment]
> I wonder would swapping the comment on line 103 and 102 of responses.go fix this.

@punkle  The `responses.Error401()` call is the main response from `./validate` back to Nginx.  Since that's the hot path it's preferential to keep it fairly light as a text document.  I agree `401` is the right status.  A new method for `responses.Error401HTTP()` feels like the best way forward.

**Comment by punkle** [comment]
@bnfinet I have pushed something up there. Let me know if you have any feed back.
