### ISSUE TITLE
Support for pre-signed URL of some sort?

### ISSUE THREAD

**Issue by bdruth** [vouch/vouch-proxy#347]
Hello! I've been searching around the docs & issues & Google and my search-fu isn't coming up with anything. I have been using Vouch Proxy + Okta OIDC for some time now with great success. I have a new use-case, however, that I haven't had any luck supporting, and I may just not understand how some of the moving parts ... move.

What I'm trying to do is generate a URL to a protected resource that can be accessed w/o needing to login separately. Similar to how AWS allows you to generate a pre-signed URL to download a file. Is there any practical way to do this? Ideally, this URL would be expired, as well ... so, 5 minutes after generating, it would just not "automatically" work and then fail over to the Okta login flow, I guess? That's ideal / optional.

Thanks in advance for your thoughts on this!

Cheers.

**Comment by bnfinet** [comment]
@bdruth  thanks for the kind words!  I don't think this is going to be feasible with VP but I'll offer some thoughts..

VP does look for the issued token in the URL query string value of  `access_token`...

https://vouch.yourdomain.com/validate?access_token=$VP_JWT

However that's practically an undocumented feature.  Its intended use was for protected apps to validate a VP token with a call back to VP's `/validate` before accepting HTTP headers for username etc from a request.

This use case feels a bit orthogonal to how VP works.  In general I'm not clear on how to fit the issuing, retrieval, deployment and response of a token into the an OAuth flow that would be backed by Okta.

It would be easier without OAuth/Okta for a simple service which uses auth_request to test the resource. 

/admin/generate?expires=5m
* creates a new token (probably just a random string of sufficient length) 
* stores it in a cache that expires in 5 min
* returns just the token and `200 OK`
* could be protected by VP or a "super admin token" of its own within this system

/validate
 * have a good token?  200
 * no? 401
 * might require `X-Original-URL` to be set by Nginx and then evaluate the contents (https://secretfiles.yourdomain.com/big_contracts.pdf?t=$TOKEN)

I'm somewhat thinking out loud here.

I'm surprised you haven't come across an implementation of something along those lines.  There must be something out there already, no?

**Comment by bdruth** [comment]
Thanks for taking the time to respond! My use case is maybe odd ... I'm generating a file (video recording) and then sending a notification to a device (my phone) ... in general, that file is "protected", but I'd like to be able to open the notification and just view the file, if it's within a few minutes.

Your idea is definitely doable, I think - my head was starting to meander in that direction, too. I'll tilt at that for a bit and see what I can get working. Thanks!

**Comment by bnfinet** [comment]
@bdruth I'm going to close this though feel free to continue the discussion here if it would be of service to your concept.
