### ISSUE TITLE
Does Vouch support JWT token validation?

### ISSUE THREAD

**Issue by phi1ipp** [vouch/vouch-proxy#351]
Sorry, if it's a duplicate, I tried to find anything w/o any luck, hence asking.

Does Vouch support validation of JWT tokens passed as `Authorization: Bearer ...` based on issuer's JWKS? It looks like no, but maybe I just missed it.

Thank you

**Comment by bnfinet** [comment]
@phi1ipp Vouch Proxy (VP) is the issuer.  If a token is passed to VP's `/validate` in an `Authorization: Bearer ...` header it will be validated.

With regard to validation of the origin token, this is a dup of #69
