### ISSUE TITLE
Install on ubuntu 18.04 without docker. 

### ISSUE THREAD

**Issue by rleal124** [vouch/vouch-proxy#363]
Hi 

Is possible install Vouch-proxy without docker on Ubuntu 18.04. 
I following the issue: https://github.com/vouch/vouch-proxy/issues/286

But I still don't understand how I can install. 

Can please help how can install without docker or more simple way?

**Comment by bnfinet** [comment]
@rleal124 #unfortunately with #361 VP won't currently build properly.  The quick fixes listed there should work for a build.  

As for installation of the software you'll need go installed.  There are several good tutorials out there for how to download and build go programs.

This is the preferred way to build... (once #361 is fixed).  As you found in #286 they are the same steps listed in the `Dockerfile`.

https://github.com/vouch/vouch-proxy#compiling-from-source-and-running-the-binary

It would be a help to the project if you could improve these instructions.  I'm sure other users would appreciate it.
