### ISSUE TITLE
ansible playbook for Vouch Proxy

### ISSUE THREAD

**Issue by sloonz** [vouch/vouch-proxy#364]
Right now, Vouch works by sharing a cookie between the Vouch instance (vouch.example.com) and the protected domain (protected.example.com). This requires the two subdomains to be on the same main domain (example.com). The cookie directly contains the session data.

I propose to support a setup where a single Vouch instance can protect subdomains not sharing the same domain. This requires the session data to not be directly stored in the cookie data, but in an external store (for example Redis, or maybe just an in-process hash table), the cookie containing only a handle to the session ("session ID").

The workflow would look like this : 

- User visits https://protected.example.com/ for the first time
- auth_request callls /validate. /validate sends back 401 error together with a `vouch_session_id` cookie
- nginx sends back the cookie to the user-agent, and redirects it to https://vouch.example.com/login?session_id=(session_id)
- Vouch redirects to IdP, IdP redirects to Vouch with `session_id` in the `state` parameter. Vouch stores the JWT in its session store and redirects to protected.example.com 

Subsequent authentication process looks like that : 

- User visits https://protected.example.com/. Cookie contains `vouch_session_id`.
- auth_request calls /validate (transmitting the cookie). Vouch retrieves the JWT from its session store and perform authorization checks (whitelist)

**Comment by bnfinet** [comment]
@sloonz how many separate domains are you trying to protect?  

The great thing about VP currently is that is scales very easily.  As long as each instance carries the same secrets the VP Cookie/JWT can be validated anywhere.

I'd like to avoid adding this feature if possible as it effects scalability and increases complexity.  Feels like the kind of thing that could trigger a bunch of support requests.

Could you clarify and expand your problem and use case just a bit with specific real world examples for your usage?  Are you running into a problem currently with VP?

Vouch uses 12M of memory, its pretty cheap to run multiple VPs.

**Comment by sloonz** [comment]
> Vouch uses 12M of memory, its pretty cheap to run multiple VPs.

My issue with running multiple instances of VP is not system resources, it is deployment simplicity.

My use case is protecting (many different) small backoffices that don't have an authentication logic programmed in it, and instead rely on the reverse proxy. All have their own domains, sometimes not under my direct control. Having one instance per domain is perfectly fine resources-wise, but having to deploy one VP instance (+ domain configuration, + letsencrypt) would honestly take a non-negligible part of the (deployment/maintenance time) savings of "don't bother programming an authentication logic, a simple standard configuration on the reverse proxy will take care of that"

**Comment by bnfinet** [comment]
Have you considered ansible, puppet, chef or those options?  If you're
going to have the setup on the nginx end you're already into templates and
boilerplates.

**Comment by sloonz** [comment]
I’m already using Ansible

**Comment by bnfinet** [comment]
Oh that's awesome!  Are you able to share your vouch procedure?   I'd love
to add it to the '/examples'

**Comment by sloonz** [comment]
As of now I’m not using Vouch, I’m using a custom-developed solution, and I’m currently exploring what to do of it (replace it with Vouch ? something else ? open source it ?)

I have one global nginx instance on each server ; each "project" has its own Linux user with its own nginx instance. I have three ansible roles : 

- Configure letsencrypt/global nginx (just add a vhost that will point to the instance-specific nginx)
- Create the project user and its environnement
- Create and configure the project-specific nginx

That third role has a role parameter `nginx_features`, which corresponds to a standard templated piece of nginx configuration. For example, a wordpress project will be given `nginx_features: [php, wordpress]`. One if these standard template is `auth_request`, which basically looks like this : 

```
auth_request /.internal/ngx-auth-request;
error_page 401 = /.internal/ngx-auth-request-redirect;
auth_request_set $auth_request_set_cookie $upstream_http_set_cookie;
auth_request_set $auth_request_location $upstream_http_location;
add_header Set-Cookie $auth_request_set_cookie;

location /.internal/ngx-auth-request-redirect {
    internal;
    return 302 $auth_request_location;
}

location /.internal/ngx-auth-request {
    internal;
    proxy_pass https://ngx-auth.example.com/auth;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-Method $request_method;
    proxy_set_header X-Original-URL $http_x_forwarded_proto://$host$request_uri;
    proxy_set_header X-Ngx-Auth-Token $http_x_ngx_auth_token;
    proxy_pass_header Cookie;
}
```

Therefore, I can add an authentication layer on any project that lacks one by just adding `auth_request` to its `nginx_features`, which in the ends just amounts to copying a configuration file (https://ngx-auth.example.com is a single instance shared by all projects, including projects on different servers/domains)

**Comment by bnfinet** [comment]
@sloonz thanks for clarifying and sharing your setup.

That all seems favorable for integration with an Ansible playbook for Vouch Proxy.  Would you be interested in working on such a playbook?  That would be a big win for the project IMHO and seems like it would satisfy your need as well.

**Comment by bnfinet** [comment]
@sloonz I'm going to leave this here as Ansible Playbook focused.  If you'd care to put effort towards that I'd love to have the conversation.

Otherwise I hope that someone else might be interested in improving VP in this manner.
