### ISSUE TITLE
use custom AWS Cognito Login Page

### ISSUE THREAD

**Issue by nswarnkar** [vouch/vouch-proxy#372]
Hello,

We are using vouch proxy with AWS Cognito. When we open the backend site, protected by Vouch, it takes us to AWS Cognito login page. But we want to land this on our own Login Page, which is already using AWS Cognito SDK to user same Cognito User Pool.

Can you please let me know how can I have my own login page?

**Comment by bnfinet** [comment]
@nswarnkar unfortunately I am not an AWS Cognito user and I'm not familiar with it's features.

Are you talking about this stuff... ?
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html

**Comment by bnfinet** [comment]
@nswarnkar I'm going to close this but please chime back in if you need more help
