### ISSUE TITLE
Configuration of Vouch Proxy and Nginx with OpenAM IdP

### ISSUE THREAD

**Issue by cdurepo** [vouch/vouch-proxy#376]
Hello.  I am trying to get VP to work with OpenAM.  
It seems that OpenAM returns the JWT as a url parameter called code. 
So in nginx I try to tell VP that by doing this in my /validate location: 
 auth_request_set $auth_resp_jwt $arg_code;

but I keep getting these errors and a redirect loop
{"level":"error","ts":1616189394.1838589,"msg":"no jwt found in request"}

The question is how do I set the token name for VP when it is a parameter?

**Comment by bnfinet** [comment]
Please post your config and logs in the manner described in the README.

**Comment by cdurepo** [comment]
I am working on doing that but I get an error when I try to run the bug report. 

#
# redacted Vouch Proxy config/config.yml
# 2021-03-22
#

sed: -e expression #1, char 24: unknown option to `s'

**Comment by bnfinet** [comment]
Could you please elaborate on your operating environment. Please cut and
paste commands you run and errors you receive and post them to a gist.

**Comment by cdurepo** [comment]
I was putting the secret in the command line and the special chars must have been breaking it.  It looks like it redacts it anyway so once I remove that it worked.  I am cleaning up my nginx now so I can post it.  Thank you for the help so far!  :-)

**Comment by cdurepo** [comment]
Here is my gist: https://gist.github.com/cdurepo/eff8858a259f468052cc226e2e804a98

When I go to /protected I get my 302 to login via openAM.  Once I do that I get a 302 sending me back to my nginx at /protected,  nginx logs show me hitting /protected with the JWT in the url as ?code=JWT
that is why I have the entry in my nginx trying to grab that and set the header for vouch-proxy.

**Comment by bnfinet** [comment]
Where are the VP logs?

Could you please post as per the README.

**Comment by bnfinet** [comment]
Oh they're there!  You'll need to fix that error and repost.

**Comment by cdurepo** [comment]
I saw that error to but it not accurate.  Obviously vouch is finding the config file as it is running and sending me to the redirect.  I run it and I see that I hit it and I see output from where I ran, ./vouch-proxy.  
When I don't start it I get 500 errors, if that error was correct I would only ever get a 500 error right? 

I don't get why I see more output to my screen than the logs show.  Not sure what that is.

**Comment by cdurepo** [comment]
on the screen, after I start vouch I get this output: 
2021-03-22T17:38:04.327Z	DEBUG	/validate
2021-03-22T17:38:04.327Z	ERROR	no jwt found in request
2021-03-22T17:38:04.327Z	DEBUG	domain IP.ADDR matched array value at [0]=IP.ADDR
2021-03-22T17:38:04.327Z	DEBUG	CaptureWriter.Write set w.StatusCode 401
2021-03-22T17:38:04.327Z	INFO	|401|  151.138µs /validate	{"statusCode": 401, "request": 21, "latency": "151.138µs", "avgLatency": "221.54µs", "ipPort": "127.0.0.1:54904", "method": "GET", "host": "IP.ADDR", "path": "/validate", "referer": ""}

**Comment by bnfinet** [comment]
@cdurepo could you please re-read the README and post you information to a gist in that manner.

If the README is unclear, could you please suggest improvements.

**Comment by cdurepo** [comment]
I read it many times in the process of setting up my gist.  I don't understand what you are not seeing that I missed.  I don't see logs in my vouch directory.  I created the gist because of the read me.  I ran the do.sh bug_report because the readme told me too.  I included the nginx config as the readme said to do.  I don't see any logs, my last post was the standard out after starting vouch via ./vouch-proxy.  What am I missing that I was supposed to include?  If you can tell me what is missing, maybe I will understand that part of the README better.

**Comment by bnfinet** [comment]
the VP logs are sent to standard out.  Please copy and paste them into the
gist.  If `./do.sh bug_report` isn't working for you then please do find
another way.

We need logs from a "full roundtrip"...
/validate
/login
login at your IdP
/auth
/auth/$STATE

do not post logs to the issue please.

**Comment by cdurepo** [comment]
I am sorry to be a pain, but I don't even understand what I am getting wrong. I put the logs that were in the ticket into the gist. https://gist.github.com/cdurepo/eff8858a259f468052cc226e2e804a98. is that all that was missing?  I have done everything else that has been asked.  
"Round trip"
I hit my nginx, I get the redirect to my authentication, I authenticate, I get the redirect back to my nginx box, that then goes to VP again because my JWT is in the url not a header.  So VP does not see a token and just loops back.  But my auth thinks I am authenticated so I just loop on my nginx.  When I look at my nginx logs, I see my hitting my nginx box with my JWT in the url.  

So I have the configs, I have the logs, I have completed as much of a round trip as I can.  Is there something else that I am still missing?

**Comment by bnfinet** [comment]
These are not logs related to the problem that you are experiencing.  
https://gist.github.com/cdurepo/eff8858a259f468052cc226e2e804a98#file-gistfile1-txt-L60-L61

Without logs I can't understand what VP is doing and what you're asking VP to do.   Please take the logs which you are seeing and put them in the gist.

**Comment by cdurepo** [comment]
I put them at the end of the file.  They report that it received no JWT token. 
https://gist.github.com/cdurepo/eff8858a259f468052cc226e2e804a98#file-gistfile1-txt-L194-L199

**Comment by bnfinet** [comment]
This is not going to work...
https://gist.github.com/cdurepo/eff8858a259f468052cc226e2e804a98#file-gistfile1-txt-L143-L150

The `error401` should 302 redirect to VP, not your IdP.

Why are you using IP addresses instead of hostnames?

**Comment by cdurepo** [comment]
I was using IP address because I am just testing and did not want to run into issues with the proxy.  I moved to hostnames and the proxy does not seem to be an issue so I will test with those.  I have made the changes that you suggested but I have to wait on changes need from the OpenAM to add the redirect to /auth.   

If I could ask another question while I wait for that, is VP expecting the connection to /auth after the login, to have the token as a header var?  That is how I understand VP to work and would like to verify that.

**Comment by bnfinet** [comment]
Look for "third leg" here..
https://github.com/vouch/vouch-proxy#the-flow-of-login-and-authentication-using-google-oauth

VP issues it's own tokens.  The token from the IdP is used only during authentication with a direct server to server request.

**Comment by cdurepo** [comment]
Looks like that biggest issue was that /auth redirect that I had wrong. 
I figured out what I had wrong with the bug_report. 

Thank you for your help.
