### ISSUE TITLE
cross domain support

### ISSUE THREAD

**Issue by nrukavkov** [vouch/vouch-proxy#379]
Hello guys. Is it possible to use your solution for cross-domains?

I mean I created an OAuth key(google) in domain example.com. But I want to use your solution for domains in zone dev: *.example.dev. I just get 400 errors. And maybe it is not possible to do.

**Comment by bnfinet** [comment]
multiple `vouch.domains` is supported as per the README and `config.yml_example` but it can be tricky.

without seeing your setup I can't really provide support.  Please provide logs and config in the manner described in the README.

**Comment by nrukavkov** [comment]
Thank you. I suppose I did it.
