### ISSUE TITLE
Packaging for the Alpine Linux distribution

### ISSUE THREAD

**Issue by rnalrd** [vouch/vouch-proxy#380]
Hi,

I've packaged vouch-proxy for Alpine [1]. I've run into an issue when running from the packaged version vs built from source. Both running version 0.23.1.

The issue is that the ***packaged version*** does not correctly set the headers **X-Vouch-User** and **X-Vouch-Success** after successful authentication.

Nginx log
https://gist.github.com/rnalrd/2481eff24494595f9da88617683b3ff7

vouch log:
https://gist.github.com/rnalrd/c374f59d09384aee608e4699a9053576

***vouch-proxy built from source** 
Nginx log:
https://gist.github.com/rnalrd/bd85c4030bd4e588c8aa4f2512066d26

vouch log:
https://gist.github.com/rnalrd/fa6becff81c4949baccf782e871481bd

Nginx configuration:
https://gist.github.com/rnalrd/b06bf8b5b3c3f36f7c510cfdb0debc34

Vouch Proxy configuration for both:
https://gist.github.com/rnalrd/59a1d393c5d6b4f4e1fe78941186bca6

[1] https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/vouch-proxy

**Comment by rnalrd** [comment]
Sorry for that.

Can't really use do.sh to prepare the bug report, as it should run against the packaged version which place configuration, binary, logs and static files in different locations.

Please let me if you want me to make additional changes to the report or need additional info.

Thanks

**Comment by bnfinet** [comment]
@rnalrd please provide full VP logs for both instances that you are offering here.  Full round trips as described in the README including the startup and the **version** of the software that is running and all other logs related to startup and each roundtrip.  Without that I can't really tell what VP is doing.

**Comment by rnalrd** [comment]
ok will do, thanks

**Comment by bnfinet** [comment]
A similar effort for NixOS and the Nix package manager
https://github.com/NixOS/nixpkgs/pull/118615

**Comment by rnalrd** [comment]
Add the gists with vouch proxy full debugging logs. Please let me know if anything else is missing.

**Comment by bnfinet** [comment]
@rnalrd  Why isn't a `semver` or `version` in the log?  Are you building from a `git clone`??  Are you building with `./do.sh build`? 
https://gist.github.com/rnalrd/c374f59d09384aee608e4699a9053576#file-gistfile1-txt-L14

Does your code base include `./.defaults.yml`?

**Comment by rnalrd** [comment]
This has been very helpful. I missed to copy the .defaults.yml file [1]. Now it's running properly.

I'm building from a tagged version, so I've now included the semver during build [2].

Thanks!

[1] https://gitlab.alpinelinux.org/alpine/aports/-/commit/6db4e2533209bc0bf735ffe859e52ffc35ba2f17
[2] https://gitlab.alpinelinux.org/alpine/aports/-/commit/d45869879fc2af4b1c6838902b72012aab7f3a7d
