### ISSUE TITLE
Infinite Redirect

### ISSUE THREAD

**Issue by eayin2** [vouch/vouch-proxy#382]
**Paste**
nginx config https://gist.github.com/eayin2/068b40e9a58e5546b8ffaebe228a177e
vouch log https://gist.github.com/eayin2/7dd5cd4be7e6f7bed4acd53d593b1150
vouch config https://gist.github.com/eayin2/d458d5ebbf2441f6d50f66e4a337bbeb
testing page: https://imgur.com/Z0uHWQV
Okta.com (API) config https://gist.github.com/eayin2/bb7abd111449e74cccb9462b01535fd1

**Problem**
Infinite redirect loop after authentifcation. Redirect between vouch, my site and okta. Displays "Redirect Error" after login / or being logged in.

**Expected behavior**
Show my site after login (owncast)

**Desktop information:**
 - OS: Ubuntu 20.04
 - Browser Chromium and Firefox
 - Version Chromium 90.0.4430.72 (Offizieller Build) (64-Bit)

**Comment by bnfinet** [comment]
@eayin2 what version of the software are you running?  Could you please offer a VP log from startup?

Things to try..
* A bear bones VP config based on /conf
* Removing the duplicate 'auth_request' in /
* Turning on 'testing'

**Comment by eayin2** [comment]
**Paste**
Full VP log: https://gist.github.com/eayin2/7b7aa8fe4eb5dd6f21ceccce1560c4f8
nginx conf: https://gist.github.com/eayin2/08d05862cdc9cbfbc2b7ac96455319b9
VP config: https://gist.github.com/eayin2/2da785ea61009d0f5468ae152bde8770

Tried:
- A bear bones VP config based on /conf
- Removing the duplicate 'auth_request' in /
- Turning on 'testing'

How can I find out the version? I installed VP with `docker run -d     -p 9090:9090     --name vouch-proxy     -v ${PWD}/config:/config     voucher/vouch-proxy`

**Comment by bnfinet** [comment]
version is here..
https://gist.github.com/eayin2/7b7aa8fe4eb5dd6f21ceccce1560c4f8#file-vp-full-log-L11

`v0.23.1` is the current version.

```
cookie: 
    secure: false
```

since you're using https, that should be `true`, which is the default so better yet removed.

**Comment by eayin2** [comment]
Removed `secure: false`. In VP log I see two relevant error, but I'm not sure what causes them:
```
{"level":"error","ts":1619106502.6912382,"msg":"no jwt found in request"}
{"level":"error","ts":1619106509.321238,"msg":"/auth Error while retreiving user info after successful login at the OAuth provider: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"The authorization code is invalid or has expired.\"}"}
```

**Comment by bnfinet** [comment]
@eayin2 the first is saying you don't have a credential token (the cookie is not present, did not get set)

the second one says there was an error from Okta when it tried to retrieve your user information for the "third leg" server to server request to `https://dev-***.okta.com/oauth2/default/v1/userinfo`

Searching for "The authorization code is invalid or has expired" provides this explanation...
https://support.okta.com/help/s/article/The-authorization-code-is-invalid-or-has-expired?language=en_US

I'm guessing your session cookies are not getting set in the browser.  Have you tried removing the nginx proxy buffer?  Is there something else preventing cookies from being stored in your browser?  Do you see the cookies in the browser when using developer tools?

Please post full updated logs when you change some aspect of the config and please update the configs too.

**Comment by eayin2** [comment]
Had to reinstall my digitalocean droplet and also create a new Okta account as I reached its rate limit (probably because of the many redirects). I will try the cookie test shortly, I wonder: what links I should click when I'm in `testing: true` mode. _Vouch_ shows me these links
```
login
logout
validate
<list of octa and /auth links>
```
When I click on the `octa link`: https://****.okta.com/oauth2/default/v1/authorize?client_id=0oamph5wxPWYzjxYI5d6&redirect_uri=https%3A%2F%2Floginasia.awsmppl.com%2Fauth&response_type=code&scope=openid+email&state=vVNH3VXQTHwu7PNWNpA8Pwsv5vZb2oK
then new `/auth` links are added.

**Comment by bnfinet** [comment]
> I wonder what links I should click when I'm in testing: true mode

in general, you should click the newest link which is added to the bottom

**Comment by eayin2** [comment]
Great then I understood the procedure. With testing I can see now that it redirects in circles:
https://gist.github.com/eayin2/0dbe14b0b387b971771f411914c81cdf

**Paste**
VP conf https://gist.github.com/eayin2/79b81a16f1e4805b6a4c0ccdde19d80e
auth request (could produce only once, then it showed no cookie) https://gist.github.com/eayin2/43cee9e5b88bb743dea01ad1a230cc2d
VP logs https://gist.github.com/eayin2/c667f9dfb7391c70b8609e8d3b8c8a54

Removing the nginx proxy buffer made no change.

**Comment by bnfinet** [comment]
You're still configured `secure: false`.
https://gist.github.com/eayin2/79b81a16f1e4805b6a4c0ccdde19d80e#file-gistfile1-txt-L16-L17

**Comment by eayin2** [comment]
Removed `secure: false` again. Added it accidently again, when reinstalled my server
**Paste**
log https://gist.github.com/eayin2/7e04f6a06ece2fd5cc3f7422f07ef03f
conf https://gist.github.com/eayin2/581fd06ba7ed2c127a9c7de863f64c3d
nginx https://gist.github.com/eayin2/9f17f23ac8d91b7bee4f795a4dc16186

**Comment by bnfinet** [comment]
@eayin2 try setting `vouch.cookie.domain: awsmppl.com`

**Comment by eayin2** [comment]
When I click on the /auth link only then I see the cookie, once I click on the other links the cookie is not visible anymore (in chrome inspect).
**Paste**
https://gist.github.com/eayin2/7e74edae5ec8daca766b271d30dafba1
https://gist.github.com/eayin2/74aef4e98fb463dbef60765d24dfd3b3

**Comment by bnfinet** [comment]
do not click on the other links, just click on the new link at the bottom

what happens if you turn `testing` off?

Is the cookie present when you access https://streamasia.awsmppl.com/ ??

Is it getting set by the call to loginasia.awsmppl.com/auth/$STATE ??

**Comment by bnfinet** [comment]
Is this accurate?
https://gist.github.com/eayin2/9f17f23ac8d91b7bee4f795a4dc16186#file-gistfile1-txt-L36

Is the `host` header being passed properly?


https://gist.github.com/eayin2/7e74edae5ec8daca766b271d30dafba1#file-gistfile1-txt-L13

**Comment by eayin2** [comment]
No I see a different request URL
Also I see this error in the response header:
x-vouch-error: /auth Error while retreiving user info after successful login at the OAuth provider: oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."}


Request URL: https://loginasia.awsmppl.com/auth/CWqvRWMXKb76EJ0h92A7sg6Qk0C1dvx/?code=cKgNxQtnkTQplJIWOiVt8Jmf3ifbqdZdSdRRIe2H4g0&state=CWqvRWMXKb76EJ0h92A7sg6Qk0C1dvx

and @ Request Header: :path: /auth/CWqvRWMXKb76EJ0h92A7sg6Qk0C1dvx/?code=cKgNxQtnkTQplJIWOiVt8Jmf3ifbqdZdSdRRIe2H4g0&state=CWqvRWMXKb76EJ0h92A7sg6Qk0C1dvx

**Comment by bnfinet** [comment]
I can't tell what question you are answering.

There's something wrong with the cookie not getting set into your browser.  I would advise you too only change one thing at a time.

I'm going to be afk for a few days.  Best of luck, feel free to update and I'll look again next week.

**Comment by eayin2** [comment]
I think maybe this is a bug. You can reproduce like this:
**Create dydns**
- Create a an account on nsupdate.info and create two dyndns subdomains and set the IPv4 of the droplet to it. Delete any IPv6 for the two subdomains
- Disable IPv6 on the droplet. Add to sysctl.conf
```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
```
Run `sysctl -p` to apply.
(I tried it also with IPv6, but I wanted to make the test scenario simpler)

**Installation**
- Create a digitalocean droplet (I used the smallest with 25GB Space 1 vcpu, also tried a droplet with 2 intel-cpu cpu)
  and I used Ubuntu 20.04 LTS as distribution
- Install curl `apt update && apt install curl `
- Install owncast (https://owncast.online/quickstart/)
  `cd $HOME; curl -s https://owncast.online/install.sh | bash`
- Run `./owncast`
- Install nginx-extras: `apt install nginx-extras`
- Remove the default nginx config in `/etc/nginx/sites-enabled/default` and one of the above pasted nginx config
- Install docker with
```
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
```
- Create an Okta dev account on https://developer.okta.com/, then create a new application in Okta and select `Web` and `OpenID`, add as callback the dydns VP subdomain. See: https://gist.github.com/eayin2/bb7abd111449e74cccb9462b01535fd1
- Copy the VP config to $HOME and run `docker run -d -p 9090:9090 --name vouch-proxy -v ${PWD}/config:/config voucher/vouch-proxy`
- Visit the dyndns subdomain

I can't help anymore, but maybe you'll can reproduce it and find the cause.

**Comment by bnfinet** [comment]
Nothing I'm seeing there or in your other offerings indicates a bug in VP.
If there were a problem with using OIDC with Okta there would be quite a
few users having issues.  Occam's Razor suggests a configuration issue on
your end related to the cookie.  It's usually alignment issues between the
domains and that's what the logs are implying.

**Comment by bnfinet** [comment]
> I can't help anymore, but maybe you can reproduce it and find the cause.

@eayin2 if you are no longer pursuing this issue could you please close
