### ISSUE TITLE
403 error when account is not logged in.

### ISSUE THREAD

**Issue by nrukavkov** [vouch/vouch-proxy#383]
Hello. We use your amazing solution but we have a small inconvenience. If a user has only 1 google account and this account doesn't belong to our domain(we use google provider) - we got an error like in the screenshot. 

![Снимок](https://user-images.githubusercontent.com/54890287/115694965-09ba5780-a36a-11eb-8e5c-3c28cad1520e.PNG)

**Expected behavior**
See a login page - not error.

**Additional context**
I suppose it could be a google issue. But maybe we need a pass some option or something else... Anyway, thank you

**Workaround**
You need to go to any google service and add an account there.

**Comment by bnfinet** [comment]
Have you tried these solutions..

https://stackoverflow.com/questions/55285369/google-cloud-oauth-authorization-error-this-client-is-restricted-to-users-withi


What else have you tried?

**Comment by nrukavkov** [comment]
I'm not sure that I was understood right. I do not want to grant access to external users. The thing is google chrome doesn't allow add a new account for logging. It just drops this error when only one account is present in google chrome. 

But it doesn't look like that is your issue. Thank you
