### ISSUE TITLE
General OIDC Debug Question

### ISSUE THREAD

**Issue by jwomackgsa** [vouch/vouch-proxy#385]
I am setting up VP and trying to make it work with an Idp called SecureAuth via OIDC.  I have enabled debug and testing, and I am fairly certain the issue resides with on the IDP side because of the error I am getting which is around it being unauthorized to access the user info endpoint, but my question is should I expect to be seeing the token exchange part as part of the testing mode?  Like a url or the api call that is being used with the code that is received from the idp to get its token?

All I see is the the initial redirection to the idp auth endpoint and then an error about oauth2 cannot fetch token.

**Comment by bnfinet** [comment]
@jwomackgsa please provide your config and logs as per the README.  It's difficult to understand what you're seeing.  It's much easier if you offer the logs to understand what VP is doing.

**Comment by jwomackgsa** [comment]
Here is a bug_report output.

https://gist.github.com/jwomackgsa/38e7166672fa067ff300b0db5cd56f30

**Comment by jwomackgsa** [comment]
I built the latest version from code and this time used an updated git version so the build tags populated properly.  I worked through an error with the SecureAuth vendor related to the Access Denied error but now getting a Bad Response.  The idp vendor is asking if I can confirm what token URL I am hitting but the debug log doesn't seem to provide this information which is what my original question was about.  Additionally, the error message is a bit confusing as it says error retrieving user info but then the oauth2 error is token related.

`/auth Error while retrieving user info after successful login at the OAuth provider: oauth2: cannot fetch token: 400 Bad Request`

**Comment by bnfinet** [comment]
Often that's firewall related.  VP is trying to contact the IdP to exchange
the token for the userinfo.  Can the system make outbound requests?

**Comment by jwomackgsa** [comment]
Yeah I can confirm that I have connectivity on 80/443 to the idp web endpoint.  Since I can't see the server side token access portion in the logs, we are turning the idp logs up so we can ensure I am hitting the correct endpoint.

**Comment by bnfinet** [comment]
This is your token URL.  Did you vendor confirm that it's correct?
https://gist.github.com/jwomackgsa/38e7166672fa067ff300b0db5cd56f30#file-gistfile1-txt-L40

The only place where that would be shown in the log is at the very beginning when the entire config is dumped to the log.

**Comment by jwomackgsa** [comment]
Yes I have confirmed the token url is correct with the vendor and the idp web logs show the go-http-client is reaching the endpoint correctly so that is good.   The vendor is now looking at the idp logs and has found some configuration issues related to the signing certificate on their side.  We are making changes on that end to see if that resolves the issues or presents the next challenge.  At this point, there doesn't seem to be any issues with VP or its configuration, however I would like to keep this issue open so that I can hopefully share a working configuration with SecureAuth idp via OIDC.

**Comment by bnfinet** [comment]
@jwomackgsa were you able to make any progress?

**Comment by jwomackgsa** [comment]
Yes, sorry for the delay of the update.  I was successfully able to use the OIDC configuration with VP to get it working with SecureAuth idp.  The problem ended up being a cert configuration issue related to the private key not being exportable (it runs on Windows using pfx).  I am not using any complex use cases but I am getting all my scope data as expected.  Let me know if there is any further information you would like me to provide, otherwise we can close out this issue.
