### ISSUE TITLE
Vouch requires the Host header to be that of the sending site which can be problematic for remote site proxying

### ISSUE THREAD

**Issue by mig5** [vouch/vouch-proxy#386]
**Describe the problem**

The Vouch documentation says that when proxying a `/validate` endpoint in a Client Site (let's call it www.example.com) to the Vouch Site (let's call it https://vouch.example.com), the Host header should be sent to Vouch with a value of the Client Site:

```
    location = /validate {
      # forward the /validate request to Vouch Proxy
      proxy_pass http://127.0.0.1:9090/validate;
      # be sure to pass the original host header
      proxy_set_header Host $http_host;
```

The above is fine when the Client Site is on the same server as the Vouch instance.

But when the Client Site is on a remote server, the `proxy_pass` is a remote URL of the Vouch instance:

```
     resolver 8.8.8.8 8.8.4.4;
     proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
     proxy_ssl_session_reuse on;
     proxy_ssl_verify_depth 2;
     proxy_ssl_verify on;
     proxy_pass https://vouch.example.com/validate;
     proxy_set_header Host $http_host;
```

(note also the additional config since Nginx does *not* do SSL validation of https:// endpoints in proxy_pass by default - it blindly allows the traffic, opening up the potential for MITM attacks - ugh!)

There is a bit of a quirk with this requirement of the Host header being that of the Client Site. It means that if the Vouch Site has, say, an Nginx proxy in front for the HTTPS over public endpoints, it actually needs to 'answer' for the Client Site's domain, e.g have something in its `server_name` (or ServerName/ServerAlias if it was Apache) that allows the webserver to use this vhost to answer for that request after it evaluates the Host header.

Without this, you can imagine this could be a problem if there were other websites on the same server that runs Vouch. If there is no vhost that is considered 'answerable' for the Client Site of 'www.example.com', the web server will pick the first alphabetical vhost and serve *that* in the response to the /validate proxy request, instead of Vouch.

I imagine that in most cases it's feasible for people to add something like `*.example.com` to the `server_name` of the SSL vhost fronting Vouch. At least when the source domains are on the same 'upper' domain e.g example.com -  there are other knock-on effects then, such as ensuring the SSL cert in use on the Vouch vhost actually works for the Client Domain. Cool for a wildcard SSL cert or things of that nature but problematic if you are also using this Vouch app for foobar.com and aren't using SAN certs.

On top of that, without SNI, even if your Vouch vhost has the Client Site's domain in its `server_name` block, the SSL cert validation would potentially be done against a different SSL vhost if one exists on the server.

I was able to get Nginx to use SNI to help us with this issue but it still depends on the Vouch Nginx vhost 'answering' as if it were the Client site. In case it helps others battling the same issue, my nginx snippet in the `/validate` location block of the Client site ends up looking something like this:

```
   location = /validate {
     # We are going to proxy to a remote host, but Nginx doesn't
     # do SSL verification by default for proxy_pass.
     #
     # For that we need nameservers and trusted CA roots to validate
     # just like a browser would, and we need to
     # explicitly set proxy_ssl_verify on.
     resolver 8.8.8.8 8.8.4.4;
     proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
     proxy_ssl_session_reuse on;
     proxy_ssl_verify_depth 2;
     proxy_ssl_verify on;
   
     # We also should use SNI to validate the SSL cert against
     #  the right vhost, if there are multiple SSL sites on the
     # remote Vouch server
     proxy_ssl_name vouch.example.com;
     proxy_ssl_server_name on;
   
     # forward the /validate request to Vouch Proxy
     proxy_pass https://vouch.example.com/validate;
   
     # Vouch expects the Host header to be that of the
     # sender domain, to check that it can do auth for
     # this website's domain
     #
     # This doesn't seem to interfere with the proxy_pass
     # above, thanks to the proxy_ssl_name and proxy_ssl_server_name
     # settings above, but it *does require that the
     # Vouch vhost on the remote side has a 'server alias'
     # for the sending domain (e.g a wildcard *.thisdomain.com)
     # to catch the request.
     proxy_set_header Host $http_host;
```

In short: the requirement of Vouch to get a `Host` header being that of the Client Site, is a bit problematic (but not insurmountable for the most part) when proxying over https (e.g not 127.0.0.1:9090 to the direct Vouch app/container), and especially if using different domains on your Client Sites.

I imagine it's an even bigger problem for infrastructure that uses some sort of ingress proxying (e.g in front of clusters of Docker apps such as ALBs with Amazon ECS, maybe also k8s) whereby the Host header is used in some sort of 'rule evaluation' to work out which backend target/port to send the traffic to, to ensure the request goes to the right container. What happens if both Vouch and the Client Site are behind the same ingress proxies and the Host header is that of the Client Site, even though *it* was the one requesting a proxied hit to Vouch?

I haven't dug closely into the code, but I assume that the point of Vouch receiving the `Host` header as that of the Client site, is to evaluate against the `domains` config option as to whether it can even answer for that domain before it moves onto actually delegating to the oAuth provider. Maybe there are other reasons. 

Vouch already has a lot of other custom headers with `X-` prefixes for other uses. Would it be possible for Vouch to expect to receive something like `X-Vouch-Client-Host` rather than the `Host` header? That would go a long way to solving the problem.

Perhaps if X-Vouch-Client-Host is *not* present in the request, it could fall *back* to the Host header, to avoid backwards-incompatible problems.

I hope this explanation makes sense. If I can explain it better I'd be most happy to!

**Comment by bnfinet** [comment]
@mig5 thanks for the info

Nginx offers this documentation regarding securing upstream proxied https connections
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/

HTTPS/HTTP routing is tricky but we haven't had any problems with having the `$host` header passed.  If you're administering Nginx with an eye towards what inbound requests are offering and downstream apps are expecting you're hopefully able to wrangle the bits to your satisfaction.  I don't see how `X-Vouch-Client-Host` would improve on `Host`.  You're welcome to pass what you'd like to VP as `Host` of course.  In the case of `allowAllUsers: true` it won't even `Host` in validation.

If there is some aspect of VP's docs which you feel could use expansion, PRs are always welcome.

Cheers!

ben

**Comment by mig5** [comment]
Hmm, thanks @bnfinet  - I don't think I explained it sufficiently, but not to worry.

>  You're welcome to pass what you'd like to VP as Host of course.

This is a surprise - are you saying that we could sort of pick a 'reserved' host name to send, not being that of the actual client site? I am assuming, so long as it falls on the same domain as that configured in the `domains:` list in the Vouch config?

In other words, Client Site foo.example.com proxies /validate to vouch.example.com, but sets the Host header as 'specialvouchclient.example.com'. Will the jwt still work because it was still a Host header that used example.com, even though it wasn't the true host name of the Client site ? (foo.example.com)

**Comment by mig5** [comment]
Ahh cancel that, it turns out that doing SNI in the Nginx proxy request is all that's needed. You don't actually need to have your Vouch SSL vhost recognise the incoming 'Host' header at all.

The magic was this bit:

```
     proxy_ssl_name vouch.example.com;
     proxy_ssl_server_name on;
```

I had set the host in the server_name of the vhost prior to trying SNI, but it works without it. Thanks again.

**Comment by mig5** [comment]
Just tested the above. 

For a client site foo.example.com, and a Vouch site vouch.example.com, where foo.example.com proxies /validate to vouch.example.com over *https* (note: not http:// to a local IP/port of the Docker container, but over the internet)... I have found that I can set the Host value to vouch.example.com instead of foo.example.com.

Because I have 'example.com' in my `domains:` allow list in Vouch's config.yml, it seems to work fine.

Can I confirm that the above is ok and safe in your opinion? That is, this host validation is purely being done to check against the domains list, but it's not important for anything else really in terms of jwt etc?

Thanks!

**Comment by bnfinet** [comment]
yep, that all seems correct
