### ISSUE TITLE
vouch proxy on localhost

### ISSUE THREAD

**Issue by rammote** [vouch/vouch-proxy#388]
As I am new with golang i really want to know that setting vouch proxy with localhost is possible or not?

if possible will you please guide me how should I configure it, as I am getting a "no jwt found in request " error.

thank you

**Comment by bnfinet** [comment]
`localhost` can work.  Personally I prefer to setup a host in `/etc/hosts` which points to,,

`127.0.0.1  vouch.ourdomain.com`

or such.  This usually models your deployed environment a bit more closely and allows establishing certs and whatnot.

@rammote for further support, please consult the README for how to submit an issue
