### ISSUE TITLE
Can I just allow one user with an environment variable?

### ISSUE THREAD

**Issue by nickshanks347** [vouch/vouch-proxy#391]
Hi,

I wish to only allow one user to access the services I host behind vouch-proxy. 

Is there a way of setting this user with an environment variable?

**Comment by nickshanks347** [comment]
Didn't seen the configs! Thanks!

**Comment by nickshanks347** [comment]
Actually, I've set VOUCH_WHITELIST to my github username and email address (separate variables) and set VOUCH_ALLOWALLUSERS to false yet I get forbidden on my account which should be authorized

**Comment by nickshanks347** [comment]
Found `x-vouch-error: /auth User is not authorized: verifyUser: user.Username not found in WhiteList: nickshanks347 . Please try again or seek support from your administrator` in my response headers. VOUCH_WHITELIST is set to nickshanks347.

**Comment by bnfinet** [comment]
Please post configs and logs in the manner described in the README

**Comment by bnfinet** [comment]
Read the README please.

**Comment by bnfinet** [comment]
@nickshanks347 are you still working this issue?  If not, please close the issue.
