### ISSUE TITLE
get error when callback from idp

### ISSUE THREAD

**Issue by taagholi** [vouch/vouch-proxy#392]
Hello
With below configuration, when I enter the address of https://www.fcb.ir 
in the browser, I go to the IDP login page. After entering the information and confirmation, when my browser wants to go to the callback URL that I set in vouch, 
the browser sends a message as follows and does not go to my indexPage.
"**This site can not be reached**"

My Configuration and logs are as follows

1- [my etc/hosts](https://gist.github.com/taagholi/3eb4578225dbf7a685510ff9027cf377)

2- [sso.conf in conf.d folder of nginx](https://gist.github.com/taagholi/914747f182bbe9f80569eab638e5dff8)

3- [log and config of voch-proxy](https://gist.github.com/taagholi/b67e0e6e2d982feaf0b6725069591d3e)

Please help me.
thanks.

**Comment by bnfinet** [comment]
Your IdP can't be reached directly by VP.  Check the user_info url and make sure an outbound request to your IdP can traverse the firewall.

https://gist.github.com/taagholi/b67e0e6e2d982feaf0b6725069591d3e#file-log-and-config-yml-of-vouch-L46

**Comment by taagholi** [comment]
Can you tell me exactly what to do?
If I send a request to user_info_url with the postman and receive the answer, will I understand?

**Comment by bnfinet** [comment]
Confirm that there url is correct.  Confirm that VP can make requests of your IdP.

What IdP is it?

**Comment by taagholi** [comment]
OK
I will review the network access and the correctness of the URL of addresses,
But then how do I know that VP can make requests of your IdP?

**Comment by taagholi** [comment]
The user_info_url was incorrect, but after correcting the user_info_url, I got this error again.
To make sure, I used the postman, first I got the authorization code from the browser and then I was able to get the id_token with the postman and by entering the amount of authorization code.
Please help, where is the problem?

**Comment by taagholi** [comment]
Given that the oidc certificate is self-signed, I think the problem is here. How can I solve the problem?

**Comment by taagholi** [comment]
i added my *.crt to ca-certificates.crt
But there is still a problem

**Comment by bnfinet** [comment]
@taagholi are you still working this issue?  Could you please close if you are not.
