### ISSUE TITLE
Redirecting back to IDP

### ISSUE THREAD

**Issue by mpn-peter-smith** [vouch/vouch-proxy#394]
NGINX Protected Application - https://gist.github.com/mpn-peter-smith/cbe62a67f68b61786901fe706397ad9e
NGINX Vouch Reverse Proxy - https://gist.github.com/mpn-peter-smith/2905805187ccc07f8784bb6e3e113e74
Vouch Config - https://gist.github.com/mpn-peter-smith/c2f29bcf89da8d079d5455a94ce035aa
Log - https://gist.githubusercontent.com/mpn-peter-smith/56e040972831967b8ef2b7a518c701a4/raw/31f1e09582ff7d34926fe93247c8a9aad5a6c4ac/error.log

I have an issue where i keep getting infinitely redirected back to the IDP. In the logs there is an error with "no jwt found in request". I have tried entering debug and testing mode but with no success as to finding the error.

In the log it complains about not being able to access "open /config/secret: permission denied". The Vouch proxy is running in a docker container.

Any suggestions appreciated.
Cheers

**Comment by bnfinet** [comment]
@mpn-peter-smith what IdP are you using?  Could you please supply full logs in the manner described in the README?  Two full round trips, with `testing`.

> in the log it complains about not being able to access "open /config/secret: permission denied". The Vouch proxy is running in a docker container.

that seems odd, is the docker container being run on top of a read only fs?

**Comment by mpn-peter-smith** [comment]
@bnfinet 
The filesystem is not read only and is running in /etc/vouch/ under a docker container.
I have given docker full access to the folder but am still seeing the error.
I have done multiple testing rounds but with no success.
Cheers

**Comment by bnfinet** [comment]
@mpn-peter-smith what IdP are you using? Could you please supply full logs in the manner described in the README? Two full round trips, with testing.

**Comment by mpn-peter-smith** [comment]
My IDP is Keycloak and i am generating the logs now

**Comment by shadow38** [comment]
Hello,

I've got the same issue here with keycloak v8.0.2. 
My configuration is very closed to the configuration of @mpn-peter-smith ; in the logs we can see that the referer is set to the IdP at the end. I've got the same error message too : "no jwt found in request"

Logs : https://gist.github.com/shadow38/6c4ffccab942b1260fb8dfc048799f83

FYI I could'nt get vouch-proxy working properly with an old version of Keycloak neither (v3.4.0).

**Comment by bnfinet** [comment]
@shadow38 please read the README and post your conf and logs accordingly.

**Comment by shadow38** [comment]
@bnfinet 
Actually it was as a misconfiguration of my VP. VP works perfectly with Keycloak (v3.4.0, v8.0.2, v14.0). My mistake was on the cookie domain configuration :( (I read again the README as you proposed and found out what was wrong).

Thanks a lot for your work on this project!

**Comment by bnfinet** [comment]
@mpn-peter-smith any updates?  If you're no longer working this issue could you please close it.
