### ISSUE TITLE
Passing the email address from IdP to application (answer: use scopes & claims)

### ISSUE THREAD

**Issue by manthena81** [vouch/vouch-proxy#396]
I am using Vouch to use Github enterprise Oath app for authentication into my app via nginx (standard flow). I can see the vouch cookie passed on to my application http header. But I cant find the email id/user name in the header. I am trying to configure that in vouch config and nginx config. somehow its not working. Can you provide any reference on how to pass emailid/user name via http header?

**Comment by bnfinet** [comment]
@manthena81 please post your configs to a gist as per the README.

**Comment by manthena81** [comment]
THank you for the response. Here are the links to gist.. Hope this is how you would need it.
nginx-conf: https://gist.github.com/manthena81/c5b9b0c930c9b64255b4de45cc617476
Vouch-conf  https://gist.github.com/manthena81/2426cf5e9aa100c70d4b95d96b128fd9

**Comment by bnfinet** [comment]
The VP config looks odd (that first item should get flagged as invalid) but generally both configs look fine.

Could you please upload your logs as described in the README.

**Comment by manthena81** [comment]
@bnfinet  
I couldn't quite understood on how to collect logs from README guidance. I run Vouch in a seperate cointainer and I cant access shell to execute anything. 
May be If I ask the question differently and it may lead to quicker solution to what I am trying to solve. 
I could see vouchcookie that is passed to application with header and application can read it. But How do I decode the cookie?  Is JWT token within the encoded cookie itself? If yes, If I can manage to decode the cookie, my problem is solved. So can you help with that? do we need jwt secret to decode the cookie or something? JWT secret is generated by vouch internally, and I cant access that. (This is the message I get in the kubectl logs.)
{"level":"debug","ts":1626849693.6035695,"msg":"open /config/secret: no such file or directory"}
{"level":"info","ts":1626849693.603591,"msg":"jwt.secret not found in /config/secret"}
{"level":"warn","ts":1626849693.6035945,"msg":"generating random jwt.secret and storing it in /config/secret"}
{"level":"debug","ts":1626849693.6036067,"msg":"open /config/secret: read-only file system"}
{"level":"warn","ts":1626849693.6036086,"msg":"generating random session.key"}

**Comment by bnfinet** [comment]
@manthena8 if you're interested in decoding the jwt directly you'll need to use the secret and make sure that you turn compression off.  However you should be able to get the username from the header passed by vouch.  I'm not in a position to support decoding JWTs outside of VP but that's well documented on the internet in various libraries.

Are you working from the VP helm chart?  If you're configuring an nginx ingress controller, please upload your K8s config.

That snippet of logs look like regular startup.

kubectl has the ability to generate the logs from the VP container.  Please upload the logs in the manner described in the README.  Without those it's very difficult to offer you any help.

**Comment by manthena81** [comment]
I am not using helm but using K8S deployment yamls. And I am using k8s ingress controller. I have uploaded logs to gist.
https://gist.github.com/manthena81/e890fbf5253533f51115b92a6bed045c. 
How do i access jwt secret in order to decode it because all I get in the header is a vouch cookie. Also Does vouch cookie already include jwt?

**Comment by bnfinet** [comment]
The VP log is reporting configuration errors.  Your configuration is not getting loaded properly.

You can set the secret in the config.

**Comment by bnfinet** [comment]
@manthena81 any progress?  If you're no longer working this issue would you please close it.

**Comment by manthena81** [comment]
@bnfinet Apologies for the delay. I will try to fix the configuration errors. meanwhile can you help with below.
1. Is there any documentation on how to set secret for JWT in the vouch config? 
2. I am guessing that the vouch cookie includes the JWT in an encrypted format. Is it correct? Will I be able to decode if I manually set secret ?
3.Is there any good guidance documentation on passing & consuming user details in application?

**Comment by bnfinet** [comment]
@manthena81 ...

1. please take a look at the config example describing `vouch.jwt.secret` https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example
2. yes though you'll want to turn compression off
3. have you looked at the README's "Scope's and Claim's section? https://github.com/vouch/vouch-proxy#scopes-and-claims

**Comment by manthena81** [comment]
@bnfinet 

Thank you for your patience. Finally, I managed to pass the user and email to application using claims and nginx. It solved half of my problem. I am wondering if I can have my application access the team of the GIthub user so my application can manage the access level based on team. Is it possible to pass the team of github user? I cant find the reference for the same. 
btw, corrected all configuration problems. config is much cleaner now. Thanks

**Comment by bnfinet** [comment]
@manthena81 I'm glad you got it to work.

I don't know of a scope and claim [1] which would have GitHub return the teams but perhaps there is one. VP makes an api call to GitHub to get the team information for `vouch.teamWhitelist`.  The teams cannot currently be added to the downstream HTTP request, but I could see this as a nice feature.

I'll close this issue.  If you'd care to propose such a feature, please do open a new issue.

[1] https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps
