### ISSUE TITLE
returning the username from Gitea in an HTTP header

### ISSUE THREAD

**Issue by mindfuucker** [vouch/vouch-proxy#397]
**Describe the problem**
I have a working Vouch Proxy + Gitea in oicd mode. I login using a username/password. Somehow this translates into an email-address being put in the nginx header. I cannot seem to figure out how to pick a specific ?claim/scope? and put it into the header. 

The music player called [Navidrome ](https://github.com/navidrome/navidrome) just implemented header-based login. So I want to use that. The problem is that Navidrome want to have my username, not my email. 

- [Vouch config](https://paste.gg/p/anonymous/96a6e92629cc4600ba4e21f2f217cd3d)
- [Gitea openid-configuration](https://paste.gg/p/anonymous/6f83f430c3ae4af4ae0646190bf55507)
- [Header being send](https://paste.gg/p/anonymous/70811b571302403c9fe3de3e53a26bd4)  (made using [http-https-echo](https://hub.docker.com/r/mendhak/http-https-echo), great tool)
- [Navidrome nginx config file ](https://paste.gg/p/anonymous/1da732bbb76646f5acdeaa65dbae0826)(music.domain.nl)

**Expected behavior**
x-vouch-user being filled with my username, not my email. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome

**Additional context**
I suspect it's just a config somewhere but its not documented very well. I tried searching the oicd provider code and i've checked all the past issues.

**Comment by bnfinet** [comment]
@mindfuucker please supply the logs as per the README.  We need to look a what the `user_info_url` is returning to VP

**Comment by bnfinet** [comment]
If you'd like to offer improvement to the "Scopes and Claims" section of the README that would be much appreciated.
https://github.com/vouch/vouch-proxy#scopes-and-claims

**Comment by mindfuucker** [comment]
> @mindfuucker please supply the logs as per the README. We need to look a what the `user_info_url` is returning to VP

The do.sh script was too difficult for my monkey brain to comprehend. I'm running from docker-compose and need to do some docker exec that I don't understand. 

I have copied the docker terminal output here: [LINK](https://paste.gg/p/anonymous/d9d04a6df3e44cd982996d8c29b46031)

**Comment by mindfuucker** [comment]
> If you'd like to offer improvement to the "Scopes and Claims" section of the README that would be much appreciated.
> https://github.com/vouch/vouch-proxy#scopes-and-claims

Ah, I read over that part of the documentation. I was searching with the oicd/openID keywords. Sorry for wasting your time.

**Comment by bnfinet** [comment]
@mindfuucker please take another look at the README and then update your logs as described.
