### ISSUE TITLE
After redirect to Cognito and login with localhost, Vouch returns `400 Bad Request` on callback to /auth with session ID 

### ISSUE THREAD

**Issue by quaintgondor** [vouch/vouch-proxy#399]
**Use a Paste Service**
[Logs here](https://gist.github.com/quaintgondor/a822e12601bad6b86f52ca87ae53274d)

**Describe the problem**
After redirect to Cognito and login, Vouch returns `400 Bad Request` on callback to /auth with session ID .

**Expected behavior**
I expect to be redirected to my protected application (reverse proxied at '/' in Nginx to simple app running on port 3000 on host) after authenticating.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chrome, Firefox
 - Versions: 91.0.4472.114 (Chrome), 89.0.2 (Firefox)

**Additional context**
I'm running vouch-proxy and nginx in two different docker containers.  I've tried with domains set, allowing both localhost and my host address.

Callback and Sign out URL in Cognito client settings are set as `http://localhost:9090/auth` and `http://localhost:9090/logout` respectively.

**Comment by bnfinet** [comment]
@quaintgondor the cookie is getting set into `localhost` but all of your requests are for `192.168.1.72`.  The cookie will not be presented back to your browser due to the domain mismatch.  You could add an entry to your hosts file such as..

`192.168.1.72  myapp.ourdomain.com` 

and then set the cookie domain as `ourdomain.com`.

**Comment by bnfinet** [comment]
@quaintgondor did that work?  Are you still working this issue?

**Comment by tspoorthyreddy** [comment]
I am having the same issue , after the authentication in cognito it keeps redirectingand throws this error ERR_TOO_MANY_REDIRECTS
https://hasteb.in/Rotp8NNSw4TXx1V
