### ISSUE TITLE
OAuth Provider logout?

### ISSUE THREAD

**Issue by cmollis** [vouch/vouch-proxy#40]
Can the OAuth provider logout be implemented?  For Okta, this would require the passing an id_token.. which could be obtained using the access_token obtained obtained here:

providerToken, err := cfg.OAuthClient.Exchange(oauth2.NoContext, r.URL.Query().Get("code"))

**Comment by bnfinet** [comment]
@cmollis sorry for the delayed response

to clarify, you're suggesting that when visiting `/logout` vouch should 302 redirect the client to https://organization.url/login/signout along with the `providerToken` such as described in
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout ?

**Comment by cmollis** [comment]
Hi.. yes, sorry for my delayed response.. so, yes, at least for the Okta implementation I think this would work.

**Comment by bnfinet** [comment]
Can you please take a look at #56 and see if the `/logout?url=https://organization.url/login/signout ` solution is sufficient for your case?

**Comment by bnfinet** [comment]
@cmollis really I'm curious if the 302 would suffice or if the providerToken is required in the 302 redirect

@aaronpk do you happen to know?

**Comment by cmollis** [comment]
Yeah.. I think for okta logout, it looks like the id_token from the
original auth grant is required for logout

https://developer.okta.com/docs/api/resources/oidc#logout

**Comment by bnfinet** [comment]
it looks like it will still clear the cookie at Okta, it will just throw an error.  Am I reading that right?

@cmollis without this in place are you unable to deploy Vouch Proxy in your environment?  How important is this feature to you?

**Comment by cmollis** [comment]
ok..   actually, not a huge deal right now.  But thanks for checking on it.
  If I ever get a free minute, I definitely would like to help you guys out
with this.

**Comment by artagel** [comment]
Since logout is actually something we can get from .well-known, and is offered by providers, can't we just provide an option to redirect the user on logout?

**Comment by bnfinet** [comment]
The vouch proxy logout url already allows a url argument to be passed which
will result in a 302 to a different logout facility.

/logout?url=https://myidp.com/logout

In the case of the idp (okta), they usually need a token passed back to
authorize the logout request.  It's the storage and retrieval of this token
which is the sticky parton the vouch proxy side.

Different idps do different things depending on if you hit the logout
endpoint without offering the correct token.  For okta, it will only
forward you back (or on) if you have the token.

**Comment by artagel** [comment]
Right, but right now I'd need to set the url= in nginx?  Or is there a config option I missed in vouch?
My point was, considering that there's an issue in to implement discovery anyways, we'd be able to add functionality to handle this with a config option to allow the admin to choose how to handle logouts.

**Comment by bnfinet** [comment]
Yep I hear you.  It should probably be more obvious or at least the url
parameter could be better documented.

Is it too onerous to leave it on the app or nginx side?

How are you using logout in your environment?  Could you describe your
setup and use case?

If we're diving into logout, I'd like to solve the token problem at the
same time if possible.

**Comment by artagel** [comment]
I'm prototyping 2 architectures right now.  One with keycloak, and one with adfs.  I haven't specifically looked if either of these require a token, but I'll check.  
I'm doing some work on adding some functionality I need anyways, so I can help take a took at this. one too.

**Comment by bnfinet** [comment]
That's awesome.  Thanks for the contributions!

In the case of the token storage need to keep multi deployed vouch proxy
node environments in mind.

I'll be in and out all weekend but I'll try to be responsive if something
come through.

Cheers!

**Comment by ptr727** [comment]
Hi, sorry to jump in here, but I'm trying to add a logout option, at least so that I can easily test logging in again.
Any update on how to logout for an Okta login?

**Comment by bnfinet** [comment]
@ptr727 is this comment helpful to you? ...
https://github.com/vouch/vouch-proxy/issues/40#issuecomment-478266562

Are you testing logging in with Vouch Proxy or with Okta?

if you're testing logout, or anything else.  Be sure to consider settting `vouch.testing: true` which may be of help in your development.

**Comment by ptr727** [comment]
I want to put a logout button on my website, and I will call whatever I need to to log the user out, i.e. next time they hit a protected site they need to login again.

I did try calling http://vouchserver/logout, but my user remained logged in.
I saw that comment, and I assumed that vouch is not (yet) supporting logout.

Or am I doing the logout operation wrong, should I call Okta isntead of Vouch to logout?

**Comment by bnfinet** [comment]
When you say "my user remained logged in" do you mean, logged into Okta?

If so, you should figure out what your Okta logout endpoint is and then append it to your call to logout as the query string paramater `url` such as... 
http://vouchserver/logout?url=http://yourokta/logout

**Comment by ptr727** [comment]
Ah, ok, I misunderstood the URL purpose, I thought that is the return redirect URL.
Will vouch add the session id as required by Okta to the URL?
See https://developer.okta.com/docs/api/resources/oidc/#logout

Should the logout URL not be part of the vouch configuration yaml?

I can't test this right now, so please excuse my questions without testing it first.

**Comment by ptr727** [comment]
Ok, matching the sentiment of the previous comments, it looks to me as if vouch needs to be responsible for adding the id_token parameter to the logout command.

I tried to point my logout link to:
http://vouch.home.insanegenius.net:9090/logout?url=https://dev-424935.okta.com/oauth2/default/v1/logout

And as expected I get a 400 bad request error:
Error Code: invalid_token
Description: The id token is invalid.

The Okta expected URL is:
http://vouch.foo.net:9090/logout?url=https://dev-424935.okta.com/oauth2/default/v1/logout?id_token_hint=${id_token}
Where id_token is "A valid ID token with a subject that matches the current session."

So, unless I'm missing something, vouch needs to explicitly support the logout flow by:
1) adding a config option for the logout URL (unless this is OIDC standard?)
2) automatically pass the id_token value in the URL
4) Optionally take a return page URL option
4) Optionally handle the logout success failure state

**Comment by bnfinet** [comment]
That sounds about right.

Will you be submitting a PR?

**Comment by ioMatrix** [comment]
Was there any movement on this? I am also using Okta and need the logout function to work. The token seems to be a required element to send in GET request.

**Comment by bnfinet** [comment]
no, no change, if you'd be interested in working on this feature please do let us know

**Comment by ioMatrix** [comment]
I modified the vouch-proxy logout function to send the id token. However, there is no test for other auth provider options so it would be sending it when not required if used in a non-okta situation which probably isn't what the dev wants.

For what it's worth, here is the hacked function. When I have more time, I can probably add checks for Okta specific urls etc.

`handlers.go

func LogoutHandler(w http.ResponseWriter, r *http.Request) {
	log.Debug("/logout")

	jwt := FindJWT(r)
	
	log.Debug("LOGOUT JWT:",jwt)

	claims, err := ClaimsFromJWT(jwt)

	log.Debug("LOGOUT TOKEN:", claims.PIdToken)
	cookie.ClearCookie(w, r)

	log.Debug("saving session")
	//ssessstore.MaxAge(-1)
	session, err := sessstore.Get(r, cfg.Cfg.Session.Name)
	if err != nil {
		log.Error(err)
	}
	if err = session.Save(r, w); err != nil {
		log.Error(err)
	}
	sessstore.MaxAge(300)

	var requestedURL = r.URL.Query().Get("url")
	req, err := http.NewRequest("GET", requestedURL, nil)
	q := req.URL.Query()
	q.Add("id_token_hint", claims.PIdToken)
	req.URL.RawQuery = q.Encode()
	if requestedURL != "" {
		redirect302(w, r, req.URL.String())
	} else {
		renderIndex(w, "/logout you have been logged out")
	}
}`

**Comment by bnfinet** [comment]
thanks @ioMatrix, that looks promising

Could you please submit a PR or publish the branch with this code?

**Comment by bnfinet** [comment]
@airbornemint thank you for submitting PR #258 

There are a number of issues to address..
* [1] the token to be sent to Okta is session specific.  It does not make sense to carry it as a configuration element. 
* [2] the elements that you would like to add to the config and oauth struct are divergent from OIDC
* there are no tests submitted with the PR

[1] https://developer.okta.com/docs/reference/api/oidc/#logout
[2] https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

Further more, I am currently making adjustments to `/logout` as part of other work which will have impact upon this part of the code. Please hold off on anything further until I have a chance to push these changes, hopefully within the next few days.

Thanks again.

**Comment by airbornemint** [comment]
Re point 1: I am not sure what you mean — the token is coming from JWT, not from Config.

Re point 2: I didn't check the logout spec (my bad) so I didn't realize that the two keys were dictated by the spec (as opposed to vendor extensions by Okta. Since they are not vendor extensions, we can definitely take them out of the config, and I'd be happy to do so.

Re point 3: I can do that (after you're done making the changes you mentioned).

**Comment by bnfinet** [comment]
>Re point 1: I am not sure what you mean — the token is coming from JWT, not from Config.
oops, my bad, yes indeed, that looks good

**Comment by bnfinet** [comment]
@airbornemint `v0.11.1` is a refactoring of `/login` and `/logout` to mitigate url redirection attacks

Could you please refactor your changes to the new setup (`logout.go`).

Thanks again for the contribution.

**Comment by airbornemint** [comment]
@bnfinet Thanks; I'll work on that and the unit test for my code over the next couple of days.

**Comment by airbornemint** [comment]
@bnfinet Refactored on v0.11.1, addressed point #2 above, test added, ready for review.

**Comment by bnfinet** [comment]
thanks much @airbornemint 

I'll take a look in the next day or two.

**Comment by bnfinet** [comment]
@airbornemint I've made a few comments on files but overall it looks good, just a few implementation details.

If I'm reading the code correctly, when the provider's logout url is configured, if the request comes as https://vouch.example.com/logout?url=https://myapp.example.com/login it will 302 to https://providerurl/logout?post_logout_redirect_uri-=https://myapp.example.com/login.  Is that correct?

**Comment by airbornemint** [comment]
That is correct. Thanks for the feedback, will review shortly.

**Comment by bnfinet** [comment]
@airbornemint thanks for the code!  Much appreciated.

#258 is merged
