### ISSUE TITLE
Empty string instead of (probably X-Vouch-User) header name.

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#400]
Trying to set is working with Keycloak
Authorization itself WORKS, but i want to pass some user info into my application, and here comes problems.

VP Config:
https://gist.github.com/ShyLionTjmn/a25617e340c61241d38315e7f08329e8

Nginx Config:
https://gist.github.com/ShyLionTjmn/3bac9a18145f362b3e6ff62bdf35b1ba

tcpflow on port 9090
https://gist.github.com/ShyLionTjmn/1c061ace12bf2719fb292437fe517495

VP console log:
https://gist.github.com/ShyLionTjmn/0ba81ab32659d926627184a63b710a28

**Expected behavior**
I expected to get X-Vouch-User set in VP replies to nginx, but instead there is some strange headers:

```
HTTP/1.0 200 OK
: no@way
: true
Given-Name: ..........
```
or
```
HTTP/1.0 200 OK
: no@way,true
Given-Name: ..........
```

Why there is no X-Vouch-IDp prefix on Given-Name? Where is X-Vouch-User at all?

**Comment by shadow38** [comment]
Hello,

In my (working) configuration with Keycloak, I've got this section in my VP configuration :

```
  headers:
    jwt: X-Vouch-Token
    user: X-Vouch-User
    success: X-Vouch-Success
    error: X-Vouch-Error
    querystring: access_token
    redirect: X-Vouch-Requested-URI
    # https://github.com/vouch/vouch-proxy/issues/287
    # accesstoken: X-Vouch-IdP-AccessToken
    # idtoken: X-Vouch-IdP-IdToken
    claimheader: X-Vouch-IdP-Claims-
    claims:
      - ctemail
```

And in my nginx configuration

```
    auth_request_set $auth_resp_x_ctemail           $upstream_http_x_vouch_idp_claims_ctemail;
    proxy_set_header ctemail        $auth_resp_x_ctemail;
```

Hope it helps!

**Comment by ShyLionTjmn** [comment]
Thanks. That helped.
Still, i couldn't find anywhere that i should set those headers manually. I supposed there had to be some default values, not empty string?

**Comment by shadow38** [comment]
Sure there's something odd; .defaults.yml (in rootdir) doesn't seem to be loaded properly in my case. It seems that you've got the same problem and need to define all variables in your config.yml to ensure that VP works properly. 

I didn't try to understand what went wrong with the .default.yml.

**Comment by bnfinet** [comment]
@ShyLionTjmn is `.defaults.yml` present at `/opt/vouch-proxy/vouch-proxy/.defaults.yml`?  

Is the `$VOUCH_ROOT` env var set?

**Comment by ShyLionTjmn** [comment]
Ouch. Should it?
