### ISSUE TITLE
UTF-8 Headers values

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#401]
Claim values comes UTF-8 encoded, and directly passed to corresponding headers. Isn't that a violation of standarts? I thought HTTP headers should be ASCII only.

I think that coode should check if text is non ASCII and properly encode header if it is not.

**Comment by bnfinet** [comment]
@ShyLionTjmn could you please point to the standard?

I think technically you are correct.  Are you experiencing a bug?  Is this having impact on your setup?  Could you please offer some details about what you're trying to accomplish and what you're seeing.

**Comment by ShyLionTjmn** [comment]
Didn't experience any impact in that regard, just noticed.
