### ISSUE TITLE
Are groups claim special treated? (ShyLionTjmn questions)

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#405]
I try to get groups claim into separate header and nginx complains about too big header.
tcpview shows that there is strange line break or not a header at all in the vouch-proxy output:

https://gist.github.com/ShyLionTjmn/679e8d59c2dcd4758ceb4ebea59aa4b1

Notice Set-Cookie: VouchSession= has a line break!

**Comment by ShyLionTjmn** [comment]
If i remove grups from headers->claims  - everything returns to normal

**Comment by bnfinet** [comment]
@ShyLionTjmn could you please provide your config and logs in the manner described in the README?

@ShyLionTjmn you've opened several issues in the VP repo recently.  Can we contain your issues to this thread for the time being?  Lets get you up and running. using this thread for the time being.

If we do happen to encounter an enhancement or bug along the way we can decide together if it warrants a new issue.

I'm going to close your other issues for the time being.

**Comment by ShyLionTjmn** [comment]
Ok.

VP config:
https://gist.github.com/ShyLionTjmn/4ee6cef85587a2cff50bdc1016b2a060

nginx:
https://gist.github.com/ShyLionTjmn/be858923d498578ffadeb0b68cc9e711

vouch-proxy debug log:

https://gist.github.com/ShyLionTjmn/a256a651e84fa6c5e3f437eb4e501d81

tcpflow vouch-proxy:

https://gist.github.com/ShyLionTjmn/d8b689677882170689c5481d019aa3fb

notice line starting with YUlRNbEU1YTFCWGQyb - that's the "header" nginx complains about:

```
2021/07/30 17:32:54 [error] 21157#21157: *528 upstream sent too big header while reading response header from upstream, client: 10.96.147.253, server: _, request: "GET /auth/Ni0rXrZMqIVEBjGr6rgKftTH8RPz6F/?state=Ni0rXrZMqIVEBjGr6rgKftTH8RPz6F&session_state=9b0a7a8d-dd55-40d6-a210-928ae21a2de2&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..kXFIv4JZnFa-cteRP-2C9A.woiZwudqWhimXKffvPILCiD35_y0Dgll1FUZPejK6O82BLSw7q4lxo_0_hRjxk06BbIlXHEwLMlf10d9bTWcIA8khsqDXV9J0S3X3Mf1ELig11k6Ok5ohwfSe9gzmZ1aAHcFXxw_UB1g7HLELpVto19upVpZjaHzRpY6nhQTx-pw8bYwT7vVxBiAc5jHrBwkpPMhwD_P1niGTz2jyirsxq2iWs3knc6EnePzLu4I9XwbdDlJoQvQjx3avaQMHzFv.V-wX9fOtYiHX4ADaJGkLdg HTTP/1.1", upstream: "http://127.0.0.1:9090/auth/Ni0rXrZMqIVEBjGr6rgKftTH8RPz6F/?state=Ni0rXrZMqIVEBjGr6rgKftTH8RPz6F&session_state=9b0a7a8d-dd55-40d6-a210-928ae21a2de2&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..kXFIv4JZnFa-cteRP-2C9A.woiZwudqWhimXKffvPILCiD35_y0Dgll1FUZPejK6O82BLSw7q4lxo_0_hRjxk06BbIlXHEwLMlf10d9bTWcIA8khsqDXV9J0S3X3Mf1ELig11k6Ok5ohwfSe9gzmZ1aAHcFXxw_UB1g7HLELpVto19upVpZjaHzRpY6nhQTx-pw8bYwT7vVxBiAc5jHrBwkpPMhwD_P1niGTz2jyirsxq2iWs3knc6EnePzLu4I9XwbdDlJoQvQjx3avaQMHzFv.V-wX9fOtYiHX4ADaJGkLdg", host: "10.96.37.249"
```

**Comment by ShyLionTjmn** [comment]
Also, have you considered about using redis for session storage and shorter cookies?

**Comment by ShyLionTjmn** [comment]
If i remove groups claim from headers  in vp config - it works fine

**Comment by bnfinet** [comment]
> Also, have you considered about using redis for session storage and shorter cookies?
Yes we have.  That would impact scalability. Search the tickets for related discussion.

@ShyLionTjmn please provide your entire nginx config's server block

Have you read this?  Specifically the nginx config parts.
https://github.com/vouch/vouch-proxy#scopes-and-claims

@ShyLionTjmn please adjust your VP config and produce logs in the manner described in the README.  
https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests-read-this-before-submitting-an-issue-at-github

**Comment by bnfinet** [comment]
@ShyLionTjmn are you still working this issue?  Could you please close it if you are not.
