### ISSUE TITLE
400 Bad Request when redirected from URL with another URL in its parameters

### ISSUE THREAD

**Issue by darkphoenix** [vouch/vouch-proxy#409]
Occasionally (when following links, or reauthenticating after a timeout), there are URLs with parameters in the query string.  Currently nginx just leaves all that as it is when generating the /login URL with the current example config, and that leads to a 400 Bad Request error.  I'm not entirely sure how to fix it, as Vouch also doesn't seem to like it when I try to for example urlencode the ? as %3F, so maybe this needs to be fixed in Vouch itself?  I'm kind of clueless as to the inner workings here, but the end result is it just doesn't work for these URLs, which is an annoyance because it breaks the nice and transparent "if you have an IdP session, it'll just work" I normally have thanks to Vouch.

Update: it appears to be specific to parameters containing urlencode'd things already - I originally hit this issue specifically for an application that uses multiple parameters that have URLs in them that are encoded.  It appears to work fine once those parameters are removed, so Vouch does seem to correctly distinguish between the URL including parameters and its own parameters after it.

Update 2: after further testing it appears the issue indeed only appears when there is specifically another URL in the query parameters (whether or not it is encoded).

**Comment by bnfinet** [comment]
@darkphoenix thanks for the report.

This is as intended as a security feature.  There's a note in the README regarding URL chaining for `/login`.

See [/login and /logout endpoint redirection](https://github.com/vouch/vouch-proxy#login-and-logout-endpoint-redirection)

**Comment by darkphoenix** [comment]
Thanks for answering that - it took me a while to figure this out, I initially assumed it was a general issue with arguments in the redirect URL.  I don't suppose there's an option to exempt specific URLs from this or anything?

**Comment by bnfinet** [comment]
@darkphoenix could you elaborate a bit on your setup?  Is there a specific app you're protecting that is referencing other URLs?  Are you chaining proxies together?

> I don't suppose there's an option to exempt specific URLs from this or anything?

Unfortunately there is not an allow list for `/login` urls.  Perhaps we could add that but you're the first to ask for such a feature.

**Comment by darkphoenix** [comment]
It's a bit of an odd situation, with a HomeAssistant instance in "trusted networks" mode, where this appears to break the login flow for apps.  I'm trying to get a workaround by stripping out parameters in the 401 request (using $uri instead of $request_uri), authenticating, then retrying the request, but something still isn't quite right.  I realise this is an incredibly specific situation with a lot of factors that aren't exactly normal, but that's what I'm trying to get working, as I use Vouch to power an auth gateway to access local services securely over the internet.
