### ISSUE TITLE
Whitelist file for Allowed email addresses

### ISSUE THREAD

**Issue by erdemozor** [vouch/vouch-proxy#412]
Hello there,
I was wondering if there is a way to have a seperate file for writing the email whitelist to?
I'm using google as a provider. 
Just a file instead of editing the config file to add allowed emails (someone@example.com).

Happily waiting replies :).

**Comment by bnfinet** [comment]
@erdemozor thanks for opening this issue

There is not a way to do that out of the box but it shouldn't be too difficult to build a configuration and restart VP...

Take a look at this gist for one example...
https://gist.github.com/bnfinet/f77f4ff1cc48b88897e524c05f136fbd

**Comment by erdemozor** [comment]
This is really helpful, Thanks.

Perhaps this could be implemented natively in the future? Definitely possible to do it this way but I think if there was a config argument for setting a path to a whitelist file it would be a nice quality of life feature.

Vouch could also periodically check this file for any changes but I think a manual restart is enough.
Thanks for considering this feature.

**Comment by bnfinet** [comment]
> This is really helpful, Thanks.

You're very welcome.

> Perhaps this could be implemented natively in the future? Definitely possible to do it this way but I think if there was a config argument for setting a path to a whitelist file it would be a nice quality of life feature.

How many email addresses are you managing?  Are you using Ansible or any other configuration management tool?  Is this developer convenience you're addressing?  What problem are you experiencing?

I'm expecting at some point we'll be moving away from `WhiteList/AllowList` for something fancier which accommodates other claims and maybe something along the lines of ACL or RBAC.  Even so, I'm not sure using an external file solves a real problem.  The VP config is not overly long IMHO such that it needs to be split up.  When it does, perhaps an `include` directive or scanning a `vouch.conf.d` directory feels a bit cleaner and clearer overall.

You could put all the addresses into the `VOUCH_WHITELIST` environmental variable.  That might be a bit closer to what you're looking for.

**Comment by bnfinet** [comment]
@erdemozor if you care to continue the conversation then please do chime in.  I'm going to close this and assume that the prior solution is worthwhile.
