### ISSUE TITLE
How to authorize user using username OR sub claim instead of email address

### ISSUE THREAD

**Issue by cpatel-secureauth** [vouch/vouch-proxy#413]
I have tested authentication successfully as Email which is within a Vouch Proxy managed domain.

To avoid below error , I was looking for something which I can authorize user using Username OR Sub claim.

{"level":"warn","ts":1629395919.9066803,"msg":"/auth User is not authorized: verifyUser: Email  is not within a Vouch Proxy managed domain

Is it possible?

**Comment by bnfinet** [comment]
@cpatel-secureauth that level of access control is not currently natively supported in Vouch Proxy.

There are some examples in #107 and other issues in the repository which show how to do it on the Nginx side with openresty.

**Comment by bnfinet** [comment]
@cpatel-secureauth feel free to continue the conversation here.  If it becomes evident there's more to discuss I'm happy to reopen the issue.

**Comment by bnfinet** [comment]
#175 is a very similar request

**Comment by cpatel-secureauth** [comment]
@bnfinet It is working as expected. I didn't see #367 before and I am glad that I was able to figure out my self.
Yes I did checked and #367 and and similar thing I was trying in structs.go by define Username as Sub claim as per below. 

// PrepareUserData implement PersonalData interface
func (u *User) PrepareUserData() {
	if u.Username == "" {
		u.Username = u.Sub
	}
}
