### ISSUE TITLE
Azure AD doesn't seem to autodiscover UserInfoURL.

### ISSUE THREAD

**Issue by fkelava** [vouch/vouch-proxy#417]
**Describe the problem**

The Azure AD provider does not seem to autodetect the UserInfoURL, although there is a known way to do this. The default config for Azure AD does not contain a ``user_info_url`` field, further making me believe it's intended for it to automatically find out. However, I haven't found a configuration in which that succeeds.

Nginx configs, Vouch ``bug_report`` output here. https://pastebin.com/k1St1erf

**Expected behavior**

Since the bare minimum config does not seem to require ``user_info_url`` and there is a known way to autodetect it, it should be autodetected for the Azure provider. See https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo.

Of course, maybe this is already done and I have misconfigured Vouch or Nginx. Please advise if you spot any mistakes in the configuration - it is all too likely one exists and may be causing this.

**Desktop (please complete the following information):**
 - OS: Windows 11 (22449)
 - Browser: Edge
 - Version: 93.0.961.38

Vouch/Nginx host:
- OS: Debian 10

**Additional context**
I'm probably at fault here, but I'm not getting how. Hardcoding the current AAD user info URL works great.

**Comment by bnfinet** [comment]
You're very right, `provider: azure` does not seem to provide a default `oauth.user_info_url` and the code does seem to want it to be configured.

VP does not currently have OIDC discovery facilities: #41 

There is this note, which would imply that the `oauth.user_info_url` is not used.
https://github.com/vouch/vouch-proxy/blob/master/pkg/providers/azure/azure.go#L44-L46

Perhaps this block should be updated to include `Provider.Azure`
https://github.com/vouch/vouch-proxy/blob/master/pkg/cfg/oauth.go#L140-L142

**Comment by bnfinet** [comment]
@fkelava does it work if you add a dummy entry (anything) to `oauth.user_info_url`?

**Comment by fkelava** [comment]
@bnfinet Bafflingly enough, yes, I am getting a functional result by simply including ``user_info_url = anything`` in the configuration. Even if it's not the correct URL as of the time of writing (that would be https://graph.microsoft.com/oidc/userinfo), it functions. 

However, if the entry is commented out, Vouch will fail to start.

I do not see the point in actually determining the proper URI at runtime because the relevant MSDN article states that the ID token given by Azure provides a superset of information from the UserInfo endpoint. See https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo#consider-use-an-id-token-instead.

I'm assuming doing ``azure_token = id_token`` accomplishes this. In which case adding Azure to that block is warranted.

However, in case this were to change (and in the name of OIDC standards compliance), it may be worth marking this a partial fix in case Microsoft reverse their behavior and do require us to find the UserInfo endpoint at some point in the future.

**Comment by bnfinet** [comment]
@fkelava thanks for the PR, I'm not in a position to merge but will do so in the coming days

> However, in case this were to change (and in the name of OIDC standards compliance), it may be worth marking this a partial fix in case Microsoft reverse their behavior and do require us to use the UserInfo endpoint at some point in the future.

If they were to become OIDC compliant I'd hope we could just use `oauth.provider: oidc`

**Comment by bnfinet** [comment]
@fkelava merged!  thanks again
