### ISSUE TITLE
Restricting access based on userinfo parameter

### ISSUE THREAD

**Issue by rml596** [vouch/vouch-proxy#419]
[config file](https://paste.gg/p/anonymous/ed96b92f263a450fb7b285ed4ea8ceb7)

I am using a company hosted OIDC system. In the userinfo body, the issuer sends a list of group names. I'd like to restrict login to a specific group. For example, `site1-admin`.
[userinfo example](https://paste.gg/p/anonymous/77db633a1c6a45199411a2948c1b4dee)

**Expected behavior**
If users are not a member of x group, they be given a invalid login page.

I am not sure if my configuration is incorrect or if this is not something that can be done by vouch and needs to be done by OpenResty.

**Comment by bnfinet** [comment]
@rml596 yes that's right, the way to do that is to use OpenResty along with the claims http heasds.  See `config/config.yml_example` and the README

If there's any improvements to the documentation that you feel would be helpful I hope you would considering offering a PR.

**Comment by bnfinet** [comment]
@rml596 I should have offered that `oauth.provider: github` does currently offer restriction by group as configured by [vouch.teamWhitelist](https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L57-L60) however this has not been developed for any other provider such as OIDC.

**Comment by rml596** [comment]
Yeah, unfortunately I was not using Github. I was able to get it successfully working using OpenResty using your documentation. This is an awesome project. Thanks for all the work!

**Comment by bnfinet** [comment]
@rml596 thanks for the kind words, I'm glad that it's working well for you!
