### ISSUE TITLE
[question] Customize templates in case of error

### ISSUE THREAD

**Issue by sp-manuel-jurado** [vouch/vouch-proxy#420]
Hi,
congratulations on the vouch proxy, it is a very useful tool.

I would have a question.
I would like to be able to customize the templates in case of error:

- /templates/auth.tmpl
- /templates/index.tmpl
- /templates/error.tmpl

I have the vouch proxy running in Kubernetes. Using your image from `quay.io/vouch/vouch-proxy`.
So I had thought to overwrite the custom templates in the filesystem, using a ConfigMap and Volume in `${VOUCH_ROOT}/templates/`.

But checking closed issues and merged PRs I see that you're using `go:embed` for embedding files related to templates into the application binary at compile-time: https://github.com/vouch/vouch-proxy/pull/398.

I understand that in order to overwrite these templates, I would have to modify the files and compile the application, so I could no longer use your image with the binary already compiled as a base.

Is this correct or is it possible to carry out a workaround to overwrite templates in runtime?

Thanks in advance.

**Comment by bnfinet** [comment]
@sp-manuel-jurado thanks for the kind words

> I understand that in order to overwrite these templates, I would have to modify the files and compile the application, so I could no longer use your image with the binary already compiled as a base.

Yes that's correct.  There is no facility to substitute templates at runtime.  Custom templates will require you to modify the templates in the git tree and compile from source.  Or build a docker image from source.

Please run `./do.sh` for information on how to do that.

**Comment by Shogobg** [comment]
Are there any plans to make these page customizable?

**Comment by bnfinet** [comment]
@nicornk thanks for the kind offer but that's already been discussed here.  If you'd like to customize those templates your best bet is to carry a fork.
