### ISSUE TITLE
Resiliency Question

### ISSUE THREAD

**Issue by tjschuler** [vouch/vouch-proxy#425]
Is it possible to have multiple vouch instances running behind a load balancer for resiliency? 

Not sure if the JWT issued in the cookie by the first vouch instance would be valid when the second instance evaluates it. 

Is there any documentation covering resiliency for vouch-proxy?

**Comment by bnfinet** [comment]
Yes, provided they share the same secrets either set in 'vouch.jwt.secret' or '/config/secret'.  May need to share 'vouch.session.secret' as well.

> Is there any documentation covering resiliency for vouch-proxy?

Not specifically, but the intention has been to carry no state information other than the secrets in VP.  All state is stored in the browser's cookies.  It should scale horizontally quite well.

**Comment by bnfinet** [comment]
@tjschuler if you cared to provide any documentation of your setup I'd be happy to link to it from the README like three others that are there.  If you'd like to offer documentation as a contribution to this repo in '/examples' that would be most welcome.
