### ISSUE TITLE
nginx problem with really big tokens

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#426]
Just run into trouble when one user works just fine and another user get 501 error after successful login.
nginx puts "upstream sent too big header while reading response header from upstream" into error log.

After hours of debugging, i found the reason - my keycloak returns "groups" claim with tokens and for one user list is short, and for another user this list is pretty large - about 30 groups, and this user gets 501 error.

Removing groups claim or dropping some groups for user (not acceptable in production) helps.

I tried this settings in nginx config, but it didn't help:

proxy_buffers 16 1024k;
proxy_busy_buffers_size 2048k;

large_client_header_buffers 16 1024k;
client_header_buffer_size 128k;

Looks like auth_request mechanism does not honor this settings and have some hard limit around 4K.
Error happens when GET /vouch/auth/..../?state=... request comes and vouch-proxy returns over 4K bytes in headers, combined.

vouch-proxy spews no errors.

Any thoughts?

**Comment by bnfinet** [comment]
Did you set proxy_buffer_size?

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size

If that doesn't work, please provide all logs and config as per the README.

**Comment by bnfinet** [comment]
This is similar to your original issue #405

**Comment by ShyLionTjmn** [comment]
> Did you set proxy_buffer_size?

Thanks, that's what i needed!
