### ISSUE TITLE
Passing original JWT through as a header

### ISSUE THREAD

**Issue by mikebryant** [vouch/vouch-proxy#43]
Would it be possible to pass the original JWT (from the openid provider) back as a header from the validate request?

I'm trying to use nginx/lasso in front of the istio gateway, and if I could use lasso to do the openid redirection and pass on the jwt to istio, I could then use istio authorization.

**Comment by mikebryant** [comment]
Alternatively, copying the claims, in particular `groups`, from the original JWT into the lasso jwt and providing an endpoint to get the lasso public key would be reasonable

**Comment by simongottschlag** [comment]
Hi,

I need this together with ADFS (to pass the authorization header to kubernetes dashboard) and created a PR which seems to be working OK together with ADFS:
https://github.com/vouch/vouch-proxy/pull/71

**Comment by artagel** [comment]
I'm working on a branch that will allow users to choose which claims they want to send through as headers to the downstream server in a proxy_pass.
I'm also working on additional functionality to allow users to specifically specify 'groups' they want to allow for specific domains, as I've found just passing groups to nginx and then trying to parse for access is problematic.

**Comment by bnfinet** [comment]
What's an example of a group?

**Comment by artagel** [comment]
In many cases claims can be provided for group membership, such as ldap or active directory group memberships.  This would allow an admin to either send the groups down to the application as a header, or allow them to only allow access to an application of a user is a member of the correct group.

**Comment by pcaro** [comment]
+1
