### ISSUE TITLE
infinite redirect, cookie not stored, domain issue

### ISSUE THREAD

**Issue by deadbeef-development** [vouch/vouch-proxy#433]
✔️ **First read the README**
Specifically ***[Troubleshooting, Support and Feature Requests](https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests)***.

And turn on `vouch.testing` before you ask for support.

✔️ **Use a Paste Service**
https://gist.github.com/deadbeef-development/3e6aad3efbf8d71b6e752c7df02148c9

✔️ **Describe the problem**
While going through a flow, I get to a "400 Bad Request" with the following text:
```
For support, please contact your network administrator or whomever configured Nginx to use Vouch Proxy.

For help with Vouch Proxy or to file a bug report, please visit https://github.com/vouch/vouch-proxy 
```

Looking at the logs, the first thing that stood out to me (after the final `/login` step) was `WARN    no destination URL requested`. Looking a little further up, I see `deleting cookie: VouchCookie`.

✔️ **Expected behavior**
I expected the cookie to be stored, and `/login` would redirect me back to the home page. Future requests would be validated with the `auth_request /vouch-validate` directive.

✔️ **Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Browser: Firefox 92.0 (64-bit)

✔️ **Additional context**
My project is located [here](https://gitlab.com/dev-learning-group/users/deadbeef-development/angular-vouch-nginx-server
). The Nginx conf is located in the [nginx-server](https://gitlab.com/dev-learning-group/users/deadbeef-development/angular-vouch-nginx-server/-/tree/master/nginx-server) folder, and the VP configuration is located in the [files](https://gitlab.com/dev-learning-group/users/deadbeef-development/angular-vouch-nginx-server/-/tree/master/files) folder.

Thank you in advanced...

[nginx.conf](https://gitlab.com/dev-learning-group/users/deadbeef-development/angular-vouch-nginx-server/-/blob/master/nginx-server/nginx.conf)
[VP config.yml](https://gitlab.com/dev-learning-group/users/deadbeef-development/angular-vouch-nginx-server/-/blob/master/files/config.yml)

**Comment by bnfinet** [comment]
@deadbeef-development please do post fresh logs in the manner described by the README (two round trips and the other requests) and ensure that your configs are up to date

**Comment by deadbeef-development** [comment]
I pruned all my docker containers and even images (so it uses the latest `config.yml`). I ran it with the updated validate block to set the host header.

I made two trips this time and it seems for sure that it is an infinite redirect since it restarts the process/flow on the second try.

The log: https://gist.github.com/deadbeef-development/e6c21d22653d588308b6d01513152a1d

You may notice that there isn't much time between the OAuth departure and the `/auth/` return (~12 seconds), but that is because I logged in quickly, for my browser saved my account credentials.

Each of these flows that I am doing are done in a completely fresh incognito session (I closed all incognito windows before opening a new session in order to do a flow), so no cookies should be interfering.

Something I also noticed was that I keep declining to "stay signed in" at the Microsoft login page. I doubt that has to do with anything, but I think that it is still worth mentioning.

The only thing that stood out to me was `WARN    no User found in jwt`, and this was after getting to the `/auth/` URL.

I will try to slow this down even further by disabling `accessibility.blockautorefresh` in Firefox so I can check the cookies in `document.cookie` for `https://site.vouchtest1.ngrok.io/`.

**Comment by bnfinet** [comment]
@deadbeef-development glad to hear it's working

> I am getting CORS errors in the browser

There's some CORS related documentation linked to from the README or and info in the issues here.

Happy Vouching!
