### ISSUE TITLE
Containerized processes should not run as root 

### ISSUE THREAD

**Issue by mjobst-necls** [vouch/vouch-proxy#442]
**Describe the problem**
The process _vouch-proxy_ currently runs as user _root_ which is not recommended from a security perspective.
It is expected that vouch-proxy can run as a non-root user without limitations

**Expected behavior**
Run vouch-proxy as a non-root user

**Comment by apanzerj** [comment]
taking a stab myself https://github.com/vouch/vouch-proxy/pull/444

**Comment by bnfinet** [comment]
@apanzerj nice stuff!

We should consider the upgrade path.  I'd expect this change to require changes to the config permissions...

If someone has an existing `/config/secret` which was created by VP as  `root:root 0600` VP will bail  This may also be the case for `config/config.yml`

We should probably offer at least a `log.Warn()` which includes the URL of this issue along with an explanation.

**Comment by apanzerj** [comment]
Ooop! Just saw this comment. Reading

**Comment by apanzerj** [comment]
I'm not familiar with Go at all. I can leave this work here for somebody else to add to but I don't know where to toss the log.Warn.

**Comment by bnfinet** [comment]
@apanzerj thanks for your work on this PR!  It has been merged in `v0.36.0`
