### ISSUE TITLE
Why no new docker image since 0.27.1?

### ISSUE THREAD

**Issue by tomer-amir** [vouch/vouch-proxy#448]
I've been using vouch-proxy for a while now using the docker image `alpine-0.27.1`.
I wanted to upgrade now to get some of the latest features (like session `maxAge`) but it seems like there aren't no newer docker images on docker hub except for `latest`.

Is there a reason for it?

**Comment by bnfinet** [comment]
See #406 the README and the CHANGELOG.

Images have been moved to quay.io
