### ISSUE TITLE
Support or documentation for custom error pages (eg. 400, 401) instead of vouch-proxy rendered pages

### ISSUE THREAD

**Issue by nichogenius** [vouch/vouch-proxy#452]
I have a working setup utilizing nginx as a reverse proxy, vouch-proxy in a docker container, and keycloak in a docker container using OIDC.  When a user follows the normal login path, everything behaves as expected.  If the user does something unexpected, they land on the rendered Vouch Proxy error page instead of a custom error page or being redirected to the correct location.

Scenario 1 -

A user takes longer than the default 5 minute session timeout to login.  Upon being redirected back to vouch-proxy, their state code is no longer valid and Vouch Proxy renders an ambiguous 400 - Bad Request error.

I have attempted to handle this in nginx by setting a custom error page, but this does not work unless I enable proxy_intercept_errors in the nginx config.  This quickly created performance issues rendering the application unusable (or maybe I don't understand how to use it correctly).

Scenario 2 -

A user clicks 'Decline' on the terms and conditions page in Keycloak.  Keycloak redirects back to vouch-proxy with " /auth Error from IdP: access_denied -".  The response code is 401.

Ideally, I would like to set custom redirects or error pages instead of serving the vouch proxy error page.  Other than writing in an html redirect into the vouch-proxy code, is there a better alternative? Perhaps in the vouch-proxy config.yml or a trick that I am missing in the nginx config?

**Comment by nichogenius** [comment]
I feel like this could be solved by adding config options - something like
IDP_ACCESS_DENIED_REDIRECT_URL=https://myapp/login
BAD_REQUEST_REDIRECT_URL=https://myapp/login

**Comment by bnfinet** [comment]
see discussion in #420

The preferred method for customizing the error page is to fork the project and then build from source.

My thinking is that if you're at the point of wanting to customize the template and error page, why not fork?  `git` is a fantastic tool for managing bespoke changes.  This saves us from adding knobs to VP for templates or outside redirects.

**Comment by nichogenius** [comment]
Thanks for your help and quick response!

Given your advice, I think I can mount the templates via docker-compose  - though I might have to write my own Dockerfile so that it compiles the static content every time the VP container is started.  That would give me the flexibility I need.

Forking via version control isn't ideal for project maintenance - usually I reserve project forks for submitting pull requests as I prefer to have my applications anchored on the main fork for maintenance and security reasons (though perhaps this is a bit from an open source perspective)

Knobs aren't inherently bad if they add useful functionality.   SUPPRESS_VOUCH_ERRORS and AUTH_ERROR_REDIRECT_URL would be useful in my opinion.
