### ISSUE TITLE
Users with emails in domains not listed in vouch.domains can login

### ISSUE THREAD

**Issue by paulojmdias** [vouch/vouch-proxy#453]
**Config**

https://pastebin.com/PHxt9riF

**Describe the problem**

Issues and PR Related:
#199
#198

I'm using the provider Google and I have the following values in `vouch.domains`:
- dummy.com
- sub1.dummy.com
- sub2.dummy.com
- sub3.dummy.com
- sub4.dummy.com

However, isn't expected but a user with email `user@sub5.dummy.com` could log in without any issues since the main domain `dummy.com` is on `vouch.domains`.

Since we have emails in all domains listed in `vouch.domains`, we can't remove the main domain `dummy.com` from the list.

**Expected behavior**

Users with an email domain not listed in `vouch.domains` couldn't be allowed to log in.

**Comment by bnfinet** [comment]
@paulojmdias that is the expected behavior

`user@sub5.dummy.com` is in the domain `dummy.com`  If you'd like to not serve those users, then you'll need to drop `dummy.com` from you list of domains, or use `vouch.whitelist` to be explicit about who can come through.
