### ISSUE TITLE
transfer/fork vouch helm chart (Thank you Gavin for your years of support!!)

### ISSUE THREAD

**Issue by halkeye** [vouch/vouch-proxy#457]
👋 I think i'm shutting down my home k8s server and as such, kinda want to find owners for my helm charts. Are you willing to take it over? there's lots of github actions for publishing helm charts. Its been essentially no maintaince for a while now, but probably could get the version number updated more often.

**Comment by martina-if** [comment]
Hi 👋 , if no one else claims this @punkle and myself can keep an eye on it.

**Comment by halkeye** [comment]
👍 Its not like i'd abandon ya'll, but i don't want to be the responsible maintainer for something I'm not actively using

**Comment by halkeye** [comment]
https://github.com/halkeye-helm-charts/vouch/

Then something like https://helm.sh/docs/howto/chart_releaser_action/

That way vouch could also be a verified publisher on artifacthub.io

**Comment by bnfinet** [comment]
@halkeye thanks for holding down the VP helm chart these past years!  I hope I'll get a chance to buy you a beverage in person next time I'm in Vancouver.

I myself am not an active k8s user and only have a smattering of skill with charts and chart maintenance and as such am (still) not in a position to support a helm chart.

@martina-if thank you for such a kind offer. If you and @punkle and your colleagues at [roadie.io](https://roadie.io/) were able to support the VP helm chart that would be wonderful.

When folks have offered code to VP which includes a major feature addition or a new platform I've asked if they could commit to supporting the work "for at least two years".  That seems like a reasonable ask for this as well.  I'd hate to have to work through another transition sooner than that.  How's that sound to you @martina-if? 

I'd be happy to fork Gavin's repo to https://github.com/vouch/vouch-proxy-helm-charts or such and setup a gh team which has authority over that repo and include all of you on that.

**Comment by halkeye** [comment]
> I'd be happy to fork Gavin's repo to https://github.com/vouch/vouch-proxy-helm-charts or such and setup a gh team which has authority over that repo and include all of you on that.

typically I've seen the repo called "helm-charts" with a directory called charts.

ex https://github.com/jenkinsci/helm-charts/

**Comment by bnfinet** [comment]
@martina-if @punkle How's that all sound to you?

**Comment by punkle** [comment]
Yes that all sounds good. Would you like to setup the repo and we can take care of the rest of how would you like to take care of it?

**Comment by halkeye** [comment]
Do you want to add me the org and I just transfer the repo? that will mean that if anyone comes to the repo (old link or something) it'll get auto redirected?

Otherwise ya'll can fork and I can update the readme.

Also, i'm looking into renovate to automate updates to my matrix helm charts, so I should be able to have that ready soon if you want to wait a day or two.

**Comment by martina-if** [comment]
Hi @bnfinet, @halkeye , asking for 2 years of commitment is a very reasonable thing to do but we discussed this internally and we believe it wouldn't be fair to commit to more than 1 year since since we are a startup and things change quickly for us (including changing our architecture). What do you think about that?

We are also happy if someone else wants to take this and we help out sometimes.

Regarding the repo in https://github.com/vouch/vouch-proxy-helm-charts that sounds good to me.

**Comment by bnfinet** [comment]
@martina-if sure that's fine.  Thanks for taking it on.

@halkeye @punkle @martina-if I've invited you all to to a new team `helm-charts`
https://github.com/orgs/vouch/teams/helm-charts/member

**Comment by bnfinet** [comment]
@halkeye do let me know if you need additional permissions or some other change in order to transfer the repo

**Comment by halkeye** [comment]
https://github.com/vouch/vouch-helm-chart is moved over
(anyone in an org can transfer things into an org)
I had to rename it because I didn't want it to be called vouch/vouch
Its up to you now, permissions, nameing, etc

I'm working on a renovate.json for helm charts, but not having super luck yet, but I should have enough to open a bug with them now.

**Comment by bnfinet** [comment]
@halkeye thanks!

as per previous discussion I think next steps are to..
* rename the repo to `vouch/helm-charts` and then
* move everything into  `charts/vouch-proxy` similar to https://github.com/jenkinsci/helm-charts/

does that sound right?

**Comment by halkeye** [comment]
> move everything into `charts/vouch-proxy` similar to https://github.com/jenkinsci/helm-charts/

Assuming that's required for the github actions? I've never used them so can't say.

Probably worth submitting to https://artifacthub.io/ once the action is all setup

**Comment by punkle** [comment]
I have a bit of time this after noon so I am going to see what I can do around

- renaming the repo
- moving the code under the charts directory
- and publish it to artifact hub

**Comment by punkle** [comment]
Ive started doing those bits: https://github.com/vouch/vouch-helm-chart/pull/18, and https://github.com/vouch/vouch-proxy/pull/463

Working on the publish step.

**Comment by punkle** [comment]
I do not have the ability to rename the repo @bnfinet, would you mind taking care of the repo rename?

**Comment by bnfinet** [comment]
@punkle done!

https://github.com/vouch/helm-charts

Let me know if there's anything else I can help with.

**Comment by punkle** [comment]
@bnfinet there are a couple of other bits I will need.

- The GitHub actions do not appear to be running on the helm-charts repo.
- Would it be possible to configure GitHub pages on a branch called gh-pages on the helm-charts repo?
- Also I am unsure if myself and Martina have the ability to merge changes to the repository.

**Comment by bnfinet** [comment]
@punkle see this comment WRT membership..
https://github.com/vouch/helm-charts/pull/18#issuecomment-1051186723

I hope that resolves the access issues.

**Comment by punkle** [comment]
I was able to do everything I needed to do. Thanks @bnfinet

**Comment by bnfinet** [comment]
glad it worked @punkle 

Thanks again!

**Comment by bnfinet** [comment]
@punkle @martina-if (and @halkeye too) I adjusted the portion of the README a few days back that links to `vouch/helm-charts`. (in #457)

https://github.com/vouch/vouch-proxy#kubernetes-nginx-ingress

If there's any change you'd like there (perhaps mentioning / linking to @roadieHQ ??) please do feel free to adjust to your liking.

And same of course with the README for https://github.com/vouch/helm-charts

Please be sure to take the credit that you deserve!
