### ISSUE TITLE
Multiple providers?

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#460]
Am i missing something, or there is no support for multiple providers?

**Comment by ShyLionTjmn** [comment]
iss claim should be available if there is multiple providers support.

unique user id is sub and iss combination

**Comment by bnfinet** [comment]
@ShyLionTjmn correct!

**Comment by ShyLionTjmn** [comment]
I've chained vouch-proxy with Keycloak.
Now i can connect many Social networks, AD, or even local database.
