### ISSUE TITLE
Vouch in a path with keycloak initial login error

### ISSUE THREAD

**Issue by bedaronco** [vouch/vouch-proxy#461]
[Log and config files](https://gist.github.com/bedaronco/aa429fd003f3ff91abf91672945d1c44)

I currently have vouch configured in a path and using keycloak as my OIDC.  Nginx is correctly protecting certain paths of my site and redirecting to login.  The issue is that the initial login doesn't seem to be correctly setting the cookie for some reason.  

If I turn testing on it doesn't have this problem.  I can click each new link and everything works great.  If I turn testing off then as soon as  I login I get an error in the log:  `/auth Invalid session state: stored %!s(<nil>), returned GQaqXVDKs1vGeIJyCKgrXU3rXu0Jb5R`

Once I get that error I can immediately go to the navigation bar in my browser and press enter.  I don't have to login and I have access to the protected area of my site. 

I've tried setting cookie secure to false but that didn't do anything.  I added cookie sameSite to lax, but that didn't change anything either.

The log file in the gist above contains the following flow: 

1. Launch vouch via containers
2. Access a protected area of the site
2. Redirect to login through keycloak
3. successful login, error page shown from vouch
4. Click in browser address bar and press enter 
5. Protected documented is displayed

Any help would be greatly appreciated.

**Expected behavior**
Initial, successful login should not result in error.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome and Firefox
 - latest versions

**Comment by bedaronco** [comment]
Since my authentication server is running in a different domain, setting `cookie: sameSite: none` seems to have fixed this problem.

**Comment by bnfinet** [comment]
@bedaronco that's great, I'm going to close this but do let me know if there's anything further to resolve

**Comment by Anefu** [comment]
I'm trying to use vouch with keycloak using the same config as above, but anytime I try to reach the application endpoint, I get redirected to vouch endpoint, and that throws a 400 error

**Comment by bnfinet** [comment]
@Anefu please do consult the README and open a new issue as described..
https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests-read-this-before-submitting-an-issue-at-github

I'm happy to help but it's impossible to understand what's going on without that information
