### ISSUE TITLE
Multiple providers

### ISSUE THREAD

**Issue by prawnsalad** [vouch/vouch-proxy#464]
**First read the README**
- The link in the issue template no longer works. But I have read the readme.

Are there any plans to support multiple providers? My app has multiple tenants and I would need to support different providers for each tenant. Running multiple instances of vouch would technically be possible but not really feasible when there are many providers to be used (100+ in this case).

**Comment by bnfinet** [comment]
@prawnsalad no there is no plan at this point to support multiple providers.  When we've visited this in the past we always point at the fact that running multiple vouch-proxy instances is pretty cheap resource wise, though usually that's with just a handful of providers.

I'm curious what service you're providing that requires such a broad identity domain.  Could you expand on your use case a bit more?

**Comment by prawnsalad** [comment]
@bnfinet in my case each tenant can use an idp of their choosing, so tenant1 may use okta while tenant2 may use azure, etc. If each tenant uses iodc/okta for example, then as far as I understand I would need a vouch instance for each tenant to support different client id/secrets.

**Comment by bnfinet** [comment]
@prawnsalad thanks for offering a bit more info.

Yes that's correct, each would need to be separate.

For that specific use case you'd want to make sure to use a separate secret for each "tenant" as well.  That's best handled with a separate instance of VP.

I'm going to close this but feel free to continue the thread.  By my reckoning for most users a separate VP instance per IdP is the way to go.
