### ISSUE TITLE
cannot load embed while compiling

### ISSUE THREAD

**Issue by ridvankaratas** [vouch/vouch-proxy#465]
hi,

I wanted to compile the source via ./do.sh goget and I got this error:

> build github.com/vouch/vouch-proxy: cannot load embed: malformed module path "embed": missing dot in first path element

when I want to ./do.sh build, it doesn't just run and it gives some flags to use

is it possible to get a compiled binary?

**Comment by dco5000** [comment]
I also am unable to install and config on ubuntu.  I get same message about the malformed "embed". Please suggest a work around.

**Comment by bnfinet** [comment]
a quick search reveals this.. https://github.com/pjvds/tunl/issues/5#issuecomment-784894010

**Comment by ridvankaratas** [comment]
hello. thank you for the quick response. using go 1.16 solved goget issue. on the other hand, as I explained in the initial post, build command is not running as expected (I think)

` ./do.sh build
error: unknown option `sort=v:refname'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>]
		[<pattern>...]
   or: git tag -v <tagname>...

    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags

Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns

Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object

get "google.golang.org/protobuf": found meta tag vcs.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at //google.golang.org/protobuf?go-get=1
go: cloud.google.com/go@v0.89.0 requires
	google.golang.org/grpc@v1.39.0 requires
	google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/a6c5d6b8734f41936247415390043c979295646fadef73c39eedc1735cd0fef4: exit status 128:
	fatal: git fetch-pack: expected shallow list`

therefore, there is no vouch binary

**Comment by bnfinet** [comment]
@ridvankaratas what operating environment are you using?

Did you search for that error?  What did you find?

Try `go build .`

**Comment by ridvankaratas** [comment]
I found this that I thought might be relevant https://github.com/golang/go/issues/34266
I'm on Centos7 with go version go1.16.13 linux/amd64

**Comment by bnfinet** [comment]
@ridvankaratas did you try..

`go build .`

What happened?

**Comment by ridvankaratas** [comment]
hi, adding output from go build command

> go build
> go: cloud.google.com/go@v0.89.0 requires
> 	google.golang.org/grpc@v1.39.0 requires
> 	google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
> 	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/a6c5d6b8734f41936247415390043c979295646fadef73c39eedc1735cd0fef4: exit status 128:
> 	fatal: git fetch-pack: expected shallow list

**Comment by bnfinet** [comment]
This one seems a bit closer when searching for

"exit status 128: fatal: git fetch-pack: expected shallow list"

https://github.com/golang/go/issues/38373

There appears to be something wrong with the setup of either go or git or both in your operating environment.  Are you able to build other golang programs?

**Comment by ridvankaratas** [comment]
I removed go1.16 and installed go1.18 
goget and build worked without any issue. also vouch-proxy is running (at least it shows running I haven't tested anything yet)

we won't know whether it was related to go1.16 or go1.16 setup itself. bu we do know go1.18 works at least for the compile.ü

again thank you for the quick response.

**Comment by bnfinet** [comment]
@ridvankaratas glad to hear VP is working.  Thanks for the kind words.

@dco5000 I'm going to close this but feel free to continue the thread if you're still having problems
