### ISSUE TITLE
Add explanations about use of SameSite=strict to documentation

### ISSUE THREAD

**Issue by simonwgill** [vouch/vouch-proxy#470]
**Describe the problem**
I had a setup using the GitHub provider which would return a 400 Bad Request after the redirect from github to `/auth/{state}`. This did not happen when using the links provided by the testing mode.

I eventually narrowed this down to the fact I was using a server level `proxy_cookie_flags ~ httponly secure samesite=strict;` in my nginx config to prevent XSS attacks. Unfortunately, it's been long enough now that I don't remember why I did it.

Removing samesite=strict and letting it default to lax dealt with the problem.

**Expected behavior**
It would be very helpful to have a few lines in the documentation for the `vouch.cookie` parameters explaining when you might use them, when you shouldn't use them and why it matters.

**Comment by simonwgill** [comment]
I have been trying to set up a failing version of this today.

However, over http, the setup works flawlessly even when I would expect it to fail. Unfortunately, I've run out of time to try it over https before the long weekend.

What I can give you for now is the specific log message I was getting hit with from https://github.com/vouch/vouch-proxy/blob/5e819a06b26a0683d01440bb1e4b34a506a29f60/handlers/auth.go#L67

```
/auth Invalid session state: stored %!s(<nil>), returned bcd4kV8zoRIOQdQOC8HkXyfy9h0IYF
```

```
10.145.30.86 - - [13/Apr/2022:08:59:54 +0000] "GET /auth/bcd4kV8zoRIOQdQOC8HkXyfy9h0IYF/?code=a3ec9509f388f131b0c4&state=bcd4kV8zoRIOQdQOC8HkXyfy9h0IYF HTTP/1.1" 400 1167 "https://github.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36"
10.145.31.160 - - [13/Apr/2022:08:59:54 +0000] "GET /auth?code=a3ec9509f388f131b0c4&state=bcd4kV8zoRIOQdQOC8HkXyfy9h0IYF HTTP/1.1" 302 127 "https://github.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36"
```

I know this isn't much help right now - but I'll get back onto reproducing this on Tuesday

**Comment by bnfinet** [comment]
Thanks @simonwgill 

It'll be helpful to see your configurations and having a better understanding of the domains you're protecting with VP and how the session and VP cookies are held.

Enjoy the weekend!  It may take a moment to respond next week as I will be engaged to another project.

**Comment by bnfinet** [comment]
@simonwgill are you still working this issue?  I'd love to get a look at your configs and setup.

**Comment by bnfinet** [comment]
@simonwgill I've closed the issue but feel free to continue the thread if you like
