### ISSUE TITLE
Special characters in URL throw "Not a valid login URL: requested destination URL appears to be invalid parse" / invalid URL escape

### ISSUE THREAD

**Issue by mig5** [vouch/vouch-proxy#472]
**Describe the problem**

A user clicked a link to a website that is behind Vouch.

The URL was

```
https://wiki.example.com/wiki/%@!_people_say
```

The entire https://wiki.example.com site is behind Vouch (e.g not just this URL), but the link was to a specific page on the site. The user was not already authenticated via Vouch/the IDP.

The Vouch auth flow began but the user experienced a 400 HTTP error from Vouch. The underlying log entries were:

```
{"level":"info","ts":1649689946.215489,"msg":"|401|  130.912µs /validate","statusCode":401,"request":8201,"latency":0.000130912,"avgLatency":0.00065375,"ipPort":"172.17.0.1:52
786","method":"GET","host":"vouch.example.com","path":"/validate","referer":""}
{"level":"warn","ts":1649689946.4029076,"msg":"Not a valid login URL: requested destination URL appears to be invalid parse \"https://wiki.example.com/wiki/%@!_people_say\": invalid URL escape \"%@!\""}
{"level":"info","ts":1649689946.4031806,"msg":"|400|  345.021µs /login","statusCode":400,"request":8202,"latency":0.000345021,"avgLatency":0.000653713,"ipPort":"172.17.0.1:52790","method":"GET","host":"vouch.example.com","path":"/login","referer":""}
```

Going to the https://wiki.example.com site itself and completing the auth flow works fine, then the user is able to navigate to the destination page as desired, without problem. Just not if it forms part of the login flow.

**Expected behavior**

The special characters should ideally be handled somehow so as not to break the auth flow.

**Version information**
 - OS (of user who experienced the issue): Mac OS
 - Firefox (unsure of version, probably 100)
 - Vouch: 0.37.0 running via Docker-compose on Debian 11, nginx/1.18.0 as reverse proxy

**Comment by bnfinet** [comment]
@mig5 thanks for the report

This is essentially a style choice of GoLang, enforcing a strict interpretation of special character encoding using '%'
https://github.com/golang/go/issues/29808

This explanation is succinct.. 
https://github.com/golang/go/issues/29808#issuecomment-455592457

Which wiki software is it?  Technically the error is theirs.

**Comment by mig5** [comment]
@bnfinet ahh, thanks for the explanation. That makes perfect sense.

The software is Mediawiki, same as that that runs Wikipedia. Indeed I guess it ought to encode `%` as `%25`.

Sorry for the noise!

**Comment by bnfinet** [comment]
@mig5 that's not noise, that's a problem you're facing :)

There may be some way to handle it at the nginx level as that URL gets passed to the `/login?url=$URL` endpoint

As a bit of a hack for https://wiki.example.com/ you could set the `302` directive for VP to always point at one URL.  I know that means your users lose where they were trying to go but it will clean up the login flow.  You may be able to set that up for this specific URL in Nginx.

**Comment by mig5** [comment]
@bnfinet thanks! That's a good idea.

Actually it's interesting as I just realized that the same problem still occurs even if the param was encoded in the browser request:

https://vouch.example.com/login?url=https://wiki.example.com/wiki/%25@!_people_say&vouch-failcount=&X-Vouch-Token=&error= 

^ still threw a 400 with the same message, but the message shows the `%25` has become `%` again. Presumably Nginx is decoding it before passing it to Vouch, interesting..
