### ISSUE TITLE
how to get the email stored in the x-vouch-user header as a variable in my app?

### ISSUE THREAD

**Issue by brokeDude2901** [vouch/vouch-proxy#476]
My case:
mysite.com:9090/vouch_proxy_path
mysite.com:8443 (java 8 dropwizard backend)

Expected flow:
step1. vouch-proxy Google login success 
step2. send POST request to mysite.com:8443/register
 to create a new $username as vouch-proxy Google email and generate $password, then store in server file user.json
step3. user now able to speak to server via HTTP authorization header 

Problem is i dont know how to get Google email as variable in step2. Any help would be nice :)

**Comment by bnfinet** [comment]
Here's how to pass the `x-vouch-user` from NGINX which in the case of Google will hold the email..
https://github.com/vouch/vouch-proxy/issues/421#issuecomment-919520144

And this shows how to use it from a SPA / browser based request (XHR)..
https://github.com/vouch/vouch-proxy/issues/421#issuecomment-919520144
