### ISSUE TITLE
Build-time hostname detection fails on platforms other than Linux and FreeBSD

### ISSUE THREAD

**Issue by bahamat** [vouch/vouch-proxy#477]
Hello, first time contributor here.

Building on various platforms will result in `error: Could determine the fully qualified domain name using command hostname --fqdn`

The reason for this is that the `-s` flag isn't supported. There's already an exception for FreeBSD. Notably, SunOS (illumos, Solaris), and macOS (Darwin) both don't support the `-s` flag.

I propose (and am willing to do the work) to change the `_hostname` function in `do.sh` to only call `hostname` on all platforms, and subsequently trim the string at the first dot (which is what the `-s` flag does).

I'm using this now for builds on illumos, and would like to contribute my change so that I don't need to maintain a patch.

**Comment by bnfinet** [comment]
@bahamat that'd be excellent!  PR welcome!

**Comment by bahamat** [comment]
Great. I’ll submit it today.
