### ISSUE TITLE
Login in a shell session

### ISSUE THREAD

**Issue by stlorenz** [vouch/vouch-proxy#480]
I am not sure if this is a specific vouch problem. Feel free to close if the following approach is just plain wrong. 

I am using vouch in front of various applications and everything works as expected  in the browser. 

But when I want to use `git clone https://our.gitserver.com/repo.git` I get a 301 redirect, which is basically expected because the session does not have a valid token. 

But how would I approach this usage with vouch?
Do I have to write a script to obtain this token and can somehow use it in the git call or is there a more native way?
Or is the only option to disable the auth_request on those locations in the NGINX config? 

SSH is not an option, the target server has no public IP and I do not want to open SSH and forwarding on the edge. 

Desktop 
 - OS: MacOS
 - Browser: N/A

**Comment by bnfinet** [comment]
@stlorenz I do have this issue myself with a server which is on a specific local network.  I use the nginx directive `satisfy any` to allow traffic from the local subnet.

This example describes that strategy...
https://github.com/vouch/vouch-proxy/issues/378#issuecomment-814423460

> Or is the only option to disable the auth_request on those locations in the NGINX config?

Without doing backfilps, yes.

We have discussed enhancements such as  #362 client credentials which might be an option, but that is aspirational at this time.

**Comment by stlorenz** [comment]
Thx a lot for the explanation. 
I will follow your reccomendation then.
