### ISSUE TITLE
Beginner's troubles!

### ISSUE THREAD

**Issue by jamesnicholls04** [vouch/vouch-proxy#484]
Hi everyone,

I do not have a problem but rather a question as to whether vouch would be appropriate for my particular use case.

I am authenticating users on the client via Auth0, then wish to gate access to my API server to those users only. I would like the users to authenticate only the first time they use the app, and never again - certainly not each time they make a request to my server.

I suppose my question really is this: could I pass some access token, that I could acquire on the client, (as the user will already be authenticated by Auth0), directly to vouch - and thereby grant access to my server. That is, the user would not have to *reauthenticate* with Auth0 when the request hits vouch.

Thank you so much for your time, and apologies if I'm miles off base here - very new to this stuff and any help is thoroughly appreciated!

**Comment by jamesnicholls04** [comment]
Ah, I'm with you - thanks.

Of course this is beyond the scope now, but do you have any guess about how I might approach this problem?

Again, thanks for your help! Much appreciated.

**Comment by bnfinet** [comment]
@jamesnicholls04 there are many options out there.  I wish I could advise you but without a bunch more information it's hard to judge what would be best for you and your organization.
