### ISSUE TITLE
Support unix domain sockets

### ISSUE THREAD

**Issue by squalus** [vouch/vouch-proxy#490]
I would like vouch-proxy to support listening on unix domain sockets. Currently, it only supports listening on TCP sockets.

The `listen` configuration item could support addresses like this: `unix:/path/to/socket`.

Proposed implementation in #488

**Comment by yonas** [comment]
Should be closed by https://github.com/vouch/vouch-proxy/pull/488

**Comment by bnfinet** [comment]
@yonas thanks for the reminder!
