### ISSUE TITLE
Docker version 0.37.0 won't build anymore

### ISSUE THREAD

**Issue by p-l-** [vouch/vouch-proxy#492]
Hi there,

The docker image for the latest released version (0.37.0) won't build anymore, because the `Dockerfile` forces the use of `golang:1.16` as base version and you need to use at least `:1.18`. I suppose one of your dependency, whose version was not fixed, now requires this version.

It builds by replacing `:1.16` with `:1:18`.

I suppose (not tested) that the problem also exists with the current development version.

Thanks for this project!

**Comment by bnfinet** [comment]
@p-l- thanks for the report and the kind words.

I've fixed this with a small adjustment to `go.mod` to specify `go.uber.org/atomic@v1.9.0`.  It now builds properly both locally and via the Dockerfile in a golang `1.16` environment.

I'm not quite ready to leave `1.16`.  IMHO the addition of generics in 1.18 is still working it's way through the golang community and core codebases.  Indeed it appears that the changes to `go.uber.org/atomic` are related to generics.

At some point it will be too painful to stay on `1.16` and it'll be time to upgrade.  I can see that time coming, perhaps as soon as early 2023.
