### ISSUE TITLE
Azure / Nginx : Multiple sites, one vouch 

### ISSUE THREAD

**Issue by zoriax** [vouch/vouch-proxy#496]
Hi everyone, 

I read some issue about this feature but I can't find any correct solution. So maybe you can help me to find the best way to achieve what I'm looking for :-) 

How can I use different client_id based on my nginx server for the same domain name ? For exemple I have : 
- App1 : financial.domain.com -> Azure App 1 with specific access rights
- App2 : support.domain.com -> Azure App 2 with specific access rights
- App3 : tec.domain.com -> Azure App 3 with specific access rights
- ...

I saw that some of you ran multiple vouch instances to do that. Ok it works but it's not really a solution. I have hundreds of app with specific access rights... So what's the correct way to do that ? Vouch can have multiple config files ? 

I'll appreciate your help

**Comment by bnfinet** [comment]
@zoriax yes that's correct.  Spin up one vouch proxy per access rights.  VP is pretty efficient memory wise.  There's further discussion in other closed issues.

**Comment by zoriax** [comment]
Ok thanks for your return ! I assume I need to copy/paste my compiled vouch-proxy in separate directories to have one VP per app ?

**Comment by bnfinet** [comment]
No, you should be able to keep the binary in one place and use the environmental variables to configure VP.

**Comment by zoriax** [comment]
Nice ;-) ! Sorry for my lack of knowledge but do you have a simple example for that ? I think it could be a really plus to have this kind of configuration in default doc :-)

Many thanks

**Comment by bnfinet** [comment]
I support the effort but I'm short on time.  Can you show me what you've tried so far?

**Comment by zoriax** [comment]
For now I just copy paste 2 times vouch, in 2 different directories with 2 different config files :
- Folder A : vouch and config
- Folder B : vouch and config
I tried with a vouch in parent folder and config in folders A and B then I "ln" vouch in each folder. But impossible to target different config file. I don't know if it is possible to launch for exemple a command with something like : vouch-proxy --config B/config.yml and vouch-proxy --config B/config.yml

Many thanks

**Comment by bnfinet** [comment]
please read the README and consult the config.yml_example.

Keep your configs in different directories.  Use a different $VOUCH_CONFIG to reference each config.

**Comment by zoriax** [comment]
Thanks for your return. I read the doc but there as I can see there is noting about $VOUCH_CONFIG in config.yml_example. Sorry :-(

So know, how can I set different config files and where ? I I understant the logic, I suppose I can set something like that : 
```yml
vouch:
   root : /foderA/
   config : /folderA/config.xml
````
Many thanks !

**Comment by bnfinet** [comment]
When I do a Google search for $VOUCH_CONFIG, the first hit is what you say you can't find.  It's from the README of this repo.

@zoriax I'm so sorry, I just don't have the capacity at this time to guide you further.  If you figure it out, please do post your solution here.  I agree, that could be useful to others.

**Comment by zoriax** [comment]
Ok thanks @bnfinet I understand you are busy !

But unfortunatelly, without a good example it will be complicated to do it mayself. It's a pity because it's a feature that seems essential. I think if you can "update" vouch to be "multiple instances" by design it will be a more awesome app ! And if you found time to add a little point in README about it I think it could be very very usefull for all the community. 

In the meantime, I will continue my investigation and be sure I will add a post here with my conclusions :-)

Thanks for the job !

**Comment by zoriax** [comment]
Ok, so don't waste your time :-), I've got it ! Let me explain here and give you a basic example (hope it will help) : 

### Prepare Vouch

1. Compile vouch and move it to /opt/vouch-proxy (or where you want)
2. Create your multiple config files, for exemple, config_file_App1.yml, config_file_App2.yml
3. Add your different parameters here. **Be carefull,** if you want to run multiple vouch, you need to custom ports

config_file_App1.yml
```yml
vouch:
  listen: 127.0.0.1
  port: 9091
````
config_file_App2.yml
```yml
vouch:
  listen: 127.0.0.1
  port: 9092
````

### Prepare your services

1. Go to /etc/systemd/system
2. Create your servides. For exemple ```vouch@App1.service``` and ```vouch@App2.service```. Add a target, for example ```vouch-proxy.target``` if needed (usefull to stop and start all services in one shot) 

vouch@App1.service 
```config
[Unit]
Description=Vouch Proxy Support
After=network.target
PartOf=vouch-proxy.target

[Service]
Type=simple
User=vouch-proxy
WorkingDirectory=/opt/vouch-proxy/
ExecStart=/opt/vouch-proxy/vouch-proxy
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3
Environment="VOUCH_CONFIG=/opt/vouch-proxy/config_file_App1.yml"

[Install]
WantedBy=vouch-proxy.target
```

vouch@App2.service 
```config
[Unit]
Description=Vouch Proxy Support
After=network.target
PartOf=vouch-proxy.target

[Service]
Type=simple
User=vouch-proxy
WorkingDirectory=/opt/vouch-proxy/
ExecStart=/opt/vouch-proxy/vouch-proxy
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3
Environment="VOUCH_CONFIG=/opt/vouch-proxy/config_file_App2.yml"

[Install]
WantedBy=vouch-proxy.target
```

vouch-proxy.target
```config
[Unit]
Description=vouch-proxy target
Requires=multi-user.target
After=multi-user.target
AllowIsolate=yes

[Install]
WantedBy=multi-user.target
```

### Run your multi vouch

You are now able to run all your vouch with a simple 
```sudo systemctl start vouch-proxy.target```
To be sure you services are running correctly, you can simply do a ```netstat -nltp```
```
deb:~$ netstat -nltp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9091          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:9092          0.0.0.0:*               LISTEN      -
``

### Finally

It's also possible to configure all what you need directly in service file. You can add more than one Environment directive.

**Comment by bnfinet** [comment]
@zoriax thanks for sharing your solution.  I'm so glad you got it working.  Cheers.
