### ISSUE TITLE
Vouch and CORS

### ISSUE THREAD

**Issue by zoriax** [vouch/vouch-proxy#499]
Hi everyone ! 

After a week of search and debug, I can't find the way to solve CORS issue when my app is authenticated with vouch and Azure.

I have in my debug log this behavior : 
```
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5355232,"msg":"/login"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5355377,"msg":"setting the cookie domain to mydomain.com"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5355806,"msg":"session state set to v3v6rKffzCHbpcneoCngiAIK1cOrENO"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5356019,"msg":"Login url param normalized to 'https://myapp.mydomain.com/?a=b'"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.535611,"msg":"session requestedURL set to https://myapp.mydomain.com/?a=b"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5356145,"msg":"Adding code challenge"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5356262,"msg":"saving session with failcount 1"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5356991,"msg":"redirecting to oauthURL https://login.microsoftonline.com/abcd/oauth2/v2.0/authorize?client_id=1234&code_challenge=z4567&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fmyapp.mydomain.com%2Fauthenticate%2Fauth&response_type=code&scope=openid+email+profile&state=v3v6rKczYCHbpcneoCnfft6OrENO"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"debug","ts":1661765249.5357094,"msg":"CaptureWriter.Write set w.StatusCode 302"}
Aug 29 11:27:29 P1 vouch-proxy[586]: {"level":"info","ts":1661765249.5357652,"msg":"|302|  209.364µs /authenticate/login","statusCode":302,"request":1932,"latency":0.000209364,"avgLatency":0.004592089,"ipPort":"127.0.0.1:18046","method":"GET","host":"support-lab.ciad.ch","path":"/authenticate/login","referer":"https://myapp.mydomain.com/?a=b"}
```
Related to this error in my browser console : 
```
Access to XMLHttpRequest at 'https://login.microsoftonline.com/abcd/oauth2/v2.0/authorize?client_id=1234&code_challenge=z4567&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fmyapp.mydomain.com%2Fauthenticate%2Fauth&response_type=code&scope=openid+email+profile&state=v3v6rKczYCHbpcneoCnfft6OrENO' (redirected from 'https://support-lab.ciad.ch/ajax/updatecurrenttab.php?itemtype=Central&id=0&tab=2') from origin 'https://myapp.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```` 

I have the OPTION setting in NGINX (regarding to other issues), and I have ```    add_header                          Access-Control-Allow-Origin "*" always;``` too

I used vouch in a path and my config.yml looks like 
```yml
vouch:
    listen: 127.0.0.1
    port: 9091
    logLevel: debug
    allowAllUsers: true
    document_root: /authenticate
    cookie:
        domain: mydomain.com
    post_logout_redirect_uris:
        - https://login.microsoftonline.com/abc/oauth2/v2.0/logout?post_logout_redirect_uri=https://myapp.mydomain.com
    
oauth:
  provider: azure
  client_id: aaabbbb
  client_secret: cccfff
  auth_url: https://login.microsoftonline.com/abc/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/abc/oauth2/v2.0/token
  scopes:
    - openid
    - email
    - profile
  callback_url: https://myapp.mydomain.com/authenticate/auth
  azure_token: id_token
```

I really need your help. I can't find the culprit :-(

Many many thanks !

**Comment by zoriax** [comment]
Ok I think I have a solution here. As I can see there is a difference betweend 
```yml
vouch:
    allowAllUsers: true
    document_root: /authenticate
    cookie:
        domain: mydomain.com
```

And

```yml
vouch:
    allowAllUsers: true
    document_root: /authenticate
    domains : 
       - myapp.mydomain.com
````

So for you what is the correct config ?

**Comment by bnfinet** [comment]
@zoriax welcome back

Could you please read the README on how to post a support issue.  A gist with full logs and complete configs connected to line numbers would help me considerably.

**Comment by zoriax** [comment]
@bnfinet sorry for that. I've missed this part in issue description. I will try to reproduce a complete example in lab and give you here more informations. But as I can see it's related to the difference betweend domains or allowAllUsers: true

**Comment by zoriax** [comment]
After some search in lab, it was due to cookie MaxAge. After 240 minutes, my xhr request failed due to cookie expiration. 
I have a question about cookie maxAge. In config example, you says :  _Must not be longer than jwt.maxAge_ but what should I put in jwt.maxage if cookie.maxage is 0 ? 

Thanks

**Comment by bnfinet** [comment]
Hi @zoriax 

TBH I'm not sure what would happen with `cookie.maxage: 0`  Did you try it?  What did happen?  My recollection is that an error is logged when one exceeds the other.

I'm going to close this as it has veered away from it's original intention but feel free to continue posting here and I'll provide answers as I can

**Comment by zoriax** [comment]
HI @bnfinet,

With ```cookie.maxage: 0```, the cookie stay active unitl you close and restart browser. It's why I need to know what value I had to set in ```jwt.maxage```

**Comment by bnfinet** [comment]
@zoriax how long would you like to have the jwt be valid for?  The default is 240 minutes.  When the jwt is invalid, a user will need to login again.

**Comment by zoriax** [comment]
Ok thanks ! I'm not sure it's related to vouch but when my token expire and I run an "ajax" query, I'm not redirected to login page. I need to refresh my browser to do that. Do you think I can act directly on this behaviour with NIGNX and Vouch ?

**Comment by mig5** [comment]
I am facing a similar issue with a wiki app that makes asynchronous requests. If the jwt has expired, these requests 'silently' 302 to Vouch but there is no behavior change in the user's browser (their tab doesn't actually redirect and go through the auth flow again).

Even without asynchronous activity, if the user was making a big change (say, writing a big document in a form) and then hits submit, and their jwt had expired, the user is then stepped through the auth redirect flow, but problematically, when they return to the original page, they have lost the POST payload! The net effect is 'I just lost all my work'.

It strikes me that increasing the maxAge is not going to help, here: if the user hasn't done anything else on the page for a while and the jwt expires... we can't predict how long they might've sat idle for.

Is there a way in Vouch we can ensure the user's POST payload isn't lost once they are redirected back from Vouch to the original page? I can't think of a way aside from skipping the auth process in Nginx for POST requests (or, perhaps, for specific routes) but it's not ideal, and nor is setting a maxAge of 0.
