### ISSUE TITLE
Customize error page / Redirect to custom page

### ISSUE THREAD

**Issue by zoriax** [vouch/vouch-proxy#500]
Hi ! 

I just have a questoin, is it possible tu customize Vouch error page ? For example, it should be nice to have a way to redirect http 400 or 403 to a custom page. Is it possible to do that ? 

For example, I need to change language beacause my dosen't seek english :-)

Thanks

**Comment by bnfinet** [comment]
> it should be nice to have a way to redirect http 400 or 403 to a custom page
please see #420 and #452

`il8n` multi language translation of the existing templates certainly makes sense, perhaps in a manner similar to https://golangexample.com/i18n-for-golang/

Please fee free to open an issue specific to that effort
