### ISSUE TITLE
docker image inaccessible

### ISSUE THREAD

**Issue by davegaulke** [vouch/vouch-proxy#505]
Here’s what I see when trying to pull the image from quay.io. I can pull other images from quay.io without problem.

Trying to pull quay.io/voucher/vouch-proxy:latest...
Error: initializing source docker://quay.io/voucher/vouch-proxy:latest: reading manifest latest in quay.io/voucher/vouch-proxy: unauthorized: access to the requested resource is not authorized

**Comment by bnfinet** [comment]
@davegaulke 'voucher' in those image names should by 'vouch'...

quay.io/vouch/vouch-proxy

 Did you see that URL on the documentation?  Do let me know if there's a docu-bug.
