### ISSUE TITLE
OAUTH_SCOPES environment variable does not seem to work

### ISSUE THREAD

**Issue by cveilleux** [vouch/vouch-proxy#511]
I am running docker image `quay.io/vouch/vouch-proxy:0.37.3`

When setting the `OAUTH_SCOPES=oidc,email,profile` env variable as documented in:

- https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L216
- https://github.com/vouch/vouch-proxy#configuring-via-environmental-variables

I get the warning:

```
Configuration Warning: for 'oauth.provider: oidc', 'oauth.scopes' should usually contain: -openid -email -profile
```

If I set it in a config.yml, the warning disappears. This is the only setting I can't set using env vars.

**Comment by bnfinet** [comment]
@cveilleux have you tried it as a quoted string?

`OAUTH_SCOPES="oidc,email,profile"`

What else have you tried?

**Comment by cveilleux** [comment]
My bad, I had copy-pasted `oidc` instead of `openid`

With the following it works as it should:

```
OAUTH_SCOPES=openid,email,profile
```

Sorry about that.

**Comment by bnfinet** [comment]
@cveilleux oh I'm so glad it was that easy.  Do let me know if you have any other questions.
