### ISSUE TITLE
first time logging in with Okta + SAML Google results in `/auth` 400 with Invalid session state (after that it works)

### ISSUE THREAD

**Issue by flipsed** [vouch/vouch-proxy#512]
**Describe the problem**
Hi, I'm having an issue with similar symptoms to https://github.com/vouch/vouch-proxy/issues/430 and https://github.com/vouch/vouch-proxy/issues/91. We have configured okta as a provider and have our custom login page running at auth.example.com.

I'm currently having the following issue: when a user logs on for the first time, they have 2 auth steps: they complete the okta OAuth step first, then they have a google SAML authentication step. After this they land on the vouch 400 Bad Request page.

If they refresh the page, they are able to access the application. The 400 only happens on the first login. I've been able to reproduce this but can't find the root cause.

**Expected behavior**
200 OK and redirection to the application after a successful auth

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Additional context**
* we're using sops + kubernetes secrets + terraform so our config isn't in the yaml. Here's the gist for the .tf config: https://gist.github.com/flipsed/5156a2bbc849fe4e8fc498b048b4ab88
* here are the debug logs: https://gist.github.com/flipsed/2ab2ed9991b0d81f32c1e0ba3e0f013b . What stands out to me is this `/auth Invalid session state: stored %!s(<nil>)`
* here is what the ingress looks like: https://gist.github.com/flipsed/35fa9b482acf50db0aa3a03ce0e1cfe6 . We're using the nginx real-ip module and cloudflare proxying

note: much like https://github.com/vouch/vouch-proxy/issues/430 the issue doesn't occur when testing is set to true... We've done a side by side comparison of the requests in burp and there doesn't seem to be any difference, other than the code & state, until we hit the 400

**Comment by bnfinet** [comment]
@flipsed forgive me if this stuff comes off harsher than I mean it to, I'm on the road with little time so please don't think I'm being dismissive..

Could you show logs as per the README?  from startup, two round trips, etc...

Your ingress shows
https://vouch.example.com
but your VP config shows
https://vouch-internal.example.com/auth

those will need to align properly

Your config says testing but those logs don't look like testing logs so the config doesn't appear to correspond to those logs.

That first pass login flow with SAML is kind of hard for me to reason around.  Could you list sequentially the specific URLs that are visited by a user including intermediary redirects? 

Obviously the state is being lost but it's hard to understand where.  Often this is cookie related but with the hand off to the SAML it could just no longer be following there.

You're saying it works fine when testing is set to `false`?  Very odd.

If y'all are up for poking at it harder via fork please do let me know how it goes.  Sure seems like there's a bug in the `testing` mode around but it's still unconfirmed.

**Comment by flipsed** [comment]
@bnfinet yes apologies for the messy config/logs, as you can imagine I've been testing lots of various things to try fix this problem. For context our end goal is to have two vouch instances running: one at vouch-internal.example.com with internal users assigned (to restrict access of internal tooling) and another at vouch.example.com with all our okta users (for our public facing apps with customers).

All our internal apps are currently hooked up to vouch-internal.example.com so it's tough to capture clean logs since we have polling from other services etc. Since we're still in development phase, vouch.example.com is unused by other apps so I've hooked up our ingress to that instance for now. I've updated the gist to reflect the current config. Apologies for any confusion.

As you might have guessed, I meant that the bug is only present when `testing: false` - when we activate testing mode and use the index with redirect links, everything works as intended.

No worries about being harsh, I appreciate the fast reply!

I'll capture the authn redirects in the vouch logs and burp so you can get an idea of what's going on

**Comment by flipsed** [comment]
@bnfinet 
## Testing enabled
here are the logs with testing enabled: https://gist.github.com/flipsed/1266e56c3ce856526df07e9b99366108

I followed the readme and captured this:
    1. VP startup
    2. /validate
    3. /login - (with error)
    4. /auth
    5. /validate

Interestingly enough, found this in the logs:
```
2022-12-16T05:46:10.541Z    DEBUG    Login url param normalized to '<nil>'
2022-12-16T05:46:10.541Z    DEBUG    Stray params in login url ([""]) will be ignored
2022-12-16T05:46:10.541Z    WARN    no destination URL requested
2022-12-16T05:46:10.541Z    DEBUG    setting the cookie domain to example.com
2022-12-16T05:46:10.541Z    DEBUG    rendering error for user: 400 Bad Request
```

## Testing disabled
here are the logs without testing disabled (invalid state): https://gist.github.com/flipsed/5f3b1f7d1f3a49c263ff159c9bce717e

Here's what the flow looks like in burp.
![image](https://user-images.githubusercontent.com/111711808/208039259-b7a0cf9a-e19b-48f2-893c-ec71e808a283.png)

1. navigate to alertmanager-demos3.example.com
2. redirect to okta oauth page - login
3. google saml page - login
4. vouch 400
5. navigate to alertmanager-demos3.example.com - 200 OK

**Comment by infosec-au** [comment]
This issue was to do with SameSite cookie configuration. If you experience this, review your config for vouch to ensure that samesite cookie.

**Comment by bnfinet** [comment]
@infosec-au oh I'm glad it was that straight forward.  I'm guessing you had to set SameSite=none.  Is that correct?

Is there something to be added to the docs in config/config.yml_example?

**Comment by infosec-au** [comment]
Hi @bnfinet - @flipsed should have further information about the context and fix for this. I just wanted to make sure I looped back on this issue for other people experiencing the same issue, in case we forgot to reply to this issue. Thanks for this great project.

**Comment by flipsed** [comment]
@bnfinet so adding this to our config is what caused the issue:
```
            "secure" = true
            "sameSite" = "strict"
```
when we removed it, the first auth returned 200 as expected. Thanks for the help along the way!

**Comment by bnfinet** [comment]
@flipsed thanks for the clarification and details.

FYI - the default is 'secure=true'.  Removing that setting should have no change and would require https for the cookie to be set/read.
