### ISSUE TITLE
Question whether vouch-proxy works behind VPN (non public domain)

### ISSUE THREAD

**Issue by meitham** [vouch/vouch-proxy#516]
I was following the README, in combination with a blog post about vouch-proxy from Okta https://developer.okta.com/blog/2018/08/28/nginx-auth-request and the basic things work, as in I get redirected to the login page of Okta, then I get authenticated, though things stop after that with 400 bad request to the /auth{state} url, followed by a "/auth Error while retrieving user info after successful login at the OAuth provider: Post \"https://REDACTED.okta.com/oauth2/v1/token\": net/http: TLS handshake timeout"}

It is not clear to me from reading the docs whether my domain needs to be public as I am behind a company vpn and strict firewall.  Are there any connectivity expected from the identity provider to my private vouch-proxy (or the protected nginx app)?

**Comment by bnfinet** [comment]
@meitham yes that's right.  It should work fine as long as VP is operating within one domain such as `*.internal.ourcompany.com` and the server <--> server connection from VP to Okta can occur.
