### ISSUE TITLE
using refresh token

### ISSUE THREAD

**Issue by ShyLionTjmn** [vouch/vouch-proxy#517]
> After some consideration we've decided to take this off the roadmap, at least for now.  We've discussed this on IRC and we're not sure of the utility of a refresh token vs. just asking the user to go log in again.  Because of the long lived nature of refresh tokens we see it as a potential exposure to carry the refresh token in VP.
> 
> I'm going to close this for now but please (anyone) do let us know if you have a strong argument for inclusion of this feature.
> 
> _Originally posted by @bnfinet in https://github.com/vouch/vouch-proxy/issues/149#issuecomment-540708641_
> 

            

Here is my argument: i work on some database app and make changes, more frequently than, suppose, an hour. and i know that auth timeout is an hour. i've subbmited some data few minutes ago and want to submit some more, but suddenly my app throws me at IdP page, saying i must reauthenticate, loosing just submitted data.
Very frustrating user expirience.

Please, consider implementing refresh tokens as standart suggests.

**Comment by bnfinet** [comment]
@ShyLionTjmn thanks for the perspective and comment

I'm going to close this as dup in favor of #149.  Please let's keep the conversation there
