### ISSUE TITLE
Is the repo dead yet?

### ISSUE THREAD

**Issue by kylhuk** [vouch/vouch-proxy#519]
hey @bnfinet 

you are probably hella busy, just wanted to check if you have abandoned this project yet. No pull requests accepted since August 2022 and nearly no contributions from you on Github in whole 2022.

I get that lifes can change over the years, but its always sad to see a project dying, just because the repo was not archived. Or you could give maintainer rights to someone capable on here, just to get the spice flowing again.

Cheers,
kylhuk

**Comment by bnfinet** [comment]
@kylhuk are you looking to submit a PR or something?  Why do you ask?
