### ISSUE TITLE
Azure AD authorization code being reused

### ISSUE THREAD

**Issue by airpaio** [vouch/vouch-proxy#520]
With Azure AD as my provider, I have an app that was working fine with vouch proxy for a while, but then started getting 400 Bad Request. The log message that I am facing is `AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.`

I found https://learn.microsoft.com/en-us/answers/questions/311300/oauth2-authorization-code-was-already-redeemed that says that this is expected behavior if your application reuses authorization codes. 

I'm not sure what I have done to make the Authorization code be reused or if that is something that can be changed in VP config. I have linked to my VP config and logs below.

VP Config: https://gist.github.com/airpaio/11489603bfca4a2f5046cb5abc1becb2
VP Logs: https://gist.github.com/airpaio/0e8dfd8808d507c2234e7e5dec367e43

**Comment by bnfinet** [comment]
@airpaio that seems really odd

When you say "was working fine with vouch proxy for a while, but then started getting 400 Bad Request" could you elaborate on timeframe?  Did you upgrade and then it started having problems?  If so between what versions?

Do you use an outbound proxy?  Is there anything which could be shadowing the server-to-server requests?

Could you please post full logs, two round trips as per the README? and your nginx config too please.

**Comment by airpaio** [comment]
Regarding the timeframe, I can't say exactly when it stopped working, but it was on the order of a few weeks.

I deployed the app (all running in Docker containers using docker-compose) back in early part of December 2022. I haven't touched the app development-wise since then, and I'm the only developer. I visited the web app a few times in December and in early Jan 2023 and it all seemed to be working fine. A user reported to me yesterday that they were getting the VP error 400 Bad Request. I've tried restarting the app with docker-compose, clearing cookies in browser, etc.

There is no outbound proxy that I know of. Only proxies I have configured are vouch and an nginx reverse proxy.

Here's the gists:
VP Config: https://gist.github.com/airpaio/11489603bfca4a2f5046cb5abc1becb2
NGINX Config: https://gist.github.com/airpaio/e322250687cb0f4b169572f7a1056f41
VP Logs 2 Round Trips: https://gist.github.com/airpaio/8575e6131e4d14a65dfabb3f6a5dae3c

**Comment by bnfinet** [comment]
@airpaio I'll look closer later but my initial take is that you should simplify your VP config as much as possible.  Most of those settings are default.  Some of them such as the headers or the azure oauth token you are not using in your nginx config.  The cookie should be secure (default).

Could you please try provider OIDC and see if that works?
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

Where is it running?  It's it in an azure instance?

Are those two consecutive round trips? 

For redacting logs see './do.sh'

Is there anything particularly unique about your setup?  Have you made any configuration changes recently in azure?

I'm not an azure user so I'm not in a position to test any setup.  I have to think we'd be hearing of other folks having this issue if there were a problem with VP and azure.

**Comment by airpaio** [comment]
This is running on an AWS EC2. I'm a brand new azure user, so still learning about it - we were just told recently that we will be migrating from Okta to AzureAD :)

I tried changing provider to OIDC, and got the same issue.

Yes they are two consecutive round trips. If I understand the two round trips correctly, it's just a matter of clicking thru the links presented on the "test mode" web page.

I have asked our admins, and we're not aware of any changes on the azure side. 

I'm leaning towards a VP/Nginx misconfiguration, because we have one other app using VP (another colleague set it up), and it doesn't seem to have any authorization code issues.

**Comment by bnfinet** [comment]
@airpaio have you analyzed your colleagues working config?  What's different?  If you use that config in place of this one does it work?

**Comment by airpaio** [comment]
I pretty much copied his when I was setting up this application. I'm getting with him today to review everything together. Maybe I'll have it fixed or can provide an update here early next week.

**Comment by airpaio** [comment]
I'm still troubleshooting this issue, but just an update.

When comparing configurations between this application (app1) which is having the reused authorization code issue and my colleagues application (app2) which is not having the issue, we noted two differences:

* NGINX Configuration:  
  * app1 is configured with SSL certificates where the cert lives on the same EC2 as the `docker-compose` application is running.
  * app2 has a basic [nginx.conf](https://gist.github.com/airpaio/be4843279fbd783f640bfbd3af22cbe3) with no SSL. The SSL for this app is terminated at the AWS Load Balancer using an AWS certificate, and the app is running on k8s.
* Azure AD Configuration:
  * Within the Azure AD console, app1 has ID tokens checked as shown below, while app2 does not. In both vouch configs we specify `azure_token: id_token`. I'm going to try testing with ID token unchecked for app1 as soon as I get in touch with my Azure admin.
![image](https://user-images.githubusercontent.com/5142567/215575184-0decd034-ae42-42f4-b783-d428c2faad2d.png)

**Comment by airpaio** [comment]
Closing for now. We recreated the app in question in AzureAD, and it has been working. I also created another couple of apps that use vouch-proxy in the same way with AzureAD, and they are working too.

Not sure what happened here, but may re-open and continue if I face the issue again in the future.

**Comment by bnfinet** [comment]
Thanks for the follow up.  I'm glad you got it working.

That's a curious one, please do reopen if it occurs again.
