### ISSUE TITLE
Recommendations for using several OIDC endpoints

### ISSUE THREAD

**Issue by Insighter2k** [vouch/vouch-proxy#524]
Hi everyone,

I am just thinking about a good setup to secure my one subdomain.
I want to host several different applications under sub.domain.org, for example /app1, /app2 /app3/api/test
Currently, I have vouch configured with AAD (with subpath) and its working without any issues. I would like to add different app registrations to ensure each context is served and authenticated as it should. Vouch itself doesn't support more than one endpoint and tell my reverse proxy (nginx), please use endpoint a,b or c.
My approach would be to have several instances of vouch proxy and bundle it up under my reverse proxy.
From your point of view, is this approach recommended? Any suggestions?

Kind regards

**Comment by bnfinet** [comment]
@Insighter2k yes that's right

VP is pretty cheap memory wise.  Whenever we've evaluated multi-tenancy / multi-provider / multi-permissions / multi OAuth it's come around to "just setup another one" as best practice.
