### ISSUE TITLE
Vouch 400 and  Invalid session state when opening a previous tab or returning to a tab after the laptop and browser has gone to sleep

### ISSUE THREAD

**Issue by zoriax** [vouch/vouch-proxy#525]
Hello everyone,

**Describe the problem**

I'm facing an "old" issue with vouch-proxy in a path. I'm searching during a few days trough issues and it really looks like issues : 

-  https://github.com/vouch/vouch-proxy/issues/373
- https://github.com/vouch/vouch-proxy/issues/323

But after some test I'm definitively facing a vouch 400. To reproduce this, I'm using on my Edge browser for example : "Open tabs from the previous session", so my browser reopen previous tab.

If during this process, my token or my cookie or session expire (seems to be jwt expiration) and my user open its browser again, I'm facing vouch 400. 

With vouch testing, I can 302 see that after opening browser :
![image](https://user-images.githubusercontent.com/12936546/223403156-f02aeaa3-4d14-48a0-a974-86f8ed91e55a.png)

But if I tried to login I have : 
![image](https://user-images.githubusercontent.com/12936546/223402904-5eee8127-4e5d-4484-a022-c7536b00ce6f.png)

And If I tried to validate I have : ```no jwt found in request```

Please fin here gist  for logs and vouch config here : https://gist.github.com/zoriax/ca6528a51123593ff0725d48198f40b3

**Expected behavior**
I think the login process should be respected according to the vouch config. /!\ one important point is if I try to reach my url for exemple www.test.com in a new tab, the whole vouch login process works as expected

**Desktop (please complete the following information):**
 - OS: Windows 10 -11
 - Browser : Chrome and Edge
 - Version : Laset
 
**Smartphone (please complete the following information):**
- Not used for this test

**Additional context**
I'm using vouch in a path on ```/authenticate```. According to the logs it seems vouch is trying to reach ```/auth``` regarding of ``/authenticate/auth``` but I'm not totally sure of the whole process... I missed something somewhere but I can't find the culprit ;-( so your help could me warmly useful. 

Many many thanks if a way to solve this can be found ! It will save my day.

**Comment by bnfinet** [comment]
@zoriax happy to help but please read the README and adjust your post accordingly.  It makes it much easier when it's done as such.  Cheers.

**Comment by bnfinet** [comment]
@zoriax your session is configured to timeout (`maxAge`) after one minute, your JWT will only be valid for 1 minute.  Try removing those to use defaults (5 minutes, 2 hours).

If that doesn't change the behavior please offer your nginx config as well and offer logs that show two round trips with `testing` as described in the README.

**Comment by zoriax** [comment]
Hello,

MaxAge is set to 1 for testing purpose. The behavior is the same if I set for example maxAge to 4 hour for token. If I close my browser and wait for 4 hours and 2 minutes, then when I open it again and tab is restored, I see vouch 400 error page.

Please find here in gist : https://gist.github.com/zoriax/ca6528a51123593ff0725d48198f40b3

Nginx config and log for round trop (first when I started "from scratch", then when jwt as expire and browser open tab)

Many thanks

**Comment by bnfinet** [comment]
@zoriax need the VP config

**Comment by zoriax** [comment]
@bnfinet sure, it's added to gist. The JWT MaAge is set to 1 for testing purpose. It I set it to 4 hours, then when I close my browser, wait for 4hours and 2 minutes, I encounter vouch 400 too. So it really seems to be related to somethin with token expiration

**Comment by zoriax** [comment]
Hello @bnfinet,

You founded something in logs / config ? I think i tried all the possible ways to configure vouch in a path with Nginx but I continue du have a vouch 400 after tab are restored. It could be very very very nice if we can find a solution for this problem. 

I'm available to provide the logs / config you need to help you to understand this behavior.

By advance, many thanks for your return and your next help

**Comment by nicornk** [comment]
We have also started to see this issue recently, I am still gathering some data on it.

**Comment by nicornk** [comment]
After some investigations we figured out that the issue only occurred when the users clicks the link to the app from an MS Teams chat.

Teams changes the link to 
`https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html?url=https%3A%2F%2F<url-of-the-app>` and adds some "link checker" in front which apparently can not be disabled.

This in combination with SameSite: Strict Cookie Policy led to the issue that Chrome is not sending the VouchSession Cookie in the 
`https://<app-url>/auth/53tYpfjVN5nxaQRtKaI50RHmq8jYAJq/?code=2b850561-7642-4501-85bd-e1bb5ccdd8c4&state=53tYpfjVN5nxaQRtKaI50RHmq8jYAJq` redirect request.

Relaxing the SameSite policy to Lax did fix the issue.

**Comment by bnfinet** [comment]
@nicornk nice sleuthing!

**Comment by j6b72** [comment]
I had the exact same problem - in my case I could solve it by explicitly forbidding the caching of the 302 redirects using headers.

In the server block of auth.<domain>:
```nginx
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        add_header Pragma no-cache always;
```

In the @error401-block inside the protected service's server block:
```nginx
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        add_header Pragma no-cache always;
```

It instantly solved this previously easily reproducible problem.
