### ISSUE TITLE
Token secrets are generated insecurely

### ISSUE THREAD

**Issue by mmdriley** [vouch/vouch-proxy#54]
If a token isn't explicitly provided, vouch generates one using a non-cryptographic random number generator seeded with the current time in nanoseconds:

https://github.com/vouch/vouch-proxy/blob/233ffeebc528823c89cd600927f3839e9f226beb/pkg/cfg/cfg.go#L384-L390

Vouch has only existed for 2 years, or about 2^56 nanoseconds, so this code could only ever have generated one of 2^56 secrets. That's plausibly in the realm of brute force, especially since [vouch uses `HS256`](https://github.com/vouch/vouch-proxy/blob/233ffeebc528823c89cd600927f3839e9f226beb/pkg/jwtmanager/jwtmanager.go#L62) which is just non-iterated SHA256.

This code should be using `crypto/rand`.

Even if the RNG problem is fixed, a secret with 18 characters chosen from ["`a-z A-Z 0-9 except no l, o, O`"](https://github.com/vouch/vouch-proxy/blob/233ffeebc528823c89cd600927f3839e9f226beb/pkg/cfg/cfg.go#L371-L372) (_why exclude those characters??_) could only ever have log2(54^18) or about 104 bits of entropy. The [definition of `HS256`](https://tools.ietf.org/html/rfc7518#section-3.2) says:
>A key of the same size as the hash output (for instance, 256 bits for "HS256") or larger MUST be used with this algorithm.

Please consider using something like [this library](https://godoc.org/github.com/theckman/go-securerandom#Base64OfBytes) to generate a string with at least 32 bytes of randomness.

**Comment by bnfinet** [comment]
@mmdriley thank you for evaluating Vouch Proxy and bringing this to our attention.  I've implemented your suggested fix using the [library you suggested](1) in `v0.4.2` and have added a check for the current secret length.

Please do let me know if there is anything you feel should be adjusted further. 

[1] https://github.com/theckman/go-securerandom/blob/master/securerandom.go#L86
