### ISSUE TITLE
Try To connect to Cognito but i have error: "Required String parameter 'redirect_uri' is not present"

### ISSUE THREAD

**Issue by daerlnaxe** [vouch/vouch-proxy#548]
Hi,

it's 2am, sorry if it's an easy question, it's the first time i use cognito to connect a web app. 
My purpose is to protect a jellyfin web app, that have not a good security.

Everything run under docker and behind a NGINX reverse proxy.

I don't know why but i get this error :"Required String parameter 'redirect_uri' is not present"

Thank a lot

**Comment by bnfinet** [comment]
Sorry you're having trouble.  

Please read the README and offer the requested information exactly as described there.  WHERE do you see that error?  Under what conditions?  Without additional context I can't be of much help.

My best advice is to rest on it and then try again later.

**Comment by daerlnaxe** [comment]
Hi, it's better i still to have problem.
Sorry for my message.

It was a problem about yaml config file the last line was not indented and i get this error when i used the url: "Required String parameter 'redirect_uri' is not present"

**Comment by bnfinet** [comment]
No need to apologize, I'm glad you're getting it in shape.

Since there's nothing actionable here I'm going to close this.

Feel free to add additional information to this issue.  I'm sure others will appreciate it.

If you do need help please do provide the items described in the README.
