### ISSUE TITLE
Raspberry Pi 2/3 version

### ISSUE THREAD

**Issue by UniverseXXX** [vouch/vouch-proxy#55]
Is there a docker container for armhf processor? If not, would you be able to generate it?
Thanks.

**Comment by bnfinet** [comment]
Thanks for your interest.  Unfortunately I've never experienced Docker for arm.  And I've never had a Pi.  I've always done my small stuff on the Teensy or the ESP8266.

I'm very curious about your use case.  How would Vouch Proxy help you?

If you're interested in doing this development yourself I'd be happy to offer support on the `#vouch` irc channel or otherwise

**Comment by UniverseXXX** [comment]
> Thanks for your interest. Unfortunately I've never experienced Docker for arm. And I've never had a Pi. I've always done my small stuff on the Teensy or the ESP8266.
> 
> I'm very curious about your use case. How would Vouch Proxy help you?
> 
> If you're interested in doing this development yourself I'd be happy to offer support on the `#vouch` irc channel or otherwise

Thanks for the reply, @bnfinet I'm trying to find a reverse proxy with built in OAuth functionality. Unfortunately, at the moment only Caddy provide this via JWT plugin. However, there is an issue with Portainer which is not pulled through when JWT used. That's why I've tried to switch back to Nginx when I've seen the article about Nginx+Lasso solution on Medium. I might try to create a vouch-proxy docker config for ARM and submit Pull request here so you might consider adding it. Thanks.

**Comment by bnfinet** [comment]
if you're willing to commit to supporting a `Dockerfile.armhf` setup in `vouch/vouch-proxy` i'd take the PR, though you may also prefer to keep your own repo for `UniverseXXX/vouch-proxy-docker-arm` which I'd be happy to link to from our README.  Of if you preferred we could setup `vouch/vouch-proxy-docker-arm` with you as maintainer.

I'll close this issue for now, though feel free to reopen if there's some need for support.  Good hacking!

**Comment by marhoy** [comment]
I'm using vouch-proxy as a docker image on raspberrypi together with nginx (using balena).
I currently have to recompile docker image for ARM, so I would also be very happy of you enabled building arm-versions.

The image builds on a raspberrypi3 without any changes, so there's no need for a separate Dockerfile.

**Comment by svrooij** [comment]
Great news guys see #178 

There is a new github actions that builds the arm images, **arm64** and **arm/v7** for now. 
See https://hub.docker.com/layers/voucher/vouch-proxy/latest-arm/images/sha256-8fce5b3e329f2d9f52e2e4d8b323a540dde88599a614835f704e6a95975041b5?context=explore tagname `voucher/vouch-proxy:latest-arm`
