### ISSUE TITLE
Question: Is there a flexible way to configure AuthZ with Vouch-Proxy in Kubernetes with annotations & Keycloack User Attributes?

### ISSUE THREAD

**Issue by qdrddr** [vouch/vouch-proxy#550]
Question: Is there a flexible way to configure AuthZ with Vouch-Proxy in Kubernetes with annotations & Keycloack User Attributes?Hi,

I'm looking for a way to have multiple different Websites/DNS proxied by the same Vauch-Proxy. All websites are running in my Kubernetes cluster. I'm also using Keycloack OIDC.

**I want to configure AuthoriZation so that only some users can access some websites more flexibly** and not based on:
- The Keycloack user role
- User email address
- Name of the visited website

I was wondering if there is a way to add some annotations to my Kubernetes ingress config for a given website for Vauch-Proxy to read to perform AuthZ and check if the User in the Keycloack User attributes match the visited website and, based on that, allow or don't allow access to that particular website. 

So if I have a user admin in Keycloack with Attributes:
```yaml
allowed-dns: example1.com
allowed-dns: xyz.net
```

In this example, the admin user should be authorized if the website is https://xyz.net. If the User is trying to log in to a website not listed in the Keycloack attributes, then deny the User even if the User is authenticated.

**Comment by bnfinet** [comment]
I'm sorry, but this is not the `OAuth2-proxy` project.

Closing as off topic, and then deleting the issue so as to not confuse anyone searching in the future
