### ISSUE TITLE
[question] understanding integration 

### ISSUE THREAD

**Issue by Dialgatrainer02** [vouch/vouch-proxy#553]
Hello, I'm new to server infrastructure like this and I'm struggling to understand how I can implement vouch proxy in a setup.

My current setup uses nginx proxy manager as a reverse proxy for my domain and also deals with SSL termination for many apps like portainer and Heimdall using subdomains.

 I would like to change to swag as a reverse proxy and Implement vouch for sso and keycloak as my identity provider. 
When you use vouch does it take the place of a reverse proxy eg forward everything to vouch and have vouch redirect to apps as needed? I've read the documentation for swag, vouch and keycloak and I'm feeling a little lost as how to combine the 3 services.

Edit #551 helps with understanding keycloak but I'm still unsure about configuring a reverse proxy with vouch and SSL termination by extension

**Comment by bnfinet** [comment]
SWAG appears to be NGINX based but beyond that I'm not familiar enough with SWAG to offer you support.

https://github.com/linuxserver/docker-swag/blob/master/Dockerfile

Vouch Proxy is a "sidecar".  The headers of every request is sent to VP via the `autrh_request` module.

I can't advise you on how to integrate SWAG + VP + Keycloak.  Forgive me, I just don't have time to offer that level of support.  

If you do get to the point where you have something working to the point where you're getting errors please read the README and offer the items describe there.

I'm going to close this for now but please do feel free to ask more questions here.

**Comment by Dialgatrainer02** [comment]
Thank you for your time. I'm probably going to spend some time researching more and if I have any more questions I'll come back here

**Comment by Dialgatrainer02** [comment]
https://pastebin.com/h4XMkSt5 
i get an ssl error and i think the authentication fails but i haven't been able to test due to this error
i can access the service locally and through nginx proxy manager when  i remove 
"auth_request /validate;"

**Comment by bnfinet** [comment]
Well that's good progress!

Please do provide all configs and logs as described in the README

**Comment by Dialgatrainer02** [comment]
https://pastebin.com/1XWpjsxD
here are all the config 
im unsure how to get the bugreport as im running vouch proxy using env vars not a config file and in docker compose would i just need to change the config volume to the env vars i use? And use docker run the same?

**Comment by Dialgatrainer02** [comment]
i changed line 111 and another line i can now access the testing page

here are the vouch logs from container startup

https://pastebin.com/HDViiX0f

**Comment by bnfinet** [comment]
Getting closer.

Please do leave comments here instead of in the pastebin so we can be clear about what question you're asking.

Feel free to edit out the health check logs.  Though everything else is very helpful.

Can you clarify what's happening now?

**Comment by Dialgatrainer02** [comment]
when i go a site which i enabled vouch proxy by adding 
![image](https://github.com/vouch/vouch-proxy/assets/96637854/1c954d1a-d6d2-45ae-914b-73cbb570f816)
 i get to the testing page 
if i follow it to key cloak i get 
"Invalid parameter: redirect_uri"
i looked at my redirect uri found i missed a colon fixed that 
now when i follow the testing page link it takes me back to the testing page

**Comment by bnfinet** [comment]
What happens if you turn off testing?

**Comment by Dialgatrainer02** [comment]
without testing it takes me to the login and then i get 400 bad request

**Comment by bnfinet** [comment]
Please turn on testing and update your pastebin with the current info

What happens after keycloak returns you to VP's / auth endpoint?  What's the error in the logs?  Try searching here and generally online for that error

I'm going to be afk for a while here.  But it feels like you're closer

**Comment by Dialgatrainer02** [comment]
log in appears to be successful i see a 200 repsonse code auth has a 200 
after authenticating it seems to error trying to read the json file 
```
2024-02-15T19:24:14.807Z	DEBUG	id_token missing - may not be supported by this provider
2024-02-15T19:24:14.807Z	DEBUG	ptokens: accessToken length: 1641, IdToken length: 0
2024-02-15T19:24:14.824Z	INFO	OpenID userinfo body: 
2024-02-15T19:24:14.824Z	ERROR	Error unmarshaling claims
2024-02-15T19:24:14.824Z	ERROR	unexpected end of JSON input
2024-02-15T19:24:14.824Z	WARN	/auth Error while retrieving user info after successful login at the OAuth provider: unexpected end of JSON input
2024-02-15T19:24:14.824Z	DEBUG	domain vouch.gunnar.duckdns.org matched array value at [0]=gunnar.duckdns.org
2024-02-15T19:24:14.824Z	DEBUG	rendering error for user: 400 Bad Request
2024-02-15T19:24:14.824Z	DEBUG	CaptureWriter.Write set w.StatusCode 400
```
this occurs just after the successfully /auth 

here is  the full logs :
 https://pastebin.com/YxqdrRGP

**Comment by Dialgatrainer02** [comment]
When using keycloak the opening claim is changed and the claim is called preferred_username and not username. How do I change this in the config as that might fix the issue

**Comment by Dialgatrainer02** [comment]
i was looking through the config and i saw this 
```
{"level":"info","ts":1708107741.7217891,"msg":"setting OAuth param 'claims' to null"}
```
im my compose file i have  
```
OAUTH_CLAIMS: | 
   preferred_username
```
keycloak uses a different username claim called preferred_username  instead of the default i configured a different service with just oauth2 and keycloak and also had to change this

do you know why this might be being blanked?

**Comment by shkpk** [comment]
you need `OAUTH_CLAIMS` because you are not using `scopes:`
![image](https://github.com/vouch/vouch-proxy/assets/7137926/0436827c-987c-4555-9938-802233581bab)

**Comment by Dialgatrainer02** [comment]
> you need `OAUTH_CLAIMS` because you are not using `scopes:` ![image](https://private-user-images.githubusercontent.com/7137926/306199695-0436827c-987c-4555-9938-802233581bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjA2NzksIm5iZiI6MTcwODQyMDM3OSwicGF0aCI6Ii83MTM3OTI2LzMwNjE5OTY5NS0wNDM2ODI3Yy05ODdjLTQ1NTUtOTkzOC04MDIyMzM1ODFiYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDkxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEyODBlYzcwMjU4MTYyMDM5OGNmZTQxNzM5MjViN2JkYjVlMjY4NzFlMTEwMTlmOGFkYjEyNTdiMTIxY2FiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GbBUsXqm2Ybp4hovbjMvrQzpiLBKJCw4dKnF3-G9W6k)

I am setting oauth claims in my compose file however it's not being picked up if you look at the compose file at the bottom of here:
https://pastebin.com/sjLzgA7x

**Comment by shkpk** [comment]
> > you need `OAUTH_CLAIMS` because you are not using `scopes:` ![image](https://private-user-images.githubusercontent.com/7137926/306199695-0436827c-987c-4555-9938-802233581bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjA2NzksIm5iZiI6MTcwODQyMDM3OSwicGF0aCI6Ii83MTM3OTI2LzMwNjE5OTY5NS0wNDM2ODI3Yy05ODdjLTQ1NTUtOTkzOC04MDIyMzM1ODFiYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDkxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEyODBlYzcwMjU4MTYyMDM5OGNmZTQxNzM5MjViN2JkYjVlMjY4NzFlMTEwMTlmOGFkYjEyNTdiMTIxY2FiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GbBUsXqm2Ybp4hovbjMvrQzpiLBKJCw4dKnF3-G9W6k)
> 
> I am setting oauth claims in my compose file however it's not being picked up if you look at the compose file at the bottom of here: https://pastebin.com/sjLzgA7x

well it can be the problem of how you make docker container image.
you better first test it manually, may be inside container, by creating config file and run vouch proxy..and later figure out why those values are being ignored when using docker compose.
