### ISSUE TITLE
400 Error with vouch in a path

### ISSUE THREAD

**Issue by Smith-Chris1** [vouch/vouch-proxy#554]
I successfully have used Vouch + nginx on the same host using a port number, 9091. I decided to move vouch to a path in nginx. Once I did that, I get a 400 bad request return after the OKTA sequence has completed successfully. 

Any help is appreciated

Here's my gist: https://gist.github.com/Smith-Chris1/80e11a760ee2c2a6bda7105364fa4369

**Comment by bnfinet** [comment]
line [223](https://gist.github.com/Smith-Chris1/80e11a760ee2c2a6bda7105364fa4369#file-gistfile1-txt-L223) shows `localhost` and but your VP config shows a much longer domain.  Those must be aligned.

**Comment by Smith-Chris1** [comment]
I changed line 223 to the same domain and am still seeing the issue. I am doing this locally with my hosts file remapping 127.0.0.1 to the domain

**Comment by bnfinet** [comment]
Something must be wrong with the authorization cookie.

Do you see the cookie getting set in the /login response?  It should include a session code.  That cookie and code is later used in the /auth requests.  Is it there?  Does it include a path?

Does the browser operate in the same domain for the entire round trip? 

If you continue to have problems, please update your gist with the current configs you're using and fresh logs.  Also please include one run with 'testing enabled'

**Comment by Smith-Chris1** [comment]
ok - that's helpful. I see the VouchSession cookie in the /login request. But the domain is set to localhost. I'm not sure why its localhost, the only times I'm using localhost is in the proxy_pass config for nginx. I thought that was acceptable according to the examples in github?

**Comment by bnfinet** [comment]
@Smith-Chris1 are you still working this issue?  If not could you please close it?

If you do still want help please do provide current configs and logs.

**Comment by bnfinet** [comment]
What have you tried?  Are you able to 'curl' the user info URL?

**Comment by Smith-Chris1** [comment]
I am able to curl the user_info_url from the host I'm on. I notice that I am going through a proxy server though, not sure if that would affect anything

**Comment by Smith-Chris1** [comment]
I am using the docker image and have configured it to run with this service file:

```
[Unit]
Description=Vouch-Proxy container
After=docker.service
Wants=network-online.target docker.socket
Requires=docker.socket

[Service]
TimeoutStartSec=0
Type=forking
Restart=always
RestartSec=10s
ExecStartPre=-/usr/bin/docker rm vouch-proxy-container
ExecStart=-/usr/bin/docker run --rm --name vouch-proxy-container --net=host -p 9091:9091 -v /path/to/config/config:/config quay.io/vouch/vouch-proxy
ExecStop=-/usr/bin/docker stop vouch-proxy-container
Type=simple
NotifyAccess=all

[Install]
WantedBy=multi-user.target
```

**Comment by bnfinet** [comment]
that's documented in the README
