### ISSUE TITLE
scope of nginx auth_request_set

### ISSUE THREAD

**Issue by andriykrefer** [vouch/vouch-proxy#555]
Hi,

This is a question about the nginx example config.

Not sure if it any conflicting configuration on my side (very possible).

Config from example:
```
    # send all requests to the `/validate` endpoint for authorization
    auth_request /validate;

    location = /validate {
      ...

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        # ************ $auth_resp_jwt and others are empty **************
        return 302 https://vouch.yourdomain.com:9090/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }
```

But the variables created with "auth_request_set" directive are not available at the redirected page.
I was only able to get its values, changing its scopes, like:

```
    auth_request /validate;
    # ****** PUT HERE **************
    auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
    auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
    auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;

    location = /validate {
      ...    
    }
```

Any clue why did this happen?

I´m also not sure if my change may cause other problems

**Comment by bnfinet** [comment]
I'm not sure I'm following this correctly.

Could you please clarify the scope of the variables with a more complete example?

Which nginx version are you running?

**Comment by jtackaberry** [comment]
I'm seeing this too with ingress-nginx.  I'm using the latest version as of now (v1.11.1 which uses nginx 1.25.5), although I'm not sure when this might have changed.

Given the ingress-nginx [example from the README](https://github.com/vouch/vouch-proxy#kubernetes-nginx-ingress), the $auth_resp_* variables set in auth-snippet are all empty when redirected to the auth-signin URL.  Moving the `auth_request_set` calls to `nginx.ingress.kubernetes.io/configuration-snippet` instead fixes.  When the ingress controller renders out nginx.conf, this moves the declarations to the location block for the path being auth-proxied, as in @andriykrefer's example.

**Comment by bnfinet** [comment]
@andriykrefer I'm going to close this but feel free to provide more info if you'd like support

**Comment by srstsavage** [comment]
I'm seeing this as well with `nginxproxy/nginx-proxy:1.7.1`. If `auth_request_set` directives are inside the `/validate` location the set variables are not available inside other `location` blocks. Moving `auth_request_set` directives to the `server` context fixes.

Working/fixed config: 

```
auth_request /validate;

auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;

location = /validate {
  proxy_pass http://vouch:9090/validate;
  proxy_set_header Host $http_host;
  proxy_pass_request_body off;
  proxy_set_header Content-Length "";
}

# if validate returns `401 not authorized` then forward the request to the error401block
error_page 401 = @error401;
location @error401 {
  # redirect to Vouch Proxy for login
  return 302 https://vouch.yourdomain.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
}
```
