### ISSUE TITLE
Vouch Loses Redirect URL upon re-authorization

### ISSUE THREAD

**Issue by manavkapoor** [vouch/vouch-proxy#558]
**First read the README**
Specifically ***[Troubleshooting, Support and Feature Requests](https://github.com/vouch/vouch-proxy#troubleshooting-support-and-feature-requests-read-this-before-submitting-an-issue-at-github)***.

And please turn on `vouch.testing` before you ask for support.

** Please DO NOT post config and logs to this issue,  use a Gist**
[gist](https://gist.github.com/manavkapoor/558b68c6886b828611793754521a52a6)

**Describe the problem**
A clear and concise description of the behavior you are observing.
Please include which OAuth provider you are using.
Hi, I'm using Okta as my OAuth provider. Currently, we are using vouch proxy to front Kibana which has been working great. However, it seems that upon re-authentication with Okta (when a cookie expires), the redirect url isn't properly persisted and users are redirected to the Kibana homepage where they lose their original query (which is found in the query string). I've done some deep [digging](https://devforum.okta.com/t/is-it-possible-to-tack-on-parameters-to-the-redirect-uri/13518) and it seems that okta doesn't support dynamic urls due to security reasons and encourages using the state keyword to pass a jwt which has the encoded url and then decode that jwt to redirect the user to their original url. I've tried this implementation but it doesn't seem to be working. I wanted to see if this is an issue that vouch has tackled or if there are any actual workarounds to resolving this issue.

**Expected behavior**
In an ideal state, we expect users who share a url to be able to open that url with the full query string preserved even upon re-authentication. Currently, it drops the query string.

**Desktop (please complete the following information):**
 - macbook, chrome, 122.0.6261.156

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by bnfinet** [comment]
This is pretty good...

https://stackoverflow.com/questions/55524480/should-dynamic-query-parameters-be-present-in-the-redirection-uri-for-an-oauth2/55577647#55577647

Yes, the redirect URL must be static for security reasons.

After you've authenticated you should be able to use the back button, usually by clicking a few times, to get back to your previous Kibana dashboard.
