### ISSUE TITLE
Nginx Proxy Manager ?

### ISSUE THREAD

**Issue by Ghoost666** [vouch/vouch-proxy#570]
Hello, i was wondering if someone got vouch proxy working together with nginx proxy manager, my first attempts to get it running failed, could someone who has it running make a small guide for me?

both nginxproxymanager and vouch proxy have their own docker compose file inside a debian VM (on truenas)

i was copying this example : 

`server {
    listen 443 ssl http2;
    server_name vouch.domain.org;
    ssl_certificate /etc/letsencrypt/live/vouch.domain.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vouch.domain.org/privkey.pem;

    location / {
      proxy_pass http://127.0.0.1:9090;
      # be sure to pass the original host header
      proxy_set_header Host $http_host;
    }
}`

inside the advanced configuration of the vouch.domain.org proxy host, but i get an SSL error, no ssl cert was found

**Comment by bnfinet** [comment]
@Ghoost666 for that kind of support request, please read the README and supply the requested config and logs in the manager suggested

**Comment by simcop2387** [comment]
I have done this.  I did it by setting up a proxy host to vouch with default settings (enable ssl, give it the ip and port).  This was so that I could setup the redirection on a 401 properly in the advanced config section, see below.

Then I added a location based forward for `/validate` on the protected domain to that vouch-proxy host.

I also added the following advanced config to the protected domain to configure things:

```
auth_request /validate;
location = /validate {
      # forward the /validate request to Vouch Proxy
      proxy_pass http://<vouch-proxy-ip>:<vouch-proxy-port>/validate;

      # be sure to pass the original host header
      proxy_set_header Host $http_host;

      # Vouch Proxy only acts on the request headers
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # optionally add X-Vouch-User as returned by Vouch Proxy along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 https://<vouch-proxy-domain>/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }
```

Everything else was just an otherwise normal vouch-proxy setup giving it the oidc client info for keycloak and it then just works.
