### ISSUE TITLE
Vouch Proxy with Cloudflare DNS - SSL Handshake & Self-Signed Certs

### ISSUE THREAD

**Issue by jiriteach** [vouch/vouch-proxy#573]
Hi - Has anyone setup Vouch with Cloudflare DNS? While it sounds simple enough - I keep getting SSL handshake errors on passback.

Scenario -
Domain name setup with dns on Cloudflare and to proxy through Cloudflare
eg. app.domain.comn and auth.domain.com
Using Vouch as a docker container and NGINX as the reverse proxy.
Cloudflare is using TLS 1.3.

Client --> app.domain.com --> requires auth --> goes to Azure for auth and is OK --> passback to auth.domain.com and I get SSL handshake errors.

```
2024/08/29 20:38:19 [error] 281512#281512: *56772 SSL_do_handshake() failed
(SSL: error:0A000410:SSL routines::sslv3 alert handshake failure:SSL alert number 40) 
while SSL handshaking to upstream, client: xxx, server: xxx.xxx.co.nz, request: "GET / HTTP/2.0", 
subrequest: "/validate", upstream: "https://xxx.xxx.xxx.xxx:443/validate", host: "xxx.xxx.co.nz"
```

I've configured Vouch for SSL and provided it the Cloudflare origin cert but its treating that a self-signed so throwing errors. 
How can I include  Cloudflare's root certificate so its trusted? This is using Vouch as a docker container.

I've also tried a valid ssl certificate and still throws ssl handshake errors.

Any pointers? Thanks

**Comment by jiriteach** [comment]
I think I have narrowed this issue down to being TLS1.3. Anyone know how I enable TLS1.3 on the Vouch docker container? Thanks

**Comment by bnfinet** [comment]
@jiriteach sorry for the delay in response.

It's difficult to understand which endpoint you're hitting.  Could you please provide config and logs in the manner described in the README

**Comment by jiriteach** [comment]
@bnfinet - No worries. I guess as a starting question, do you know how I enable TLS1.3 on the Vouch docker container? Thanks

**Comment by jiriteach** [comment]
Attemping to get logs - looks like I have narrowed down the issue. It never gets to Vouch.

Errors thrown in nginx logs - its changing the address for Vouch to Cloudflare IP's when calling /validate so that must be based of one of the variables using the standard config. Will try and change and should fix it.
 
```
upstream: "https://172.66.41.22:443/validate"

request: "GET /favicon.ico HTTP/2.0", subrequest: "/validate", upstream: "https://172.66.42.234:443/validate"
```

**Comment by bnfinet** [comment]
Please consult the  README on how to get support

**Comment by jiriteach** [comment]
> Please consult the README on how to get support

Whoops - sorry. Will close this issue for now since i think I know what it is. Thanks
