### ISSUE TITLE
Build fails due to new breaking change in gorilla/sessions 1.4.0

### ISSUE THREAD

**Issue by aladeeb** [vouch/vouch-proxy#575]
Hey, 

I'm experiencing a build issue while trying to build the docker image due to some breaking changes in the vouch dependecies.

To be more precise, gorilla/sessions does have a new realease 1.4.0 https://github.com/gorilla/sessions/releases/tag/v1.4.0 which only works with golang 1.23 and currently you are using golang 1.22
Below is the error message:
>....
>19.73 go: downloading google.golang.org/protobuf v1.28.1
>19.98 go: downloading google.golang.org/protobuf v1.34.2
>20.71 go: github.com/gorilla/sessions@v1.4.0 requires go >= 1.23 (running go 1.21.13; GOTOOLCHAIN=local)
>Dockerfile:18
>  16 |     
>  17 |     
>  18 | >>> RUN ./do.sh goget
>  19 |     RUN ./do.sh gobuildstatic # see `do.sh` for vouch-proxy build details
>  20 |     RUN ./do.sh install
>ERROR: failed to solve: process "/bin/sh -c ./do.sh goget" did not complete successfully: exit code: 1
>Error response from daemon: reference does not exist

To overcome this, I did pump up the golang version to 1.23 and I was able to build the image again.

**Comment by bnfinet** [comment]
merged!  thanks much @aladeeb
