### ISSUE TITLE
Can't deploy vouch-proxy on another port with variable VOUCH_PORT

### ISSUE THREAD

**Issue by Grey999** [vouch/vouch-proxy#579]
image: voucher/vouch-proxy:0.27.1
Hello, 

I'm trying to run several vouch-proxy on a vm using docker containers. I have one binding to port 9090 and I wanted to deploy two more on 9091 and 9092.

However, when trying to deploy the second container, I received this error:

Error: Bind for 0.0.0.0:9090 failed: port is already allocated

While I specifically precised VOUCH_PORT: 9091 and expose port 9091.
![image](https://github.com/user-attachments/assets/46c5b7d6-393a-4179-9d13-ebfacf6b4940)
![image](https://github.com/user-attachments/assets/16ad8ad0-3bd2-4d07-a59f-1f81f69f2864)

Could someone tell me what am I doing wrong ?

**Comment by bnfinet** [comment]
That's a very old version of VP.  Please try a newer version.
