### ISSUE TITLE
panic: configuration error: oauth.auth_url not found

### ISSUE THREAD

**Issue by davidgibbons** [vouch/vouch-proxy#62]
Trying to set this up with google oauth and getting the following error:

> panic: configuration error: oauth.auth_url not found

This appears to be related to the commit just made for #61 f16e5345c261d78caa8dfc737bb32eb5ab92f68c

auth_url is not in the config.yml for google

**Comment by davidgibbons** [comment]
Confirmed!

**Comment by bnfinet** [comment]
Oh that's great, sorry for the regression!
