### ISSUE TITLE
GitHub provider default scope is R/W

### ISSUE THREAD

**Issue by martin2250** [vouch/vouch-proxy#63]
Hi,

why does vouch default to requesting R/W access to all user data?
Read-only access seems to work fine. As long as OAuth is only used for authentication, I think this should become the default.
```
oauth:
  scopes: read:user
```

https://github.com/vouch/vouch-proxy/blob/22772be2fdeede59baf5af21b9cb35c517d86858/pkg/cfg/cfg.go#L444

Cheers!

**Comment by halkeye** [comment]
Yea none of the data needed for writes is passed to the backend so :+1: from me

**Comment by bnfinet** [comment]
thanks for the suggestion @martin2250

**Comment by martin2250** [comment]
sure thing!
