### ISSUE TITLE
Forward OpenID Provider token to upstream

### ISSUE THREAD

**Issue by simongottschlag** [vouch/vouch-proxy#70]
Hi,

Is it possible to extract the token received from the OpenID Provider as a header to the upstream server? For example, if we've received an id_token it would be great to be able to inject it to the upstream Authorization-header.

This would be especially great with Kubernetes-dashboard, since they are using the id_token for authentication: https://github.com/kubernetes/dashboard/wiki/Access-control#authorization-header

**Comment by bnfinet** [comment]
closing, please use #43
