### ISSUE TITLE
offer an alpine Dockerfile (in addition to existing scratch)

### ISSUE THREAD

**Issue by simongottschlag** [vouch/vouch-proxy#73]
Hi,

A suggestion would be to use alpine instead of scratch for the container, which means it will be a few MB larger but quay will support the security scan as well as make it possible (easier) to troubleshoot since cat / sh etc is there.

I've also noted that ENTRYPOINT doesn't support to change the initial command, so maybe change that to CMD instead.

I hit some issues when I had to troubleshoot the config generation from a consul template and the only solution to actually do "cat /config/config.yml" was to change both of those things.

**Comment by bnfinet** [comment]
It should be just a couple lines using 'COPY --from' to add the binary to
Alpine.

If you cared to contribute a separate additional 'Docker.alpine' on a fresh
branch as a separate PR is probably find a home for it and setup the build
infra for an alpine.

https://docs.docker.com/develop/develop-images/multistage-build/

Here's the method..
https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by bnfinet** [comment]
@simongottschlag do let me know if you'd like to work on this!

**Comment by simongottschlag** [comment]
Hi!

I've created the PR: https://github.com/vouch/vouch-proxy/pull/75

I'm not 100% sure this is the right way, but at least a start.

**Comment by bnfinet** [comment]
thanks @simongottschlag works great!
