### ISSUE TITLE
Allow multiple callback_urls for all backends

### ISSUE THREAD

**Issue by dubit0** [vouch/vouch-proxy#79]
In principle one vouch proxy instance can be used to authenticate users on different vhosts. Putting the nginx config for vouch in a separate file and including it for different vhosts adds a lot of convenience. Such setup currently almost works and only fails at the callback since only a single callback url can be specified in the vouch config. Only the google backend already allows for multiple callback_urls.  As can be seen below, it chooses the callback url that matches the identified domain.

https://github.com/vouch/vouch-proxy/blob/db84bc6cfc1aacf0d92613e1bf34669c2e4af325/handlers/handlers.go#L60-L70

To enable using one vouch proxy on different vhosts, it would be great to move the code out of the if-statement and apply this logic to all backends.

**Comment by bnfinet** [comment]
Yeah that seems like it'd be good.

`domains.Matches` in that block is specific to the `vouch.domains` config element.
https://github.com/vouch/vouch-proxy/blob/a83233064598b1a62ed8aff1ae07caa771f1f10c/pkg/domains/domains.go#L20

The test might be better against the originally provided URL stored in the session variable.

**Comment by bnfinet** [comment]
As per #133 @libussa do you have working code?  Care to submit a PR?

If not @jayb1122 perhaps you'd care to work on this?

**Comment by libussa** [comment]
@bnfinet I do, I just moved the if logic. I didn't however do what you suggested (against the originally provided URL stored in the session variable)

I can submit a PR if you still want it
