### ISSUE TITLE
Not able set additional claims to Ngnix proxy header

### ISSUE THREAD

**Issue by rohithudupa** [vouch/vouch-proxy#80]
Hello,

I have a OIDC authorization server OKTA, where I have created a claim called "sub" and it's been included to fetched along ID_Token as well as Access_Token. I am trying to set both user and sub as header attributes using following settings in ngnix server.

auth_request_set $auth_user $upstream_http_x_vouch_user;
auth_request_set $sub $upstream_http_x_vouch_sub;

proxy_set_header username $auth_user;
proxy_set_header sub $sub;

At the endpoint, I am only receiving  username in the header, not the sub.

Please let me know the exact settings I should follow in order to get the included claim "sub" in the endpoint header

**Comment by bnfinet** [comment]
Unfortunately this is not possible at this time.

Not all of the claims from the OIDC provider (OKTA) are not exposed by vouch to nginx.  Only the `user` which is set as a claim in Vouch's jwt is exposed.  `user` is populated by different backends in different ways (email for Google, username for github, url for indieauth)
