### ISSUE TITLE
/auth User is not authorized. %!s(<nil>) Please try again.

### ISSUE THREAD

**Issue by cyounkins** [vouch/vouch-proxy#81]
The string literal '%!s(<nil>)' is output where a reason is supposed to go.

It's also logged: `time="2019-03-14T21:07:06Z" level=error msg="<nil>"`

It appears to be happening here: https://github.com/vouch/vouch-proxy/blob/a83233064598b1a62ed8aff1ae07caa771f1f10c/handlers/handlers.go#L394

`VerifyUser(user)` is returning !ok but err = nil. I believe err is set to nil here: https://github.com/vouch/vouch-proxy/blame/a83233064598b1a62ed8aff1ae07caa771f1f10c/handlers/handlers.go#L341

My config has a `whiteList` of email addresses and is set up for Google oauth.

**Comment by bnfinet** [comment]
I think what's happening is that `err` is never set and is default `nil`.

The whitelist is present, so it is tested but the user is not found in the whitelist.  The err should be set after not finding the user in the whilte list.  That happens here:
https://github.com/vouch/vouch-proxy/blame/a83233064598b1a62ed8aff1ae07caa771f1f10c/handlers/handlers.go#L332

The error is logged and rendered here..
https://github.com/vouch/vouch-proxy/blame/a83233064598b1a62ed8aff1ae07caa771f1f10c/handlers/handlers.go#L392-L396

**Comment by cyounkins** [comment]
<img width="955" alt="Screen Shot 2019-03-19 at 7 33 50 PM" src="https://user-images.githubusercontent.com/346185/54648866-39595000-4a7e-11e9-92ed-8239f7dd650b.png">

**Comment by bnfinet** [comment]
suweet!

Hey @cyounkins thanks for all your thoughts and contributions.  I'm playing a bit of catch-up after being gone for a few weeks on a trip.  I may not get this merged for a day or two here but I very much appreciate you poking your nose around and offering your code and thoughts.
