### ISSUE TITLE
open data/vouch_bolt.db no such file

### ISSUE THREAD

**Issue by jayb1122** [vouch/vouch-proxy#83]
Previously I built my own vouchproxy image. However, today I did a docker pull of voucher/vouch-proxy:0.5.2 and encountered issues...

Using the configuration above results in the error shown below. If I mount ${NFS_PATH}vouchproxy/data containing a file called vouch_bolt.db, then the error goes away.

ERROR MESSAGE ---->
vouchproxy.1.yslza02z9gdv@moab-101    | time="2019-03-15T20:20:33Z" level=fatal msg="open data/vouch_bolt.db: no such file or directory"

Question 1: Is there a /data/vouch_bolt.db file present by default?
Question 2: The vouch-proxy code shown in this git repo shows "lasso_bolt.db" file under the data directory. That doesn't seem to match what's happening in vouch-proxy docker pull for version 0.5.2.

The config.yml example files should be updated to show the correct location for the xxx_bolt.db file. The one example in config/config.yml_example shows  file: data/vouch_bolt.db. Note there's no slash in front of data. So, where should the xxx_bolt.db file be located? In /data or xxx/data?

Thanks!

Here's my docker compose:

version: '3.6'
    
    . . .
    vouchproxy:
        image: voucher/vouch-proxy:0.5.2
        hostname: vouchproxy
        ports:
            - "3012:9090"
        restart: always
        volumes:
            - type: bind
              source: ${NFS_PATH}/vouchproxy/config/config.yml
              target: /config/config.yml
            #- type: bind
            #  source: ${NFS_PATH}/vouchproxy/data
            #  target: /data
        deploy:
            mode: replicated
            replicas: 1
        networks:
          my-net:
            aliases:
              - vouchproxy.service
    . . .

config.yml file

vouch:
  logLevel: debug
  listen: 0.0.0.0
  port: 3012
  allowAllUsers: true
  publicAccess: false
  jwt:
    secret: This-is-a-random-string-of-989adjfkjdf;k
    issuer: Vouch
    maxAge: 240
    compress: true
  ###db:
    #file: /data/vouch_bolt.db
cookie:
    name: VouchCookie
    secure: false
    httpOnly: false
session:
    name: VouchSession
oauth:
    # okta
    provider:      oidc
    client_id:     xxxx
    client_secret: yyyy
    auth_url:      https://dev-145432.oktapreview.com/oauth2/default/v1/authorize
    token_url:     https://dev-145432.oktapreview.com/oauth2/default/v1/token
    user_info_url: https://dev-145432.oktapreview.com/oauth2/default/v1/userinfo
    scopes:
    - openid
    - email
    - profile
    callback_url:  https://192.168.56.101:8443/auth

**Comment by bnfinet** [comment]
I am not able to reproduce the behavior that you are seeing.  Are you certain that your mount is properly mounted to `/data`?

> Question 1: Is there a /data/vouch_bolt.db file present by default?

No there is not initially, but it will be created if one is not present

> Question 2: The vouch-proxy code shown in this git repo shows "lasso_bolt.db" file under the data directory. 

Good catch!  That shouldn't be there and it isn't used.  I've removed it from the code base.

**Comment by bnfinet** [comment]
@jayb1122 are you still experiencing a problem?
