### ISSUE TITLE
Add separate config option for cookie maxage

### ISSUE THREAD

**Issue by artagel** [vouch/vouch-proxy#92]
Related to #91, Some users may want to have a separate maxage for the vouch cookie compared to the JWT age.  
This is useful if you want the cookie to be deleted when a browser is closed, while retaining a logical JWT maxage.

**Comment by artagel** [comment]
I can help add this.

**Comment by bnfinet** [comment]
Sounds like a reasonable request.

Is there ever a situation where `vouch.cookie.maxAge` would be longer than `vouch.jwt.maxAge`?  That condition should probably be at least `log.Warn` but maybe `log.Fatal`.

Thanks much @artagel

**Comment by artagel** [comment]
Yeah, I think you are right.  makes no sense to make a cookie that can live longer than the JWT.
