### ISSUE TITLE
Document bearer token usage.

### ISSUE THREAD

**Issue by jwhittem** [vouch/vouch-proxy#94]
So I may have something misconfigured or perhaps vouch doesn't yet do this.  Maybe I'm not sending the curl correctly to test it.  I'm trying to test a curl to OKTA using a bearer token in the authorization header and I get:

time="2019-04-05T03:00:32Z" level=error msg="jwtParsed returned error, clearing cookie"
time="2019-04-05T03:00:32Z" level=error msg="token contains an invalid number of segments"

With:

curl localhost:9090/validate -H "Authorization: Bearer ${TOKEN}"

Can anyone help a poor soul like me, with some guidance or documentation on this?  Thanks in advance.

**Comment by bnfinet** [comment]
Vouch Proxy does not use a bearer token.  The jwt is stored in a cookie.  This will not work.

**Comment by bnfinet** [comment]
Are you expecting an Okta issued bearer token to work against the '/validate' endpoint?

Vouch Proxy issues its own token (jwt) and maintains it's own keys for validation. There is no facility for validating a token from an IdP.

**Comment by jwhittem** [comment]
@bnfinet yes, sir thanks for your help, I just wrote a little jwt verifier against okta.  We'll get the token from upstream, and just need to verify a few things.

**Comment by jessecooper** [comment]
Why dose vouch use the Cookie header instead of Authorization?  Since most oauth libs place the tokens in the Authorization header in a Authorization: <type> <token>` format this seems like it could cause some potential workflow issues.

**Comment by aaronpk** [comment]
Vouch is meant to be accessed by browsers, which send a Cookie header.

**Comment by jessecooper** [comment]
That statement should probably be documented in the README. 
> Vouch is meant to be accessed by browsers
This will help people understand the direction of the project as well.
