### ISSUE TITLE
Allow users to specify which claims to store

### ISSUE THREAD

**Issue by artagel** [vouch/vouch-proxy#95]
Add the ability for users to specify the claims they want to store that are coming back from the various auth providers.
Example:
vouch is configured as oidc provider through keycloak, which is tied to active directory.  A SSO sign-on sends back a claim for user groups.  The user groups are saved by vouch and can be later used in different ways for authentication, sending them as headers, etc.

**Comment by bnfinet** [comment]
Thanks again for splitting these out @artagel and opening the issues

I'll post some comments to each

**Comment by artagel** [comment]
After discussion on IRC, we want to accomplish the following:
1. Add custom claim support 
2. Add it to the JWT instead of the user struct
3. pass them down to nginx using X-Vouch-IdP-Claims-"claim"
4. Add config item vouch.headers.claims

**Comment by bnfinet** [comment]
fixed in #102
