### ISSUE TITLE
Allow /validate to returns headers with claims

### ISSUE THREAD

**Issue by artagel** [vouch/vouch-proxy#97]
If #95 is implemented, we can provide a fully customizable interface for sending headers down to the proxies application.

**Comment by bnfinet** [comment]
This is certainly something we've talked quite a bit and that I'm fully in support of.

Were you able to look at the performance for `mappedClaims` and returning headers from `/validate` in #90?

The SLA we've set is "less than `1ms`" but my hope is to stay closer to the `0.5ms` we're at now (on reasonable hardware).

Really `/validate` performance should be a unit test with mocking of the IdP but we're not there yet.

**Comment by artagel** [comment]
No, I'll try to find a good way to measure the performance impact.

**Comment by artagel** [comment]
After discussion on IRC, we want to accomplish the following:

1. Add custom claim support
2. Add it to the JWT instead of the user struct
3. pass them down to nginx using X-Vouch-IdP-Claims-"claim"
4. Add config item vouch.headers.claims

**Comment by bnfinet** [comment]
fixed in #102
