### ISSUE TITLE
Interoperability with OAuth2 Server Library for PHP

### ISSUE THREAD

**Issue by tgal** [vouch/vouch-proxy#99]
When trying to get Vouch to talk to a Symfony app with this PHP library (see https://github.com/bshaffer/oauth2-server-bundle) after successful authentication Vouch aborts with this error message:

```
INFO    OpenID userinfo body: %!(EXTRA string={"id":"me@myemailprovider.com","name":" "})
ERROR   json: cannot unmarshal string into Go struct field User.id of type int
```

The email address (me@myemailprovider.com) in the OpenID userinfo body is the primary user id in the Symfony app and I am expecting it in the X-Vouch-User HTTP header.

Any hints what's wrong here?

**Comment by bnfinet** [comment]
Instead of returning a field named 'id', can you get it to return 'email'?
May need to put a number in the 'id' field too.

**Comment by tgal** [comment]
No, unfortunately it is not possible to remove the 'id' field or have it return an integer.

**Comment by bnfinet** [comment]
Unfortunately this aspect of OIDC is not specified.  Everyone returns
slightly different user information.

Even if we turned 'id' from int to string there would be other changes
necessary.  It would necessitate establishing a new 'oauth.provider' and
getting the id copied to 'User.username'.

Its probably easier to hack the php library but if you cared to work on a
PR I would be happy to support.

**Comment by tgal** [comment]
Thanks for your reply, after all it was possible to have PHP return the OpenID userinfo as 'email' and now it all works. Thanks for providing this excellent piece of software!

**Comment by bnfinet** [comment]
Oh I'm so glad!

Would you be able to provide your config (redacted) for use with the php
library and psuedocode for any modification you needed to make to get it to
generate the email field?  I'd love to link to the thread from the README.

Thanks much!

**Comment by tgal** [comment]
It was not the PHP library's fault and least of all, Vault's. The PHP app's user_info_url endpoint now simply returns {"email":"me@myemailprovider.com"} instead of formerly {"id":"me@myemailprovider.com"}. It was a change in the way the PHP library was used. Thanks again!
